force-app/main/default/objects/Case/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <label>Apellido</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AprobacionBeneficiarios__c.field-meta.xml
<CustomField>
    <fullName>AprobacionBeneficiarios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobación Beneficiarios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Constancia__c.field-meta.xml
<CustomField>
    <fullName>Constancia__c</fullName>
    <label>Constancia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constancia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Es_primer_prestamo__c.field-meta.xml
<CustomField>
    <fullName>Es_primer_prestamo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validar desde el detalle del caso de Pignoración si es primer préstamo.</description>
    <inlineHelpText>Validar desde el detalle del caso de Pignoración si es primer préstamo.</inlineHelpText>
    <label>¿Es primer préstamo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Estado_Civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_Civil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Soltero/a</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Casado/a</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado/a</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo/a</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Unión Libre</label>
            </value>
            <value>
                <fullName>Comprometido/a</fullName>
                <isActive>false</isActive>
                <label>Comprometido/a</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/FPC_Asunto__c.field-meta.xml
<CustomField>
    <fullName>FPC_Asunto__c</fullName>
    <label>Asunto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reposición Carnet</fullName>
                <label>Reposición de Carnet</label>
            </value>
            <value>
                <fullName>Problemas Sitio Transaccional</fullName>
            </value>
            <value>
                <fullName>Problemas en la Aplicación Móvil</fullName>
            </value>
            <value>
                <fullName>Problemas Interbanca</fullName>
            </value>
            <value>
                <fullName>Retiro Manual</fullName>
            </value>
            <value>
                <fullName>Consulta Seguro Vida</fullName>
                <label>Consulta Seguro de Vida</label>
            </value>
            <value>
                <fullName>No se Realizó Aporte</fullName>
            </value>
            <value>
                <fullName>Problemas Caja Banco</fullName>
            </value>
            <value>
                <fullName>Actualización Información</fullName>
            </value>
            <value>
                <fullName>Modificación Aportes</fullName>
            </value>
            <value>
                <fullName>Estado Cuenta</fullName>
            </value>
            <value>
                <fullName>Constancia</fullName>
            </value>
            <value>
                <fullName>Reversiones</fullName>
            </value>
            <value>
                <fullName>Varios Débitos</fullName>
            </value>
            <value>
                <fullName>Consulta Proceso Retiro</fullName>
            </value>
            <value>
                <fullName>Consulta Préstamos</fullName>
            </value>
            <value>
                <fullName>Consulta Cuenta</fullName>
            </value>
            <value>
                <fullName>Consulta de correo electrónico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lugar_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Lugar_Nacimiento__c</fullName>
    <label>Pais de Nacimiento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afgano</fullName>
            </value>
            <value>
                <fullName>Alemán</fullName>
            </value>
            <value>
                <fullName>Árabe</fullName>
            </value>
            <value>
                <fullName>Argentino</fullName>
            </value>
            <value>
                <fullName>Australiano</fullName>
            </value>
            <value>
                <fullName>Belga</fullName>
            </value>
            <value>
                <fullName>Boliviano</fullName>
            </value>
            <value>
                <fullName>Brasilero</fullName>
            </value>
            <value>
                <fullName>Camboyano</fullName>
            </value>
            <value>
                <fullName>Canadiense</fullName>
            </value>
            <value>
                <fullName>Chileno</fullName>
            </value>
            <value>
                <fullName>Chino</fullName>
            </value>
            <value>
                <fullName>Colombiano</fullName>
            </value>
            <value>
                <fullName>Coreano</fullName>
            </value>
            <value>
                <fullName>Costarricense</fullName>
            </value>
            <value>
                <fullName>Cubano</fullName>
            </value>
            <value>
                <fullName>Danés</fullName>
            </value>
            <value>
                <fullName>Ecuatoriano</fullName>
            </value>
            <value>
                <fullName>Egipcio</fullName>
            </value>
            <value>
                <fullName>Salvadoreño</fullName>
            </value>
            <value>
                <fullName>Español</fullName>
            </value>
            <value>
                <fullName>Estadounidense</fullName>
            </value>
            <value>
                <fullName>Estonio</fullName>
            </value>
            <value>
                <fullName>Etiope</fullName>
            </value>
            <value>
                <fullName>Filipino</fullName>
            </value>
            <value>
                <fullName>Finlandés</fullName>
            </value>
            <value>
                <fullName>Francés</fullName>
            </value>
            <value>
                <fullName>Galés</fullName>
            </value>
            <value>
                <fullName>Griego</fullName>
            </value>
            <value>
                <fullName>Guatemalteco</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nombre_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cliente__c</fullName>
    <label>Nombre del Cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segundo_apellido__c.field-meta.xml
<CustomField>
    <fullName>Segundo_apellido__c</fullName>
    <label>Segundo apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Segundo_nombre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_nombre__c</fullName>
    <label>Segundo nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_Casa__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Casa__c</fullName>
    <label>Teléfono Casa</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_Movil__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Movil__c</fullName>
    <label>Teléfono Movil</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Identificacion2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Constancia.recordType-meta.xml
<RecordType>
    <fullName>Constancia</fullName>
    <active>true</active>
    <businessProcess>Constancia</businessProcess>
    <label>Constancia</label>
</RecordType>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Retiros.recordType-meta.xml
<RecordType>
    <fullName>Retiros</fullName>
    <active>true</active>
    <businessProcess>Retiros</businessProcess>
    <label>Retiros</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reversiones.recordType-meta.xml
<RecordType>
    <fullName>Reversiones</fullName>
    <active>true</active>
    <businessProcess>Reversiones</businessProcess>
    <label>Reversiones</label>
</RecordType>

force-app/main/default/objects/Constancia__c/Constancia__c.object-meta.xml
<CustomObject>
    <label>Constancia</label>
    <nameField>
        <label>Nombre de Constancias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constancias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLA_gestion__mdt/SLA_gestion__mdt.object-meta.xml
<CustomObject>
    <label>SLA gestión</label>
    <pluralLabel>SLA gestiones</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLA_gestion__mdt/fields/Tiempo__c.field-meta.xml
<CustomField>
    <fullName>Tiempo__c</fullName>
    <description>Tiempo en horas</description>
    <inlineHelpText>Tiempo en horas</inlineHelpText>
    <label>Tiempo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/myMilestoneTimeCalculator.cls
global class myMilestoneTimeCalculator implements Support.MilestoneTriggerTimeCalculator { 
    global Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId) {
    	Case c = [SELECT Id, AprobacionBeneficiarios__c, RecordTypeId,RecordType.Name,Type,Lugar_Nacimiento__c,Nacionalidad__c,Estado_Civil__c,Correo_Electronico__c,Telefono_Casa__c,Telefono_Movil__c,Telefono_Trabajo__c/*1*/,/*2*/Nombre_Cliente__c,Segundo_nombre__c,Apellidos__c,Segundo_apellido__c,Tipo_Identificacion__c,Identificacion__c,Sexo__c,Fecha_Nacimiento__c/*2*//*Otros*/,FPC_Asunto__c/*Otros*/,Status,Constancia__c,Es_primer_prestamo__c FROM Case WHERE Id=:caseId];
        MilestoneType mt = [SELECT Name FROM MilestoneType WHERE Id=:milestoneTypeId];        
        //Obteniendo valores de los SLA's
        System.debug(milestoneTypeId +' ----- '+caseId);
        List<SLA_gestion__mdt> servicio = [Select Id,MasterLabel,DeveloperName,Tiempo__c From SLA_gestion__mdt Order By MasterLabel]; 
        Integer tiempo;       
        for(SLA_gestion__mdt sla: servicio) {
            //Actualización de información - SAC
            if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c == null && c.Segundo_nombre__c == null && c.Apellidos__c == null && c.Segundo_apellido__c == null && c.Tipo_Identificacion__c == null && c.Identificacion__c == null && c.Sexo__c == null && c.Fecha_Nacimiento__c == null && !c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CNC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Actualización de información / Campos no Críticos SAC*/ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c != null || c.Segundo_nombre__c != null || c.Apellidos__c != null || c.Segundo_apellido__c != null || c.Tipo_Identificacion__c != null || c.Identificacion__c != null || c.Sexo__c != null || c.Fecha_Nacimiento__c != null || c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Campos Críticos SAC*/ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Actualización de información / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Reclamo */ break;
            }
            	//Devolución 1
            if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c == null && c.Segundo_nombre__c == null && c.Apellidos__c == null && c.Segundo_apellido__c == null && c.Tipo_Identificacion__c == null && c.Identificacion__c == null && c.Sexo__c == null && c.Fecha_Nacimiento__c == null && !c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CNC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Actualización de información / Campos no Críticos SAC */ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c != null || c.Segundo_nombre__c != null || c.Apellidos__c != null || c.Segundo_apellido__c != null || c.Tipo_Identificacion__c != null || c.Identificacion__c != null || c.Sexo__c != null || c.Fecha_Nacimiento__c != null || c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Campos Críticos SAC*/ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Actualización de información / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Reclamo*/ break;
            }
            	//Devolución 2
            if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c == null && c.Segundo_nombre__c == null && c.Apellidos__c == null && c.Segundo_apellido__c == null && c.Tipo_Identificacion__c == null && c.Identificacion__c == null && c.Sexo__c == null && c.Fecha_Nacimiento__c == null && !c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CNC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Actualización de información / Campos no Críticos SAC*/ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && (c.Nombre_Cliente__c != null || c.Segundo_nombre__c != null || c.Apellidos__c != null || c.Segundo_apellido__c != null || c.Tipo_Identificacion__c != null || c.Identificacion__c != null || c.Sexo__c != null || c.Fecha_Nacimiento__c != null || c.AprobacionBeneficiarios__c) && sla.MasterLabel == 'Actualización de información / CC - SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Campos Críticos SAC*/ break;
            } else if(c.RecordType.Name == 'Actualización de Información' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Actualización de información / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Actualización de información / Reclamo*/ break;
            }
            //Cambio de subproducto - SAC
            else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / SAC*/ break;
            }
            	//Devolución 1
            else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / SAC*/ break;
            }
            	//Devolución 2
            else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Cambio de Subproducto' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Cambio de subproducto / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Cambio de subproducto / SAC*/ break;
            }
            //Constancias - SAC
            /*else if(c.RecordType.Name == 'Constancia' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Constancias / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Constancias / Reclamo
                break;
            }*/ 
            else if(c.RecordType.Name == 'Constancia' && /*c.Constancia__c != 'P1' &&*/ /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Constancias / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Constancias / SAC*/ break;
            } else if(c.RecordType.Name == 'Constancia' && c.Es_primer_prestamo__c == true && c.Status == 'Esperando Documentación' && sla.MasterLabel == 'Constancias / SAC Pignoración' && mt.Name != null && mt.Name.equals('Oficiales SAC Pignoracón')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*188 horas - Constancias / SAC*/ break;
            }
            	//Devolución 1
            /*else if(c.RecordType.Name == 'Constancia' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Constancias / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Constancias / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Constancia' && /*c.Constancia__c != 'P1' &&*/ /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Constancias / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Constancias / SAC*/ break;
            }
            	//Devolución 2
            /*else if(c.RecordType.Name == 'Constancia' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Constancias / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Constancias / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Constancia' && /*c.Constancia__c != 'P1' &&*/ /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Constancias / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Constancias / SAC*/ break;
            }
            //Estados de cuenta - SAC 
            else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / General' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Estados de cuenta / General*/ break;
            } 
            else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Estados de cuenta / Reclamo*/ break;
            } 
            	//Devolución 1
            /*else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / General' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { 
				tiempo = Integer.valueOf(sla.Tiempo__C)*60; //4 horas - Estados de cuenta / General 
            	break;
            }*/
            /*else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { 
                tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Estados de cuenta / Reclamo
                break;
            }*/
            	//Devolución 2
            else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / General' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Estados de cuenta / General*/ break;
            } 
            else if(c.RecordType.Name == 'Estados de Cuenta' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Estados de cuenta / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Estados de cuenta / Reclamo*/ break;
            }
            //Modificación de aportes - SAC
            /*else if(c.RecordType.Name == 'Modificación de aportes' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Modificación de aportes / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Modificación de aportes / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Modificación de aportes' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Modificación de aportes / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Modificación de aportes / SAC*/ break;
            }
            	//Devolución 1
            /*else if(c.RecordType.Name == 'Modificación de aportes' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Modificación de aportes / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Modificación de aportes / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Modificación de aportes' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Modificación de aportes / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Modificación de aportes / SAC*/ break;
            }
            	//Devolución 2
            /*else if(c.RecordType.Name == 'Modificación de aportes' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Modificación de aportes / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Modificación de aportes / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Modificación de aportes' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Modificación de aportes / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Modificación de aportes / SAC*/ break;
            }
            //Otros - SAC
            /*else if(c.RecordType.Name == 'Otros' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Otros / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Otros / Reclamo
                break;
            }*/ else if(c.RecordType.Name == 'Otros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ c.FPC_Asunto__c == 'Consulta Seguro Vida' && sla.MasterLabel == 'Otros / Consulta Seguros' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*4 horas - Otros / Consulta Seguros*/ break;
            } else if(c.RecordType.Name == 'Otros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ (c.FPC_Asunto__c == 'No se Realizó Aporte' || c.FPC_Asunto__c == 'Estado Cuenta' || c.FPC_Asunto__c == 'Modificación Aportes') && sla.MasterLabel == 'Otros / No se Realizó Aportes' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*16 horas - Otros / No se Realizó Aportes*/ break;
            } else if(c.RecordType.Name == 'Otros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ (c.FPC_Asunto__c == 'Reposición Carnet' || c.FPC_Asunto__c == 'Problemas Sitio Transaccional' || c.FPC_Asunto__c == 'Problemas en la Aplicación Móvil' || c.FPC_Asunto__c == 'Problemas Interbanca' || c.FPC_Asunto__c == 'Problemas Caja Banco' || c.FPC_Asunto__c == 'Varios Débitos' || c.FPC_Asunto__c == 'Consulta de correo electrónico' || c.FPC_Asunto__c == 'Constancia' || c.FPC_Asunto__c == 'Actualización Información') && sla.MasterLabel == 'Otros / Reposición y Problemas CD' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Otros / Reposición y Problemas Canales Digitales*/ break;
            } else if(c.RecordType.Name == 'Otros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ c.FPC_Asunto__c == 'Retiro Manual' && sla.MasterLabel == 'Otros / Retiro Manual' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*80 horas - Otros / Retiro Manual*/ break;
            } else if(c.RecordType.Name == 'Otros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ (c.FPC_Asunto__c == 'Consulta Proceso Retiro' || c.FPC_Asunto__c == 'Consulta Préstamos' || c.FPC_Asunto__c == 'Consulta Cuenta') && sla.MasterLabel == 'Otros / Consultas' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Otros / Consultas*/ break;
            }
            //Reposición de carnet - SAC
            else if(c.RecordType.Name == 'Reposición de Carnet' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Reposición de carnet / General' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Reposición de carnet / General*/ break;
            }
            /*else if(c.RecordType.Name == 'Reposición de Carnet' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reposición de carnet / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) {
            	tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Reposición de carnet / Reclamo
                break;
            }*/
            	//Devolución 1
            else if(c.RecordType.Name == 'Reposición de Carnet' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reposición de carnet / General' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Reposición de carnet / General*/ break;
            }
            else if(c.RecordType.Name == 'Reposición de Carnet' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reposición de carnet / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reposición de carnet / Reclamo*/ break;
            }
            	//Devolución 2
            else if(c.RecordType.Name == 'Reposición de Carnet' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reposición de carnet / General' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Reposición de carnet / General*/ break;
            }
            else if(c.RecordType.Name == 'Reposición de Carnet' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reposición de carnet / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reposición de carnet / Reclamo*/ break;
            }
            //Retiros - SAC
            /*else if (c.RecordType.Name == 'Retiros' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Retiros / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) {
                tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Retiros / Reclamo
                break;
            }*/ else if (c.RecordType.Name == 'Retiros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Retiros / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Retiros / SAC*/ break;
            }
            	//Devolución 1
            /*else if (c.RecordType.Name == 'Retiros' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Retiros / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) {
                tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Retiros / Reclamo
                break;
            }*/ else if (c.RecordType.Name == 'Retiros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Retiros / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Retiros / SAC*/ break;
            }
            	//Devolución 2
            /*else if (c.RecordType.Name == 'Retiros' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Retiros / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) {
                tiempo = Integer.valueOf(sla.Tiempo__C)*60; //8 horas - Retiros / Reclamo
                break;
            }*/ else if (c.RecordType.Name == 'Retiros' && /*(c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') &&*/ sla.MasterLabel == 'Retiros / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*24 horas - Retiros / SAC*/ break;
            }
            //Reversiones - SAC
            else if(c.RecordType.Name == 'Reversiones' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Reversiones' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / SAC*/ break;
            }
            	//Devolución 1
            else if(c.RecordType.Name == 'Reversiones' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Reversiones' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 1')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / SAC*/ break;
            }
            	//Devolución 2
            else if(c.RecordType.Name == 'Reversiones' && (c.Type == 'Gestión' || c.Type == 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / Reclamo' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / Reclamo*/ break;
            } else if(c.RecordType.Name == 'Reversiones' && (c.Type != 'Gestión' || c.Type != 'Gestión Usuario Financiero') && sla.MasterLabel == 'Reversiones / SAC' && mt.Name != null && mt.Name.equals('Oficiales SAC / Devolución 2')) { tiempo = Integer.valueOf(sla.Tiempo__C)*60; /*8 horas - Reversiones / SAC*/ break;
            }
        }
        System.debug('Tiempo SLA: '+tiempo);
        return tiempo;
    }
}