force-app/main/default/objects/Case/fields/DAU_Identidad__c.field-meta.xml
<CustomField>
    <fullName>DAU_Identidad__c</fullName>
    <description>Identidad que devuelve el servicio de consulta.</description>
    <inlineHelpText>Identidad que devuelve el servicio de consulta.</inlineHelpText>
    <label>DAU_Identidad</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_No_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>DAU_No_Cuenta__c</fullName>
    <description>Número de cuenta que devuelve el servicio de validación de Identidad.</description>
    <inlineHelpText>Número de cuenta que devuelve el servicio de validación de Identidad.</inlineHelpText>
    <label>DAU_No.Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_de_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Dia_de_pago__c.field-meta.xml
<CustomField>
    <fullName>DAU_Dia_de_pago__c</fullName>
    <label>DAU_Día de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nueva_fecha_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nueva_fecha_aporte__c</fullName>
    <label>Nueva fecha de aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nuevo_canal_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nuevo_canal_aporte__c</fullName>
    <label>Nuevo canal de aporte</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_Operacion__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CK</fullName>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>AH</fullName>
                <label>Debito a Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Debito a Tarjeta de Crédito Ficohsa</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Debito a Tarjeta de Crédito Otros Bancos</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Móvil</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/Parametros_DAU__mdt.object-meta.xml
<CustomObject>
    <label>Parámetros DAU</label>
    <pluralLabel>Parámetros DAU</pluralLabel>
</CustomObject>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Contrasenia__c.field-meta.xml
<CustomField>
    <fullName>DAU_Contrasenia__c</fullName>
    <label>Contraseña</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Dias__c.field-meta.xml
<CustomField>
    <fullName>DAU_Dias__c</fullName>
    <label>Días</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Token__c.field-meta.xml
<CustomField>
    <fullName>DAU_Token__c</fullName>
    <label>Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Usuario__c.field-meta.xml
<CustomField>
    <fullName>DAU_Usuario__c</fullName>
    <label>Usuario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BAT_CallCardServiceFicohsa.cls
global class BAT_CallCardServiceFicohsa implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    
    public Boolean enviarSolicitud;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
    	return Database.getQueryLocator([SELECT Id,Caso__c,Caso__r.CaseNumber,Caso__r.Status,Nuevo_canal_aporte__c,Caso__r.Tipo_de_Operacion__c,
                                         Caso__r.Account.Name,DAU_Dia_de_pago__c,Caso__r.DAU_Identidad__c,Cuenta__r.CurrencyIsoCode,
                                         N_Cuenta_Bancaria__c,Caso__r.DAU_No_Cuenta__c,Cuenta__r.Name,Nueva_fecha_aporte__c,CreatedDate 
                                         From Detalle_caso__c Where Caso__r.Id = '5006300000CxWIJAA3' and Caso__r.Status = 'Cerrado' 
                                         and Nuevo_canal_aporte__c = 'TA' and Caso__r.Tipo_de_Operacion__c = 'A8']); 
    }
	
	global void execute(Database.BatchableContext bc, List<Detalle_caso__c> scope) {
        try {
            //Entra a llamar a servicios de Tarjeta Ficohsa Regional
            enviarSolicitud = false;
            String tipoGestion = 'ALTA';
            String identidad,moneda;
            String DAU_Usuario, DAU_Contrasenia, DAU_Token;
            Decimal Dias;
            
            Parametros_DAU__mdt[] mdt = [SELECT Id,DeveloperName,DAU_Usuario__c,DAU_Contrasenia__c,DAU_Token__c,DAU_Dias__c 
                                         FROM Parametros_DAU__mdt];
            
            for(Parametros_DAU__mdt m : mdt) {
                if(m.DeveloperName == 'Parametro_dias') {
                    Dias = m.DAU_Dias__c;   
                }
                if(m.DeveloperName == 'Salesforce_regional') {
                	DAU_Usuario = m.DAU_Usuario__c; 
                    DAU_Contrasenia = m.DAU_Contrasenia__c; 
                    DAU_Token = m.DAU_Token__c;    
                }
            }
            
            //Validando la fecha
            Date fechaComparacion, fechaComparacion2;
            for(Detalle_caso__c dt : scope) {
                fechaComparacion = Date.valueOf(dt.CreatedDate.addDays(30));
                fechaComparacion2 = dt.Nueva_fecha_aporte__c.addDays(-Integer.ValueOf(Dias));
                if(fechaComparacion > dt.Nueva_fecha_aporte__c && fechaComparacion == Date.Today()) {
                    enviarSolicitud = true;
                } else if(fechaComparacion2 == Date.Today()) {
                	enviarSolicitud = true;    
                } else {
                    System.debug('No se llama al servicio de tarjetas regional');
                }
            }
            //System.debug('enviarSolicitud: '+enviarSolicitud);
            if(enviarSolicitud == true) {
                partnerSoapSforceCom.Soap con = new partnerSoapSforceCom.Soap();
                partnerSoapSforceCom.LoginResult loginResult = con.login(DAU_Usuario, DAU_Contrasenia + DAU_Token);
                
                http http = new Http();
                HttpRequest request = new HttpRequest();
                request.setEndpoint('https://cs211.salesforce.com/services/Soap/class/WS_DAU_Pensiones');
                request.setMethod('POST');
                request.setHeader('Content-Type', 'text/xml');
                request.setHeader('SOAPAction','action');
                request.setTimeout(120000);
                   
                String SOAPXML = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://soap.sforce.com/schemas/class/WS_DAU_Pensiones">\n';
                SOAPXML += '<soapenv:Header>\n';
                SOAPXML += '<ws:SessionHeader>\n';
                SOAPXML += '<ws:sessionId>'+loginResult.sessionid+'</ws:sessionId>\n';
                SOAPXML += '</ws:SessionHeader>\n';
                SOAPXML += '</soapenv:Header>\n';        
                SOAPXML += '<soapenv:Body>\n';
                SOAPXML += '<ws:GestionDAU>\n';
                SOAPXML += '<ws:Identidad>0801199403628</ws:Identidad>\n';
                SOAPXML += '<ws:Cuenta>0000051000399200672</ws:Cuenta>\n';
                SOAPXML += '<ws:SubProducto>Pensiones y Cesantías - Seguro de Vida L</ws:SubProducto>\n';
                SOAPXML += '<ws:NumReferencia>73232</ws:NumReferencia>\n';
                SOAPXML += '<ws:DiaPago>10</ws:DiaPago>\n';
                SOAPXML += '<ws:Moneda>HNL</ws:Moneda>\n';
                SOAPXML += '<ws:Monto>650</ws:Monto>\n';
                SOAPXML += '<ws:Pais>HONDURAS</ws:Pais>\n';
                SOAPXML += '<ws:Comentarios></ws:Comentarios>\n';
                SOAPXML += '<ws:MotivoBaja></ws:MotivoBaja>\n';
                SOAPXML += '<ws:TipoGestion>ALTA</ws:TipoGestion>\n';
                SOAPXML += '</ws:GestionDAU>\n';
                SOAPXML += '</soapenv:Body>\n';
                SOAPXML += '</soapenv:Envelope>';
        
                System.debug(SOAPXML);
        
                request.setBody(SOAPXML);
                HttpResponse response = http.send(request);
                     
                System.debug('La respuesta es: '+response.getBody());
                
                String Afiliacion, CodigoError, estadoGestion, Gestion; 
                String bodyXML = response.getBody(); //grab the body of the response
                XmlStreamReader reader = new XmlStreamReader(bodyXML); //construct an XmlStreamReader object
                while(reader.hasNext()) { //while there are more XML events
                    if (reader.getEventType() == XmlTag.START_ELEMENT) { //if this is the opening tag
                        if ('Afiliacion' == reader.getLocalName()) { //if the tag is Afiliacion
                            while(reader.hasNext()) { //while there are more XML events
                                if (reader.getEventType() == XmlTag.END_ELEMENT) { //if this is the closing tag
                                    break; //exist the loop
                                } else if (reader.getEventType() == XmlTag.CHARACTERS) { //if this is the content between the tags
                                    Afiliacion = reader.getText(); //grab the content
                                }
                                reader.next(); //advance to the next XML event
                            }
                        }
                        if ('CodigoError' == reader.getLocalName()) { //if the tag is CodigoError
                            while(reader.hasNext()) { //while there are more XML events
                                if (reader.getEventType() == XmlTag.END_ELEMENT) { //if this is the closing tag
                                    break; //exist the loop
                                } else if (reader.getEventType() == XmlTag.CHARACTERS) { //if this is the content between the tags
                                    CodigoError = reader.getText(); //grab the content
                                }
                                reader.next(); //advance to the next XML event
                            }
                        }
                        if ('estadoGestion' == reader.getLocalName()) { //if the tag is estadoGestion
                            while(reader.hasNext()) { //while there are more XML events
                                if (reader.getEventType() == XmlTag.END_ELEMENT) { //if this is the closing tag
                                    break; //exist the loop
                                } else if (reader.getEventType() == XmlTag.CHARACTERS) { //if this is the content between the tags
                                    estadoGestion = reader.getText(); //grab the content
                                }
                                reader.next(); //advance to the next XML event
                            }
                        }
                        if ('Gestion' == reader.getLocalName()) { //if the tag is Gestion
                            while(reader.hasNext()) { //while there are more XML events
                                if (reader.getEventType() == XmlTag.END_ELEMENT) { //if this is the closing tag
                                    break; //exist the loop
                                } else if (reader.getEventType() == XmlTag.CHARACTERS) { //if this is the content between the tags
                                    Gestion = reader.getText(); //grab the content
                                }
                                reader.next(); //advance to the next XML event
                            }
                        }
                    }
                    reader.next(); //advance to the next XML event   
                }
                system.debug('Afiliacion: '+Afiliacion);
                system.debug('CodigoError: '+CodigoError);
                system.debug('estadoGestion: '+estadoGestion);
                system.debug('Gestion: '+Gestion);
            }    
        } catch(Exception ex) {
            System.debug('Error en servicio: '+ex.getLineNumber()+'---'+ex.getMessage());
        }    
    }  
    
    global void finish(Database.BatchableContext bc) { }
    
}