force-app/main/default/objects/Case/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <formula>MONTH(DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Retiros.recordType-meta.xml
<RecordType>
    <fullName>Retiros</fullName>
    <active>true</active>
    <businessProcess>Retiros</businessProcess>
    <label>Retiros</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Comision_retiro_anticipado__c.field-meta.xml
<CustomField>
    <fullName>Comision_retiro_anticipado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comisión por retiro anticipado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta_colectiva2__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_colectiva2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta colectiva</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cuentas__c.Colectiva__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Fecha_Aporte__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Aporte__c</fullName>
    <label>Fecha de Aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Frecuencia_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia_Aportacion__c</fullName>
    <label>Frecuencia de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Trimestral</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Semestral</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Quincenal</label>
            </value>
            <value>
                <fullName>W</fullName>
                <isActive>false</isActive>
                <label>W</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Monto_aporte__c</fullName>
    <label>Monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Ano_tarjeta__c.field-meta.xml
<CustomField>
    <fullName>Ano_tarjeta__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
                <isActive>false</isActive>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <isActive>false</isActive>
                <label>2018</label>
            </value>
            <value>
                <fullName>2026</fullName>
                <isActive>false</isActive>
                <label>2026</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cliente_quiere_capital_semilla__c.field-meta.xml
<CustomField>
    <fullName>Cliente_quiere_capital_semilla__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cliente quiere capital semilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cliente_sigue_Laborando__c.field-meta.xml
<CustomField>
    <fullName>Cliente_sigue_Laborando__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cliente sigue Laborando</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Comision_Retiro_Anticipado__c.field-meta.xml
<CustomField>
    <fullName>Comision_Retiro_Anticipado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comisión por Retiro Anticipado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Fecha_aporte__c.field-meta.xml
<CustomField>
    <fullName>Fecha_aporte__c</fullName>
    <label>Fecha de aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Trimestral</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Semestral</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Anual</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Quincenal</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Semanal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nueva_fecha_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nueva_fecha_aporte__c</fullName>
    <label>Nueva fecha de aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nuevo_canal_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nuevo_canal_aporte__c</fullName>
    <label>Nuevo canal de aporte</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_Operacion__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CK</fullName>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>AH</fullName>
                <label>Debito a Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Debito a Tarjeta de Crédito Ficohsa</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Debito a Tarjeta de Crédito Otros Bancos</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Móvil</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nuevo_monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nuevo_monto_aporte__c</fullName>
    <label>Nuevo monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
                <default>true</default>
                <label>Aumento de Aporte</label>
            </value>
            <value>
                <fullName>A2</fullName>
                <label>Disminución de Aporte</label>
            </value>
            <value>
                <fullName>A3</fullName>
                <label>Cambio de Canal de Aporte</label>
            </value>
            <value>
                <fullName>A4</fullName>
                <label>Cambio de Fecha de Aporte</label>
            </value>
            <value>
                <fullName>A5</fullName>
                <label>Cambio de # de CA/CC</label>
            </value>
            <value>
                <fullName>A6</fullName>
                <label>Cambio de # Tarjeta</label>
            </value>
            <value>
                <fullName>A7</fullName>
                <label>Cancelación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_retiro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_retiro__c</fullName>
    <label>Tipo de retiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>52</fullName>
                <label>Total</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>Parcial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllerAprobarCasos.cls
public class controllerAprobarCasos {
    public Case caso{get;set;}
    public Detalle_caso__c detalleCaso{get;set;}
    public list<Detalle_caso__c> listSaldosCaso{get;Set;}
    public claseTipoCaso cTipoCaso{get;set;}
    public boolean mbAprobado{get;set;}
    public boolean popAdjuntar{get;set;}
    public string comentarios{get;Set;}
    public list<ProcessInstanceHistory> historialApp{get;set;}
    Id newWorkItemIds;
    
    public controllerAprobarCasos(){
        try{
            Caso = [Select Owner.Name, RecordTypeId, CaseNumber, Account.Name, Status, Type, Origin,
                    Priority, Subject, Description,Account.IsPersonAccount, RecordType.DeveloperName
                    From Case
                    Where Id =: ApexPages.currentPage().getParameters().get('id')];
            cTipoCaso = new claseTipoCaso(Caso.RecordType.DeveloperName);
                    
            listSaldosCaso = [Select Tipo_Operacion__c,Nuevo_monto_aporte__c,Nuevo_canal_aporte__c,N_Cuenta_Bancaria__c,
                    Nueva_fecha_aporte__c,Mes__c,Ano_tarjeta__c,Frecuencia__c, Cuenta__r.Name, Cuenta__r.Subproducto__r.Name,
                    Cuenta__r.Cuenta_Colectiva2__r.Name, Cuenta__r.Fecha_aporte__c, Cuenta__r.Monto_aporte__c,
                    Cuenta__r.Frecuencia_Aportacion__c, Cuenta__r.Forma_Aportacion__c
                    ,Tipo_retiro__c,Comision_Retiro_Anticipado__c,Cliente_quiere_capital_semilla__c,Cliente_sigue_Laborando__c,
                    Comision_retiro_anticipado_empresa__c,Porcentaje_comision__c,Cobrar_empleado_sigue_laborando__c,
                    Permitir_Retiro_Saldos_Patronales__c,Forma_Retiro__c,Cobro_TSP__c,Cobro_Cheque__c,
                    Banco__c,Tipo_Cuenta__c,currencyIsoCode,Cobro_ACH__c,Saldo_retirar__c,Monto_saldo__c,Monto_retirar__c
                    From Detalle_caso__c
                    Where Caso__c =: Caso.Id order by Cabeza_retiro__c desc];
            
            if(!listSaldosCaso.isEmpty()){
                detalleCaso = listSaldosCaso[0];
                if(cTipoCaso.retiros){
                    listSaldosCaso.remove(0);  
                }
            }

            comentarios = '';
            
            list<ProcessInstance> procesos = [SELECT Id, (SELECT Id, ActorId, IsPending, StepStatus, Comments FROM StepsAndWorkitems)
                    FROM ProcessInstance Where TargetObjectId =: Caso.id];
            
            newWorkItemIds = [SELECT Id FROM ProcessInstanceWorkitem 
                                 WHERE processInstance.TargetObjectId=: Caso.Id].Id;
           
            historialApp = new list<ProcessInstanceHistory>(); 
            For(ProcessInstance proceso : [SELECT Id, 
                          (SELECT Id, ActorId, IsPending, StepStatus, Comments,ProcessInstance.CompletedDate,
                          ElapsedTimeInDays,ElapsedTimeInHours,ElapsedTimeInMinutes,ProcessInstance.CreatedDate 
                          FROM StepsAndWorkitems order by ProcessInstance.CreatedDate desc)
                              FROM ProcessInstance Where TargetObjectId =: Caso.id order by CreatedDate desc]){
              
              For(ProcessInstanceHistory item : proceso.StepsAndWorkitems){
                historialApp.add(item);  
              }
            }
            
            mbAprobado = true;
            popAdjuntar = false;            
        }Catch(Exception e){
            mbAprobado = False; 
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, '¡No tiene proceso de aprobación pendiente!'));    
        }
    }
    
    public void cerrar(){
        popAdjuntar = false;
    }
    
    public void adjuntar(){
        popAdjuntar = true;
    }
    
    public void aprobar(){
        accionFinal('Approve');
    }   
    
    public void rechazar(){
        if(comentarios == null || comentarios == '' || comentarios.length() < 5){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 
                                'Debes especificar el motivo del rechazo en el campo comentario')); 
        }else{
            accionFinal('Reject');
        }
    }
    
    public void accionFinal(String accion){
        try{
            User user1 = [Select Id From User Where Alias = 'AUser' AND isActive = true Limit 1];
            
            //Id newWorkItemIds = [SELECT Id FROM ProcessInstanceWorkitem 
              //                   WHERE processInstance.TargetObjectId=: Caso.Id].Id;
            
            Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
            req2.setComments(comentarios);
            req2.setAction(accion);
            req2.setNextApproverIds(new Id[] {User1.id});
            
            req2.setWorkitemId(newWorkItemIds);
            
            Approval.ProcessResult result2 =  Approval.process(req2);          
            
            mbAprobado = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Confirm, 'Gracias.!')); 
            mbAprobado = False; 
        }Catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL, 'Error: No existe proceso de aprobación pendiente'));        
        }
    }
}