force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fantasma_portal__c/Fantasma_portal__c.object-meta.xml
<CustomObject>
    <label>Fantasma portal</label>
    <nameField>
        <label>Nombre Objeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fantasma Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fantasma_portal__c/fields/Motivo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_contacto__c</fullName>
    <label>Motivo contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fantasma_portal__c/fields/Usuario_referencia__c.field-meta.xml
<CustomField>
    <fullName>Usuario_referencia__c</fullName>
    <label>Usuario referencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Motivo de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>CLUB DE BENEFICIOS</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Usuario_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Referencia__c</fullName>
    <label>Usuario de Referencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/classes/ControllerPromociones.cls
public class ControllerPromociones {

 public list<Lead> prospectos {get;set;}
     public Lead candidato {get;Set;}
   
    public boolean pop3 {get;Set;}
    public string nombrePersonaRefiere {get; set;}
    private RecordType natural;
    private map<id, Lead> mapProspectos;
    
    public List<SelectOption> options {get;set;}
    private string usuario;

    public Fantasma_portal__c fantasma{get;Set;}
    
    public ControllerPromociones(){
        candidato = new Lead();
        usuario = Apexpages.currentPage().getParameters().get('usuario');
        natural = [Select id From RecordType Where sObjectType = 'Lead' AND DeveloperName = 'Natural' Limit 1];
        pop3=true;
        candidato.Motivo_Contacto__c = 'Campaña HTML';
        //candidato.Motivo_Contacto__c = apexpages.;
        //[select Motivo_Contacto__c from Motivo_Contacto ];
            //opcionColonia = new list <selectOption>();
    }
     
    public pageReference guardarPop(){
        
        try{
            if(candidato.Phone.length() > 8 ){          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Movil excede la cantidad de 8 caracteres permitidos'));
            return null;    
        }
        if(candidato.Telefono_Trabajo__c != null){
            if(candidato.Telefono_Trabajo__c.length() > 8 ){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Trabajo excede la cantidad de 8 caracteres permitidos'));
                return null;
            }
        }
            if(candidato.Departamento__c  == 'N/A')
        {          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe Seleccionar un Departamento'));
            return null;
        }
        else   
        { 
            
        candidato.RecordTypeId = natural.id;
        candidato.status = 'En Proceso';
        candidato.Usuario_Referencia__c = usuario;
        candidato.LeadSource='Web';
        //candidato.Motivo_Contacto__c = 'Referido';
        //nombrePersonaRefiere +=' '+candidato.Description; 
        //candidato.Description = nombrePersonaRefiere;
        insert candidato;
        system.debug(candidato);  
        candidato = new Lead();
        pop3 = False;
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente')); 
            
        reiniciar(); 
        }
        return null;//new pagereference('/apex/vfReferidos');
           //nombrePersonaRefiere = null; 
            //candidato.Description = null;
        }catch (exception e){
            system.debug(e.getLineNumber()+e.getMessage());
        }
        return null;
        
    }
    
    public void reiniciar()
     {          
    candidato.Motivo_Contacto__c = 'Referido';
    candidato.Departamento__c  = 'N/A';    
        
     }
    
    
}