force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Cliente_Localizable__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Localizable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Cliente Localizable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Nombre_Empresa__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Empresa__c</fullName>
    <label>Nombre de la Empresa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referido_por__c.field-meta.xml
<CustomField>
    <fullName>Referido_por__c</fullName>
    <label>Referido por</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Trabaja__c.field-meta.xml
<CustomField>
    <fullName>Trabaja__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Información sobre si cliente trabaja o no.</description>
    <label>Trabaja</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/classes/testTR_TrasladarProspecto.cls
@isTest(SeeAllData=true)
public class testTR_TrasladarProspecto {
    
    static testMethod void testTR_TrasladarProspecto() {
        test.startTest();
        
          
        
        Lead obj = new Lead ();
            
            obj.Referido_por__c = 'Referido por';
            obj.Description = 'Description';
            obj.Cliente_Localizable__c = true;
            //CurrencyIsoCode = sc.CurrencyIsoCode,
            obj.Departamento__c = 'Gracias a Dios';
            obj.Email = 'dluarca@sbfcorp.com';
            obj.LeadSource = 'Web';
            obj.Nombre_Empresa__c = 'Empresa David Luarca';
            obj.Phone = '5024141414';
            obj.Status = 'En Proceso';
            //Trabaja__c = sc.Trabaja__c,
            obj.FirstName = 'David';
            obj.LastName = 'Luarca';
			obj.RecordTypeid = [Select id From RecordType Where DeveloperName ='Natural' and SObjectType = 'Lead'].id; 
         
        
       // try {
            insert obj;
        //} catch (exception ex){
            
      //  } 
        
        test.stopTest();
        
    }
}