force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Correo_Empleado_Ficohsa__c.field-meta.xml
<CustomField>
    <fullName>Correo_Empleado_Ficohsa__c</fullName>
    <label>Correo Empleado Ficohsa</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <description>Identidad del candidato.</description>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Motivo de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>CLUB DE BENEFICIOS</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referido_por__c.field-meta.xml
<CustomField>
    <fullName>Referido_por__c</fullName>
    <label>Referido por</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/classes/testRefeXCanal.cls
@isTest
public class testRefeXCanal {
    
    static testMethod void controllerRefeXCanal(){
        
        test.startTest();
        controllerRefeXCanal pro =  new controllerRefeXCanal();
        pro.candidato = new Lead();
        pro.candidato.FirstName = 'carlo';
        pro.candidato.LastName = 'escoto';
        pro.guardarPop();
        
        pro.candidato.Phone = '886125101465';
        pro.candidato.Telefono_Trabajo__c = '227524005454';
        pro.candidato.Departamento__c = 'N/A';
        pro.guardarPop();
        pro.candidato.Phone = '88612510';
        pro.candidato.Telefono_Trabajo__c = '22752400';
        pro.guardarPop();
        pro.candidato.Identificacion__c = '0801199411013';
        pro.candidato.Identificacion__c = '';
        pro.candidato.Motivo_Contacto__c = 'Campaña HTML';
        pro.candidato.Referido_por__c = 'paola';
        pro.candidato.Correo_Empleado_Ficohsa__c = 'wendy.alvarado@ficohsa.com';
        pro.guardarPop();
        //prospecto.RecordTypeId = '';
        pro.candidato.Status = 'En Proceso';
        pro.candidato.LeadSource = 'Web';
        pro.candidato.RecordTypeid = [Select id From RecordType Where DeveloperName ='Natural' and SObjectType = 'Lead'].id; 
        pro.guardarPop();
        pro.candidato.Departamento__c = 'Francisco Morazan';
        
        pro.guardarPop();
        pro.pop3= true;
        pro.bloq2 = true;

        list<Lead> lista = new list<Lead>();


        pro.DesbAgen();
        pro.BloqAgen();
        
        pro.canalr = 'Agencias';
        pro.agenciar = ' --Ninguno-- ';
        pro.BloqAgen();
        pro.guardarPop();
        //insert pro.candidato;
        //pro.guardarPop();
        pro.reiniciar();
        
        controllerRefeXCanal pre =  new controllerRefeXCanal();
        pre.candidato = new Lead();
        
        pre.candidato.FirstName = '';
        pre.candidato.LastName = '';
        pre.guardarPop();
        pre.candidato.FirstName = 'pao';
        pre.candidato.LastName = '';
        pre.guardarPop();
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '8861251';
        pre.guardarPop();
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '88612510';
        pre.candidato.Telefono_Trabajo__c = '2275240000';
        pre.guardarPop();
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '88612510';
        pre.candidato.Telefono_Trabajo__c = '2275';
        pre.canalr = ' --Ninguno-- ';
        pre.guardarPop();
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '88612510';
        pre.candidato.Telefono_Trabajo__c = '22752400';
        pre.canalr = 'A';
        pre.candidato.Description = 'test';
        pre.candidato.Referido_por__c = '';
        pre.guardarPop();
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '88612510';
        pre.candidato.Telefono_Trabajo__c = '22752400';
        pre.canalr = 'A';
        pre.candidato.Description = 'test';
        pre.candidato.Referido_por__c = 'pao';
        pre.candidato.Correo_Empleado_Ficohsa__c = '';
        pre.guardarPop();
        
        pre.candidato.FirstName = 'w';
        pre.candidato.LastName = 'p';
        pre.candidato.Phone = '88612510';
        pre.candidato.Telefono_Trabajo__c = '22752400';
        pre.canalr = 'A';
        pre.candidato.Description = 'test';
        pre.candidato.Referido_por__c = 'pao';
        pre.candidato.Correo_Empleado_Ficohsa__c = 'wendy.alvarado@ficohsa.com';
        pre.guardarPop();
        
        test.stopTest();
        
    

	}

}