force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Asesor_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor_Comercial__c</fullName>
    <label>Código Asesor Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Entrega_KIT__c.field-meta.xml
<CustomField>
    <fullName>Entrega_KIT__c</fullName>
    <label>Entrega de KIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Si</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Espediente_Completo__c.field-meta.xml
<CustomField>
    <fullName>Espediente_Completo__c</fullName>
    <label>Expediente Completo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Si</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testcontroladorENtregaKitCom.cls
@isTest
public class testcontroladorENtregaKitCom {
	@isTest static void executeTest() {
        Usuarios_de_Pantallas__c usuario = new Usuarios_de_Pantallas__c ();
        usuario.Activo__c = true;
        usuario.Usuario__c = 'juan123';
        usuario.Contrase_a__c = 'juan123';
        usuario.name = 'Juan';
        usuario.Apellido__c='Perez';
        usuario.Email__c = 'juanperez@test.com';
        insert usuario;
        
        Reporte_calidad__C afiliacion = new Reporte_calidad__C();
        afiliacion.Codigo_Asesor_Comercial__c = usuario.Usuario__c;
        afiliacion.Entrega_KIT__C = 'S';
        afiliacion.Espediente_Completo__c = 'S';
        afiliacion.Identificacion__c = '1234';
        insert afiliacion;
        
        afiliacion = new Reporte_calidad__C();
        afiliacion.Codigo_Asesor_Comercial__c = usuario.Usuario__c;
        afiliacion.Entrega_KIT__C = 'S';
        afiliacion.Espediente_Completo__c = 'S';
        afiliacion.Identificacion__c = '12345';
        insert afiliacion;
            
        
        
        
        Test.StartTest();
        ApexPages.currentPage().getParameters().put('usuario',usuario.Usuario__c);
        controladorENtregaKitCom controller = new controladorENtregaKitCom();
        controller.idAfiliacion = controller.listAfiliaciones[0].id;
        controller.editar();
        controller.guardar();
        controller.idAfiliacion = controller.listAfiliaciones[0].id;
        controller.editar();
        controller.ValidacionIdentidad();
        
       // controller.ValidacionIdentidad();
        
        
        /*controller.listSubProductos = new list<selectOption>();
        controller.listEmpresas = new list<selectOption>();
        controller.NombreProducto = 'Test';
        controller.URLPagina = 'url';
        controller.reiniciar();
        controller.editar();
        controller.guardar();
        controller.ValidacionIdentidad();
        Test.StopTest();*/
    }
}