force-app/main/default/objects/Fecha_SYSDE__c/Fecha_SYSDE__c.object-meta.xml
<CustomObject>
    <description>Fecha cierre traída desde SYSDE.</description>
    <label>Fecha SYSDE</label>
    <nameField>
        <label>Nombre de Fecha_SYSDE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fecha SYSDES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retiro_Aprobacion__c/Retiro_Aprobacion__c.object-meta.xml
<CustomObject>
    <description>Objeto el cual almacenara todos los retiros para que se puedan aprobar, denegar o modificar.</description>
    <label>Retiro Aprobacion</label>
    <nameField>
        <label>Nombre de Retiro Aprobacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retiro Aprobaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Aprobacion_Final__c.field-meta.xml
<CustomField>
    <fullName>Aprobacion_Final__c</fullName>
    <description>Aprobación final realizada por la sub-gerente de operaciones. &apos;S&apos; o &apos;N&apos;</description>
    <label>Aprobacion Final</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/AprobacionM__c.field-meta.xml
<CustomField>
    <fullName>AprobacionM__c</fullName>
    <description>Aprobacion echa por Mariel &apos;S&apos; O &apos;N&apos;</description>
    <label>AprobacionM</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/banco_destino__c.field-meta.xml
<CustomField>
    <fullName>banco_destino__c</fullName>
    <label>banco destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/cheque__c.field-meta.xml
<CustomField>
    <fullName>cheque__c</fullName>
    <label>cheque</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/compara_monto__c.field-meta.xml
<CustomField>
    <fullName>compara_monto__c</fullName>
    <label>compara monto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/cuenta_bancaria__c.field-meta.xml
<CustomField>
    <fullName>cuenta_bancaria__c</fullName>
    <label>cuenta bancaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/cuenta_Destino__c.field-meta.xml
<CustomField>
    <fullName>cuenta_Destino__c</fullName>
    <label>cuenta Destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripcion</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Fecha_SalesForce__c.field-meta.xml
<CustomField>
    <fullName>Fecha_SalesForce__c</fullName>
    <label>Fecha SalesForce</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Fecha_Sysde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Sysde__c</fullName>
    <label>Fecha Sysde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Forma_Pago__c.field-meta.xml
<CustomField>
    <fullName>Forma_Pago__c</fullName>
    <label>Forma Pago</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/moneda__c.field-meta.xml
<CustomField>
    <fullName>moneda__c</fullName>
    <label>moneda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Monto_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Monto_Salesforce__c</fullName>
    <label>Monto Salesforce</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Monto_Sysde__c.field-meta.xml
<CustomField>
    <fullName>Monto_Sysde__c</fullName>
    <label>Monto Sysde</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/monto_total__c.field-meta.xml
<CustomField>
    <fullName>monto_total__c</fullName>
    <label>monto total</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Nombre_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Cliente__c</fullName>
    <label>Nombre Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Nombre_Propietario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Propietario__c</fullName>
    <label>Nombre Propietario</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Numero_Caso__c.field-meta.xml
<CustomField>
    <fullName>Numero_Caso__c</fullName>
    <label>Numero Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/Numero_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Numero_Referencia__c</fullName>
    <label>Numero Referencia</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/tasa_seguridad_poblacional__c.field-meta.xml
<CustomField>
    <fullName>tasa_seguridad_poblacional__c</fullName>
    <label>tasa seguridad poblacional</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/tipo_cuenta__c.field-meta.xml
<CustomField>
    <fullName>tipo_cuenta__c</fullName>
    <label>tipo cuenta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retiro_Aprobacion__c/fields/transferencia_ACH__c.field-meta.xml
<CustomField>
    <fullName>transferencia_ACH__c</fullName>
    <label>transferencia ACH</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testClassCRetiros.cls
@isTest
public class testClassCRetiros {
    static testMethod void controllerCRetiros()
    {
       test.startTest();
        Retiro_Aprobacion__c w = new Retiro_Aprobacion__c();
        w.Aprobacion_Final__c = '';
        w.AprobacionM__c = '';
        w.banco_destino__c = '';
        w.cheque__c = null;
        w.compara_monto__c = '';
        w.Cuenta__c = '';
        w.cuenta_bancaria__c = '';
		w.cuenta_Destino__c = '';
        w.CurrencyIsoCode = 'HNL';
        w.Descripcion__c = '';
        w.Fecha_SalesForce__c = DATE.valueOf('2019-05-21');
        w.Fecha_Sysde__c = DATE.valueOf('2019-05-21');
        w.Forma_Pago__c = '';
        w.moneda__c = '';
        w.Monto_Salesforce__c = '1';
        w.Monto_Sysde__c = null;
        w.monto_total__c = '1';
        w.Numero_Referencia__c = '1234567';
        w.tasa_seguridad_poblacional__c = '1';
        w.tipo_cuenta__c = '';
        w.transferencia_ACH__c = '1';
        w.AprobacionM__c = 'S';
        w.Nombre_Cliente__c = 'Paola';
        w.Numero_Caso__c = '1';
        w.Nombre_Propietario__c = 'Esteban';
        insert w;
        
        controllerCRetiros ra = new controllerCRetiros();
        
        list<cuadreRetiros> laa = new list<cuadreRetiros>();
        list<cuadreRetirosC> lee = new list<cuadreRetirosC>();
        list<cuadreRetirosP> llll = new list<cuadreRetirosP>();
        list<cuadreRetirosB> lllll = new list<cuadreRetirosB>();
        list<cuadreRetirosI> llllll = new list<cuadreRetirosI>();
        
        ra.conciliaRetiros();
        ra.mostrarTablaRetirosP = true;
        ra.mostrarTablaRetiros = true;
        ra.mostrarTablaRetirosC = true;
        ra.mostrarTablaRetirosB = true;
        ra.mostrarTablaRetirosI = true;
        ra.Num_CodReferencia = '1234567';
        ra.envioAprobacion();
        ra.envioAprobacionP();
        ra.envioAprobacionB();
        ra.envioAprobacionI();
        ra.Num_CodReferencia = '';
        ra.envioAprobacion();
        ra.envioAprobacionP();
        ra.envioAprobacionB();
        ra.envioAprobacionI();
        ra.enviarListaTotal();
        ra.enviarListaTotalP();
        ra.enviarListaTotalB();
        ra.enviarListaTotalI();
        test.stopTest();
    }

}