force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiario</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Numero Beneficiario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>FLOOR((TODAY() - Fecha_Nacimiento__c)/365.2425)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Identidad__c.field-meta.xml
<CustomField>
    <fullName>Identidad__c</fullName>
    <label>Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>ABUELO(A)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>AMIGO(A)</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CONYUGE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>CUÑADO(A)</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>HERMANO(A)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>HIJASTRO(A)</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>HIJO(A)</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>NIETO(A)</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>PADRE/MADRE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>PRIMO(A)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>SOBRINO(A)</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SUEGRO(A)</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>TIO(A)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>YERNO/NUERA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Primer_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Primer_Nombre__c</fullName>
    <label>Primer Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Segundo_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Segundo_Apellido__c</fullName>
    <label>Segundo Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Segundo_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_Nombre__c</fullName>
    <label>Segundo Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Direccion__c/Direccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para guardar las direcciones de clientes y prospectos.</description>
    <label>Direccion</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Numero Direccion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direccion__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relación con el cliente de las direcciones.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Identidad__c/Identidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>En este objeto se almacenan los tipos de documentos.</description>
    <label>Identidad</label>
</CustomObject>

force-app/main/default/objects/Telefono__c/Telefono__c.object-meta.xml
<CustomObject>
    <label>Telefono</label>
    <nameField>
        <label>Numero de Telefono</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telefonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/extensionSolicitudInfo.cls
public class extensionSolicitudInfo {
    public list<Beneficiario__c> hijos {get;Set;}
    public Beneficiario__c padre{get;set;}
    public Beneficiario__c madre{get;set;}
    
    public extensionSolicitudInfo(ApexPages.StandardController controller) {
        Opportunity opo = (Opportunity)controller.getRecord();
        hijos = new list<Beneficiario__c>();
        padre = new Beneficiario__c();
        madre = new Beneficiario__c();
        
        list<Beneficiario__c> benes = [Select Identidad__c,Parentesco__c, Primer_Apellido__c, Primer_Nombre__c,Segundo_Apellido__c, Segundo_Nombre__c
                                        ,Fecha_Nacimiento__c,Cliente__c,Telefono__c, direccion__c,edad__c
                                         From Beneficiario__c Where Oportunidad__c =: opo.id];
                                        
        For(Beneficiario__c b : benes){
            if(b.Parentesco__c == 'Padre')
                padre = b;
            else if( b.Parentesco__c == 'Madre')
                madre = b;
            else if( b.Parentesco__c == 'Hijo(a)')
                hijos.add(b);        
        }
                                                
    }

}