force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/FPC_InicioFinSubEstadosSLARC__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra fecha de inicio y fecha fin de cada estado del reporte de calidad.</description>
    <label>Inicio Fin Sub Estados SLA RC</label>
    <nameField>
        <displayFormat>IF-{0000000000}</displayFormat>
        <label>Nombre de Tiempos SLA RC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inicio Fin Sub Estados SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_FechaFin__c.field-meta.xml
<CustomField>
    <fullName>FPC_FechaFin__c</fullName>
    <label>Fecha Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>FPC_FechaInicio__c</fullName>
    <label>Fecha Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_ReporteCalidad__c.field-meta.xml
<CustomField>
    <fullName>FPC_ReporteCalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporte de Calidad</label>
    <referenceTo>Reporte_Calidad__c</referenceTo>
    <relationshipLabel>Inicio Fin Sub Estados SLA RC</relationshipLabel>
    <relationshipName>Inicio_Fin_Sub_Estados_SLA_RC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_TiempoConfigurado__c.field-meta.xml
<CustomField>
    <fullName>FPC_TiempoConfigurado__c</fullName>
    <label>Tiempo Configurado</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/FPC_TiemposSLARC__c.object-meta.xml
<CustomObject>
    <label>Tiempo SLA RC</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Tiempos SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiempos SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Codigo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Codigo__c</fullName>
    <label>Código</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FPC_PantallaRC__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Tiempo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Tiempo__c</fullName>
    <label>Tiempo (Horas)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/SubEstadoRCSF__c.field-meta.xml
<CustomField>
    <fullName>SubEstadoRCSF__c</fullName>
    <label>Sub Estado RC SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Tipo_Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Afiliacion__c</fullName>
    <label>Tipo Afiliacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Afiliacion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReporteCalidadTriggerHelper.cls
public class ReporteCalidadTriggerHelper {

    public static void asignarSubEstado(List<Reporte_Calidad__c> listRecords, Map<Id, Reporte_Calidad__c> mapRecords){
        for(Reporte_Calidad__c item: listRecords){
            if(item.Estado__c != mapRecords.get(item.Id).Estado__c && item.Estado__c == 'C'){
                item.SubEstadoRCSF__c = 'C';
            }
        }
    }
    
     public static void registraTiempoSLA(List<Reporte_Calidad__c> listRecords, Map<Id, Reporte_Calidad__c> mapRecords){
         Map<String, EstadoRC> mapRC = new Map<String, EstadoRC>(); 
         Map<String, Decimal> mapTiempo = new Map<String, Decimal>(); 
         for(Reporte_Calidad__c item: listRecords){
             EstadoRC estado = new EstadoRC();
             estado.recordId = item.Id;
             estado.tipoAfilaicion = item.Tipo_Afiliacion__c;
             
             if(getTipoAfiliacion(item.Tipo_Afiliacion__c) && ((item.SubEstadoRCSF__c != null && mapRecords == null) ||
                (mapRecords != null && item.SubEstadoRCSF__c != mapRecords.get(item.Id).SubEstadoRCSF__c))){
                    estado.estadoNuevo = item.SubEstadoRCSF__c;
                    estado.estadoAnterior = mapRecords != null ? mapRecords.get(item.Id).SubEstadoRCSF__c : null;
                    mapRC.put(item.Id, estado);
                }else if(!getTipoAfiliacion(item.Tipo_Afiliacion__c) && 
                         ((item.Estado__c != null && mapRecords == null) ||
                          (mapRecords != null && item.Estado__c != mapRecords.get(item.Id).Estado__c))){
                              estado.estadoNuevo = item.Estado__c;
                              estado.estadoAnterior = mapRecords != null ? mapRecords.get(item.Id).Estado__c : null;
                              mapRC.put(item.Id, estado);
                }
         }
         if(mapRC.size() > 0){
             for(FPC_TiemposSLARC__c item: [Select FPC_Tiempo__c, FPC_Codigo__c from FPC_TiemposSLARC__c ]){
                 mapTiempo.put(item.FPC_Codigo__c, item.FPC_Tiempo__c);
             }
             List<FPC_InicioFinSubEstadosSLARC__c> listTiempo = new List<FPC_InicioFinSubEstadosSLARC__c>();
             for(FPC_InicioFinSubEstadosSLARC__c item:  
                 [Select Id, FPC_EstadoSLA__c, FPC_ReporteCalidad__c, FPC_FechaInicio__c , FPC_FechaFin__c  
                  From FPC_InicioFinSubEstadosSLARC__c Where FPC_ReporteCalidad__c in : mapRC.keySet() and  FPC_FechaFin__c = null]){
                      //EstadoRC estado = mapRC.get(item.FPC_ReporteCalidad__c);
                      item.FPC_FechaFin__c = System.now();
                      listTiempo.add(item);
                  }
             for(String item: mapRC.keySet()){
                 EstadoRC estado = mapRC.get(item);
                 if(estado.estadoNuevo != 'C' && mapTiempo.containsKey(estado.estadoNuevo)){
                     FPC_InicioFinSubEstadosSLARC__c inicio = new FPC_InicioFinSubEstadosSLARC__c();
                     inicio.FPC_FechaInicio__c = System.now();
                     inicio.FPC_EstadoSLA__c = estado.estadoNuevo;
                     inicio.FPC_ReporteCalidad__c = item;
                     inicio.FPC_TiempoConfigurado__c = mapTiempo.containsKey(estado.estadoNuevo) ? mapTiempo.get(estado.estadoNuevo) : 0;
                     listTiempo.add(inicio); 
                 }
             }
             upsert listTiempo;
         }
    }

    public static Boolean getTipoAfiliacion(String tipoA){
        return (tipoA == 'FCA' || tipoA == 'TV' || tipoA == 'TF' || tipoA == 'BFK' || tipoA == 'PM' );
    }    
    public class EstadoRC{
        public String recordId;
        public String estadoNuevo;
        public String estadoAnterior;
        public String tipoAfilaicion;
    }
}