force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/FPC_InicioFinSubEstadosSLARC__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra fecha de inicio y fecha fin de cada estado del reporte de calidad.</description>
    <label>Inicio Fin Sub Estados SLA RC</label>
    <nameField>
        <displayFormat>IF-{0000000000}</displayFormat>
        <label>Nombre de Tiempos SLA RC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inicio Fin Sub Estados SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>FPC_FechaInicio__c</fullName>
    <label>Fecha Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_ReporteCalidad__c.field-meta.xml
<CustomField>
    <fullName>FPC_ReporteCalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporte de Calidad</label>
    <referenceTo>Reporte_Calidad__c</referenceTo>
    <relationshipLabel>Inicio Fin Sub Estados SLA RC</relationshipLabel>
    <relationshipName>Inicio_Fin_Sub_Estados_SLA_RC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/FPC_TiemposSLARC__c.object-meta.xml
<CustomObject>
    <label>Tiempo SLA RC</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Tiempos SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiempos SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FPC_PantallaRC__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/Oficial_X_Asesor__c.object-meta.xml
<CustomObject>
    <label>Oficial por Asesor</label>
    <nameField>
        <displayFormat>OS-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Asesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Codigo_Asesor__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor__c</fullName>
    <label>Código Asesor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CS</fullName>
                <label>Centro - Sur</label>
            </value>
            <value>
                <fullName>NO</fullName>
                <label>Nor - Occidental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Asesor_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor_Comercial__c</fullName>
    <label>Código Asesor Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <label>Oficial SAC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Tipo_Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Afiliacion__c</fullName>
    <label>Tipo Afiliacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Afiliacion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Perfil__c.field-meta.xml
<CustomField>
    <fullName>Perfil__c</fullName>
    <label>Perfil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SGS</fullName>
                <label>Sub Gerencia SAC</label>
            </value>
            <value>
                <fullName>OS</fullName>
                <label>Oficial SAC</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Jefatura Comercial</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Asesor Comercial</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Otro</label>
            </value>
            <value>
                <fullName>OP</fullName>
                <label>Operaciones</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>Supervisor SAC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControladorReporteCalidadSLA.cls
public class ControladorReporteCalidadSLA {
    
    public List<EnvioCorreoSLA.afilaicionSLA> listAfiliacionesSLA{get;set;}
    
    public List<SelectOption> listOficialSac{get;set;}
    public String sacSeleccionado{get;set;}
    public String sacSeleccionadoOP{get;set;}
    public Boolean filtroSac{get;set;}
    
    public List<SelectOption> listAsesorComercial{get;set;}
    public String asesorSeleccionado{get;set;}
    public Boolean filtroComercial{get;set;}
    
    public List<SelectOption> listReporteCalidad{get;set;}
    public String reporteSeleccionado{get;set;}
    public Boolean filtroReporteCalid{get;set;}
    
    public List<SelectOption> listEstados{get;set;}
    public String estadoSeleccionado{get;set;}
    public Boolean filtroEstado{get;set;}
    
    public List<SelectOption> listTipoAfiliacion{get;set;}
    public String tipoAfilSeleccionado{get;set;}
    public Boolean filtroAfiliacion{get;set;}
    
    String perfil;
    String usuario;
    public ControladorReporteCalidadSLA(){
        usuario = ApexPages.currentPage().getParameters().get('usuario');
        perfil = ApexPages.currentPage().getParameters().get('perfil');
        listAfiliacionesSLA = new List<EnvioCorreoSLA.afilaicionSLA>();
        
        Usuarios_de_Pantallas__c usuarioObj = [Select Perfil__c, Zona__c from Usuarios_de_Pantallas__c Where Usuario__c =:usuario];
        perfil = usuarioObj.Perfil__c;
        
        filtroSac = perfil == 'SGS' || perfil == 'OSP' || perfil == 'SS';
        filtroAfiliacion = true;
        filtroEstado = perfil == 'SGS' || perfil == 'OSP';
        filtroReporteCalid = true;
        filtroComercial = perfil == 'SGS' || perfil == 'OSP' || perfil == 'JC';
        
        sacSeleccionadoOP = '(';
        if(perfil == 'JC'){
            for(Usuarios_de_Pantallas__c item: [Select Usuario__c from Usuarios_de_Pantallas__c where perfil__c = 'AC' and Zona__c= :usuarioObj.Zona__c]){
                sacSeleccionadoOP += '\'' + item.Usuario__c + '\',';
            }
            sacSeleccionadoOP = sacSeleccionadoOP.substring(0, sacSeleccionadoOP.length() - 1);
        }
		sacSeleccionadoOP += ')';
        
        listOficialSac = new List<SelectOption>();
        listAsesorComercial = new List<SelectOption>();
        listOficialSac.add(new SelectOption('', ' -- Ninguno -- '));
        listAsesorComercial.add(new SelectOption('', ' -- Ninguno -- '));
        
        asesorSeleccionado = perfil == 'AC' ? usuario : '';
        sacSeleccionado = perfil == 'OS' ? usuario : '';
        
        List<String> listControl = new List<String>();
        
        for(oficial_x_asesor__C item: [select Oficial_SAC__r.name, Codigo_Oficial_SAC__c from oficial_x_asesor__C where Codigo_Oficial_SAC__c != null order by Oficial_SAC__r.name asc]){
            if(!listControl.contains(item.Codigo_Oficial_SAC__c)){
                listControl.add(item.Codigo_Oficial_SAC__c);
                listOficialSac.add(new selectOption(item.Codigo_Oficial_SAC__c, item.Oficial_SAC__r.name));
                
            }
        }
        listControl = new List<String>();
        String query = 'select Asesor__r.Name, Codigo_Asesor__c  from oficial_x_asesor__C Where Codigo_Asesor__c !=null';
        query += perfil == 'JC' ? ' and Codigo_Asesor__c in ' + sacSeleccionadoOP + '' : '';
        query += ' order by  Asesor__r.Name asc ';
        for(oficial_x_asesor__C item:DataBase.query(query) ){
            if(!listControl.contains(item.Codigo_Asesor__c)){
                listControl.add(item.Codigo_Asesor__c);
                listAsesorComercial.add(new selectOption(item.Codigo_Asesor__c, item.Asesor__r.Name));
                
            }
        }
        
        listTipoAfiliacion = getValoresPicklist('Reporte_Calidad__c', 'Tipo_Afiliacion__c');
        listEstados = getValoresPicklist('FPC_TiemposSLARC__c', 'FPC_EstadoSLA__c');
        listReporteCalidad = getValoresPicklist('Reporte_Calidad__c', 'Reporte_Calidad__c');
        //inicar();
    }
    
    public void iniciar(){
        try{
            String condicion = '';
            if(String.isNotBlank(sacSeleccionado)){
                condicion += ' and FPC_ReporteCalidad__r.Codigo_Oficial_SAC__c = \'' + sacSeleccionado + '\'';
            }/*else if(perfil == 'JO'){
                 condicion += ' and FPC_ReporteCalidad__r.Codigo_Oficial_SAC__c in ' + sacSeleccionadoOP + '';
                
            }*/
            if(String.isNotBlank(asesorSeleccionado)){
                condicion += ' and FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c = \'' + asesorSeleccionado + '\'';
            }
            if(String.isNotBlank(reporteSeleccionado)){
                condicion += ' and FPC_ReporteCalidad__r.Reporte_Calidad__c = \'' + reporteSeleccionado + '\'';
            }
            
            if(String.isNotBlank(estadoSeleccionado)){
                condicion += ' and FPC_ReporteCalidad__r.Estado__c = \'' + estadoSeleccionado + '\'';
            }else if(perfil == 'JC' || perfil == 'AC' ){
                 condicion += ' and FPC_ReporteCalidad__r.Estado__c in (\'N\',\'D\') ';
            }else if(perfil == 'JO' || perfil == 'OO'){
                 condicion += ' and FPC_ReporteCalidad__r.Estado__c in ( \'F\',\'A\') ';
            }else if(perfil == 'OS' ||  perfil == 'SS'){
                 condicion += ' and FPC_ReporteCalidad__r.Estado__c = \'V\'';
            }
            
            if(String.isNotBlank(tipoAfilSeleccionado)){
                condicion += ' and FPC_ReporteCalidad__r.Tipo_Afiliacion__c = \'' + tipoAfilSeleccionado + '\'';
            }
            BusinessDays SAC = new BusinessDays('Horario Oficiales SAC');
            BusinessDays comercial = new BusinessDays();
            System.debug('condicion: '+condicion);
            Boolean esSabado = System.now().format('EEEE') == 'Saturday'; //Saturday
            //condicion = ' and Id = \'a1q63000001HoflAAC\'';
            List<FPC_InicioFinSubEstadosSLARC__c> listTiemposSLA = EnvioCorreoSLA.getRecords(condicion);
            Map<String, List<EnvioCorreoSLA.afilaicionSLA>> mapCorreo = EnvioCorreoSLA.getMapaUsuario(listTiemposSLA);
            Map<String, String> mapEstados = EnvioCorreoSLA.getEstados('FPC_TiemposSLARC__c', 'FPC_EstadoSLA__c');
            Map<String, String> mapTipoAfiliacion = EnvioCorreoSLA.getEstados('Reporte_Calidad__c', 'Tipo_Afiliacion__c');
            System.debug('listTiemposSLA: '+listTiemposSLA.size());
            for(FPC_InicioFinSubEstadosSLARC__c tiempo: listTiemposSLA){
                Boolean flagSla = true;
                Boolean aplicaAgen = ReporteCalidadTriggerHelper.getTipoAfiliacion(tiempo.FPC_ReporteCalidad__r.Tipo_Afiliacion__c);
                if(aplicaAgen &&(tiempo.FPC_EstadoSLA__c == 'NS' || tiempo.FPC_EstadoSLA__c == 'VS' || tiempo.FPC_EstadoSLA__c == 'VF' || tiempo.FPC_EstadoSLA__c == 'PF')){
                    //DateTime horaActual = tiempo.FPC_FechaInicio__c;
                    DateTime fechaInicio = DateTime.newInstanceGmt(tiempo.FPC_FechaInicio__c.year(), tiempo.FPC_FechaInicio__c.month(), tiempo.FPC_FechaInicio__c.day()).addHours(14);
                    Integer horasTransc = calcularMinutos(tiempo.FPC_FechaInicio__c, SAC);
                    fechaInicio = fechaInicio.addDays(1);
                    while(fechaInicio < System.now()){
                        horasTransc += calcularMinutos(fechaInicio, SAC);
                        fechaInicio = fechaInicio.addDays(1);
                    }
                    
                    List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c), horasTransc);
                    mapCorreo.put(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c, listAfilaicion);
                    flagSla = false;
                }else if(aplicaAgen &&(tiempo.FPC_EstadoSLA__c == 'NC' || tiempo.FPC_EstadoSLA__c == 'DC' || tiempo.FPC_EstadoSLA__c == 'DA'|| tiempo.FPC_EstadoSLA__c == 'PS' || tiempo.FPC_EstadoSLA__c == 'PF')){
                    DateTime fechaInicio = DateTime.newInstanceGmt(tiempo.FPC_FechaInicio__c.year(), tiempo.FPC_FechaInicio__c.month(), tiempo.FPC_FechaInicio__c.day()).addHours(14);
                    Integer horasTransc = calcularMinutos(tiempo.FPC_FechaInicio__c, comercial);
                    fechaInicio = fechaInicio.addDays(1);
                    while(fechaInicio < System.now()){
                        horasTransc += calcularMinutos(fechaInicio, comercial);
                        fechaInicio = fechaInicio.addDays(1);
                    }
                    List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c), horasTransc);
                    mapCorreo.put(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c, listAfilaicion);
                    flagSla = false;
                    
                }
                System.debug('aplicaAgen: '+aplicaAgen);
                System.debug('flagSla: '+flagSla);
                System.debug('tiempo.FPC_EstadoSLA__c : '+tiempo.FPC_EstadoSLA__c );
                if(!aplicaAgen && flagSla && (tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V' || tiempo.FPC_EstadoSLA__c == 'D'|| tiempo.FPC_EstadoSLA__c == 'A')){
                    DateTime fechaInicio = DateTime.newInstanceGmt(tiempo.FPC_FechaInicio__c.year(), tiempo.FPC_FechaInicio__c.month(), tiempo.FPC_FechaInicio__c.day()).addHours(14);
                    BusinessDays calendario = tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V' ? SAC : comercial;
                    Integer horasTransc = calcularMinutos(tiempo.FPC_FechaInicio__c, calendario);
                    fechaInicio = fechaInicio.addDays(1);
                    while(fechaInicio < System.now()){
                        horasTransc += calcularMinutos(fechaInicio, calendario);
                        fechaInicio = fechaInicio.addDays(1);
                    }
                    if(tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V'){
                        List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c), horasTransc);
                        mapCorreo.put(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c, listAfilaicion);
                    }else{
                        List<EnvioCorreoSLA.afilaicionSLA>listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c), horasTransc);
                        mapCorreo.put(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c, listAfilaicion);
                    }
                }
                
            }
            listAfiliacionesSLA = new List<EnvioCorreoSLA.afilaicionSLA>();
            for(String user1 : mapCorreo.keySet()){
                for(EnvioCorreoSLA.afilaicionSLA item: mapCorreo.get(user1)){
                    item.estado =  mapEstados.get(item.estado);
                    item.afiliacion =  mapTipoAfiliacion.get(item.afiliacion);
                    listAfiliacionesSLA.add(item);
                }
            }
            System.debug('listAfiliacionesSLA '+json.serialize(listAfiliacionesSLA));
            if(listAfiliacionesSLA.isEmpty()){
                ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.warning, 'No se han encontrado registros para mostrar.'));
            }
        }catch(Exception ex){
            System.debug('Error: '+ex.getMessage()+', Línea: '+ex.getLineNumber());
            ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'Ha ocurrido un error, por favor contacte a su administrador.'));
        }
    }
    
    public static Integer calcularMinutos(DateTime fechaInicio, BusinessDays calendario){
        Integer horasTransc = 0;
        fechaInicio = fechaInicio.hour() < 8 ? DateTime.newInstanceGmt(fechaInicio.year(), fechaInicio.month(), fechaInicio.day()).addHours(14) : fechaInicio;
        DateTime horaHasta;
        String diaLetras = fechaInicio.format('EEEE');// == 'Saturday';
        Integer horasMas = diaLetras == 'Saturday' ? 12 : 17;
        if(System.now().day() != fechaInicio.day() || System.now().year() != fechaInicio.year() || System.now().month() != fechaInicio.month()){
            horaHasta = DateTime.newInstanceGmt(fechaInicio.year(), fechaInicio.month(), fechaInicio.day(), horasMas + 6, 0, 0);
        }else{
            horaHasta = System.now().hour() > horasMas ? 
                DateTime.newInstanceGmt(fechaInicio.year(), fechaInicio.month(), fechaInicio.day(), horasMas + 6, 0, 0) :
            system.now();
        }
        DateTime horaActual = fechaInicio;
        if(calendario.isWorkingDay(DateTime.newInstanceGmt(fechaInicio.year(), fechaInicio.month(), fechaInicio.day(), 16,0,0))){
            while(horaActual.addHours(1) <= horaHasta){
                horaActual = horaActual.addHours(1);
                horasTransc += 60;
            } 
            while(horaActual.addMinutes(1) <= horaHasta){
                horaActual = horaActual.addMinutes(1);
                horasTransc ++;
            } 
        }
        System.debug('fechaInicio '+fechaInicio +' ---  hour '+fechaInicio.hour()+' ----- horasTransc '+horasTransc);
        return horasTransc;
    }
    
    public  List<SelectOption> getValoresPicklist(String objApiName, String fieldApiName){
        List<SelectOption> listOptiones = new List<SelectOption>();
        listOptiones.add(new SelectOption('', ' -- Ninguno -- '));
        SObjectType objectType = Schema.getGlobalDescribe().get(objApiName);
        List<Schema.PicklistEntry> ple = objectType.getDescribe()
            .fields.getMap()
            .get(fieldApiName)
            .getDescribe().getPickListValues();
        for(Schema.PicklistEntry entry : ple)  {
            listOptiones.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return listOptiones;
    }
    
    
}