force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/FPC_InicioFinSubEstadosSLARC__c.object-meta.xml
<CustomObject>
    <description>Objeto que registra fecha de inicio y fecha fin de cada estado del reporte de calidad.</description>
    <label>Inicio Fin Sub Estados SLA RC</label>
    <nameField>
        <displayFormat>IF-{0000000000}</displayFormat>
        <label>Nombre de Tiempos SLA RC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inicio Fin Sub Estados SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>FPC_FechaInicio__c</fullName>
    <label>Fecha Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FPC_InicioFinSubEstadosSLARC__c/fields/FPC_ReporteCalidad__c.field-meta.xml
<CustomField>
    <fullName>FPC_ReporteCalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporte de Calidad</label>
    <referenceTo>Reporte_Calidad__c</referenceTo>
    <relationshipLabel>Inicio Fin Sub Estados SLA RC</relationshipLabel>
    <relationshipName>Inicio_Fin_Sub_Estados_SLA_RC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/FPC_TiemposSLARC__c.object-meta.xml
<CustomObject>
    <label>Tiempo SLA RC</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Tiempos SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiempos SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_EstadoSLA__c.field-meta.xml
<CustomField>
    <fullName>FPC_EstadoSLA__c</fullName>
    <label>Estado SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FPC_PantallaRC__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/Oficial_X_Asesor__c.object-meta.xml
<CustomObject>
    <label>Oficial por Asesor</label>
    <nameField>
        <displayFormat>OS-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Asesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Codigo_Asesor__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor__c</fullName>
    <label>Código Asesor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Asesor_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor_Comercial__c</fullName>
    <label>Código Asesor Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <label>Oficial SAC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Tipo_Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Afiliacion__c</fullName>
    <label>Tipo Afiliacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Afiliacion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControladorReporteCaldiadSLA.cls
public class ControladorReporteCaldiadSLA {
    
    public List<EnvioCorreoSLA.afilaicionSLA> listAfiliacionesSLA{get;set;}
    
    public List<SelectOption> listOficialSac{get;set;}
    public String sacSeleccionado{get;set;}
    public Boolean filtroSac{get;set;}
    
    public List<SelectOption> listAsesorComercial{get;set;}
    public String asesorSeleccionado{get;set;}
    public Boolean filtroComercial{get;set;}
    
    public List<SelectOption> listReporteCalidad{get;set;}
    public String reporteSeleccionado{get;set;}
    public Boolean filtroReporteCalid{get;set;}
    
    public List<SelectOption> listEstados{get;set;}
    public String estadoSeleccionado{get;set;}
    public Boolean filtroEstado{get;set;}
    
    public List<SelectOption> listTipoAfiliacion{get;set;}
    public String tipoAfilSeleccionado{get;set;}
    public Boolean filtroAfiliacion{get;set;}
    
    String perfil;
    String usuario;
    public ControladorReporteCaldiadSLA(){
        usuario = ApexPages.currentPage().getParameters().get('usuario');
        perfil = ApexPages.currentPage().getParameters().get('perfil');
        
        filtroSac = true;
        filtroAfiliacion = true;
        filtroEstado = true;
        filtroReporteCalid = true;
        filtroComercial = true;
        
        listOficialSac = new List<SelectOption>();
        listAsesorComercial = new List<SelectOption>();
        
        List<String> listControl = new List<String>();
        
        for(oficial_x_asesor__C item: [select Oficial_SAC__r.name, Codigo_Oficial_SAC__c from oficial_x_asesor__C where Codigo_Oficial_SAC__c != null order by Oficial_SAC__r.name asc]){
            if(!listControl.contains(item.Codigo_Oficial_SAC__c)){
                listControl.add(item.Codigo_Oficial_SAC__c);
                listOficialSac.add(new selectOption(item.Codigo_Oficial_SAC__c, item.Oficial_SAC__r.name));
                
            }
        }
        listControl = new List<String>();
        for(oficial_x_asesor__C item: [select Asesor__r.Name, Codigo_Asesor__c  from oficial_x_asesor__C Where Codigo_Asesor__c !=null order by  Asesor__r.Name asc]){
            if(!listControl.contains(item.Codigo_Asesor__c)){
                listControl.add(item.Codigo_Asesor__c);
                listAsesorComercial.add(new selectOption(item.Codigo_Asesor__c, item.Asesor__r.Name));
                
            }
        }
        
        listTipoAfiliacion = getValoresPicklist('Reporte_Calidad__c', 'Tipo_Afiliacion__c');
        listEstados = getValoresPicklist('FPC_TiemposSLARC__c', 'FPC_EstadoSLA__c');
        listReporteCalidad = getValoresPicklist('Reporte_Calidad__c', 'Reporte_Calidad__c');
       
        //inicar();
    }
    
    public static  List<SelectOption> getValoresPicklist(String objApiName, String fieldApiName){
        List<SelectOption> listOptiones = new List<SelectOption>();
        listOptiones.add(new SelectOption('', ' -- Ninguno -- '));
        SObjectType objectType = Schema.getGlobalDescribe().get(objApiName);
        List<Schema.PicklistEntry> ple = objectType.getDescribe()
            .fields.getMap()
            .get(fieldApiName)
            .getDescribe().getPickListValues();
        for(Schema.PicklistEntry entry : ple)  {
            listOptiones.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return listOptiones;
    }
    
    public void inicar(){
        try{
            String condicion = perfil == 'SAC' ? ' and FPC_ReporteCalidad__r.Codigo_Oficial_SAC__c = \'' + usuario + '\' ' : ' and FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c = \'' + usuario + '\' ';
            BusinessDays SAC = new BusinessDays('Horario Oficiales SAC');
            BusinessDays comercial = new BusinessDays();
            List<FPC_InicioFinSubEstadosSLARC__c> listTiemposSLA = EnvioCorreoSLA.getRecords(condicion);
            Map<String, List<EnvioCorreoSLA.afilaicionSLA>> mapCorreo = EnvioCorreoSLA.getMapaUsuario(listTiemposSLA);
            Map<String, String> mapEstados = EnvioCorreoSLA.getEstados('FPC_TiemposSLARC__c', 'FPC_EstadoSLA__c');
            Map<String, String> mapTipoAfiliacion = EnvioCorreoSLA.getEstados('Reporte_Calidad__c', 'Tipo_Afiliacion__c');
            System.debug('listTiemposSLA: '+listTiemposSLA);
            for(FPC_InicioFinSubEstadosSLARC__c tiempo: listTiemposSLA){
                Boolean flagSla = true;
                if(perfil == 'SAC' &&
                  ReporteCalidadTriggerHelper.getTipoAfiliacion(tiempo.FPC_ReporteCalidad__r.Tipo_Afiliacion__c) && (tiempo.FPC_EstadoSLA__c == 'NS' || tiempo.FPC_EstadoSLA__c == 'VS' || tiempo.FPC_EstadoSLA__c == 'VF'
                   || tiempo.FPC_EstadoSLA__c == 'PS' || tiempo.FPC_EstadoSLA__c == 'PF')){
                        Integer horasTransc = SAC.getNoOfBusinessDaysBetweenDates(tiempo.FPC_FechaInicio__c, System.now()) * 8;
                        horasTransc -= horasTransc > 0 ? 8 : 0;
                        Integer horasDiaActual = 18 - tiempo.FPC_FechaInicio__c.hour();
                        horasTransc += horasDiaActual > 8 ? 8 : horasDiaActual;
                        System.debug(tiempo.FPC_FechaInicio__c.hour()+' horasTransc2: '+horasTransc);
                        List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c), horasTransc);
                        mapCorreo.put(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c, listAfilaicion);
                        flagSla = false;
                        
                    }
                if(perfil != 'SAC' &&
                   ReporteCalidadTriggerHelper.getTipoAfiliacion(tiempo.FPC_ReporteCalidad__r.Tipo_Afiliacion__c) 
                   &&(tiempo.FPC_EstadoSLA__c == 'NC' || tiempo.FPC_EstadoSLA__c == 'DC' || tiempo.FPC_EstadoSLA__c == 'DA'
                   || tiempo.FPC_EstadoSLA__c == 'PS' || tiempo.FPC_EstadoSLA__c == 'PF')){
                        Integer horasTransc = comercial.getNoOfBusinessDaysBetweenDates(tiempo.FPC_FechaInicio__c, System.now()) * 8;
                        horasTransc -= horasTransc > 0 ? 8 : 0;
                        Integer horasDiaActual = 18 - tiempo.FPC_FechaInicio__c.hour();
                        horasTransc += horasDiaActual > 8 ? 8 : horasDiaActual;
                        List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c), horasTransc);
                        mapCorreo.put(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c, listAfilaicion);
                       flagSla = false;
                        
                    }
                if(!ReporteCalidadTriggerHelper.getTipoAfiliacion(tiempo.FPC_ReporteCalidad__r.Tipo_Afiliacion__c) && flagSla &&
                   (tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V' || tiempo.FPC_EstadoSLA__c == 'D'
                    || tiempo.FPC_EstadoSLA__c == 'A')){
                        Integer horasTransc = comercial.getNoOfBusinessDaysBetweenDates(tiempo.FPC_FechaInicio__c, System.now()) * 8;
                        if(tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V'){
                            horasTransc = SAC.getNoOfBusinessDaysBetweenDates(tiempo.FPC_FechaInicio__c, System.now()) * 8;
                        }
                        horasTransc -= horasTransc > 0 ? 8 : 0;
                        Integer horasDiaActual = 18 - tiempo.FPC_FechaInicio__c.hour();
                        horasTransc += horasDiaActual > 8 ? 8 : horasDiaActual;
                        if(tiempo.FPC_EstadoSLA__c == 'N' || tiempo.FPC_EstadoSLA__c == 'V'){
                            List<EnvioCorreoSLA.afilaicionSLA> listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c), horasTransc);
                            mapCorreo.put(tiempo.FPC_ReporteCalidad__r.codigo_oficial_sac__c, listAfilaicion);
                        }else{
                            List<EnvioCorreoSLA.afilaicionSLA>listAfilaicion = EnvioCorreoSLA.getTiempoSLA(tiempo, mapCorreo.get(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c), horasTransc);
                            mapCorreo.put(tiempo.FPC_ReporteCalidad__r.Codigo_Asesor_Comercial__c, listAfilaicion);
                        }
                    }
            }
            listAfiliacionesSLA = new List<EnvioCorreoSLA.afilaicionSLA>();
            for(EnvioCorreoSLA.afilaicionSLA item: mapCorreo.get(usuario)){
                item.estado =  mapEstados.get(item.estado);
                item.afiliacion =  mapTipoAfiliacion.get(item.afiliacion);
                listAfiliacionesSLA.add(item);
            }
        }catch(Exception ex){
            System.debug('Error: '+ex.getMessage()+', Línea: '+ex.getLineNumber());
        }
    }
}