force-app/main/default/objects/CambioAsesor__c/CambioAsesor__c.object-meta.xml
<CustomObject>
    <description>Muestra el Cambio del asesor de un numero de cuenta, arrastrando un archivo excel</description>
    <label>CambioAsesor</label>
    <nameField>
        <label>Nombre de CambioAsesor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CambioAsesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CambioAsesor__c/fields/Asesor_Actual__c.field-meta.xml
<CustomField>
    <fullName>Asesor_Actual__c</fullName>
    <description>Contiene el nombre del asesor actual del cliente.</description>
    <inlineHelpText>Contiene el nombre del asesor actual del cliente</inlineHelpText>
    <label>Asesor Actual</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Asesor_Nuevo__c.field-meta.xml
<CustomField>
    <fullName>Asesor_Nuevo__c</fullName>
    <description>Contiene el nuevo asesor del cliente.</description>
    <inlineHelpText>Contiene el nuevo asesor del cliente.</inlineHelpText>
    <label>Asesor Nuevo</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <description>Contiene el nombre de la empresa al que pertenece el cliente</description>
    <inlineHelpText>Debe contener el nombre de la empresa al que pertenece el cliente</inlineHelpText>
    <label>Empresa</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Contiene los diferentes estados que tiene el documento.</description>
    <inlineHelpText>Contiene los diferentes estados que tiene el documento.</inlineHelpText>
    <label>Estado</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Fecha_Inclusion_Carga__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inclusion_Carga__c</fullName>
    <description>Captura la fecha del usuario que realiza la carga del archivo</description>
    <label>Fecha_Inclusion_Carga</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Identidad__c.field-meta.xml
<CustomField>
    <fullName>Identidad__c</fullName>
    <description>Contiene el numero de identificación del cliente.</description>
    <inlineHelpText>Contiene el numero de identificación del cliente.</inlineHelpText>
    <label>Identidad</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Identificador_Carga__c.field-meta.xml
<CustomField>
    <fullName>Identificador_Carga__c</fullName>
    <description>Identificador único por cada carga de archivo excel</description>
    <label>Identificador_Carga</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/NoCuenta__c.field-meta.xml
<CustomField>
    <fullName>NoCuenta__c</fullName>
    <description>Contiene el numero de cuenta del cliente</description>
    <inlineHelpText>Contiene el numero de cuenta del cliente</inlineHelpText>
    <label>NoCuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_Asesor_actual__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Asesor_actual__c</fullName>
    <description>Contiene el nombre del asesor</description>
    <inlineHelpText>Muestra el nombre del asesor actual</inlineHelpText>
    <label>Nombre Asesor actual</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_asesor_nuevo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_asesor_nuevo__c</fullName>
    <description>Contiene el nombre del asesor nuevo.</description>
    <inlineHelpText>Muestra el nombre del asesor nuevo.</inlineHelpText>
    <label>Nombre asesor nuevo</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_Completo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Completo__c</fullName>
    <description>Contiene el nombre completo al que corresponde</description>
    <inlineHelpText>Debe contener el nombre  completo del cliente</inlineHelpText>
    <label>Nombre_Completo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Situaci_n__c.field-meta.xml
<CustomField>
    <fullName>Situaci_n__c</fullName>
    <description>Muestra si estan correctos los datos en la tabla</description>
    <inlineHelpText>Si a parece OK esta correcto, si aparece NO COINCIDE es que hay un error</inlineHelpText>
    <label>Situación</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <description>Usuario para pantalla Cambio de Asesor</description>
    <inlineHelpText>Para definir el usuario que realiza la carga.</inlineHelpText>
    <label>Usuario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Identidad__c/Identidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>En este objeto se almacenan los tipos de documentos.</description>
    <label>Identidad</label>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testCambioAsesor.cls
@isTest 
public class testCambioAsesor {
    static testMethod void CambioAsesor()
    {
        test.startTest();        
        CambioAsesor__c archivo = new CambioAsesor__c  (NoCuenta__c= '24280',Nombre_Completo__c= 'MEJIA LOPEZ FRANCISCO JOSE',
                                                        Identidad__c= '0801198601371',Empresa__c='BANCO FINANCIERA COMERCIAL HONDUREÑA, S.A.', 
                                                        Nombre_Asesor_actual__c='URRUTIA BAIRES ALEYDA SABRINA', Nombre_asesor_nuevo__c='RUBIO NIETO WENDY GERALDINA', 
                                                        Asesor_Nuevo__c='HN19964', Asesor_Actual__c='HN22258',Situaci_n__c='', Estado__c='', 
                                                        usuario__c='HN19577',Fecha_Inclusion_Carga__c= string.valueOf(date.today()),Identificador_Carga__c= 3); 
        insert archivo;
        
        /*Bitacora_Masivo__c bita = new Bitacora_Masivo__c (Actividades__c ='prueba', Estado__c ='aprob', 
                                                          Fecha__c = date.today(), Pantalla__c ='prueba1', Usuario__c = 'hn1263');      
        
        insert bita;*/
              
        String objeto;       
        objeto=CambioAsesor.llenarObjetos('"prueba"');
        objeto=CambioAsesor.llenarObjetos('""');
        objeto=CambioAsesor.llenarObjetos('prueba');
        
        string ags=''; 
	    string encabezado='"NCuenta","Identidad","Asesor Actual","Asesor Nuevo"';
        string cuerpo='"21528", "08011922073","N21529","N19778"';
        string stringCSV= encabezado+'\n'+ cuerpo;
        classWRetorno2 error = new classWRetorno2();
        error = CambioAsesor.SUbirInformacion(stringCSV, 'UserPru', ags); 
        
        String prueba;
        String prueba2;
        String pruebaCSV;
        prueba='"NCuenta","Identidad","Asesor Actual","Asesor Nuevo"';
        prueba2='"21528", "08011922073","N21529","N19778"';
        pruebaCSV=prueba+prueba2;
        error = CambioAsesor.SUbirInformacion(pruebaCSV, 'UserPru' ,ags);
        
        String prueba3;
        String prueba4;
        String pruebaCSV1;
        prueba='"NCuenta","Identidad","Asesor Actual","Asesor Nuevo"';
        prueba2='"21528", "08011922073","N21529","N19778"';
        pruebaCSV1=prueba3+prueba4;
        error = CambioAsesor.SUbirInformacion(pruebaCSV1, 'UserPru' ,ags);       
       
               
        CambioAsesor p = new CambioAsesor();
        
        p.EnvioD=false;
        p.modifi=false;
        p.rechazarM =false;
        p.Cont = 0;
        p.total = 0;
        p.Motivo= ''; 
        p.valida = false;
        p.mTabla1 =false;
        p.Num_CodReferencia =3;
        p.Num_Cod =4;
        p.VerContenido =false;
       
        p.usuario = 'usuario';
        p.usuario1 = 'usuario1';
        p.mailA='mailA';
        p.mailD='mailD';
                
        p.salir();
        p.aprobarM =false;
        p.rechazarM1 =false;
        p.VentanaPlanilla = false; 
        p.aprobado();
        p.cambio();
        p.Cambiar = true;
        p.rechazoPla();
        p.ocul();       
        
                
        list<CambioAsesor__c> CambioAsesor = new list<CambioAsesor__c>();
        list<CambioAsesor__c> CambioAses = new list<CambioAsesor__c>();
        p.VerPlanilla();                        
        list<ContenidoCambioAsesor> validaDatos= new list<ContenidoCambioAsesor>();
        //list<ContenidoCambioAsesor> validaDatos1= new list<ContenidoCambioAsesor>();
        list<CambioAsesor__c> ModifList = new list<CambioAsesor__c>(); 
        Usuarios_de_Pantallas__c InfoUsuario = new Usuarios_de_Pantallas__c ();
               
       
        //list<CambioAsesor__c> CambioAsesor1 = CambioAsesor;        
        /*integer idP;
        CambioAsesor__c carga1 = new CambioAsesor__c (Identificador_Carga__c= 3) ;
        idP = integer.valueOf(carga1.Identificador_Carga__c);                
        insert carga1;    */                 
                
        p.Limpiar();
               
        p.ModificarContenido(); 
        
       	p.ValidarContenido();
       
        p.VerContenido();
                
        p.VerPlanillaArchivo();
        
        p.MostrarVentanaPlanilla();
        //list<CambioAsesor__c> CambioAses = new list<CambioAsesor__c>(); 
       
		p.paraMotivo();
                
        p.aprobarPlanilla();
        //p.total =null;
        //update CambioAsesor;        
        
        ContenidoCambioAsesor ClaseDatos = new ContenidoCambioAsesor('NCuenta','Identidad','AsesorActual','Asesornuevo',
                                                                     'Registrador','Autorizador',1, date.today(),'Descripcion');      
              
        Api_CambioAsesor apii = new Api_CambioAsesor();  
       //api_CambioAsesor.actualizaCambioAsesor
        
        p.denegarPlanilla();  
        /*p.EnvioCorreoAprobado();
        p.EnvioCorreoDenegado();*/
        
        /*Bitacora_Masivo__c bita = new Bitacora_Masivo__c ();
        bita.Actividades__c = ''; 
        bita.Estado__c='denegar';
        bita.Fecha__c = date.today() ;
        bita.Pantalla__c ='prueba';
        bita.Usuario__c='1234';*/
        
        //EL API
			
        Api_CambioAsesor.classRespuestaCambioAsesor A= new Api_CambioAsesor.classRespuestaCambioAsesor();
        A.Certificado='325';
        A.Mensaje='325';   
        A.nEmpresa ='prueba';
        A.nombreCliente ='Maria';
        A.nombreAsesoractual= 'Carla Hernandez';
        A.nombreAsesornuevo = 'Jorge Barahona';         
        
        CambioAsesor__c carga = new CambioAsesor__c (Identificador_Carga__c = 1);  
        insert carga;
        
        A.ModificarEstado = [select Situaci_n__c, NoCuenta__c,Empresa__c , Nombre_Completo__c,Nombre_Asesor_actual__c,Nombre_asesor_nuevo__c, Identificador_Carga__c                              
                             from CambioAsesor__c where Identificador_Carga__c =: 1];
 
        
        A.sizeResu = 5;
        A.sizeModi = 5;     
        A.IdCarga = 2;  
        
        enviarCambioAsesor env = new enviarCambioAsesor(validaDatos); 
        Api_CambioAsesor.actualizaCambioAsesor(env);
        Api_CambioAsesor.BitacoraDCambioAsesor(env);      
		                
        test.stopTest();
    }
}