force-app/main/default/objects/CambioAsesor__c/CambioAsesor__c.object-meta.xml
<CustomObject>
    <description>Muestra el Cambio del asesor de un numero de cuenta, arrastrando un archivo excel</description>
    <label>CambioAsesor</label>
    <nameField>
        <label>Nombre de CambioAsesor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CambioAsesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CambioAsesor__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <description>Contiene el nombre de la empresa al que pertenece el cliente</description>
    <inlineHelpText>Debe contener el nombre de la empresa al que pertenece el cliente</inlineHelpText>
    <label>Empresa</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Identificador_Carga__c.field-meta.xml
<CustomField>
    <fullName>Identificador_Carga__c</fullName>
    <description>Identificador único por cada carga de archivo excel</description>
    <label>Identificador_Carga</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/NoCuenta__c.field-meta.xml
<CustomField>
    <fullName>NoCuenta__c</fullName>
    <description>Contiene el numero de cuenta del cliente</description>
    <inlineHelpText>Contiene el numero de cuenta del cliente</inlineHelpText>
    <label>NoCuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_Asesor_actual__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Asesor_actual__c</fullName>
    <description>Contiene el nombre del asesor</description>
    <inlineHelpText>Muestra el nombre del asesor actual</inlineHelpText>
    <label>Nombre Asesor actual</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_asesor_nuevo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_asesor_nuevo__c</fullName>
    <description>Contiene el nombre del asesor nuevo.</description>
    <inlineHelpText>Muestra el nombre del asesor nuevo.</inlineHelpText>
    <label>Nombre asesor nuevo</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Nombre_Completo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Completo__c</fullName>
    <description>Contiene el nombre completo al que corresponde</description>
    <inlineHelpText>Debe contener el nombre  completo del cliente</inlineHelpText>
    <label>Nombre_Completo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CambioAsesor__c/fields/Situaci_n__c.field-meta.xml
<CustomField>
    <fullName>Situaci_n__c</fullName>
    <description>Muestra si estan correctos los datos en la tabla</description>
    <inlineHelpText>Si a parece OK esta correcto, si aparece NO COINCIDE es que hay un error</inlineHelpText>
    <label>Situación</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Api_CambioAsesor.cls
public class Api_CambioAsesor {

    public class classRespuestaCambioAsesor
    {
        public string Certificado { get; set; }
        public string Mensaje { get; set; }
        public string nEmpresa { get; set; }
        public string nombreCliente { get; set; }
        public string nombreAsesoractual { get; set; }
        public string nombreAsesornuevo { get; set; }
        
        //agregado 
        public list<CambioAsesor__c> ModificarEstado {get;set;}
        public integer sizeModi {get;set;}
        public integer sizeResu {get;set;}
       // public list<CambioAsesor__c> Carga {get;set;}
        public integer idCarga {get;set;}

    }
    
 /*      public class Prueba
    {
        public List<classRespuestaCambioAsesor> PruebaAse {get; set;}      
    } */
        
    public static list<classRespuestaCambioAsesor> CambioAsesor(enviarCambioAsesor claseEnvio)
    {
        
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
		request.setEndpoint(url + 'api/CambioAsesor');
        
        classRespuestaCambioAsesor fcsd= new classRespuestaCambioAsesor(); //agregado 10042019
        list<classRespuestaCambioAsesor> resultado = new list<classRespuestaCambioAsesor>();
		
		String respuesta = '';
		system.debug('Entro al REST del EDC');
		try{
			 			
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(claseEnvio);
			String cons = 'contenido=' + envio.contenido;
			system.debug(cons);		
			request.setBody(cons);	
			HttpResponse response/*= http.send(request)*/;
	    	//respuesta = response.getBody();
            if(test.isRunningTest())
            { 
                respuesta='{"classRespuestaCambioAsesor":[{"Certificado":null,"Mensaje":"A"}]}';
            	fcsd = (classRespuestaCambioAsesor)System.JSON.deserialize(respuesta, classRespuestaCambioAsesor.class);
            }
            
            else{
                response = http.send(request); 
               
            }
             
            resultado = (list<classRespuestaCambioAsesor>)JSON.deserialize(response.getBody(), list<classRespuestaCambioAsesor>.class);
            
           //respuesta = String.valueOf(resultado);
           //system.debug('Respuesta'+ resultado);
           //system.debug('Respuesta_texto '+ respuesta); 
                      
            fcsd.sizeResu = resultado.size();
            
            CambioAsesor__c carga = new CambioAsesor__c ();             
            carga = [select Identificador_Carga__c from CambioAsesor__c order by Identificador_Carga__c desc limit 1] ;
            fcsd.idCarga = integer.valueOf(carga.Identificador_Carga__c);   
                       
            fcsd.ModificarEstado  = [select Situaci_n__c, NoCuenta__c,Empresa__c , Nombre_Completo__c,Nombre_Asesor_actual__c,Nombre_asesor_nuevo__c, Identificador_Carga__c                              
                                   from CambioAsesor__c where Identificador_Carga__c =: fcsd.idCarga];
            
            fcsd.sizeModi = fcsd.ModificarEstado.size();
              for(integer i=0; i<fcsd.sizeModi; i++)
              {
                for(integer k=0; k<fcsd.sizeResu; k++)
                {
                	if(fcsd.ModificarEstado[i].NoCuenta__c == resultado[k].Certificado)
                	{
                        fcsd.ModificarEstado[i].Situaci_n__c = resultado[k].Mensaje;
                        fcsd.ModificarEstado[i].Empresa__c = resultado[k].nEmpresa;
                        fcsd.ModificarEstado[i].Nombre_Completo__c = resultado[k].nombreCliente;
                        fcsd.ModificarEstado[i].Nombre_Asesor_actual__c = resultado[k].nombreAsesoractual;
                        fcsd.ModificarEstado[i].Nombre_asesor_nuevo__c = resultado[k].nombreAsesornuevo;	
                    }
                }
            }            
             update fcsd.ModificarEstado;
			/*	for(integer i=0; i<resultado.size(); i++)
            {
				CambioAsesor__c ModificarEstado = new CambioAsesor__c();
                
                ModificarEstado  = [select Situaci_n__c, Empresa__c , Nombre_Completo__c,Nombre_Asesor_actual__c,Nombre_asesor_nuevo__c                                  
                                   from CambioAsesor__c 
                                    where NoCuenta__c =: resultado[i].Certificado ];
                	
                ModificarEstado.Situaci_n__c = resultado[i].Mensaje;
                ModificarEstado.Empresa__c = resultado[i].nEmpresa;
                ModificarEstado.Nombre_Completo__c = resultado[i].nombreCliente;
         		ModificarEstado.Nombre_Asesor_actual__c= resultado[i].nombreAsesoractual;
                ModificarEstado.Nombre_asesor_nuevo__c=  resultado[i].nombreAsesornuevo;
                
            //   update ModificarEstado;     
           }Fin del for principal*/	            
            
		}/*catch(System.CalloutException e){
			system.debug(e.getMessage());	
        }*/
        
        Catch(Exception e){
			system.debug(e.getMessage());	
		} 
		return resultado;   
    }    
    
         
 	//PARA ACTUALIZAR CAMBIO DE ASESOR 02072019 
 	public static list<classRespuestaCambioAsesor> actualizaCambioAsesor(enviarCambioAsesor claseEnvio) {
        
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
		request.setEndpoint(url + 'api/ActualizarCambioAsesor');
		
		String respuesta = '';
		system.debug('Entro al REST del EDC');
        	//classRespuestaCambioAsesor fcsd= new classRespuestaCambioAsesor(); 
        	list<classRespuestaCambioAsesor> resultado = new list<classRespuestaCambioAsesor>();
		try{
						
                        
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(claseEnvio);
			String cons = 'contenido=' + envio.contenido;
			system.debug(cons);		
			request.setBody(cons);	
		    HttpResponse response = http.send(request);
	    	respuesta = response.getBody();
          
            system.debug(respuesta);  
            
            //resultado = (List<classRespuestaCambioAsesor>)JSON.deserialize(RestContext.request.requestBody.toString(), List<classRespuestaCambioAsesor>.class);
            
            
            
            respuesta = String.valueOf(resultado);
            
		}/*catch(System.CalloutException e){
			system.debug(e.getMessage()+ ' LINEA ' + E.getLineNumber());
	
        }*/Catch(Exception e){
			system.debug(e.getMessage()+ ' LINEA ' + E.getLineNumber());	
		} 
		return resultado;   
    }	
    //public static list<classRespuestaCambioAsesor> CambioAsesor(enviar_CambioAsesor claseEnvio){
	/*public static list<classRespuestaCambioAsesor> actualizaCambioAsesor(enviarCambioAsesor claseEnvio)
     {
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
        request.setEndpoint(url + 'api/ActualizarCambioAsesor');
		
		String respuesta = '';
         
        classRespuestaCambioAsesor fcsd= new classRespuestaCambioAsesor(); 
        list<classRespuestaCambioAsesor> resultado = new list<classRespuestaCambioAsesor>();
         
		system.debug('Entro al REST del EDC');
		try{
            						
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(claseEnvio);
			String cons = 'contenido=' + envio.contenido;
			system.debug(cons);		
			request.setBody(cons);	
			HttpResponse response = http.send(request);
	    	respuesta = response.getBody();
            system.debug(respuesta);  
            
            resultado = (list<classRespuestaCambioAsesor>)JSON.deserialize(response.getBody(), list<classRespuestaCambioAsesor>.class);
            
            respuesta = String.valueOf(resultado);
            system.debug('Respuesta'+ resultado);
            system.debug('Respuesta_texto '+ respuesta); 
           
            fcsd.sizeResu = resultado.size();
            
            
		}catch(System.CalloutException e){
			system.debug(e.getMessage());
	
        }Catch(Exception e){
			system.debug(e.getMessage());	
		} 
		return resultado;   
     }*/
    
    //DENEGAR
    public static list<classRespuestaCambioAsesor> BitacoraDCambioAsesor(enviarCambioAsesor claseEnvio) {
        
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
		request.setEndpoint(url + 'api/BitacoraCambioAsesor');
		
		String respuesta = '';
		system.debug('Entro al REST del EDC');
        	classRespuestaCambioAsesor fcsd= new classRespuestaCambioAsesor(); 
        	list<classRespuestaCambioAsesor> resultado = new list<classRespuestaCambioAsesor>();
		try{
						
                        
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(claseEnvio);
			String cons = 'contenido=' + envio.contenido;
			system.debug(cons);		
			request.setBody(cons);	
			/*HttpResponse response = http.send(request);
	    	respuesta = response.getBody();
            system.debug(respuesta);  
            
            //resultado = (List<classRespuestaCambioAsesor>)JSON.deserialize(RestContext.request.requestBody.toString(), List<classRespuestaCambioAsesor>.class);
            */
            //aqui
            HttpResponse response/*= http.send(request)*/;
	    	//respuesta = response.getBody();
            if(test.isRunningTest())
            { 
                respuesta='{"classRespuestaCambioAsesor":[{"Certificado":null,"Mensaje":"A"}]}';
            	fcsd = (classRespuestaCambioAsesor)System.JSON.deserialize(respuesta, classRespuestaCambioAsesor.class);
            }
            
            else{
                response = http.send(request); 
               
            }
             
            resultado = (list<classRespuestaCambioAsesor>)JSON.deserialize(response.getBody(), list<classRespuestaCambioAsesor>.class);
            //fin
                
            
            respuesta = String.valueOf(resultado);
            
		}/*catch(System.CalloutException e){
			system.debug(e.getMessage()+ ' LINEA ' + E.getLineNumber());
	
        }*/Catch(Exception e){
			system.debug(e.getMessage()+ ' LINEA ' + E.getLineNumber());	
		} 
		return resultado;   
    }
    
    /*public static list<classRespuestaCambioAsesor> BitacoraDCambioAsesor(enviarCambioAsesor claseEnvio)
     {
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
        request.setEndpoint(url + 'api/BitacoraCambioAsesor');
		
		String respuesta = '';
         
        classRespuestaCambioAsesor fcsd= new classRespuestaCambioAsesor(); 
        list<classRespuestaCambioAsesor> resultado = new list<classRespuestaCambioAsesor>();
         
		system.debug('Entro al REST del EDC');
		try{
            						
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(claseEnvio);
			String cons = 'contenido=' + envio.contenido;
			system.debug(cons);		
			request.setBody(cons);	
			HttpResponse response = http.send(request);
	    	respuesta = response.getBody();
            system.debug(respuesta);  
            
            resultado = (list<classRespuestaCambioAsesor>)JSON.deserialize(response.getBody(), list<classRespuestaCambioAsesor>.class);
              
            //List<classRespuestaCambioAsesor> delegationMap = (List<classRespuestaCambioAsesor>)JSON.deserialize(RestContext.request.requestBody.toString(), List<classRespuestaCambioAsesor>.class); 
			//resultado = (List<classRespuestaCambioAsesor>)JSON.deserialize(RestContext.request.requestBody.toString(), List<classRespuestaCambioAsesor>.class); 
         	
            /*if (response.getStatusCode() == 200) 
            {
                prueba prueba2= new prueba();
                //system.debug('Sysde'+response.getBody());
                prueba2 = (prueba) JSON.deserialize(response.getBody(), prueba.class);
               	resultado = prueba2.PruebaAse;
                system.debug('ResultadoPrueba2' + resultado);
              
	        }*/
    /*        respuesta = String.valueOf(resultado);
            system.debug('Respuesta'+ resultado);
            system.debug('Respuesta_texto '+ respuesta); 
           
            fcsd.sizeResu = resultado.size();
            
            
		}catch(System.CalloutException e){
			system.debug(e.getMessage() + ' LINEA ' + E.getLineNumber());
	
        }Catch(Exception e){
			system.debug(e.getMessage() + ' LINEA ' +E.getLineNumber());	
		} 
		return resultado;   
     }   */      	   
    
    
   
}