force-app/main/default/objects/Oficial_X_Asesor__c/Oficial_X_Asesor__c.object-meta.xml
<CustomObject>
    <label>Oficial por Asesor</label>
    <nameField>
        <displayFormat>OS-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Asesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Codigo_Asesor__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor__c</fullName>
    <label>Código Asesor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Perfil__c.field-meta.xml
<CustomField>
    <fullName>Perfil__c</fullName>
    <label>Perfil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SGS</fullName>
                <label>Sub Gerencia SAC</label>
            </value>
            <value>
                <fullName>OS</fullName>
                <label>Oficial SAC</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Jefatura Comercial</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Asesor Comercial</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Otro</label>
            </value>
            <value>
                <fullName>OP</fullName>
                <label>Operaciones</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>Supervisor SAC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ControladorReporteCalidadOperacionesFCTe.cls
@istest
public class ControladorReporteCalidadOperacionesFCTe {
    
    @testSetup 
    static void setupMethod() {
        Usuarios_de_Pantallas__c usuario = new Usuarios_de_Pantallas__c ();
        usuario.Activo__c = true;
        usuario.Usuario__c = 'HN123';
        usuario.Contrase_a__c = 'juan123';
        usuario.name = 'Juan';
        usuario.Apellido__c='Perez';
        usuario.Email__c = 'juanperez@test.com';
        usuario.Perfil__c = 'SGS';
        insert usuario;
        
        Producto__c producto = new Producto__C();
        producto.Codigo__c = '01';
        producto.CurrencyIsoCode = 'HNL';
        insert producto;
                
        SubProducto__C subP = new SubProducto__C ();
        subP.Producto__c = producto.id;
        subP.Codigo__c = 'FPC1O';
        subP.Name = 'Sub 1';
        insert subP;

        
        Oficial_X_Asesor__c asesor = new  Oficial_X_Asesor__c ( Codigo_Asesor__c = 'HN22258', Codigo_Oficial_SAC__c = usuario.Usuario__c, Oficial_SAC__c = UserInfo.getUserId());
        insert asesor; 
        
    }
    
    static testMethod void ControladorReporteCalidadOperacionesFCExecute(){
        Test.startTest();
        
        Usuarios_de_Pantallas__c user1 = [Select Usuario__c from Usuarios_de_Pantallas__c  limit 1]; 
        
        ApexPages.currentPage().getParameters().put('usuario',user1.Usuario__c);
        ControladorReporteCalidadOperacionesFC controller= new ControladorReporteCalidadOperacionesFC();
        
        controller.reinicar();
        controller.traerClientes();
        controller.idAfiliacion = controller.listAfiliaciones[0].Id;
        controller.editar();
        controller.Afiliacion.Documentacion_Recibida__c = 'S';
        controller.Afiliacion.Espediente_Completo__c = 'S';
        controller.Afiliacion.ExpedienteFisicoRecibido__c = 'S';
        controller.Afiliacion.FirmaExpediente__c = 'S';
        controller.Afiliacion.Codigo_Oficial_SAC__c = user1.Usuario__c;
        controller.cambioOficialSAC();
        controller.guardar();
        
        controller.accionVacia();
        Test.stopTest();
    }
    


}