force-app/main/default/objects/FPC_TiemposSLARC__c/FPC_TiemposSLARC__c.object-meta.xml
<CustomObject>
    <label>Tiempo SLA RC</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Tiempos SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiempos SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Codigo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Codigo__c</fullName>
    <label>Código</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_PantallaRC__c.field-meta.xml
<CustomField>
    <fullName>FPC_PantallaRC__c</fullName>
    <label>Pantalla RC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Afiliacion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Tiempo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Tiempo__c</fullName>
    <label>Tiempo (Horas)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Asesor_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asesor_Comercial__c</fullName>
    <label>Código Asesor Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/SubEstadoRCSF__c.field-meta.xml
<CustomField>
    <fullName>SubEstadoRCSF__c</fullName>
    <label>Sub Estado RC SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Tipo_Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Afiliacion__c</fullName>
    <label>Tipo Afiliacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Afiliacion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Perfil__c.field-meta.xml
<CustomField>
    <fullName>Perfil__c</fullName>
    <label>Perfil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SGS</fullName>
                <label>Sub Gerencia SAC</label>
            </value>
            <value>
                <fullName>OS</fullName>
                <label>Oficial SAC</label>
            </value>
            <value>
                <fullName>JC</fullName>
                <label>Jefatura Comercial</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Asesor Comercial</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Otro</label>
            </value>
            <value>
                <fullName>OP</fullName>
                <label>Operaciones</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>Supervisor SAC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ReporteCalidadTriggerHelperTest.cls
@isTest
public class ReporteCalidadTriggerHelperTest {

    @testSetup 
    static void setupMethod() {
        Usuarios_de_Pantallas__c usuario = new Usuarios_de_Pantallas__c ();
        usuario.Activo__c = true;
        usuario.Usuario__c = 'HN123';
        usuario.Contrase_a__c = 'juan123';
        usuario.name = 'Juan';
        usuario.Apellido__c='Perez';
        usuario.Email__c = 'juanperez@test.com';
        usuario.Perfil__c = 'SGS';
        insert usuario;
        
        List<FPC_TiemposSLARC__c> listTiempos = new List<FPC_TiemposSLARC__c>();
        FPC_TiemposSLARC__c  tiempo = new FPC_TiemposSLARC__c ();
        tiempo.FPC_Codigo__c = 'N';
        tiempo.FPC_PantallaRC__c = 'I';
        tiempo.FPC_Tiempo__c = 1;
        listTiempos.add(tiempo);
        
        tiempo = new FPC_TiemposSLARC__c ();
        tiempo.FPC_Codigo__c = 'NS';
        tiempo.FPC_PantallaRC__c = 'TV';
        tiempo.FPC_Tiempo__c = 1;
        listTiempos.add(tiempo);
        
        tiempo = new FPC_TiemposSLARC__c ();
        tiempo.FPC_Codigo__c = 'NC';
        tiempo.FPC_PantallaRC__c = 'TV';
        tiempo.FPC_Tiempo__c = 1;
        listTiempos.add(tiempo);
        
        insert listTiempos;
        
        User user1 = new User(Id = UserInfo.getUserId(), Codigo__c = 'HN123'); 
        update user1; 
        
        List<Reporte_calidad__c> listAfiliacion = new List<Reporte_calidad__c>();
        Reporte_calidad__C afiliacion = new Reporte_calidad__C();
        afiliacion.Identificacion__c = '123';
        afiliacion.Tipo_Afiliacion__c = 'I';
        afiliacion.Estado__c = 'N';
        afiliacion.Name = 'Test';
        afiliacion.Codigo_Asesor_Comercial__c = user1.Codigo__c;
        afiliacion.Codigo_Oficial_SAC__c = user1.Codigo__c;
        listAfiliacion.add(afiliacion);
        
        afiliacion = new Reporte_calidad__C();
        afiliacion.Identificacion__c = '123';
        afiliacion.Tipo_Afiliacion__c = 'TV';
        afiliacion.Estado__c = 'N';
        afiliacion.SubEstadoRCSF__c = 'NS';
        afiliacion.Name = 'Test';
        afiliacion.Codigo_Asesor_Comercial__c = user1.Codigo__c;
        afiliacion.Codigo_Oficial_SAC__c = user1.Codigo__c;
        listAfiliacion.add(afiliacion);
        
        afiliacion = new Reporte_calidad__c();
        afiliacion.Identificacion__c = '123';
        afiliacion.Tipo_Afiliacion__c = 'TV';
        afiliacion.SubEstadoRCSF__c = 'NC';
        afiliacion.Estado__c = 'N';
        afiliacion.Name = 'Test';
        afiliacion.Codigo_Asesor_Comercial__c = user1.Codigo__c;
        afiliacion.Codigo_Oficial_SAC__c = user1.Codigo__c;
        listAfiliacion.add(afiliacion);
        insert listAfiliacion;
        
        
    }
    static testMethod void ControladorReporteCalidadAgenciasTFExecute(){
        Test.startTest();
        
        Reporte_calidad__C afiliacion = [Select Id, Estado__c from Reporte_calidad__c Where Tipo_Afiliacion__c = 'I'  limit 1];
        afiliacion.Estado__c = 'C';
        update afiliacion;
        Test.stopTest();
    }
    
}