force-app/main/default/objects/FPC_TiemposSLARC__c/FPC_TiemposSLARC__c.object-meta.xml
<CustomObject>
    <label>Tiempo SLA RC</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Tiempos SLA</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiempos SLA RC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Codigo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Codigo__c</fullName>
    <label>Código</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Estado__c.field-meta.xml
<CustomField>
    <fullName>FPC_Estado__c</fullName>
    <label>Estado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPC_TiemposSLARC__c/fields/FPC_Tiempo__c.field-meta.xml
<CustomField>
    <fullName>FPC_Tiempo__c</fullName>
    <label>Tiempo (Horas)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/SubEstadoRCSF__c.field-meta.xml
<CustomField>
    <fullName>SubEstadoRCSF__c</fullName>
    <label>Sub Estado RC SF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NS</fullName>
                <label>Nuevo SAC</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>Nuevo Comercial</label>
            </value>
            <value>
                <fullName>VS</fullName>
                <label>Validación Scan</label>
            </value>
            <value>
                <fullName>PS</fullName>
                <label>Pendiente Scan</label>
            </value>
            <value>
                <fullName>PF</fullName>
                <label>Pendiente Físico</label>
            </value>
            <value>
                <fullName>VF</fullName>
                <label>Validación Físico</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>Devolución Comercial</label>
            </value>
            <value>
                <fullName>DA</fullName>
                <label>Devolución Agencia</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControladorConfiguracionSLARC.cls
public class ControladorConfiguracionSLARC {
    
    public List<FPC_TiemposSLARC__c> listTiempo{get;set;}
    public String codigo{get;set;}
    
    public ControladorConfiguracionSLARC(){
        iniciar();
    }
    public void iniciar(){
        listTiempo = getPicklistOptions('Reporte_Calidad__c', 'SubEstadoRCSF__c');
        for(FPC_TiemposSLARC__c item: [Select Id, FPC_Estado__c, FPC_Tiempo__c, FPC_Codigo__c from FPC_TiemposSLARC__c]){
            for(FPC_TiemposSLARC__c tiempo: listTiempo){
                if(tiempo.FPC_Codigo__c == item.FPC_Codigo__c){
                    tiempo.Id = item.Id;
                    tiempo.FPC_Tiempo__c = item.FPC_Tiempo__c;
                }
            }
        }
    }
    public void guardar(){
        for(FPC_TiemposSLARC__c tiempo: listTiempo){
            if(tiempo.FPC_Codigo__c == codigo){
                if(tiempo.FPC_Tiempo__c == null || tiempo.FPC_Tiempo__c <= 0){
                    ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'El tiempo del SLA debe ser mayor a cero.'));
                }else{
                    upsert tiempo;
                    ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.CONFIRM, 'Datos guardados exitosamente.'));
                    iniciar();
                }
            }
        }
    }
    
    public void eliminar(){
        FPC_TiemposSLARC__c tiempo = new FPC_TiemposSLARC__c(Id = codigo);
        delete tiempo;
        iniciar();
    }
    
    public static List<FPC_TiemposSLARC__c> getPicklistOptions(String objApiName, String fieldApiName){
        List<FPC_TiemposSLARC__c> lOptions = new List<FPC_TiemposSLARC__c>();
        SObjectType objectType = Schema.getGlobalDescribe().get(objApiName);
        List<Schema.PicklistEntry> ple = objectType.getDescribe()
            .fields.getMap()
            .get(fieldApiName)
            .getDescribe().getPickListValues();
        for(Schema.PicklistEntry entry : ple)  {
            if(entry.getValue() != 'C'){
                lOptions.add(new FPC_TiemposSLARC__c(FPC_Estado__c = entry.getLabel(), FPC_Codigo__c = entry.getValue()));
            }
        }
        return lOptions;
    }
}