force-app/main/default/objects/Partida_contable__mdt/Partida_contable__mdt.object-meta.xml
<CustomObject>
    <label>Parámetro Partida Contable</label>
    <pluralLabel>Partidas contables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Partida_contable__mdt/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Cuenta_Credito__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Credito__c</fullName>
    <label>Cuenta Crédito</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Cuenta_Debito__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Debito__c</fullName>
    <label>Cuenta Débito</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Descripcion_Credito__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Credito__c</fullName>
    <label>Descripción Crédito</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Descripcion_Debito__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Debito__c</fullName>
    <label>Descripción Débito</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Descripcion_Nota__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Nota__c</fullName>
    <label>Descripción Nota</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Fondo__c.field-meta.xml
<CustomField>
    <fullName>Fondo__c</fullName>
    <label>Fondo</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Id_Banco_Credito__c.field-meta.xml
<CustomField>
    <fullName>Id_Banco_Credito__c</fullName>
    <label>Id Banco Crédito</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Id_Banco_Debito__c.field-meta.xml
<CustomField>
    <fullName>Id_Banco_Debito__c</fullName>
    <label>Id Banco Débito</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Moneda__c.field-meta.xml
<CustomField>
    <fullName>Moneda__c</fullName>
    <label>Moneda</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/N_Doc__c.field-meta.xml
<CustomField>
    <fullName>N_Doc__c</fullName>
    <label>N° Doc.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <label>Referencia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Sub_Aplicacion__c.field-meta.xml
<CustomField>
    <fullName>Sub_Aplicacion__c</fullName>
    <label>Sub Aplicación</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Tipo_Nota__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nota__c</fullName>
    <label>Tipo de Nota</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partida_contable__mdt/fields/Tipo_Transaccion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Transaccion__c</fullName>
    <label>Tipo de Transacción</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/Rezago__c.object-meta.xml
<CustomObject>
    <description>Registra los depósitos no identificados.</description>
    <label>Rezago</label>
    <nameField>
        <label>Nombre de Rezago</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rezagos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rezago__c/fields/Asesor_Rezago__c.field-meta.xml
<CustomField>
    <fullName>Asesor_Rezago__c</fullName>
    <description>Nombre del asesor ingresado en el archivo de carga</description>
    <label>Asesor Rezago</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <description>Nombre del Banco donde se realizó el deposito</description>
    <label>Banco</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Cuenta_Credito__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Credito__c</fullName>
    <label>Cuenta Crédito</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Cuenta_Debito__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Debito__c</fullName>
    <label>Cuenta Débito</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Campo de texto con información referida al deposito</description>
    <label>Descripcion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Descripcion_Credito__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Credito__c</fullName>
    <label>Descripción Crédito</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Descripcion_Debito__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Debito__c</fullName>
    <label>Descripción Débito</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Descripcion_Nota__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Nota__c</fullName>
    <description>Campo de texto con información referida al deposito</description>
    <label>Descripcion Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Fecha_del_deposito__c.field-meta.xml
<CustomField>
    <fullName>Fecha_del_deposito__c</fullName>
    <description>DD/MM/YYYY</description>
    <label>Fecha del deposito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Fondo__c.field-meta.xml
<CustomField>
    <fullName>Fondo__c</fullName>
    <description>Identifica la cuenta de pensión empresarial a la que el Rezago será depositado, asimismo es la llave que identifica la partida contable que el sistema registra.</description>
    <label>Fondo</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Moneda_del_deposito__c.field-meta.xml
<CustomField>
    <fullName>Moneda_del_deposito__c</fullName>
    <label>Moneda del deposito</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Monto_del_deposito__c.field-meta.xml
<CustomField>
    <fullName>Monto_del_deposito__c</fullName>
    <description>Aporte</description>
    <label>Monto del deposito</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/N_Doc__c.field-meta.xml
<CustomField>
    <fullName>N_Doc__c</fullName>
    <label>N° Doc.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <description>Alfanumérico identificado como FT o TT o DC o TFS</description>
    <label>Referencia</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Rezago__c.field-meta.xml
<CustomField>
    <fullName>Rezago__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifica si el registro corresponde a un rezago</description>
    <label>Rezago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Sub_Aplicacion__c.field-meta.xml
<CustomField>
    <fullName>Sub_Aplicacion__c</fullName>
    <label>Sub Aplicación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Tipo_Nota__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nota__c</fullName>
    <label>Tipo de Nota</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rezago__c/fields/Tipo_Transaccion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Transaccion__c</fullName>
    <label>Tipo de Transacción</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControladorPartidasContables_Test.cls
@IsTest
public class ControladorPartidasContables_Test {
    
    public static string str; 
	
    static testMethod void Execute(){
        try{
            str = '"FONDO","FECHA","DESCRIPCION","DESCRIPCION_NOTA","N°_DOC.","MONEDA","MONTO","CODIGO","DESCRIPCION_DEBITO","DESCRIPCION_CREDITO"'+'\n'+
                  '101,"6/2/20","Transferencia entre Cuentas","Transferencia de la cuenta XXXXXXXX9182 de ADMINISTRADORA DE FONDOS DE PENSION a la cuenta 8493502 de ADMINISTRADORA DE FONDOS DE la cantidad de 404.00 HNL por motivo de Tralado de puntos futura pend","FT201546BRJ4","HNL",404152.56,"CM","Lorem ipsum","Lorem ipsum"';  
                
            //Inicio Metadatos
            List<Partida_contable__mdt> partidas = [Select id,Fondo__c,Codigo__c,Id_Banco_Debito__c,Id_Banco_Credito__c,Moneda__c,Cuenta_Debito__c,Cuenta_Credito__c,Modulo__c,Tipo_Nota__c,Tipo_Transaccion__c,Sub_Aplicacion__c From Partida_contable__mdt];
            System.debug('partidas: '+partidas);
            //Fin Metadatos
                    
            List<Rezago__c> rezDel = [SELECT Id FROM Rezago__c ];
            Delete rezDel;
            
            List<Rezago__c> rezList = new List<Rezago__c>();
            Rezago__c rez = new Rezago__c(Name = 'Test', Fondo__c ='113', Codigo__c = '123', Banco__c = 'Banco Ficohsa', Cuenta_Debito__c = '111121010001', Cuenta_Credito__c = '111121020001', Modulo__c = 'Bancos', Tipo_Transaccion__c = '55', Sub_Aplicacion__c = '65', Tipo_Nota__c = 'C', Monto_del_deposito__c = '307105.31', Moneda_del_deposito__c = 'HNL', Descripcion_Debito__c = 'Test', Descripcion_Credito__c = 'Test', Fecha_del_deposito__c = System.today(), Descripcion__c = 'Test', Descripcion_Nota__c  = 'Test', N_Doc__c = '123', Referencia__c = '123', Asesor_Rezago__c = 'HN001');
            rezList.add(rez);
            insert rezList;
            System.debug('rezList: '+rezList);    
            
            Test.StartTest();
            ControladorPartidasContables c = new ControladorPartidasContables();
            ControladorPartidasContables.SUbirInformacion(str);
            c.Guardar();
            Test.StopTest();
        } catch(DmlException ex) {
        	System.debug('Error: '+ex.getMessage() + '-' + ex.getLineNumber());    
        }    
    }
}