force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comercio_Afiliado__c/Comercio_Afiliado__c.object-meta.xml
<CustomObject>
    <label>Comercio Afiliado</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comercios Afiliados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/configTransacciones__c/configTransacciones__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Configuración excel transacciones</label>
</CustomObject>

force-app/main/default/objects/configTransacciones__c/fields/Es_Fecha_Hora__c.field-meta.xml
<CustomField>
    <fullName>Es_Fecha_Hora__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Fecha y Hora</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/configTransacciones__c/fields/Es_Numerico__c.field-meta.xml
<CustomField>
    <fullName>Es_Numerico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Numérico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/configTransacciones__c/fields/Es_Obligatorio__c.field-meta.xml
<CustomField>
    <fullName>Es_Obligatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Obligatorio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/configTransacciones__c/fields/Es_Texto__c.field-meta.xml
<CustomField>
    <fullName>Es_Texto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Texto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/configTransacciones__c/fields/Nombre_API_Campo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_API_Campo__c</fullName>
    <label>Nombre API Campo</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/configTransacciones__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <displayFormat>Des-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/Comercio_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Comercio_Afiliado__c</fullName>
    <label>Comercio Afiliado</label>
    <referenceTo>Comercio_Afiliado__c</referenceTo>
    <relationshipLabel>Descuentos</relationshipLabel>
    <relationshipName>Descuentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Descuento__c/fields/Porcentaje_descuento__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_descuento__c</fullName>
    <label>Porcentaje de descuento</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Usuario_de_Portal__c/Usuario_de_Portal__c.object-meta.xml
<CustomObject>
    <label>Usuario de Portal</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de Portal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_de_Portal__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_de_Portal__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuario_de_Portal__c/fields/Comercio_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Comercio_Afiliado__c</fullName>
    <label>Comercio Afiliado</label>
    <referenceTo>Comercio_Afiliado__c</referenceTo>
    <relationshipLabel>Usuarios de Portal</relationshipLabel>
    <relationshipName>Usuarios_de_Portal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Usuario_de_Portal__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/testComercioAfiliadoSitio.cls
@isTest(SeeAllData=true)
public class testComercioAfiliadoSitio{
    
    static testMethod void clasesPortal(){
        Comercio_Afiliado__c comercio = new Comercio_Afiliado__c(Name = 'ComercioTest', Activo__c = false);
        insert comercio;
        
        Usuario_de_Portal__c usuario = new Usuario_de_Portal__c(
                    Name = 'Juan', Contrase_a__c = 'Nada123', Comercio_Afiliado__c = comercio.id,
                    Apellido__c = 'Hernandez');
        insert usuario;
               
        Descuento__c descuento = new Descuento__c(Activo__c = true, Comercio_Afiliado__c = comercio.id,
                                    Porcentaje_descuento__c = 5);
               
        Account cliente = new Account(lastName = 'Cliente-1', Identificacion__c = '03030101',
                        recordTypeId = [Select id From recordType Where sObjectType = 'Account' AND DeveloperName = 'Natural'].Id);
                      
        
        /*list<configTransacciones__c> listConfig = new list<configTransacciones__c>(); 
        listConfig.add(new configTransacciones__c(Name = 'Cliente', Nombre_API_Campo__c = 'Cliente__c',
                        Orden__c = 1, Es_Obligatorio__c = true, Es_texto__c = true));
        
        listConfig.add(new configTransacciones__c(Name = 'Monto', Nombre_API_Campo__c = 'Monto__c',
                        Orden__c = 2, Es_Obligatorio__c = true, Es_Numerico__c = true));
                                        
        listConfig.add(new configTransacciones__c(Name = 'Fecha y hora de la Transacción', Nombre_API_Campo__c = 'Fecha_hora_Transaccion__c',
                        Orden__c = 3, Es_Obligatorio__c = true, Es_Fecha_Hora__c = true));
        insert listConfig;*/
                               
        string csvTest = ''; 
                    
        test.startTest();        	
            insert descuento;
            insert cliente;
            
            controllerLoginComerio control = new controllerLoginComerio();
            control.sesionIniciada();
            control.usuario = 'jhernandez';
            control.sesionIniciada();
            control.Contrasena = 'Nada123';
            control.sesionIniciada();
            
            comercio.Activo__c = true;
            update comercio;
            control.sesionIniciada();
            
            ApexPages.currentPage().getParameters().put('IdComercio', comercio.id);
            controlTransacciones control2 = new controlTransacciones();
            control2.buscarAfiliado();
            control2.numeroAfiliado = '03030101';
            control2.buscarAfiliado();
            control2.cerrar();
            control2.guardar();
            
            controlTransaccionesMasivas.classWRetorno respuesta = controlTransaccionesMasivas.processFile(csvTest, comercio.id, descuento.id, usuario.id);
            
            
            csvTest = '"Cliente","Monto de Venta Lps","Fecha y hora de la Transacción"\n'; 
            respuesta = controlTransaccionesMasivas.processFile(csvTest, comercio.id, descuento.id, usuario.id);
            
            csvTest = '"Cliente","Monto de Venta Lps","Fecha y hora de la Transacción","Nada"\n'; 
            respuesta = controlTransaccionesMasivas.processFile(csvTest, comercio.id, descuento.id, usuario.id);
            
            csvTest = '"Cliente","Monto de Venta Lps","Fecha y hora de la Transacción"\n"03030101",500,"14/10/2011-11:46"'; 
            respuesta = controlTransaccionesMasivas.processFile(csvTest, comercio.id, descuento.id, usuario.id);
            
            csvTest = '"Cliente","Monto de Venta Lps","Fecha y hora de la Transacción"\n"00000050",500,"14/10/2011-11:46"'; 
            respuesta = controlTransaccionesMasivas.processFile(csvTest, comercio.id, descuento.id, usuario.id);
            
            csvTest = '"Cliente","Monto de Venta Lps","Fecha y hora de la Transacción"\n"03030101",500,"14/10/2011-11:46"'; 
            respuesta = controlTransaccionesMasivas.processFile(csvTest, null, null, null);
            
            controlorMenuTransacciones control3 = new controlorMenuTransacciones();
            control3.transaccion();
            control3.transaccionMasiva();
            control3.tabActiva();
            control3.cerrar();
            
            DateTime xResul = claseUtil.convertToDateTime('14/10/2011-11:46');
        test.stopTest();
    }
}