force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PAPCE__c.field-meta.xml
<CustomField>
    <fullName>PAPCE__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Empleador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Empleador</inlineHelpText>
    <label>% Pilar Complementario Patrono</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAPCT__c.field-meta.xml
<CustomField>
    <fullName>PAPCT__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Trabajador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Trabajador</inlineHelpText>
    <label>% Pilar Complementario Trabajador</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_IVM__c</fullName>
    <label>Porc Apor SSoc Empleado IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_Mater__c</fullName>
    <label>Porc Apor SSoc Empleado Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_IVM__c</fullName>
    <label>Porc Apor SSoc Empleador IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_Mater__c</fullName>
    <label>Porc Apor SSoc Empleador Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_Aportaciones_Reserva_Labor__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_Aportaciones_Reserva_Labor__c</fullName>
    <label>Porcentaje de Aportaciones Reserva Labor</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Riesgo_Profecional_Patronal__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_Profecional_Patronal__c</fullName>
    <label>Riesgo Profesional Patronal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Pilar_Complementario__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Pilar_Complementario__c</fullName>
    <label>Salario Base Pilar Complementario</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Reserva_Laboral__c</fullName>
    <label>Techo Reserva Laboral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social__c</fullName>
    <label>Salario Base Seguro Social IVM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_Mater__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_Mater__c</fullName>
    <label>Salario Base Seguro Social Mater</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_RP__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_RP__c</fullName>
    <description>Salario Base Seguro Social Riesgo Profecional</description>
    <inlineHelpText>Salario Base Seguro Social Riesgo Profecional</inlineHelpText>
    <label>Salario Base Seguro Social RP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Identidad__c/Identidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>En este objeto se almacenan los tipos de documentos.</description>
    <label>Identidad</label>
</CustomObject>

force-app/main/default/objects/Planilla_Seguro_Social__c/Planilla_Seguro_Social__c.object-meta.xml
<CustomObject>
    <label>Planilla Seguro Social</label>
    <nameField>
        <label>Nombre de Planilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilla Seguro Social</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla_Seguro_Social__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planilla Seguro Social</relationshipLabel>
    <relationshipName>Planilla_Seguro_Social</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla_Seguro_Social__c/fields/Riesgo_Profecional_Patronal__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_Profecional_Patronal__c</fullName>
    <label>Riesgo Profecional Patronal</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Planilla_Seguro_Social__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipLabel>Planilla Seguro Social</relationshipLabel>
    <relationshipName>Planilla_Seguro_Social</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tiempo_Inactividad__c/Tiempo_Inactividad__c.object-meta.xml
<CustomObject>
    <label>Tiempo Inactividad</label>
    <nameField>
        <label>Nombre de Tiempo Inactividad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiempo Inactividad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tiempo_Inactividad__c/fields/Hora_ultima_consulta__c.field-meta.xml
<CustomField>
    <fullName>Hora_ultima_consulta__c</fullName>
    <label>Hora de ultima consulta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tiempo_Inactividad__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipLabel>Tiempo Inactividad</relationshipLabel>
    <relationshipName>Tiempo_Inactividad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/Usuario_Portal_Empresarial__c.object-meta.xml
<CustomObject>
    <label>Usuario Portal Empresarial</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuario Portal Empresarial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Apellidos</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Contrasena2__c.field-meta.xml
<CustomField>
    <fullName>Contrasena2__c</fullName>
    <label>Contraseña</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Identidad__c.field-meta.xml
<CustomField>
    <fullName>Identidad__c</fullName>
    <label>Identidad</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Nombre_Usuario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Nombre Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <label>Respuesta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/Usuario_X_Empresa__c.object-meta.xml
<CustomObject>
    <label>Usuario por Empresa</label>
    <nameField>
        <displayFormat>UE-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Aprobacion_Usuarios__c.field-meta.xml
<CustomField>
    <fullName>Aprobacion_Usuarios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobacion Usuarios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Cargar_Generar_Planilla__c.field-meta.xml
<CustomField>
    <fullName>Cargar_Generar_Planilla__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cargar/Generar Planilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Crear_Usuarios__c.field-meta.xml
<CustomField>
    <fullName>Crear_Usuarios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Crear Usuarios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Juridico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Usuarios por Empresa</relationshipLabel>
    <relationshipName>Usuarios_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Planilla_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Planilla_Seguro_Social__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Planilla Seguro Social</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Reportes__c.field-meta.xml
<CustomField>
    <fullName>Reportes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reportes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipName>Usuarios_X_Empresa1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ControladorEstadoDeCuentaPlanillaTest.cls
@isTest
public class ControladorEstadoDeCuentaPlanillaTest {
    
    @testSetup 
    static void setupMethod() {
        Account EmpresaPrueba= new Account();
        empresaprueba.Name='Empresa Prueba';
        EmpresaPrueba.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Juridico').getRecordTypeId();
        EmpresaPrueba.Identificacion__c='012j0000';
        EmpresaPrueba.Salario_Base_Pilar_Complementario__c=10000;
        EmpresaPrueba.Salario_Base_Reserva_Laboral__c=10000;
        EmpresaPrueba.PAPCT__c=3;
        EmpresaPrueba.PAPCE__c=3;
        EmpresaPrueba.Porcentaje_de_Aportaciones_Reserva_Labor__c=4;
        EmpresaPrueba.Salario_Base_Seguro_Social__c=432;
        EmpresaPrueba.Porc_Apor_SSoc_Empleador_IVM__c=3;
        EmpresaPrueba.Porc_Apor_SSoc_Empleado_IVM__c=3;
        EmpresaPrueba.Salario_Base_Seguro_Social_Mater__c=4;
        EmpresaPrueba.Porc_Apor_SSoc_Empleador_Mater__c=5;
        EmpresaPrueba.Porc_Apor_SSoc_Empleado_Mater__c=5;
        EmpresaPrueba.Salario_Base_Seguro_Social_RP__c=43433;
        EmpresaPrueba.Riesgo_Profecional_Patronal__c=6;
        insert EmpresaPrueba;
        
        Usuario_Portal_Empresarial__c usuario = new Usuario_Portal_Empresarial__c();
        usuario.Apellidos__c='Meraz';
        usuario.Contrasena2__c='Cualquiera';
        usuario.Email__c='marcela.meraz@gmail.com';
        usuario.Name='Yeny';
        usuario.Respuesta__c='Lunes';
        usuario.Identidad__c='0303199702883';
        usuario.Nombre_Usuario__c='chema';
        insert usuario;
        
        Tiempo_Inactividad__c hora= new Tiempo_Inactividad__c();
        hora.Usuario__c=usuario.id;
        hora.Hora_ultima_consulta__c=datetime.now();
        insert hora; 
        
        Usuario_X_Empresa__c a = new Usuario_X_Empresa__c();
        a.empresa2__C=empresaprueba.id;
        a.Usuario__c=usuario.id;
        a.Activo__c=true;
        a.Aprobacion_Usuarios__c=TRUE;
        a.Calculo_De_Pilares__c=true;
        a.Cargar_Generar_Planilla__c=true;
        a.Crear_Usuarios__c=true;
        a.Nuevo_Personal__c=true;
        a.Reportes__c=true;
        a.Planilla_Seguro_Social__c=true;
        a.Nuevos_Salarios__c = true;
        insert a;
        
    }
    
    static testmethod void ControladorEstadoDeCuentaPlanilla(){
        Account empresaprueba = [Select Id, Name from Account Where Identificacion__c = '012j0000'];
        Usuario_Portal_Empresarial__c usuario = [Select Id, Name from Usuario_Portal_Empresarial__c Where Email__c='marcela.meraz@gmail.com'];
        ApexPages.currentPage().getParameters().put('Eldudhdhyudb',empresaprueba.id);
        ApexPages.currentPage().getParameters().put('loetdncdhjch',usuario.id); 
        ControladorEstadoDeCuentaPlanilla controller =new ControladorEstadoDeCuentaPlanilla();
        controller.generarEDC();
        controller.cerrar();
    }
    

}