force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FATCA__c.field-meta.xml
<CustomField>
    <fullName>FATCA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FATCA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Tipo_Fondo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Fondo__c</fullName>
    <label>Tipo de Fondo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cesantia</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Tipo_Fondo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Fondo__c</fullName>
    <label>Tipo de Fondo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Fondo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testcontroladorAfiliacionFicopen.cls
@istest
public class testcontroladorAfiliacionFicopen {

    static testMethod void controladorAfiliacionFicopen(){
        Usuarios_de_Pantallas__c usuario = new Usuarios_de_Pantallas__c ();
        usuario.Activo__c = true;
        usuario.Usuario__c = 'juan123';
        usuario.Contrase_a__c = 'juan123';
        usuario.name = 'Juan';
        usuario.Apellido__c='Perez';
        usuario.Email__c = 'juanperez@test.com';
        insert usuario; 
        
		Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;
        
        SubProducto__C subP = new SubProducto__C ();
        subP.Producto__c = producto.id;
        subP.Codigo__c = 'FI010';
        subP.Name = 'Sub 1';
        insert subP;
        
        subP = new SubProducto__C ();
        subP.Producto__c = producto.id;
        subP.Codigo__c = 'USD';
        subP.Name = 'Sub 2';
        insert subP;
        
        
        Account empresa= new Account();
        empresa.Name='Empresa Prueba 1';
        empresa.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Juridico').getRecordTypeId();
        empresa.Identificacion__c='012j0000';
        insert empresa;
        
        cuentas__C cuenta = new cuentas__C ();
        cuenta.Cliente__c = empresa.id;
        cuenta.Activo__c = true;
        cuenta.Producto__c = producto.Id;
        cuenta.Subproducto__c = subP.Id;
        cuenta.Codigo__c = '12345';
        insert cuenta;
        
        ApexPages.currentPage().getParameters().put('usuario',usuario.Usuario__c);
        controladorAfiliacionFicopen controlador= new controladorAfiliacionFicopen();
        
        controlador.guardar();
        
        controlador.buscarEmpresa = 'Em54presa';
        controlador.BuscarEmpresa();
        controlador.buscarEmpresa = 'Empresa';
        controlador.BuscarEmpresa();
        
        controlador.Afiliacion.name = 'PN';
        controlador.Afiliacion.primer_apellido__C = 'PA';
        controlador.Afiliacion.Tipo_Identificacion__c='1';
        controlador.Afiliacion.Identificacion__c = '12345445';
        controlador.ValidacionIdentidad();
        controlador.afiliacion.empresa__c = empresa.id;
        controlador.selectEmpresa();
        controlador.Afiliacion.Tiene_Id__c = 'S';
        controlador.Afiliacion.RTN__c = 'N';
        controlador.Afiliacion.FATCA__c = 'N';
        controlador.Afiliacion.WAIVER__c = 'N';
        controlador.Afiliacion.PEP__c = 'N';
        controlador.Afiliacion.Procedencia__c = 'N';
        controlador.Afiliacion.Addendum__c = 'N';
        controlador.Afiliacion.Tipo_Fondo__c = 'M';
        //controlador.Afiliacion.Formulario_Completo__c = 'S';
        controlador.Afiliacion.espediente_completo__C = 'S';
        controlador.guardar();
        controlador.Afiliacion.Formulario_Completo__c = 'S';
        controlador.guardar();
        controlador.idAfiliacion = controlador.listAfiliaciones[0].id;
        controlador.editar();
        controlador.cerrar();
        controlador.idAfiliacion = controlador.listAfiliaciones[0].id;
        controlador.SelectPopEliminar();
        controlador.EliminarAfiliacion();
        
        
        controlador.buscarEmpresa = 'Empresa';
        controlador.BuscarEmpresa();
        
        controlador.Afiliacion.name = 'PN';
        controlador.Afiliacion.primer_apellido__C = 'PA';
        controlador.Afiliacion.Tipo_Identificacion__c='1';
        controlador.Afiliacion.Identificacion__c = '12345445';
        controlador.ValidacionIdentidad();
        controlador.afiliacion.empresa__c = empresa.id;
        controlador.selectEmpresa();
        controlador.Afiliacion.Tiene_Id__c = 'S';
        controlador.Afiliacion.RTN__c = 'N';
        controlador.Afiliacion.FATCA__c = 'N';
        controlador.Afiliacion.WAIVER__c = 'N';
        controlador.Afiliacion.PEP__c = 'N';
        controlador.Afiliacion.Procedencia__c = 'N';
        controlador.Afiliacion.Addendum__c = 'N';
        controlador.Afiliacion.Tipo_Fondo__c = 'M';
        controlador.Afiliacion.Formulario_Completo__c = 'S';
        controlador.Afiliacion.espediente_completo__C = 'S';
        controlador.guardar();
        
        controlador.listAfiliaciones[0].enviar_sac__c = true;
        controlador.haySeleccionado();
        controlador.Enviar();
        controlador.accionVacia();
       
        
            
        
        
        
        
    }
    
    
}