force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cliente_Unico_Banco__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Unico_Banco__c</fullName>
    <externalId>true</externalId>
    <label>Cliente Unico Banco</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Proceso Finalizado</fullName>
            </value>
            <value>
                <fullName>En proceso de afiliación</fullName>
            </value>
            <value>
                <fullName>Acivo</fullName>
                <isActive>false</isActive>
                <label>Acivo</label>
            </value>
            <value>
                <fullName>Inacivo</fullName>
                <isActive>false</isActive>
                <label>Inacivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficial_X_Asesor__c/Oficial_X_Asesor__c.object-meta.xml
<CustomObject>
    <label>Oficial por Asesor</label>
    <nameField>
        <displayFormat>OS-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Asesores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficial_X_Asesor__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Asesores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/Oficiales_X_Empresa__c.object-meta.xml
<CustomObject>
    <label>Oficial por Empresa</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Juridico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oficiales por Empresa</relationshipLabel>
    <relationshipName>Oficiales_por_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/Reporte_Calidad__c.object-meta.xml
<CustomObject>
    <label>Reporte de Calidad</label>
    <nameField>
        <label>Primer Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporte_Calidad__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Juridico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reportes Calidad</relationshipLabel>
    <relationshipName>Reportes_Calidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Espediente_Completo__c.field-meta.xml
<CustomField>
    <fullName>Espediente_Completo__c</fullName>
    <label>Expediente Completo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Si</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Validación</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Afiliación</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Firma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <label>Oficial SAC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Reporte_Calidad__c.field-meta.xml
<CustomField>
    <fullName>Reporte_Calidad__c</fullName>
    <label>Reporte de Calidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Contributivo</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No Contributivo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Ficopen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporte_Calidad__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Reportes Calidad</relationshipLabel>
    <relationshipName>Reportes_Calidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testControladorReporteSeguienteSac.cls
@istest
public class testControladorReporteSeguienteSac {
    
    static testMethod void ControladorReporteSeguienteSac (){
        Usuarios_de_Pantallas__c usuario = new Usuarios_de_Pantallas__c ();
        usuario.Activo__c = true;
        usuario.Usuario__c = 'juan123';
        usuario.Contrase_a__c = 'juan123';
        usuario.name = 'Juan';
        usuario.Apellido__c='Perez';
        usuario.Email__c = 'juanperez@test.com';
        insert usuario; 
        
        Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;
        
        SubProducto__C subP = new SubProducto__C ();
        subP.Producto__c = producto.id;
        subP.Codigo__c = 'FI010';
        subP.Name = 'Sub 1';
        insert subP;
        
        subP = new SubProducto__C ();
        subP.Producto__c = producto.id;
        subP.Codigo__c = 'USD';
        subP.Name = 'Sub 2';
        insert subP;
        
        
        Account empresa= new Account();
        empresa.Name='Empresa Prueba 1';
        empresa.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Juridico').getRecordTypeId();
        empresa.Identificacion__c='012j0000';
        empresa.Cliente_Unico_Banco__c = '123';
        insert empresa;
        
        cuentas__C cuenta = new cuentas__C ();
        cuenta.Cliente__c = empresa.id;
        cuenta.Activo__c = true;
        cuenta.Producto__c = producto.Id;
        cuenta.Subproducto__c = subP.Id;
        cuenta.Codigo__c = '12345';
        insert cuenta;
       
        List<Reporte_calidad__C>  Listreporte = new List<Reporte_calidad__C>();
        for(Integer i = 0; i< 1903; i++){
            Reporte_calidad__C afiliacion = new Reporte_calidad__C();
            afiliacion.Identificacion__c = '123'+i;
            afiliacion.Espediente_Completo__c = 'S';
            afiliacion.Name = 'Test';
            afiliacion.Estado__c = 'C';
            afiliacion.Codigo_Oficial_SAC__c = usuario.Usuario__c;
            Listreporte.add(afiliacion);
        }
        insert Listreporte;
        
        Oficiales_X_Empresa__c oficial = new Oficiales_X_Empresa__c();
        oficial.Empresa__c = empresa.id;
        oficial.Asesor__c = userinfo.getUserId();
        oficial.Codigo_Asesor__c = usuario.Usuario__c;
        oficial.Oficial_SAC__c = userinfo.getUserId();
        oficial.Codigo_Oficial_SAC__c = usuario.Usuario__c;
        insert oficial;
        
        Oficial_X_Asesor__c oficial2 = new Oficial_X_Asesor__c();
        oficial2.Codigo_Oficial_SAC__c = usuario.Usuario__c;
        oficial2.Oficial_SAC__c = userinfo.getUserId();
        oficial2.Codigo_Asesor__c = usuario.Usuario__c;
        oficial2.Asesor__c = userinfo.getUserId();
        insert oficial2;
        
        
        
        ApexPages.currentPage().getParameters().put('usuario',usuario.Usuario__c);
        controladorReporteSeguienteSac controlador= new controladorReporteSeguienteSac();
        controlador.filtros();
        controlador.siguiente();
        controlador.anterior();
        controlador.popEmpresas();
        controlador.cerrar();
        controlador.filtroZona = 'S';
        
        controlador.listTipoCarga[0].seleccionado = true;
        controlador.listOficialSac[0].seleccionado = true;
        controlador.listEmpresasN[0].seleccionado = true;
        controlador.listAsesoresN[0].seleccionado = true;
        controlador.filtroReporte = '3';
        controlador.filtros();
        controlador.filtroReporte = '4';
        controlador.filtros();
        
        controlador.exportarExcel();
        controlador.filtroEmpresa = 'Prueba';
        controlador.buscarEmpresa();
        controlador.filtroTipoCarga = 'ew';
        controlador.filtroAsesor = '21';
        controlador.filtroOficial = 'q';
        
        ApexPages.currentPage().getParameters().put('where', ' Estado__c = null');
        ApexPages.currentPage().getParameters().put('usuario', usuario.Usuario__c);
        ApexPages.currentPage().getParameters().put('pagActual', '1');
        new  ControladorExportarExcelReporCAlidSAC();
        
        ApexPages.currentPage().getParameters().put('where', null);
        ApexPages.currentPage().getParameters().put('usuario', usuario.Usuario__c);
        ApexPages.currentPage().getParameters().put('pagActual', '1');
        new  ControladorExportarExcelReporCAlidSAC();
        
        
        
        
        
        
    }
    
    
    
    
    
}