force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contenido_Planilla_Temporal__c/Contenido_Planilla_Temporal__c.object-meta.xml
<CustomObject>
    <label>Contenido_Planilla_Temporal</label>
    <nameField>
        <label>Nombre de Contenido_Planilla_Temporal__c</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contenido_Planilla_Temporal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contenido_Planilla_Temporal__c/fields/Identidad__c.field-meta.xml
<CustomField>
    <fullName>Identidad__c</fullName>
    <label>Identidad</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla_Temporal__c/fields/Planilla__c.field-meta.xml
<CustomField>
    <fullName>Planilla__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilla Temporal</label>
    <referenceTo>Planilla_Temporal__c</referenceTo>
    <relationshipLabel>Contenido_Planilla_Temporal</relationshipLabel>
    <relationshipName>Contenido_Planilla_Temporal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Tipo_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cuenta__c</fullName>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Cuenta bancaria</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Cuenta de pensiones</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas_Colectivas__c/Cuentas_Colectivas__c.object-meta.xml
<CustomObject>
    <label>Cuentas Colectivas</label>
    <nameField>
        <label>Nombre de Cuentas Colectivas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas Colectivas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas_Colectivas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas_Colectivas__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas Colectivas</relationshipLabel>
    <relationshipName>Cuentas_Colectivas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empresa_x_Empleado__c/Empresa_x_Empleado__c.object-meta.xml
<CustomObject>
    <label>Empleado por Empresa</label>
    <nameField>
        <displayFormat>EE-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleado por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empresa_x_Empleado__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Empleado_X_Empresa1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla__c/Planilla__c.object-meta.xml
<CustomObject>
    <label>Planilla</label>
    <nameField>
        <displayFormat>PLA-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planillas</relationshipLabel>
    <relationshipName>Planillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla_Seguro_Social__c/Planilla_Seguro_Social__c.object-meta.xml
<CustomObject>
    <label>Planilla Seguro Social</label>
    <nameField>
        <label>Nombre de Planilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilla Seguro Social</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla_Seguro_Social__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planilla Seguro Social</relationshipLabel>
    <relationshipName>Planilla_Seguro_Social</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla_Seguro_Social__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipLabel>Planilla Seguro Social</relationshipLabel>
    <relationshipName>Planilla_Seguro_Social</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tiempo_Inactividad__c/Tiempo_Inactividad__c.object-meta.xml
<CustomObject>
    <label>Tiempo Inactividad</label>
    <nameField>
        <label>Nombre de Tiempo Inactividad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiempo Inactividad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tiempo_Inactividad__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipLabel>Tiempo Inactividad</relationshipLabel>
    <relationshipName>Tiempo_Inactividad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/Usuario_Portal_Empresarial__c.object-meta.xml
<CustomObject>
    <label>Usuario Portal Empresarial</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuario Portal Empresarial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Apellidos</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Contrasena2__c.field-meta.xml
<CustomField>
    <fullName>Contrasena2__c</fullName>
    <label>Contraseña</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Identidad__c.field-meta.xml
<CustomField>
    <fullName>Identidad__c</fullName>
    <label>Identidad</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Nombre_Usuario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Nombre Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuario_Portal_Empresarial__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <label>Respuesta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/Usuario_X_Empresa__c.object-meta.xml
<CustomObject>
    <label>Usuario por Empresa</label>
    <nameField>
        <displayFormat>UE-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Aprobacion_Usuarios__c.field-meta.xml
<CustomField>
    <fullName>Aprobacion_Usuarios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobacion Usuarios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Cargar_Generar_Planilla__c.field-meta.xml
<CustomField>
    <fullName>Cargar_Generar_Planilla__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cargar/Generar Planilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Crear_Usuarios__c.field-meta.xml
<CustomField>
    <fullName>Crear_Usuarios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Crear Usuarios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Juridico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Usuarios por Empresa</relationshipLabel>
    <relationshipName>Usuarios_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Planilla_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Planilla_Seguro_Social__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Planilla Seguro Social</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Reportes__c.field-meta.xml
<CustomField>
    <fullName>Reportes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reportes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuario_X_Empresa__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Portal Empresarial</label>
    <referenceTo>Usuario_Portal_Empresarial__c</referenceTo>
    <relationshipName>Usuarios_X_Empresa1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestCargaPlanilla.cls
@istest
global class TestCargaPlanilla {
    /*static testmethod void claseutil ()
	{
Account EmpresaPrueba= new Account();
empresaprueba.Name='Empresa Prueba';
EmpresaPrueba.RecordTypeId = '012j0000000i2TcAAI'; 
EmpresaPrueba.Identificacion__c='012j0000';
insert EmpresaPrueba;

test.startTest();
string gt =claseutilplanillas.urlSysde('Test');
boolean t =claseutilplanillas.validarContrasena('Hola');
t =claseutilplanillas.validarContrasena('Holacsdfh');
t =claseutilplanillas.validarContrasena('Holac43sdbfh@');

Usuario_Portal_Empresarial__c usuario = new Usuario_Portal_Empresarial__c();
usuario.Apellidos__c='Meraz';
usuario.Contrasena2__c='Cualquiera';
usuario.Email__c='marcela.meraz@gmail.com';
usuario.Name='Yeny';
usuario.Respuesta__c='Lunes';
usuario.Identidad__c='0303199702883';
usuario.Nombre_Usuario__c='chema';
insert usuario;


Usuario_X_Empresa__c a = new Usuario_X_Empresa__c();
a.empresa2__C=empresaprueba.id;
a.Usuario__c=usuario.id;
a.Activo__c=true;
a.Aceptar_Planilla__c=true;
a.Aprobacion_Usuarios__c=TRUE;
a.Calculo_De_Pilares__c=true;
a.Cargar_Generar_Planilla__c=true;
a.Crear_Usuarios__c=true;
a.Nuevo_Personal__c=true;
a.Reportes__c=true;
a.Planilla_Seguro_Social__c=true;
insert a;

claseutilplanillas.correoEnvioPlanilla(a);        

list<Account> mnb=new list<Account>();
list<string> vc= new list<string>();
vc.add('0404040404');
mnb=aSysdePortalEmpresarial.agregarPersonaPlanilla(vc);
list<claseaportaciones> mn =aSysdePortalEmpresarial.ConsultalAportesPatronales(vc, '54769');
//aSysdePortalEmpresarial.EnviarAportesEmpleados('32,3,23,32,23,32,32,32,32,32::::',746,datetime.now(),'');
aSysdePortalEmpresarial.metodoutil();
aSysdePortalEmpresarial.metodoutil2();


test.stopTest();
}*/
    
    static testmethod void TestPortalFPCCargasPlanilla()
    {
        test.startTest();
        Account EmpresaPrueba= new Account();
        empresaprueba.Name='Empresa Prueba';
        EmpresaPrueba.RecordTypeId = '012j0000000i2TcAAI';
        EmpresaPrueba.Identificacion__c='012j0000';
        insert EmpresaPrueba;       
        
        Account EmpresaPrueba2= new Account();
        EmpresaPrueba2.Name='Empresa Prueba3';
        EmpresaPrueba2.RecordTypeId = '012j0000000i2TcAAI';
        EmpresaPrueba2.Identificacion__c='01uy62j0000';
        insert EmpresaPrueba2;
        
        Account EmpresaPrueba3= new Account();
        EmpresaPrueba3.Name='Empresa Prueba3';
        EmpresaPrueba3.RecordTypeId = '012j0000000i2TcAAI';
        EmpresaPrueba3.Identificacion__c='012jkjn00';
        insert EmpresaPrueba3;
        
        Account ClientePrueba= new Account();
        ClientePrueba.lastname='Doanire';
        ClientePrueba.firstname='Luis';
        ClientePrueba.RecordTypeId = '012j0000000i3wAAAQ';
        ClientePrueba.Identificacion__c='00000000000000';
        insert ClientePrueba;
        
        Account ClientePrueba2= new Account();
        ClientePrueba2.lastname='Castañeda';
        ClientePrueba2.firstname='Enrique';
        ClientePrueba2.RecordTypeId = '012j0000000i3wAAAQ';
        ClientePrueba2.Identificacion__c='00000000000001';
        insert ClientePrueba2;
        
        Account ClientePrueba3= new Account();
        ClientePrueba3.lastname='Castañeda';
        ClientePrueba3.firstname='Idania';
        ClientePrueba3.RecordTypeId = '012j0000000i3wAAAQ';
        ClientePrueba3.Identificacion__c='00000000000002';
        insert ClientePrueba3;
        
        Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;    
        
        Cuentas__C cuentacolectiva= new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='32546';
        cuentacolectiva.Cliente__c=EmpresaPrueba.id;
        cuentacolectiva.Producto__c=producto.id;
        insert cuentacolectiva;
        
        Cuentas_Colectivas__c Colectiva= new Cuentas_Colectivas__c();
        colectiva.Tipo_Cuenta__c='Censatías';
        colectiva.Codigo__c='32542';
        colectiva.Empresa__c=empresaprueba.id;
        insert colectiva;
        
        Cuentas_Colectivas__c Colectiva2= new Cuentas_Colectivas__c();
        colectiva2.Tipo_Cuenta__c='Voluntarias';
        colectiva2.Codigo__c='32546';
        colectiva2.Empresa__c=empresaprueba.id;
        insert colectiva2;
        
        Cuentas__C cuentaNormal= new Cuentas__C();
        cuentaNormal.CurrencyIsoCode='HNL';
        cuentaNormal.Codigo__c='der1';
        cuentaNormal.Cliente__c=ClientePrueba.id;
        cuentanormal.Cuenta_colectiva2__c=null;
        cuentaNormal.Producto__c=producto.id;
        insert cuentaNormal;
        
        
        
        cuentaNormal= new Cuentas__C();
        cuentaNormal.CurrencyIsoCode='HNL';
        cuentaNormal.Codigo__c='der3';
        cuentaNormal.Cliente__c=ClientePrueba3.id;
        cuentanormal.Cuenta_colectiva2__c=cuentacolectiva.id;
        cuentaNormal.Producto__c=producto.id;
        insert cuentaNormal;
        
        Usuario_Portal_Empresarial__c usuario = new Usuario_Portal_Empresarial__c();
        usuario.Apellidos__c='Meraz';
        usuario.Contrasena2__c='Cualquiera';
        usuario.Email__c='marcela.meraz@gmail.com';
        usuario.Name='Yeny';
        usuario.Respuesta__c='Lunes';
        usuario.Identidad__c='0303199702883';
        usuario.Nombre_Usuario__c='chema';
        insert usuario;
        
        Usuario_X_Empresa__c a = new Usuario_X_Empresa__c();
        a.empresa2__C=empresaprueba.id;
        a.Usuario__c=usuario.id;
        a.Activo__c=true;
        a.Aprobacion_Usuarios__c=TRUE;
        a.Calculo_De_Pilares__c=true;
        a.Cargar_Generar_Planilla__c=true;
        a.Crear_Usuarios__c=true;
        a.Nuevo_Personal__c=true;
        a.Reportes__c=true;
        a.Planilla_Seguro_Social__c=true;
        insert a;
        
        Tiempo_Inactividad__c hora= new Tiempo_Inactividad__c();
        hora.Usuario__c=usuario.id;
        hora.Hora_ultima_consulta__c=datetime.now();
        insert hora; 
        
        empresa_x_empleado__C empleado= new empresa_x_empleado__C();
        empleado.Activo_Nueva_Planilla__c=true;
        empleado.Empresa2__c=empresaprueba.id;
        empleado.Salario__c=20000;
        empleado.Estado__c='Activo';
        empleado.Empleado2__c=clienteprueba.id;
        insert empleado;
        
        empleado= new empresa_x_empleado__C();
        empleado.Activo_Nueva_Planilla__c=true;
        empleado.Empresa2__c=empresaprueba.id;
        empleado.Salario__c=15000;
        empleado.Estado__c='Activo';
        empleado.Empleado2__c=clienteprueba2.id;
        insert empleado;
        
        empleado= new empresa_x_empleado__C();
        empleado.Activo_Nueva_Planilla__c=false;
        empleado.Empresa2__c=empresaprueba.id;
        empleado.Salario__c=30000;
        empleado.Estado__c='Activo';
        empleado.Empleado2__c=clienteprueba3.id;
        insert empleado;
        
        Autonumerico_cuentas_Syste__c gtp= new Autonumerico_cuentas_Syste__c();
        gtp.Id_Formulario_Sysde__c=0;
        insert gtp;   
        
        
        
        
        
         
        
        string stringCSV = '"NUM IDENTIDAD", "APORTE PATRONO OBLIGATORIO", "APORTE EMPLEADO OBLIGATORIO", "RESERVA LABORAL", "APORTE PATRONO VOLUNTARIO",'+
            			   ' "CUENTA", "APORTE EMPLEADO EXTRAORDINARIO", "APORTE PATRONO EXTRAORDINARIO", "APORTE SEGURO DE VIDA", "APORTE EMPLEADO VOLUNTARIO"\n"0000000000040",12,12,12,12,12,12,12,"",12\n';
        classWRetorno2 error = new classWRetorno2();
        error=controladorCargarPlanilla.SUbirInformacion(stringCSV, empresaprueba.id);
        
        string stringCSV2 = '"NUM IDENTIDAD", "APORTE PATRONO OBLIGATORIO", "APORTE EMPLEADO OBLIGATORIO", "RESERVA LABORAL", "APORTE PATRONO VOLUNTARIO",'+
            				' "CUENTA", "APORTE EMPLEADO EXTRAORDINARIO", "APORTE PATRONO EXTRAORDINARIO", "APORTE SEGURO DE VIDA", "APORTE EMPLEADO VOLUNTARIO"\n"0000000000040",0,0,0,0,0,0,0,0,0,0\n';
        classWRetorno2 error2 = new classWRetorno2();
        error2=controladorCargarPlanilla.SUbirInformacion(stringCSV2, empresaprueba.id);
        
        string stringCSV3 = '"NUM IDENTIDAD", "APORTE PATRONO OBLIGATORIO", "APORTE EMPLEADO OBLIGATORIO", "RESERVA LABORAL", "APORTE PATRONO VOLUNTARIO",'+
            				' "CUENTA", "APORTE EMPLEADO EXTRAORDINARIO", "APORTE PATRONO EXTRAORDINARIO", "APORTE SEGURO DE VIDA", "APORTE EMPLEADO VOLUNTARIO"\n"0000000000040",12,12,12,12,"",12\n';
        classWRetorno2 error3 = new classWRetorno2();
        error3=controladorCargarPlanilla.SUbirInformacion(stringCSV3, empresaprueba.id);
        
        list<planilla> planil=new list<Planilla>(); 
        planil.add(new planilla('A','B','C','D','E','F','G','H',date.today(),'',7.7,7.7,7.7,7.7,7.7,7.7,7.7,7.7,7.7));
        
        //pp=controladorCargarPlanilla.SUbirInformacion(stringCSV2, empresaprueba.id);
        ApexPages.currentPage().getParameters().put('Eldudhdhyudb',empresaprueba.id);
        ApexPages.currentPage().getParameters().put('loetdncdhjch',usuario.id);
        ApexPages.currentPage().getParameters().put('Moneda','HNL');
        controladorCargarPlanilla Cplanilla = new controladorCargarPlanilla();
        
        Planilla_Temporal__c tem = new Planilla_Temporal__c();
        tem.Name = EmpresaPrueba.Id;
        insert tem;
        Planilla_Temporal__c NuevaPlanilla = new Planilla_Temporal__c();
        NuevaPlanilla =[select id, Numeracion_Automativa__c from Planilla_Temporal__c where name=:EmpresaPrueba.Id order by Numeracion_Automativa__c DESC limit 1];
            
        Contenido_Planilla_Temporal__c temp = new Contenido_Planilla_Temporal__c();
        temp.Identidad__c = ClientePrueba3.Identificacion__c;
        temp.Cuenta__c = cuentaNormal.Codigo__c;
        temp.Aporte_Empleado_Voluntario__c = 1.0;
        temp.Aporte_Empleado_Obligatorio__c = 0.0;
        temp.Aporte_Patronal_Obligatorio__c = 0.0;
        temp.Aporte_Patronal_Voluntario__c = 2.0;
        temp.Aporte_Reserva_Laboral__c = 0.0;
        temp.Aporte_Empleado_Extraordinario__c = 200.00;
        temp.Aporte_Patrono_Extraordinario__c =0.0;
        temp.Aporte_Seguro_de_Vida__c = 0.0;
        temp.planilla__c = NuevaPlanilla.Id;
        insert temp;
        cplanilla.VerPlanilla();
        cuentaNormal= new Cuentas__C();
        cuentaNormal.CurrencyIsoCode='HNL';
        cuentaNormal.Codigo__c='der2';
        cuentaNormal.Cliente__c=ClientePrueba2.id;
        cuentanormal.Cuenta_colectiva2__c=null;
        cuentaNormal.Producto__c=producto.id;
        insert cuentaNormal;
        cplanilla.VerPlanilla();
        cplanilla.Cargarmeses();
        cplanilla.sumas();
        cplanilla.popEnviar();
        cplanilla.popGuardar();
        cplanilla.Si();
        cplanilla.No();
        //cplanilla.EnviarPlanilla(2);
        cplanilla.siguiente();
        cplanilla.anterior();
        cplanilla.salir();
        cplanilla.NuevaCarga();
       
        cplanilla.CalculoDePilares();
        cplanilla.metodoutil();

        test.stopTest();
    }  
}