force-app/main/default/objects/Account/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_Barra__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Barra__c</fullName>
    <label>Número de Carné</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comercio_Afiliado__c/Comercio_Afiliado__c.object-meta.xml
<CustomObject>
    <label>Comercio Afiliado</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comercios Afiliados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/Descuento__c.object-meta.xml
<CustomObject>
    <label>Descuento</label>
    <nameField>
        <displayFormat>Des-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Descuentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento__c/fields/Comercio_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Comercio_Afiliado__c</fullName>
    <label>Comercio Afiliado</label>
    <referenceTo>Comercio_Afiliado__c</referenceTo>
    <relationshipLabel>Descuentos</relationshipLabel>
    <relationshipName>Descuentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/Transaccion__c.object-meta.xml
<CustomObject>
    <label>Transaccion</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Número de Transaccion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transacciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaccion__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transacciones</relationshipLabel>
    <relationshipName>Transacciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/fields/Comercio_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Comercio_Afiliado__c</fullName>
    <label>Comercio Afiliado</label>
    <referenceTo>Comercio_Afiliado__c</referenceTo>
    <relationshipLabel>Transacciones</relationshipLabel>
    <relationshipName>Transacciones</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Descuento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Comercio_Afiliado__c</field>
            <operation>equals</operation>
            <valueField>Descuento__c.Comercio_Afiliado__c</valueField>
        </filterItems>
        <filterItems>
            <field>Descuento__c.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Descuento__c</referenceTo>
    <relationshipLabel>Transacciones</relationshipLabel>
    <relationshipName>Transacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/fields/Fecha_hora_Transaccion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hora_Transaccion__c</fullName>
    <label>Fecha y hora de la Transacción</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/fields/Monto__c.field-meta.xml
<CustomField>
    <fullName>Monto__c</fullName>
    <label>Monto de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaccion__c/fields/Usuario_Portal__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Portal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario de Portal</label>
    <referenceTo>Usuario_de_Portal__c</referenceTo>
    <relationshipLabel>Transacciones</relationshipLabel>
    <relationshipName>Transacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controlTransacciones.cls
public class controlTransacciones {
    public string numeroAfiliado{get;set;}
    public string nombreAfiliado{get;set;}
    public Transaccion__c nTransaccion{get;set;}
    
    public boolean noEncontrado {get;set;}
    
    public string paso1Cabeza{get;set;}
    public string paso1Cuerpo{get;set;}
    
    public string paso2Cabeza{get;set;}    
    public string paso2Cuerpo{get;set;}
    
    public controlTransacciones(){                       
        iniciar();
    }
    
    public void iniciar(){
        numeroAfiliado = '';
        nombreAfiliado = '';
        nTransaccion = new Transaccion__c();
        nTransaccion.Monto__c = 0;
            
        paso1Cabeza = 'slds-is-current';
        paso1Cuerpo = 'slds-show';
        
        paso2Cabeza = 'slds-is-incomplete';
        paso2Cuerpo = 'slds-hide';
        
        noEncontrado = false; 
        
    }
    
    public string buscarAfiliado(){
        try{
            noEncontrado = false;
            numeroAfiliado = numeroAfiliado.replace('-','');
            numeroAfiliado = numeroAfiliado.replace(' ','');
                      
            Account cliente = [Select Id,Name, Activo__c From Account 
                                    Where Identificacion__c =: numeroAfiliado OR Codigo_de_Barra__c =: numeroAfiliado Limit 1];
            
            if(cliente.Activo__c){                        
	            nombreAfiliado = cliente.Name;
	            
	            nTransaccion.Cliente__c = cliente.Id;
	            nTransaccion.Comercio_Afiliado__c = ApexPages.currentPage().getParameters().get('IdComercio');
	            nTransaccion.Fecha_hora_Transaccion__c = system.now();
	            nTransaccion.currencyIsoCode = 'HNL';
	            nTransaccion.Descuento__c = ApexPages.currentPage().getParameters().get('idDescuento');
	            nTransaccion.Usuario_portal__c = ApexPages.currentPage().getParameters().get('idUsuario');
	            
	            paso1Cabeza = 'slds-is-complete';
	            paso1Cuerpo = 'slds-hide';
	            
	            paso2Cabeza = 'slds-is-current';
	            paso2Cuerpo = 'slds-show';
	            
            }else{
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Cliente no Activo'));	
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Cliente no encontrado'));
        }
        return null;
    }
    
    public void cerrar(){
        noEncontrado = false;
    }
    
    public void guardar(){
        try{
            insert nTransaccion;
            noEncontrado = true;
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,'Transacción guardada correctamente!'));
        }catch(System.DmlException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getDmlMessage(0)));
        }
    
    }   
}