force-app/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <label>Asesor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HN21892</fullName>
                <label>ALEJANDRA VASQUEZ</label>
            </value>
            <value>
                <fullName>HN22258</fullName>
                <label>ALEYDA URRUTIA</label>
            </value>
            <value>
                <fullName>HN02713</fullName>
                <label>ANA ANDINO</label>
            </value>
            <value>
                <fullName>HN18812</fullName>
                <label>ANA RAUDES</label>
            </value>
            <value>
                <fullName>HN19331</fullName>
                <label>ANDREA PACHECO</label>
            </value>
            <value>
                <fullName>HN18762</fullName>
                <label>ANGELA GOMEZ</label>
            </value>
            <value>
                <fullName>HN24669</fullName>
                <label>ANGELICA GALLARDO</label>
            </value>
            <value>
                <fullName>HN24668</fullName>
                <label>BELKY FERRUFINO</label>
            </value>
            <value>
                <fullName>HN25948</fullName>
                <label>CARMEN GEHL</label>
            </value>
            <value>
                <fullName>HN22758</fullName>
                <label>CAROLINA HANDAL</label>
            </value>
            <value>
                <fullName>HN02852</fullName>
                <label>CLAUDIA MANCIA</label>
            </value>
            <value>
                <fullName>HN21653</fullName>
                <label>DARIO OYUELA</label>
            </value>
            <value>
                <fullName>HN19320</fullName>
                <label>DIANA ORTIZ</label>
            </value>
            <value>
                <fullName>HN22061</fullName>
                <label>GABRIELA CARCAMO</label>
            </value>
            <value>
                <fullName>HN21718</fullName>
                <label>IRIS PINEDA</label>
            </value>
            <value>
                <fullName>HN00387</fullName>
                <label>IRIS PORTILLO</label>
            </value>
            <value>
                <fullName>HN21645</fullName>
                <label>JENNIFER NIETO</label>
            </value>
            <value>
                <fullName>HN23292</fullName>
                <label>JESICA ESPAÑA</label>
            </value>
            <value>
                <fullName>HN23268</fullName>
                <label>JOSE LUIS AGUILERA</label>
            </value>
            <value>
                <fullName>HN22984</fullName>
                <label>JULIO VALLE</label>
            </value>
            <value>
                <fullName>HN22419</fullName>
                <label>KAROL MONTENEGRO</label>
            </value>
            <value>
                <fullName>HN19334</fullName>
                <label>KENIA RIVERA</label>
            </value>
            <value>
                <fullName>HN19337</fullName>
                <label>LAURA ALMENDAREZ</label>
            </value>
            <value>
                <fullName>HN25947</fullName>
                <label>LESLY ANARIBA</label>
            </value>
            <value>
                <fullName>HN25900</fullName>
                <label>LILIAN ACEVEDO</label>
            </value>
            <value>
                <fullName>HN18774</fullName>
                <label>LILIANA SALAZAR</label>
            </value>
            <value>
                <fullName>HN19333</fullName>
                <label>LUIS MATEO</label>
            </value>
            <value>
                <fullName>HN24735</fullName>
                <label>MARYORY VASQUEZ</label>
            </value>
            <value>
                <fullName>HN23483</fullName>
                <label>MONICA ALBERTO</label>
            </value>
            <value>
                <fullName>HN00313</fullName>
                <label>NEFTALI RAMOS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/Oficiales_X_Empresa__c.object-meta.xml
<CustomObject>
    <label>Oficial por Empresa</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Corrrelativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficiales por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Empresa1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Codigo_Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Oficial_SAC__c</fullName>
    <label>Código Oficial SAC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Juridico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oficiales por Empresa</relationshipLabel>
    <relationshipName>Oficiales_por_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oficiales_X_Empresa__c/fields/Oficial_SAC__c.field-meta.xml
<CustomField>
    <fullName>Oficial_SAC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficial SAC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oficiales_por_Empresa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/controladorOficialxEmpresa.cls
public class controladorOficialxEmpresa {

    public list<Oficiales_X_Empresa__c > listAsesoresxOficiales {get;set;}
    public Oficiales_X_Empresa__c  AsesorxOficial {get;set;}
    //public list<user> listAsesores {get;set;}
    //public list<user> listOfiaales {get;set;}
    public string idAsesor {get;set;}
    public list<selectOption> listAsesores{get;set;}
    public list<selectOption> listEmpresas{get;set;}
    public list<selectOption> listOficiales{get;set;}
    public map<string, string> mapAsesores {get;set;}
    public map<string, string> mapCodigos {get;set;}

    
    public controladorOficialxEmpresa (){
        listAsesores = new list<selectOption>();
        listOficiales = new list<selectOption>();
        listEmpresas = new list<selectOption>();
        mapCodigos = new map<string, string>();
        listAsesores.add(new selectOption('', '--Ninguno--'));
        listOficiales.add(new selectOption('', '--Ninguno--'));
        for(user item :[select name, id ,codigo__C, profile.name from user where profile.name ='Asesores Financieros' OR profile.name ='Asesores Financieros Plataforma' OR profile.name = 'Servicio Cliente']){
            mapCodigos.put(item.id, item.codigo__C);
            if(item.profile.name =='Asesores Financieros' || item.profile.name =='Asesores Financieros Plataforma'){
                listAsesores.add(new selectOption(item.id, item.name));
                
            }else{
                listOficiales.add(new selectOption(item.id, item.name));
            }
        }
        for(Account item: [select id, name from Account  where recordtype.developername='Juridico' order by name asc]){
            listEmpresas.add(new selectOption(item.id, item.name));
        }
        inicio();
    }
    
    public void inicio(){
        try{
            AsesorxOficial = new Oficiales_X_Empresa__c ();
            listAsesoresxOficiales = new list<Oficiales_X_Empresa__c >();
            listAsesoresxOficiales = [select Oficial_SAC__c,asesor__C,Oficial_SAC__r.name, Asesor__r.name,id, Codigo_Oficial_SAC__C,
                           Codigo_Asesor__C, empresa__r.name from Oficiales_X_Empresa__c  where Oficial_SAC__c !=null and Asesor__c !=null  order by Oficial_SAC__r.name asc];
        }catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,' Ha ocurrido un error, por favor contacte a sus administrador.'+ex.getLineNumber()));
        }
    }
    
    public void editar(){
        AsesorxOficial = new Oficiales_X_Empresa__c ();
        for(Oficiales_X_Empresa__c  item: listAsesoresxOficiales ){
            if(item.id == idAsesor){
                AsesorxOficial = item;
            }
        }
    }
    
    public void Guardar(){
        try{
            upsert AsesorxOficial;
            inicio();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,' Datos Guardados Exitosamente.'));
        }catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,' Ha ocurrido un error, por favor contacte a sus administrador.'+ex.getLineNumber()));
        }
    }
    
    public void selectAsesor(){
        AsesorxOficial.Codigo_Asesor__c = mapCodigos.containsKey(AsesorxOficial.Asesor__c) ? mapCodigos.get(AsesorxOficial.Asesor__c) : '';
    }
   
    public void selectOficial(){
        AsesorxOficial.Codigo_Oficial_SAC__c = mapCodigos.containsKey(AsesorxOficial.Oficial_SAC__c) ? mapCodigos.get(AsesorxOficial.Oficial_SAC__c) : '';
    }
    
    
    
}