force-app/main/default/objects/Account/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>MASCULINO</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>FEMENINO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <formula>MONTH(DATEVALUE(CreatedDate) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <label>Respuesta desde Salesforce Tarjetas</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24</fullName>
                <label>Bac Honduras</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Banco Atlantida</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Banco Azteca</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>Banco Banadesa</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Banco Banrural</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Banco Central de Honduras</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Banco Davivienda</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Banco de Honduras</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Banco de los Trabajadores</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Banco del País</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Banco de Occidente</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Banco Ficensa</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Banco Ficohsa</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Banco Hondureño del Café</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Banco Lafise</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Banco Promerica</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Bancovelo</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Credi Q</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/DAU_Salesforce_Tarjetas__e.object-meta.xml
<CustomObject>
    <label>DAU_Salesforce_Tarjetas</label>
    <pluralLabel>DAU_Salesforce_Tarjetas</pluralLabel>
</CustomObject>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_IdCaso__c.field-meta.xml
<CustomField>
    <fullName>DAU_IdCaso__c</fullName>
    <label>DAU_IdCaso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Ano_tarjeta__c.field-meta.xml
<CustomField>
    <fullName>Ano_tarjeta__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
                <isActive>false</isActive>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <isActive>false</isActive>
                <label>2018</label>
            </value>
            <value>
                <fullName>2026</fullName>
                <isActive>false</isActive>
                <label>2026</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Banco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Dia_de_pago__c.field-meta.xml
<CustomField>
    <fullName>DAU_Dia_de_pago__c</fullName>
    <label>DAU_Día de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Tarjeta_Habiente__c.field-meta.xml
<CustomField>
    <fullName>DAU_Tarjeta_Habiente__c</fullName>
    <label>Nombre Tarjeta Habiente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Tipo_Tarjeta__c.field-meta.xml
<CustomField>
    <fullName>DAU_Tipo_Tarjeta__c</fullName>
    <label>Tipo de Tarjeta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nuevo_monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nuevo_monto_aporte__c</fullName>
    <label>Nuevo monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <description>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</description>
    <inlineHelpText>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</inlineHelpText>
    <label>Respuesta Otro Sistema</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
                <default>true</default>
                <label>Aumento de Aporte</label>
            </value>
            <value>
                <fullName>A2</fullName>
                <label>Disminución de Aporte</label>
            </value>
            <value>
                <fullName>A3</fullName>
                <label>Cambio de Canal de Aporte</label>
            </value>
            <value>
                <fullName>A4</fullName>
                <label>Cambio de Fecha de Aporte</label>
            </value>
            <value>
                <fullName>A5</fullName>
                <label>Cambio de # de CA/CC</label>
            </value>
            <value>
                <fullName>A6</fullName>
                <label>Cambio de # Tarjeta</label>
            </value>
            <value>
                <fullName>A7</fullName>
                <label>Cancelación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DAU_GestionesBac.cls
public class DAU_GestionesBac {
    @future(callout=true)
    public static void execute(String CaseId/*, classGestionesBac envioDatos*/) {        
        
        System.debug('Caso: '+CaseId);
        
        Case c = [Select Id,Respuesta_SF_Tarjetas__c,Account.Identificacion__c,Account.Name,Account.PersonEmail,Account.Celular__c,
                  Account.Sexo__c From Case Where Id =: CaseId];
        
        Detalle_caso__c detC = [Select Id,Cuenta__r.Name,N_Cuenta_Bancaria__c,Mes__c,Ano_tarjeta__c,DAU_Dia_de_pago__c, Tipo_Operacion__c,	
                                DAU_Tarjeta_Habiente__c,DAU_Tipo_Tarjeta__c,Nuevo_monto_aporte__c,toLabel(Banco__c) 
                                From Detalle_caso__c Where Caso__c =: c.Id];
        
        String tipoGestion;
        String estadoDebito = 'A';
        
        classGestionesBac datos = new classGestionesBac();
        if(detC.Tipo_Operacion__c == 'A3' || detC.Tipo_Operacion__c == 'A8') {
            tipoGestion = 'afiliaDebito';
        } else if(detC.Tipo_Operacion__c == 'A4') {
            tipoGestion = 'modificaDebito';
        } else if(detC.Tipo_Operacion__c == 'A7') {
            tipoGestion = 'modificaDebito';
            estadoDebito = 'C';
        }
        datos.tipoGestion = tipoGestion;
        datos.identificacion = c.Account.Identificacion__c;
        datos.nombreCliente = String.valueOf(Account.Name);
        datos.email = String.valueOf(Account.PersonEmail);
        datos.celular = String.valueOf(Account.Celular__c);
        datos.sexo = String.valueOf(Account.Sexo__c);
        datos.servicio = 'Pensiones';
        datos.cuentaPensiones = detC.Cuenta__r.Name;
        datos.tipoTarjeta = detC.DAU_Tipo_Tarjeta__c;
        datos.nombreTarjetaHabiente = detC.DAU_Tarjeta_Habiente__c;
        datos.numeroTarjeta = detC.N_Cuenta_Bancaria__c; 
        String Anio = detC.Ano_tarjeta__c;
        Anio.Substring(Anio.length()-2);
        datos.fechaExpiracion = detC.Mes__c+Anio;
        datos.bancoTarjeta = detC.Banco__c;
        datos.diaCobro = detC.DAU_Dia_de_pago__c;
        datos.montoDebito = String.valueOf(detC.Nuevo_monto_aporte__c);
        datos.estadoDebito = estadoDebito;
        
        Http http = new Http();
		HttpRequest request = new HttpRequest();
		String url = claseUtil.urlSysde('Test');		
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		request.setTimeout(120000);
		request.setEndpoint(url + 'api/gestionesBac');
        
		String respuesta = '';
		system.debug('Entro al metodo API');
		try{		
			classJson envio = new classJson();
			envio.contenido = JSON.serialize(datos/*envioDatos*/);
            String cons = 'contenido=' + envio.contenido;
			system.debug('cons: '+cons);		
			request.setBody(cons);	
			HttpResponse response = http.send(request);
	    	respuesta = response.getBody();
            system.debug('respuesta: '+respuesta);
            //respuesta = 'Débito creado correctamente';
            if(respuesta == 'Débito creado correctamente') {
                c.Respuesta_SF_Tarjetas__c = respuesta;
                update c;
            	System.debug('Entró'); 
                /*List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_EjecutarSYSDE__c = true));
                // Call method to publish events
                List<Database.SaveResult> results = EventBus.publish(Logs);*/
            }
		}catch(System.CalloutException e){
			system.debug('Mensaje Conexión: '+e.getMessage());
            respuesta = e.getMessage();
        }
		//return respuesta;     
    }    
}