force-app/main/default/objects/Account/fields/Cliente_Unico_Banco__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Unico_Banco__c</fullName>
    <externalId>true</externalId>
    <label>Cliente Unico Banco</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proyeccion__c/Proyeccion__c.object-meta.xml
<CustomObject>
    <label>Proyección</label>
    <nameField>
        <displayFormat>PYC-{000000000}</displayFormat>
        <label>Nombre de Proyección</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proyecciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyeccion__c/fields/Anios__c.field-meta.xml
<CustomField>
    <fullName>Anios__c</fullName>
    <label>Años</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
                <default>true</default>
                <label>25</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proyeccion__c/fields/AporteInicial__c.field-meta.xml
<CustomField>
    <fullName>AporteInicial__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Inicial</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proyeccion__c/fields/AporteMensual__c.field-meta.xml
<CustomField>
    <fullName>AporteMensual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Mensual</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proyeccion__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proyecciones</relationshipLabel>
    <relationshipName>Proyecciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyeccion__c/fields/ComisionAporte__c.field-meta.xml
<CustomField>
    <fullName>ComisionAporte__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Comisión por Aporte</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ControladorProyeccionConsolidado_Test.cls
@istest
public class ControladorProyeccionConsolidado_Test {
    
    static testMethod void aSysdeSincronizador() {
        Account  acc = new Account();
        acc.FirstName = 's';
        acc.LastName = 'S';
        acc.Cliente_Unico_Banco__c = '12';
        acc.PersonEmail = 'test@test.com';
        insert acc;
        Proyeccion__c proy = new proyeccion__c();
        proy.Anios__c = '10';
        proy.AporteInicial__c = 500;
        proy.AporteMensual__c = 10;
        proy.Cliente__c = acc.Id;
        proy.ComisionAporte__c = 5;
        insert proy;
        
        User u = new User(Id = UserInfo.getUserId(), MobilePhone = '123456', Phone = '12345');
        update u;
        
        Test.startTest();
        ControladorGraficoProyecciones.calculoGrafico(proy.id);
        ControladorGraficoProyecciones.envioCorreo(proy.id,'test@test.com', 'Ambas');
        Test.stopTest();
       
     }

}