force-app/main/default/objects/Account/fields/Cliente_Unico_Banco__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Unico_Banco__c</fullName>
    <externalId>true</externalId>
    <label>Cliente Unico Banco</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BitacoraCreacionUsuario__c/BitacoraCreacionUsuario__c.object-meta.xml
<CustomObject>
    <label>Bitácora Creación de Usuario</label>
    <nameField>
        <displayFormat>CU-{000000}</displayFormat>
        <label>Nombre de Bitácora Creación de Usuario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bitácora Creación de Usuarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BitacoraCreacionUsuario__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bitácora Creación de Usuarios</relationshipLabel>
    <relationshipName>BitacoraCreacionUsuarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BitacoraCreacionUsuario__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CrearUsuarioPortalAutogestion.cls
public class CrearUsuarioPortalAutogestion {


    @auraEnabled
    public static String crearUsuario(String recordId){
        Cuentas__c cuenta = [Select Codigo__c, Cliente__r.Tipo_Identificacion__c, Cliente__r.Identificacion__c, Cliente__r.Cliente_Unico_Banco__c from Cuentas__c Where cliente__c =: recordId limit 1];
        Cliente acc = new Cliente();
        acc.Cuenta = cuenta.Codigo__c;
        acc.ID = cuenta.Cliente__r.Tipo_Identificacion__c;
        acc.NroId = cuenta.Cliente__r.Identificacion__c;
        String body = JSON.serialize(acc);
        System.debug('Mandamos: '+body);
        Http http = new Http();
        String url = claseUtil.urlSysde('Api451');
        HttpRequest request = new HttpRequest();
        request.setEndpoint(url+'api/RegistroSF');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setBody(body);
        try{
            HttpResponse response = http.send(request);
            if(response.getStatusCode() != 200 || response.getStatusCode() != 201) {
                BitacoraCreacionUsuario__c bit = new BitacoraCreacionUsuario__c ();
                bit.Codigo__c = response.getStatusCode();
                bit.Response__c = response.getBody();
                bit.Request__c = body;
                bit.Cliente__c = recordId;
                insert bit;
                return 'Ha ocurrido un error en el registro del usuario de portal, por favor contacte al administrador del sistema.';
            } else {
                return 'Usuario de portal registrado correctamente.';
            }
        }catch(Exception ex){
            system.debug('Error: '+ex.getMessage()+', Linea: '+ex.getLineNumber());
            return ex.getMessage();
        }
    }
    
    
    public class Cliente{
        @auraEnabled public String Cuenta {get;set;}
        @auraEnabled public String ID {get;set;}
        @auraEnabled public String NroId {get;set;}
    }
}