force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120</fullName>
                <label>ATLANTIDA</label>
            </value>
            <value>
                <fullName>135</fullName>
                <label>CHOLUTECA</label>
            </value>
            <value>
                <fullName>137</fullName>
                <label>COLON</label>
            </value>
            <value>
                <fullName>126</fullName>
                <label>COMAYAGUA</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>COPAN</label>
            </value>
            <value>
                <fullName>122</fullName>
                <label>CORTES</label>
            </value>
            <value>
                <fullName>136</fullName>
                <label>EL PARAISO</label>
            </value>
            <value>
                <fullName>123</fullName>
                <label>FRANCISCO MORAZAN</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>GRACIAS A DIOS</label>
            </value>
            <value>
                <fullName>133</fullName>
                <label>INTIBUCA</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>ISLAS DE LA BAHIA</label>
            </value>
            <value>
                <fullName>132</fullName>
                <label>LA PAZ</label>
            </value>
            <value>
                <fullName>131</fullName>
                <label>LEMPIRA</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>ND</label>
            </value>
            <value>
                <fullName>128</fullName>
                <label>OCOTEPEQUE</label>
            </value>
            <value>
                <fullName>125</fullName>
                <label>OLANCHO</label>
            </value>
            <value>
                <fullName>127</fullName>
                <label>SANTA BARBARA</label>
            </value>
            <value>
                <fullName>134</fullName>
                <label>VALLE</label>
            </value>
            <value>
                <fullName>124</fullName>
                <label>YORO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>MASCULINO</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>FEMENINO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departamento__c/fields/Codigo_Departamento__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Departamento__c</fullName>
    <externalId>true</externalId>
    <label>Código Departamento</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Departamentos__c/Departamentos__c.object-meta.xml
<CustomObject>
    <label>Departamento</label>
    <nameField>
        <label>Nombre de Departamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departamentos__c/fields/codigo_departamento__c.field-meta.xml
<CustomField>
    <fullName>codigo_departamento__c</fullName>
    <label>codigo_departamento</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Departamentos__c/fields/codigo_pais__c.field-meta.xml
<CustomField>
    <fullName>codigo_pais__c</fullName>
    <label>codigo_pais</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Departamentos__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <description>Identidad del candidato.</description>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Pais_r__c.field-meta.xml
<CustomField>
    <fullName>Pais_r__c</fullName>
    <label>Pais_r</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Estados Unidos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
                <default>true</default>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CARNET RESIDENCIA</fullName>
            </value>
            <value>
                <fullName>CEDULA IDENTIDAD</fullName>
            </value>
            <value>
                <fullName>PASAPORTE</fullName>
            </value>
            <value>
                <fullName>RTN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/objects/Pais_R__c/Pais_R__c.object-meta.xml
<CustomObject>
    <label>Pais_R</label>
    <nameField>
        <label>Nombre de Pais</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises_R</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais_R__c/fields/codigo__c.field-meta.xml
<CustomField>
    <fullName>codigo__c</fullName>
    <label>codigo</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais_R__c/fields/nombre__c.field-meta.xml
<CustomField>
    <fullName>nombre__c</fullName>
    <label>nombre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/PreVenta__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado para prospectos o candidatos.</description>
    <label>PreVenta</label>
    <nameField>
        <label>Nombre de PreVenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreVentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreVenta__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Nombres</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Apellidos</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARNET RESIDENCIA</fullName>
            </value>
            <value>
                <fullName>CEDULA IDENTIDAD</fullName>
            </value>
            <value>
                <fullName>PASAPORTE</fullName>
            </value>
            <value>
                <fullName>RTN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <label>Natural</label>
</RecordType>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/Usuarios_para_asignacion_Casos_SAC__c.object-meta.xml
<CustomObject>
    <label>Usuarios para asignacion - Casos SAC</label>
    <nameField>
        <displayFormat>ACSAC-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios para asignación - Casos SAC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Usuarios_para_asignacion_Casos_SAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testPromociones3.cls
@isTest
public class testPromociones3 {
    static testMethod void ControllerPromociones3(){
        Account cuenta = new Account();
        cuenta.lastname='Doanire';
        cuenta.firstname='Luis';
        cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Natural').getRecordTypeId();
        cuenta.Identificacion__c='00000000000000';
        cuenta.Tipo_Identificacion__c='Cedula de identidad';
        cuenta.Sexo__c='Masculino';
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Estado_Civil__pc='Soltero';
        insert cuenta;
        
        PreVenta__c  PV = new PreVenta__c ();
        PV.FirstName__c = 'test';
        PV.LastName__c = 'Test';
        PV.Identificacion__c = '00000000000001';
        insert PV;
        
        Pais_R__c pais = new Pais_R__c();
        pais.codigo__c = '052';
        pais.nombre__c = 'Pais Name';
        insert pais;
        
        pais = new Pais_R__c();
        pais.codigo__c = '123';
        pais.nombre__c = 'Pais Name';
        //pais.ActivoAfiliacionExtranjero__C = true;
        insert pais;
        
        Departamentos__c dep =new Departamentos__c();
        dep.codigo_departamento__c = '123';
        dep.codigo_pais__c = '123';
        dep.Name = 'Nombre D';
        dep.Departamento__c = '123';
        insert dep;
        
        Usuarios_para_asignacion_Casos_SAC__c usuarioAS = new Usuarios_para_asignacion_Casos_SAC__c();
        usuarioAS.Usuario__c = userInfo.getUserId();
        usuarioAS.Objeto__c = 'Lead';
        insert usuarioAS;
        
        ApexPages.currentPage().getParameters().put('idPage:theForm:Fpais','123');
        ControllerPromociones3 controlador = new ControllerPromociones3();
        controlador.candidato.Identificacion__c = '123';
        controlador.depto = '0';
        controlador.guardar();
        
        controlador.getDepartamento();
        controlador.depto = '123';
        controlador.pais = '052';
        controlador.candidato.Phone = '123456789';
        controlador.guardar();
        
        controlador.pais = '052';
        controlador.candidato.Phone = '12345678';
        controlador.candidato.Telefono_Trabajo__c = '123456789';
        controlador.guardar();
        
        controlador.candidato.Telefono_Trabajo__c = '12345678';
        controlador.pais = '123';
        controlador.candidato.FirstName = 'Test';
        controlador.candidato.LastName = 'Test';
        controlador.guardar();
        
        controlador.candidato.Telefono_Trabajo__c = '12345678';
        controlador.pais = '123';
        controlador.candidato.Identificacion__c = '00000000000000';
        controlador.candidato.FirstName = 'Test';
        controlador.candidato.LastName = 'Test';
        controlador.candidato.Phone = '1232321';
        controlador.guardar();
        
        controlador.candidato.Telefono_Trabajo__c = '12345678';
        controlador.pais = '123';
        controlador.candidato.Identificacion__c = '00000000000001';
        controlador.candidato.FirstName = 'Test';
        controlador.candidato.LastName = 'Test';
        controlador.candidato.Phone = '1232321';
        controlador.guardar();
        
        controlador.guardar();
         
    }
    
    
}