force-app/main/default/objects/Account/fields/Departamento_Residencia2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Residencia2__c</fullName>
    <label>Departamento Residencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento_Trabajo2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Trabajo2__c</fullName>
    <label>Departamento Trabajo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agencia__c/Agencia__c.object-meta.xml
<CustomObject>
    <label>Agencia</label>
    <nameField>
        <label>Nombre de Agencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agencia__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>Centro - Sur</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Nor - Occidental</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agencia</label>
    <referenceTo>Agencia__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Constancia__c.field-meta.xml
<CustomField>
    <fullName>Constancia__c</fullName>
    <label>Constancia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constancia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Departamento_Residencia2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Residencia2__c</fullName>
    <label>Departamento Residencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Departamento_Trabajo2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Trabajo2__c</fullName>
    <label>Departamento Trabajo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Estado_Cuenta_Detallado__c.field-meta.xml
<CustomField>
    <fullName>Estado_Cuenta_Detallado__c</fullName>
    <label>Estado de Cuenta Detallado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_Estado_Cuenta__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Historico</fullName>
            </value>
            <value>
                <fullName>A1.1</fullName>
                <isActive>false</isActive>
                <label>A1.1</label>
            </value>
            <value>
                <fullName>A1.2</fullName>
                <isActive>false</isActive>
                <label>A1.2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hasta__c</fullName>
    <label>Fecha hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_Movil__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Movil__c</fullName>
    <label>Teléfono Movil</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_Estado_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Estado_Cuenta__c</fullName>
    <label>Tipo de Estado de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
                <default>true</default>
                <label>Detallado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Actualizacion_informacion.recordType-meta.xml
<RecordType>
    <fullName>Actualizacion_informacion</fullName>
    <active>true</active>
    <businessProcess>Aumento o Disminución de Aportes</businessProcess>
    <label>Actualización de información</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Aumento_Disminucion_Aportes.recordType-meta.xml
<RecordType>
    <fullName>Aumento_Disminucion_Aportes</fullName>
    <active>true</active>
    <businessProcess>Aumento o Disminución de Aportes</businessProcess>
    <label>Modificación de aportes</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Constancia.recordType-meta.xml
<RecordType>
    <fullName>Constancia</fullName>
    <active>true</active>
    <businessProcess>Constancia</businessProcess>
    <label>Constancia</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Estados_Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Estados_Cuenta</fullName>
    <active>true</active>
    <businessProcess>Estados de Cuenta</businessProcess>
    <label>Estados de Cuenta</label>
</RecordType>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicion_Carnet.recordType-meta.xml
<RecordType>
    <fullName>Reposicion_Carnet</fullName>
    <active>true</active>
    <businessProcess>Retiros</businessProcess>
    <label>Reposición de Carnet</label>
</RecordType>

force-app/main/default/objects/Constancia__c/Constancia__c.object-meta.xml
<CustomObject>
    <label>Constancia</label>
    <nameField>
        <label>Nombre de Constancias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constancias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Constancia__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Monto_aporte__c</fullName>
    <label>Monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Nombre de Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Municipio__c/fields/codigo_departamento__c.field-meta.xml
<CustomField>
    <fullName>codigo_departamento__c</fullName>
    <label>codigo_departamento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Codigo_Municipio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Municipio__c</fullName>
    <label>Código Municipio</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/nombre_municipio__c.field-meta.xml
<CustomField>
    <fullName>nombre_municipio__c</fullName>
    <label>nombre_municipio</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/Usuarios_para_asignacion_Casos_SAC__c.object-meta.xml
<CustomObject>
    <label>Usuarios para asignacion - Casos SAC</label>
    <nameField>
        <displayFormat>ACSAC-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios para asignación - Casos SAC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Usuarios_para_asignacion_Casos_SAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>Tegucigalpa</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>San Pedro Sula</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>No tiene zona el cliente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortalAutogestionE2C_Test.cls
@isTest
public class PortalAutogestionE2C_Test {
    
    static testMethod void TestCasos(){
        Account cliente = new Account();
        cliente.Name='Luis Donaire';
        cliente.Identificacion__c='0709199300157';
        cliente.Departamento_Residencia2__c = '122';
        insert cliente;
        
        Contact con = new Contact();
        con.AccountId = cliente.Id;
        con.FirstName = 'Test';
        con.LastName = 'Test';
        insert con;
        
        Producto__C producto = new Producto__C();
        producto.Codigo__c='qwqw';
        producto.name='Prueba';
        insert producto;
        
        Subproducto__c  subProducto = new Subproducto__c ();
        subProducto.Name='Test';
        subProducto.Codigo__c='3434';
        subProducto.Producto__c = producto.id;
        insert subProducto;
        
        Cuentas__C cuenta = new cuentas__C();
        cuenta.codigo__C='0000';
        cuenta.Cliente__c = cliente.id;
        cuenta.Subproducto__c = subProducto.id;
        cuenta.name='test';
        cuenta.Monto_aporte__c = 100;
        cuenta.Forma_Aportacion__c='TA';
        insert cuenta;
        
        Agencia__C agencia = new agencia__C(name='Test', zona__C='2');
        insert agencia;
        
        Usuarios_para_asignacion_Casos_SAC__c f = new Usuarios_para_asignacion_Casos_SAC__c();
        f.Zona__c='2';
        f.Usuario__c = userinfo.getUserId();
        insert f;
        
        f = new Usuarios_para_asignacion_Casos_SAC__c();
        f.Zona__c='3';
        f.Usuario__c = userinfo.getUserId();
        insert f;
        
        f = new Usuarios_para_asignacion_Casos_SAC__c();
        f.Zona__c='1';
        f.Usuario__c = userinfo.getUserId();
        insert f;
        f = new Usuarios_para_asignacion_Casos_SAC__c();
        
        f.Usuario__c = userinfo.getUserId();
        insert f;
        
        municipio__C municipio = new municipio__C();
        municipio.Codigo_Municipio__c='01';
        municipio.nombre_municipio__C='Test';
        municipio.codigo_departamento__c= ' 120';
        insert municipio;
        
        String RecordTypeId0 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Email to Case').getRecordTypeId();
        
        List<Case> caseListToInsert = new List<Case>();
        case c = new Case();
        c.AccountId = cliente.Id;
        c.ContactId = con.Id;
        c.Status = 'Nuevo';
        c.SuppliedEmail = 'test@gmail.com';
        c.RecordTypeId = RecordTypeId0;
        c.Subject = 'Test';
        c.Identificacion__c = '0709199300157';
        //insert c;
        caseListToInsert.add(c);
        insert caseListToInsert;  
        
        List<Case> caseObj = [select id, casenumber,SuppliedEmail from case where id =: caseListToInsert[0].id];
        System.debug('case number' + caseObj[0].casenumber);   
        
        Test.startTest();
        
        /*ApexPages.currentPage().getParameters().put('clie',cliente.identificacion__C);
ApexPages.currentPage().getParameters().put('caseNumber',caseObj[0].casenumber);
ApexPages.currentPage().getParameters().put('email',caseObj[0].SuppliedEmail); */
        ApexPages.currentPage().getParameters().put('idCaso',caseObj[0].Id);
        ApexPages.currentPage().getParameters().put('recordType', 'Otros');
        ControladorCasosPortalAutogestionE2C controlCasos= new ControladorCasosPortalAutogestionE2C();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(cliente);
        ControladorCasosPortalAutogestionE2C testController = new ControladorCasosPortalAutogestionE2C(sc);    
        
        //controlCasos.UrlHost = null;
        
        controlCasos.idCliente2 = '0709199300157';
        controlCasos.login();
        controlCasos.GenerarToken();
        controlCasos.validarToken();
        controlCasos.inicio();
        controlCasos.aceptarTerminos();
        controlCasos.asuntoOtro();
        controlCasos.guardar();
        controlCasos.ciudadesTrabajo();
        controlCasos.ciudadesResidencia();
        controlCasos.getCurrencySelected();
        controlCasos.updateConstanciaView();
        controlCasos.verEDCDetallado();
        controlCasos.verEDCGeneral();
        controlCasos.accionVacia();
        controlCasos.accionVacia2(); 
        controlCasos.UpdateCaseToOtros();
        
        //controlCasos.estadoCuentaHistorico(claseEnvio, idCaso);
        //controlCasos.estadoCuentaTrimestral(claseEnvio, idCaso);
        
        //Caso Email2Case
        //Id RecordTypeId0 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Email to Case').getRecordTypeId();
        
        System.debug('RecordTypeId0: '+RecordTypeId0);
        controlCasos.noRecibeToken = True; 
        controlCasos.numCel = '88458785';
        controlCasos.idCliente2 = '0801199411013';
        controlCasos.emailCliente = 'emailcliente@gmail.com';
        controlCasos.casoCliente = '500125';
        controlCasos.FechaHoy = System.now();               
        
        //controlCasos.recordType = 'Reposicion_Carnet';
        
        controlCasos.idTipoRegistro = RecordTypeId0;
        controlCasos.Caso.SuppliedEmail = 'testEmail@gmail.com';
        controlCasos.Caso.Correo_Electronico__c = 'test2Email2@gmail.com';
        controlCasos.Caso.Subject = 'Email to Case';
        controlCasos.Caso.Telefono_Movil__c = '87457858';
        controlCasos.Caso.Type = 'Solicitud';
        controlCasos.caso.OwnerId = f.Usuario__c;
        System.debug('controlCasos: '+controlCasos);
        controlCasos.guardar();
        
        //controlCasos.UpdateCaseToOtros();
        
        controlCasos.guardar();
        
        //Caso Act de Info
        //Id RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Actualización de Información').getRecordTypeId();
        String RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Actualizacion_informacion').getRecordTypeId(); 
        controlCasos.idTipoRegistro = RecordTypeId;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.ContactId = cliente.Id;
        
        controlCasos.SelectTipoGestion();
        controlCasos.guardar();
        controlCasos.caso.Fecha_Nacimiento__c = date.today().addDays(3);
        controlCasos.guardar();
        controlCasos.caso.Fecha_Nacimiento__c = null;
        controlCasos.caso.Telefono_Trabajo__c = '21321';
        controlCasos.guardar();
        controlCasos.caso.Telefono_Trabajo__c = null;
        controlCasos.caso.Departamento_Trabajo2__c = '120';
        controlCasos.CiudadesTrabajo();
        controlCasos.caso.Departamento_Residencia2__c = '120';
        controlCasos.CiudadesResidencia();
        controlCasos.caso.Departamento_Residencia2__c = null;
        controlCasos.caso.Departamento_Trabajo2__c = null;
        controlCasos.AccionVacia();
        controlCasos.caso.correo_electronico__c ='ivorcast@gmai.com';
        controlCasos.guardar();
        controlCasos.verificarCodigo();
        controlCasos.reenviarCodigo();
        controlCasos.inputCodigoVeficacion = controlCasos.codigoVeficacion;
        controlCasos.verificarCodigo();
        controlCasos.cerrar();
        
        /*
controlCasos.SelectTipoGestion();
controlCasos.guardar();
controlCasos.caso.correo_electronico__c ='ivorcast@gmai.com';
controlCasos.caso.Departamento_Trabajo2__c = '120';
controlCasos.CiudadesTrabajo();
controlCasos.caso.Departamento_Residencia2__c = '120';
controlCasos.CiudadesResidencia();
controlCasos.caso.Departamento_Residencia2__c = null;
controlCasos.caso.Departamento_Trabajo2__c = null;
controlCasos.AccionVacia();
controlCasos.guardar();*/
        
        //Caso Constancia
        String RecordTypeId6 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Constancia'].Id;        
        controlCasos.idTipoRegistro = RecordTypeId6;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.Constancia__c = 'A4';
        controlCasos.caso.ContactId = cliente.Id;
        controlCasos.SelectTipoGestion();
        controlCasos.guardar();
        controlCasos.caso.correo_electronico__c ='ivorcast@gmai.com';
        controlCasos.caso.Departamento_Trabajo2__c = '120';
        controlCasos.CiudadesTrabajo();
        controlCasos.caso.Departamento_Residencia2__c = '120';
        controlCasos.CiudadesResidencia();
        controlCasos.caso.Departamento_Residencia2__c = null;
        controlCasos.caso.Departamento_Trabajo2__c = null;
        controlCasos.AccionVacia();
        controlCasos.guardar();
        
        //Caso Estado de Cuenta
        //Id RecordTypeId2 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Estados de Cuenta').getRecordTypeId();
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Estados de Cuenta'].Id;
        controlCasos.caso = new case();
        controlCasos.idTipoRegistro = RecordTypeId2;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.ContactId = cliente.Id;
        controlCasos.cTipoCaso = new claseTipoCaso('Estados_Cuenta');
        controlCasos.Caso.Origin = 'Web';
        controlCasos.Caso.Priority = 'Media';
        controlCasos.caso.Tipo_Estado_Cuenta__c = 'A1';
        controlCasos.caso.Estado_Cuenta_Detallado__c = 'General';
        controlCasos.Caso.fecha_desde__C = date.today().addmonths(-12);
        controlCasos.Caso.fecha_hasta__C = date.today();
        controlCasos.guardar();
        controlCasos.VerEDCDetallado();
        controlCasos.VerEDCGeneral();
        
        //Caso Reposición de Carnet
        //Id RecordTypeId3 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Reposición de Carnet').getRecordTypeId();
        String RecordTypeId3 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Reposición de Carnet'].Id;
        controlCasos.caso = new case();
        controlCasos.idTipoRegistro = RecordTypeId3;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.ContactId = cliente.Id;
        controlCasos.cTipoCaso = new claseTipoCaso('Reposicion_Carnet');
        controlCasos.Caso.Priority = 'Media';
        controlCasos.guardar();
        controlCasos.ZonaSeleccionada = controlCasos.listaZonas[1].getValue();
        controlCasos.getListAgentsByZone();
        controlCasos.caso.Agencia__c =controlCasos.listAgencias[1].getvalue();
        controlCasos.guardar();
        //controlCasos.loadAgencies();
        
        //Caso Otros
        //Id RecordTypeId4 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Otros').getRecordTypeId();
        String RecordTypeId4 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Otros'].Id;
        controlCasos.caso = new case();
        controlCasos.idTipoRegistro = RecordTypeId4;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.ContactId = cliente.Id;
        controlCasos.cTipoCaso = new claseTipoCaso('Otros');
        controlCasos.Caso.Priority = 'Media';
        controlCasos.guardar();
        controlCasos.Caso.Description = 'Media';
        controlCasos.UpdateCaseToOtros();
        controlCasos.guardar();
        
        //Caso Aumento Disminución de Aporte
        //Id RecordTypeId5 = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Modificación de aportes').getRecordTypeId();
        String RecordTypeId5 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;
        controlCasos.caso = new case();
        controlCasos.idTipoRegistro = RecordTypeId5;
        controlCasos.caso.Status = 'Nuevo';
        controlCasos.caso.Origin = 'Correo electrónico FPC';
        controlCasos.caso.Type = 'Solicitud';
        controlCasos.caso.ContactId = cliente.Id;
        controlCasos.cTipoCaso = new claseTipoCaso('Aumento_Disminucion_Aportes');
        controlCasos.Caso.Priority = 'Media';
        
        controlCasos.detalleCaso.Tipo_Operacion__c='A1';
        controlCasos.detallecaso.Nuevo_monto_aporte__c=500;
        controlCasos.caso.CurrencyIsoCode ='HNL';
        controlCasos.guardar();
        
        //controlCasos.UpdateTypeCase();
        //controlCasos.loadAgencies();
        //controlCasos.cerrar();
        
        SolicitudCaso solicitud = AFPCCasos.upsertCaso(controlCasos.caso);
        
        //controlCasos.UpdateCaseToOtros();
        controlCasos.cliente.Departamento_Residencia2__c = null;
        controlCasos.zonaPorDepto();
        controlCasos.cliente.Departamento_Residencia2__c = '123';
        controlCasos.zonaPorDepto();
        controlCasos.UpdateTypeCase();
        controlCasos.loadAgencies();
        
        Test.stopTest();
        
    }
    
}