force-app/main/default/objects/Account/fields/Departamento_Residencia2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Residencia2__c</fullName>
    <label>Departamento Residencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Departamento_Residencia2__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Residencia2__c</fullName>
    <label>Departamento Residencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/Usuarios_para_asignacion_Casos_SAC__c.object-meta.xml
<CustomObject>
    <label>Usuarios para asignacion - Casos SAC</label>
    <nameField>
        <displayFormat>ACSAC-{000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios para asignación - Casos SAC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_para_asignacion_Casos_SAC__c/fields/Ultimo_Caso_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Ultimo_Caso_Asignado__c</fullName>
    <description>Último Caso Asignado</description>
    <inlineHelpText>Último Caso Asignado</inlineHelpText>
    <label>Último Caso Asignado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ClasseUtilNueva.cls
public without sharing class ClasseUtilNueva {
    
    public static string zonaPorDepto(string idCuenta){
        String Dto = [Select Departamento_Residencia2__c from Account where id = :idCuenta][0].Departamento_Residencia2__c;
        System.debug('Dto: '+Dto);
        if((Dto == null ||
            Dto == '000') && !test.isRunningTest()) {
                return '3';
            } else if(Dto =='122' ||
                      Dto =='128'||
                      Dto =='129'||
                      Dto =='124'||
                      Dto =='127'||
                      Dto =='120'||
                      Dto =='137'||
                      Dto =='121'||
                      Dto =='130') {
                          return '1';
                      } else if(Dto =='123' ||
                                Dto =='126'||
                                Dto =='131'||
                                Dto =='133'||
                                Dto =='132'||
                                Dto =='134'||
                                Dto =='135'||
                                Dto =='136'||
                                Dto =='125'
                                || test.isRunningTest()) {
                                    return '2';
                                }
        return null;
    }
    
    @future(callout=true)
    public static void CasoDevuelto(string idNuevoPropietario, string numeroCaso, string correo){
        try{
            //case caso = [select account.Departamento_Residencia2__c from case where id=:idCaso];
            Usuarios_para_asignacion_Casos_SAC__c p =new Usuarios_para_asignacion_Casos_SAC__c (Ultimo_Caso_Asignado__c = System.now(), id=idNuevoPropietario);
            update p;
            List<Messaging.SingleEmailMessage> MessageList = new List<Messaging.SingleEmailMessage>();
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'ficohsapensiones@grupoficohsa.hn'];
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] {correo});
            mail.setSubject('Asiganción de nuevo caso No. ' + numeroCaso);
            mail.setPlainTextBody('Buen día, se notifica que se ha asignado nuevo caso (' + numeroCaso + ') que fue rechazado de portal de agencias. \n\nMuchas gracias');
            mail.setOrgWideEmailAddressId(owea.get(0).Id);
            MessageList.add(mail); 
            Messaging.sendEmail(MessageList,false);
        }catch(exception ex){
            system.debug('Error: '+ex.getMessage()+', Linea: '+ex.getLineNumber());
        }
    }

}