force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120</fullName>
                <label>ATLANTIDA</label>
            </value>
            <value>
                <fullName>135</fullName>
                <label>CHOLUTECA</label>
            </value>
            <value>
                <fullName>137</fullName>
                <label>COLON</label>
            </value>
            <value>
                <fullName>126</fullName>
                <label>COMAYAGUA</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>COPAN</label>
            </value>
            <value>
                <fullName>122</fullName>
                <label>CORTES</label>
            </value>
            <value>
                <fullName>136</fullName>
                <label>EL PARAISO</label>
            </value>
            <value>
                <fullName>123</fullName>
                <label>FRANCISCO MORAZAN</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>GRACIAS A DIOS</label>
            </value>
            <value>
                <fullName>133</fullName>
                <label>INTIBUCA</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>ISLAS DE LA BAHIA</label>
            </value>
            <value>
                <fullName>132</fullName>
                <label>LA PAZ</label>
            </value>
            <value>
                <fullName>131</fullName>
                <label>LEMPIRA</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>ND</label>
            </value>
            <value>
                <fullName>128</fullName>
                <label>OCOTEPEQUE</label>
            </value>
            <value>
                <fullName>125</fullName>
                <label>OLANCHO</label>
            </value>
            <value>
                <fullName>127</fullName>
                <label>SANTA BARBARA</label>
            </value>
            <value>
                <fullName>134</fullName>
                <label>VALLE</label>
            </value>
            <value>
                <fullName>124</fullName>
                <label>YORO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fantasma_portal__c/Fantasma_portal__c.object-meta.xml
<CustomObject>
    <label>Fantasma portal</label>
    <nameField>
        <label>Nombre Objeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fantasma Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fantasma_portal__c/fields/Motivo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_contacto__c</fullName>
    <label>Motivo contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fantasma_portal__c/fields/Usuario_referencia__c.field-meta.xml
<CustomField>
    <fullName>Usuario_referencia__c</fullName>
    <label>Usuario referencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <description>Identidad del candidato.</description>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Motivo de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>CLUB DE BENEFICIOS</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Usuario_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Referencia__c</fullName>
    <label>Usuario de Referencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/objects/PreVenta__c/PreVenta__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado para prospectos o candidatos.</description>
    <label>PreVenta</label>
    <nameField>
        <label>Nombre de PreVenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreVentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreVenta__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Nombre de Campaña</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>AGUINALDO 2019</fullName>
            </value>
            <value>
                <fullName>PROTECCIÓN INTEGRAL REDES</fullName>
            </value>
            <value>
                <fullName>Hondureños en el Extranjero</fullName>
            </value>
            <value>
                <fullName>Aguinaldo2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Telefono_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Trabajo__c</fullName>
    <label>Teléfono Trabajo</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Usuario_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Referencia__c</fullName>
    <label>Usuario de Referencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <label>Natural</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Tarea.recordType-meta.xml
<RecordType>
    <fullName>Tarea</fullName>
    <active>true</active>
    <label>Tarea</label>
</RecordType>

force-app/main/default/classes/ControllerPromociones2.cls
public class ControllerPromociones2 {
      public list <Account> preven {get; set;}
     //public list <task> ko {get; set;}
     public list<Lead> prospectos {get;set;}
    public list<PreVenta__c > prev {get;set;}
     //public PreVenta__c preventa {get;Set;}
     public Lead candidato {get;Set;}
     public task Activi {get;Set;}
     public task Actividad {get;Set;}
   
    public boolean pop3 {get;Set;}
    public string identificacion {get; set;}
 //public string nombrePersonaRefiere {get; set;}
    private RecordType natural;
    private map<id, Lead> mapProspectos;
   // private map<id, Leads> mapProspectos;
    
    //public List<SelectOption> options {get;set;}
    private string usuario;
    private string  clientes;

 //public Fantasma_portal__c fantasma{get;Set;}
    
    public ControllerPromociones2(){
        candidato = new Lead();
    //    Actividades = new Lead();
        usuario = Apexpages.currentPage().getParameters().get('usuario');
        natural = [Select id From RecordType Where sObjectType = 'Lead' AND DeveloperName = 'Natural' Limit 1];
        pop3=true;
        candidato.Motivo_Contacto__c = 'PROTECCIÓN INTEGRAL REDES';
         
        //candidato.Identificacion__c = v1;
        //candidato.Motivo_Contacto__c = apexpages.;
        //[select Motivo_Contacto__c from Motivo_Contacto ];
            //opcionColonia = new list <selectOption>();
    }
     
    public pageReference guardarPop(){
        
        try{
            
            /*if(identificacion == null )
            {          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe escribir el numero de ID'));
            return null;    
            }*/
		
            if(identificacion != null)
            {
                candidato.Identificacion__c = identificacion.replace('-', '');
            }
            
           /* if(identificacion == null)
            {
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Identidad campo obligatorio'));
            }*/
            if(candidato.Phone.length() > 8 ){          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Movil excede la cantidad de 8 caracteres permitidos'));
            return null;    
        }
        if(candidato.Telefono_Trabajo__c != null){
            if(candidato.Telefono_Trabajo__c.length() > 8 ){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Trabajo excede la cantidad de 8 caracteres permitidos'));
                return null;
            }
        }
            if(candidato.Departamento__c  == 'N/A')
        {          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe Seleccionar un Departamento'));
            return null;
        }
        else   
        { 
         
          preven = [select id
                              from Account
                              where Identificacion__c =: candidato.Identificacion__c ];
            
         system.debug('Repetido' + preven);
             
            //string var2;
            prev = [select id
                              from PreVenta__c 
                              where Identificacion__c =: candidato.Identificacion__c ];
            
         system.debug('Repetidos_candidatos' + prospectos);
            
           // clientes = (select id from Account where Identificacion__c =: candidato.Identificacion__c);
		if (preven.size() > 0)
        {
            Activi = new task();
            string var1;
            string var2;
            string var3;
            string var4;
            string var5;
        
            var1= [select id
                   from Account
                   where Identificacion__c =: candidato.Identificacion__c ].id;
            
            var2= [select owner.id
                   from Account
                   where Identificacion__c =: candidato.Identificacion__c ].owner.id;
            
            var3= [select name
                   from Account
                   where Identificacion__c =: candidato.Identificacion__c ].name;
            
            var4= [select owner.name
                   from Account
                   where Identificacion__c =: candidato.Identificacion__c ].owner.name;
            
            var5= [select owner.email
                   from Account
                   where Identificacion__c =: candidato.Identificacion__c ].owner.email;
            
             system.debug('var1iii' + var1);
             system.debug('var2iii' + var2);
      
                activi.OwnerId = var2;
                activi.Subject= 'PROMOCIONES';
                activi.Status= 'No Iniciado';
                activi.Priority='Normal';
                activi.WhatId = var1;
            
                               
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente' )); 
                         
            system.debug('INFORMACION' + activi);
            insert activi;
            
            
            reiniciar(); 
            //Envio de correo - Agregado 05-04-2019
						OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'ficohsapensiones@ficohsa.com'];
						Messaging.SingleEmailMessage[] listCorreo = new List<Messaging.SingleEmailMessage>();
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setHtmlBody( 'Buenas ' + var4 + ', Se le a asignado una tarea para el cliente ' + 
                                          var3 + ' desde el portal de PROMOCIONES.');
                        mail.setSubject('Se le a asignado una tarea desde el portal de PROMOCIONES');
                        mail.setToAddresses(new String[] {var5});
						mail.setOrgWideEmailAddressId(owea.get(0).Id);
                        mail.setSaveAsActivity(true);
                        listCorreo.add(mail);
                        Messaging.SendEmailResult[] results = Messaging.sendEmail(listCorreo, false);
                        
        }
        else if  (prev.size() > 0)
        {
             Actividad = new task();
            string var2;
              var2= [select id
                              from PreVenta__c 
                              where Identificacion__c =: candidato.Identificacion__c ].id;
            
             system.debug('var2iii' + var2);
            
                Actividad.OwnerId = '005j000000BiDwQ';
                Actividad.Subject= 'PROMOCIONES';
                Actividad.Status= 'No Iniciado';
                Actividad.Priority='Normal';
            Actividad.WhatId = var2;
                  
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente' )); 
             
            system.debug('INFORMACION' + Actividad);
            insert Actividad;
                        
            reiniciar();      
                       
             }
         else {
            
                
            //candidato.Motivo_Contacto__c = 'Referido';
            //nombrePersonaRefiere +=' '+candidato.Description; 
            //candidato.Description = nombrePersonaRefiere;
           
            candidato.RecordTypeId = natural.id;
            candidato.status = 'En Proceso';
            candidato.Usuario_Referencia__c = usuario;
            candidato.LeadSource='Web';
            insert candidato;
            candidato = new Lead();
            pop3 = False;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente')); 
            
            
              
            /*
             string v1 = identificacion.replace('-', '');
             candidato.Identificacion__c = v1;
             */
            
            system.debug(candidato);  
             //identificacion
             //string v1 = candidato.Identificacion__c.replace('-', ''); 
             //candidato.Identificacion__c = v1;
             //candidato.Identificacion__c.replace('-', ''); 
             //system.debug('IdenForm' +  candidato.Identificacion__c); 
         
            reiniciar();      
         }
        
        }
        return null;//new pagereference('/apex/vfReferidos');
           //nombrePersonaRefiere = null; 
            //candidato.Description = null;
        }catch (exception e){
            system.debug(e.getLineNumber()+e.getMessage());
        }
        return null;
        
    }
    
    public void reiniciar()
    {      
        candidato.FirstName = NULL;
        candidato.LastName = NULL;
        identificacion = NULL;
        candidato.Email = NULL;
        candidato.Telefono_Trabajo__c = NULL;
        candidato.Phone = NULL;
        candidato.Motivo_Contacto__c = 'PROTECCIÓN INTEGRAL REDES';
        candidato.Departamento__c  = 'N/A';    
        
    }
    
    

}