force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120</fullName>
                <label>ATLANTIDA</label>
            </value>
            <value>
                <fullName>135</fullName>
                <label>CHOLUTECA</label>
            </value>
            <value>
                <fullName>137</fullName>
                <label>COLON</label>
            </value>
            <value>
                <fullName>126</fullName>
                <label>COMAYAGUA</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>COPAN</label>
            </value>
            <value>
                <fullName>122</fullName>
                <label>CORTES</label>
            </value>
            <value>
                <fullName>136</fullName>
                <label>EL PARAISO</label>
            </value>
            <value>
                <fullName>123</fullName>
                <label>FRANCISCO MORAZAN</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>GRACIAS A DIOS</label>
            </value>
            <value>
                <fullName>133</fullName>
                <label>INTIBUCA</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>ISLAS DE LA BAHIA</label>
            </value>
            <value>
                <fullName>132</fullName>
                <label>LA PAZ</label>
            </value>
            <value>
                <fullName>131</fullName>
                <label>LEMPIRA</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>ND</label>
            </value>
            <value>
                <fullName>128</fullName>
                <label>OCOTEPEQUE</label>
            </value>
            <value>
                <fullName>125</fullName>
                <label>OLANCHO</label>
            </value>
            <value>
                <fullName>127</fullName>
                <label>SANTA BARBARA</label>
            </value>
            <value>
                <fullName>134</fullName>
                <label>VALLE</label>
            </value>
            <value>
                <fullName>124</fullName>
                <label>YORO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Departamento__c/Departamento__c.object-meta.xml
<CustomObject>
    <label>Departamento 2</label>
    <nameField>
        <label>Nombre Departamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departamento__c/fields/Codigo_Departamento__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Departamento__c</fullName>
    <externalId>true</externalId>
    <label>Código Departamento</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Departamentos__c/Departamentos__c.object-meta.xml
<CustomObject>
    <label>Departamento</label>
    <nameField>
        <label>Nombre de Departamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departamentos__c/fields/codigo_departamento__c.field-meta.xml
<CustomField>
    <fullName>codigo_departamento__c</fullName>
    <label>codigo_departamento</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Departamentos__c/fields/codigo_pais__c.field-meta.xml
<CustomField>
    <fullName>codigo_pais__c</fullName>
    <label>codigo_pais</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Departamentos__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fantasma_portal__c/Fantasma_portal__c.object-meta.xml
<CustomObject>
    <label>Fantasma portal</label>
    <nameField>
        <label>Nombre Objeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fantasma Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fantasma_portal__c/fields/Motivo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_contacto__c</fullName>
    <label>Motivo contacto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <description>Identidad del candidato.</description>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Motivo de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>CLUB DE BENEFICIOS</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Pais_r__c.field-meta.xml
<CustomField>
    <fullName>Pais_r__c</fullName>
    <label>Pais_r</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Honduras</fullName>
            </value>
            <value>
                <fullName>Estados Unidos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <businessProcess>Proceso AFP</businessProcess>
    <description>Tipo de registro para prospectos tipo Naturales</description>
    <label>Natural</label>
</RecordType>

force-app/main/default/objects/Pais_R__c/Pais_R__c.object-meta.xml
<CustomObject>
    <label>Pais_R</label>
    <nameField>
        <label>Nombre de Pais</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises_R</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais_R__c/fields/codigo__c.field-meta.xml
<CustomField>
    <fullName>codigo__c</fullName>
    <label>codigo</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais_R__c/fields/nombre__c.field-meta.xml
<CustomField>
    <fullName>nombre__c</fullName>
    <label>nombre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/PreVenta__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado para prospectos o candidatos.</description>
    <label>PreVenta</label>
    <nameField>
        <label>Nombre de PreVenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreVentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreVenta__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Francisco Morazan</fullName>
            </value>
            <value>
                <fullName>Cortes</fullName>
            </value>
            <value>
                <fullName>Comayagua</fullName>
            </value>
            <value>
                <fullName>Lempira</fullName>
            </value>
            <value>
                <fullName>Intibuca</fullName>
            </value>
            <value>
                <fullName>La Paz</fullName>
            </value>
            <value>
                <fullName>Valle</fullName>
            </value>
            <value>
                <fullName>Choluteca</fullName>
            </value>
            <value>
                <fullName>El Paraiso</fullName>
            </value>
            <value>
                <fullName>Olancho</fullName>
            </value>
            <value>
                <fullName>Ocotepeque</fullName>
            </value>
            <value>
                <fullName>Copan</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Yoro</fullName>
            </value>
            <value>
                <fullName>Atlantida</fullName>
            </value>
            <value>
                <fullName>Colon</fullName>
            </value>
            <value>
                <fullName>Gracias a Dios</fullName>
            </value>
            <value>
                <fullName>Islas de la Bahia</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificación</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreVenta__c/fields/Motivo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Contacto__c</fullName>
    <label>Nombre de Campaña</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asesoría Producto Empresarial</fullName>
            </value>
            <value>
                <fullName>Asesoría Producto Individual</fullName>
            </value>
            <value>
                <fullName>Campaña HTML</fullName>
            </value>
            <value>
                <fullName>Inicio de Año 2019</fullName>
            </value>
            <value>
                <fullName>Queja</fullName>
            </value>
            <value>
                <fullName>Referido</fullName>
            </value>
            <value>
                <fullName>Solicitud Gestión</fullName>
            </value>
            <value>
                <fullName>Sugerencia</fullName>
            </value>
            <value>
                <fullName>BONO MARZO GFF</fullName>
            </value>
            <value>
                <fullName>CAMPAÑA INSTITUCIONAL 2019</fullName>
            </value>
            <value>
                <fullName>Referido Call Center</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electronicos</fullName>
            </value>
            <value>
                <fullName>Referido Call USA</fullName>
            </value>
            <value>
                <fullName>Referido Medios Electrónicos USA</fullName>
            </value>
            <value>
                <fullName>AGUINALDO 2019</fullName>
            </value>
            <value>
                <fullName>PROTECCIÓN INTEGRAL REDES</fullName>
            </value>
            <value>
                <fullName>Hondureños en el Extranjero</fullName>
            </value>
            <value>
                <fullName>Aguinaldo2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PreVenta__c/recordTypes/Natural.recordType-meta.xml
<RecordType>
    <fullName>Natural</fullName>
    <active>true</active>
    <label>Natural</label>
</RecordType>

force-app/main/default/classes/ControllerPromociones3.cls
public class ControllerPromociones3 {
    public list <Account> preven {get; set;} 
    //public list <task> ko {get; set;}
    public list<Lead> prospectos {get;set;}
    public list<PreVenta__c > prev {get;set;}
    //public PreVenta__c preventa {get;Set;}
    public Lead candidato {get;Set;}
    public task Activi {get;Set;}
    public task Actividad {get;Set;}
    
    public boolean pop3 {get;Set;}
    public string identificacion {get; set;}
    public string parapais {get; set;}
    public string paisRes {get; set;}
    //public string nombrePersonaRefiere {get; set;}
    private RecordType natural;
    private map<id, Lead> mapProspectos;
    // private map<id, Leads> mapProspectos;
    
    //public List<SelectOption> options {get;set;}
    private string usuario;
    private string  clientes;
    
    public string pcDeptoCN {get;set;}
    public list<SelectOption> opcionDepartamento {get;set;}
    
    public string pais {get; set;}
    public string depto {get; set;}
    
    public list<selectoption> getPaises() {
        list<selectoption> options= new list<selectoption>();
        list<Pais_R__c> pais= [select Id,Name,codigo__c,nombre__c from Pais_R__c];
        options.add(new selectoption('0', ' --Ninguno-- '));
        for(Pais_R__c c:pais){ options.add(new selectoption(c.codigo__c,c.nombre__c));
                             }
        return options;
    }
    
    public list<selectoption> getDepart(){ 
        list<selectoption> options= new list<selectoption>();
        list<Departamentos__c> depto= [select Departamento__c, codigo_departamento__c from Departamentos__c where codigo_pais__c =: pais];
        options.add(new selectoption('0', ' --Ninguno-- '));   
        for( Departamentos__c c:depto){ options.add(new selectoption(c.Departamento__c,c.Departamento__c));
                                      }
        return options;   
    }
    
    //public Fantasma_portal__c fantasma{get;Set;}
    
    //Función llamar estado
    
    public void llamarEstado(){
        try
        {
            opcionDepartamento = new list <selectOption>();
            opcionDepartamento.add(new selectOption(' --Ninguno-- ', ' --Ninguno-- '));
            for (Departamentos__c item:[select Departamento__c, codigo_departamento__c from Departamentos__c where codigo_pais__c =: '053'])
            { opcionDepartamento.add(new selectOption( item.Departamento__c ,item.Departamento__c)); }
            
        }catch(exception e){
            
        }
    }
    
    public ControllerPromociones3(){
        candidato = new Lead();
        //    Actividades = new Lead();
        usuario = Apexpages.currentPage().getParameters().get('usuario');
        natural = [Select id From RecordType Where sObjectType = 'Lead' AND DeveloperName = 'Natural' Limit 1];
        pop3=true;
        candidato.Motivo_Contacto__c = 'Hondureños en el Extranjero';
        
        //candidato.Identificacion__c = v1;
        //candidato.Motivo_Contacto__c = apexpages.;
        //[select Motivo_Contacto__c from Motivo_Contacto ];
        //opcionColonia = new list <selectOption>();
        llamarEstado();
    }
    
    public pageReference guardarPop(){
        
        try{
            
            if(identificacion != null) //|| test.isRunningTest()) 
            { 
                candidato.Identificacion__c = identificacion.replace('-', ''); 
            }
            if(pais == '0') 
            { 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe seleccionar un País ')); return null;    
            }
            
            if(depto == '0') 
            { 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe seleccionar un Estado/Departamento ')); return null;  
            }
            
            list<Pais_R__c> FpaisC= [select Id,Name,codigo__c,nombre__c from Pais_R__c where codigo__c =: '052'];
            string vPaisC = FpaisC[0].codigo__c;
            
            if(candidato.Phone.length() > 8 && pais == vPaisC) 
            { 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Móvil excede la cantidad de 8 caracteres permitidos ')); return null;    
            }
            if(candidato.Telefono_Trabajo__c != null){
                if(candidato.Telefono_Trabajo__c.length() > 8 ){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Teléfono Trabajo excede la cantidad de 8 caracteres permitidos '));
                    return null;
                }
            }
            if(candidato.Departamento__c  == '--Ninguno--')
            {          
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Debe Seleccionar un Departamento '));
                return null;
            }
            else   
            { 
                
                preven = [select id
                          from Account
                          where Identificacion__c =: candidato.Identificacion__c ];
                
                system.debug('Repetido' + preven);
                
                //string var2;
                prev = [select id
                        from PreVenta__c 
                        where Identificacion__c =: candidato.Identificacion__c ];
                
                system.debug('Repetidos_candidatos' + prospectos);
                
                // clientes = (select id from Account where Identificacion__c =: candidato.Identificacion__c);
                if (preven.size() > 0)
                {
                    Activi = new task();
                    string var1;
                    string var2;
                    string var3;
                    string var4;
                    string var5;
                    
                    var1= [select id
                           from Account
                           where Identificacion__c =: candidato.Identificacion__c ].id;
                    
                    var2= [select owner.id
                           from Account
                           where Identificacion__c =: candidato.Identificacion__c ].owner.id;
                    
                    var3= [select name
                           from Account
                           where Identificacion__c =: candidato.Identificacion__c ].name;
                    
                    var4= [select owner.name
                           from Account
                           where Identificacion__c =: candidato.Identificacion__c ].owner.name;
                    
                    var5= [select owner.email
                           from Account
                           where Identificacion__c =: candidato.Identificacion__c ].owner.email;
                    
                    
                    system.debug('var1iii' + var1);
                    system.debug('var2iii' + var2);
                    
                    activi.OwnerId = var2;
                    activi.Subject= 'Hondureños en el Extranjero';
                    activi.Status= 'No Iniciado';
                    activi.Priority='Normal';
                    activi.WhatId = var1;
                    
                    
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente' )); 
                    
                    system.debug('INFORMACION' + activi);
                    insert activi;
                    
                    
                    reiniciar(); 
                    //Envio de correo - Agregado 05-04-2019
                    OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'ficohsapensiones@ficohsa.com'];
                    Messaging.SingleEmailMessage[] listCorreo = new List<Messaging.SingleEmailMessage>();
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setHtmlBody( 'Buenas ' + var4 + ', Se le a asignado una tarea para el cliente ' + 
                                     var3 + ' desde el portal de Hondureños en el Extranjero.');
                    mail.setSubject('Se le a asignado una tarea desde el portal de Hondureños en el Extranjero');
                    mail.setToAddresses(new String[] {var5});
                    mail.setOrgWideEmailAddressId(owea.get(0).Id);
                    mail.setSaveAsActivity(true);
                    listCorreo.add(mail);
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(listCorreo, false);
                    
                }
                else if  (prev.size() > 0)
                {
                    Actividad = new task();  
                    string var2;
                    var2= [select id
                           from PreVenta__c 
                           where Identificacion__c =: candidato.Identificacion__c ].id;
                    
                    system.debug('var2iii' + var2);
                    
                    Actividad.OwnerId = '005j000000BiDwQ';
                    Actividad.Subject= 'Hondureños en el Extranjero';
                    Actividad.Status= 'No Iniciado';
                    Actividad.Priority='Normal';
                    Actividad.WhatId = var2;
                    
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente' )); 
                    
                    system.debug('INFORMACION' + Actividad);
                    insert Actividad;
                    
                    reiniciar();      
                    
                }
                else {
                    
                    
                    //candidato.Motivo_Contacto__c = 'Referido';
                    //nombrePersonaRefiere +=' '+candidato.Description; 
                    //candidato.Description = nombrePersonaRefiere;
                    
                    /*list<Pais_R__c> Fpais= [select Id,Name,codigo__c,nombre__c from Pais_R__c where codigo__c =: pais];
					string vPais = Fpais[0].Id;*/
                    Pais_R__c itemP = [SELECT id, name, nombre__c, codigo__c from Pais_R__c where codigo__c =: pais];
                    parapais = itemP.id;
                    paisRes = itemP.name;
                    
                    /*list<Departamentos__c> Fdepto= [select Departamento__c, codigo_departamento__c from Departamentos__c where codigo_pais__c =: pais];
					string vDepto = Fdepto[0].Id;*/
                    Departamentos__c itemD = [select id,Departamento__c, codigo_departamento__c from Departamentos__c where codigo_pais__c =: pais AND Departamento__c =: depto];
                    string vDepto = itemD.Id;
                    string paradepto = itemD.Departamento__c;
                    
                    candidato.RecordTypeId = natural.id;
                    candidato.status = 'En Proceso';
                    candidato.Usuario_Referencia__c = usuario;
                    candidato.LeadSource='Web';
                    candidato.F_Hon_USA_Link_Ref__c = true;
                    //agregado 
                    candidato.F_Pais__c = parapais; 
                    candidato.Departamento__c = paradepto; 
                    candidato.Pais_Residencia__c = paisRes;
                    //fin
                    candidato.F_Estado__c = vDepto;
                    insert candidato;  
                                       
                    candidato = new Lead();
                    pop3 = False;
                    
                    System.debug('CANDIDATO: '+ candidato);
                    system.debug('PAISDEPTO ' +  parapais + 'DEPTO: ' + depto );
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos guardados correctamente')); 
                    
                    /*
string v1 = identificacion.replace('-', '');
candidato.Identificacion__c = v1;
*/
                      
                    //identificacion
                    //string v1 = candidato.Identificacion__c.replace('-', ''); 
                    //candidato.Identificacion__c = v1;
                    //candidato.Identificacion__c.replace('-', ''); 
                    //system.debug('IdenForm' +  candidato.Identificacion__c); 
                    
                    reiniciar();      
                }
                
            }
            return null;//new pagereference('/apex/vfReferidos');
            //nombrePersonaRefiere = null; 
            //candidato.Description = null;
        }catch (exception e){
            system.debug(e.getLineNumber()+e.getMessage());
        }
        return null;
        
    }
    
    public void reiniciar()
    {      
        candidato.FirstName = NULL;
        candidato.LastName = NULL;
        identificacion = NULL;
        candidato.Email = NULL;
        candidato.Telefono_Trabajo__c = NULL;
        candidato.Phone = NULL;
        candidato.Motivo_Contacto__c = 'Hondureños en el Extranjero';
        candidato.Departamento__c  = 'N/A';  
        
    }        
}