force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Proceso Finalizado</fullName>
            </value>
            <value>
                <fullName>En proceso de afiliación</fullName>
            </value>
            <value>
                <fullName>Acivo</fullName>
                <isActive>false</isActive>
                <label>Acivo</label>
            </value>
            <value>
                <fullName>Inacivo</fullName>
                <isActive>false</isActive>
                <label>Inacivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>MASCULINO</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>FEMENINO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Listo Para Informe</fullName>
            </value>
            <value>
                <fullName>Informe Ejecutado</fullName>
            </value>
            <value>
                <fullName>No Aplica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchDepuracionContactoTest.cls
@isTest
public class BatchDepuracionContactoTest {
    
    static testmethod void BatchDepuracionContacto() {
        
        Account cliente = new Account();
        cliente.lastname='Doanire';
        cliente.firstname='Luis';
        cliente.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Natural').getRecordTypeId();
        cliente.Identificacion__c='00000000000000';
        cliente.Tipo_Identificacion__c='Cedula de identidad';
        cliente.Sexo__c='Masculino';
        cliente.CurrencyIsoCode = 'HNL';
        cliente.Estado_Civil__pc='Soltero';
        cliente.PersonEmail = 'test@test.com';
        insert cliente;
        
        
        
        ControllerReportEmailStatuses email = new ControllerReportEmailStatuses();
        email.dateStart = date.today().addYears(-10);
        email.dateEnd = date.today();
        email.GenerarReporte();
        
        
       /* BatchDepuracionContacto a = new BatchDepuracionContacto(0, system.now().addYears(-10), system.now());
        Database.executeBatch(a);
        
        Contact contacto = new Contact();
        contacto.Id = [Select id from Contact limit 1].Id;
        contacto.Estado__c = 'Listo Para Informe';
        update contacto;
        
        BatchDatosInformeEDC b = new BatchDatosInformeEDC( system.now().addYears(-10), system.now());
        Database.executeBatch(b);*/
        
        
        
    }
    
    
    

}