force-app/main/default/objects/Account/fields/FrecuenciaEnvioEDC__c.field-meta.xml
<CustomField>
    <fullName>FrecuenciaEnvioEDC__c</fullName>
    <label>Frecuencia de Envío EDC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FrecuenciaEnvioEDC</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/Correo_estado_cuenta__c.object-meta.xml
<CustomObject>
    <label>Correo estado de cuenta</label>
    <nameField>
        <label>Nombre de Correo estado de cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correo estado de cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correo estado de cuenta</relationshipLabel>
    <relationshipName>Correo_estado_de_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FechaDC_Sysde__c/FechaDC_Sysde__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fecha de cierre Sysde</label>
</CustomObject>

force-app/main/default/objects/FechaDC_Sysde__c/fields/Fecha_cierre__c.field-meta.xml
<CustomField>
    <fullName>Fecha_cierre__c</fullName>
    <label>Fecha de cierre</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FechaDC_Sysde__c/fields/Trimestre_Terminado__c.field-meta.xml
<CustomField>
    <fullName>Trimestre_Terminado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trimestre Terminado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/testbatchCambioEstadoEDC.cls
@istest
public class testbatchCambioEstadoEDC {
	
    static testmethod void batchCambioEstadoEDC() {
        
        Account cuenta = new Account();
        cuenta.LastName = 'Test';
        cuenta.Identificacion__c = '0303030303033';
        cuenta.PersonEmail = 'email@test.com';
        cuenta.FrecuenciaEnvioEDC__c = 'Mensual';
        insert cuenta;
        
        Correo_estado_cuenta__c v = new Correo_estado_cuenta__c (enviado__C=true, Cliente__c = cuenta.Id);
        insert v;
        
        FechaDC_Sysde__c b = new FechaDC_Sysde__c (Fecha_cierre__c=date.today(),Trimestre_Terminado__C = true,name = 'CierreAlDia');
        insert b;
        
        SchedulableContext ctx;
        JobEjecutarEDCMasivo n = new JobEjecutarEDCMasivo();
        n.execute(ctx);
        
        account natural2 = new account();
        
        ExtensionEmpresasEDC c = new ExtensionEmpresasEDC(new ApexPages.StandardController(natural2));
        c.ImprimirEDC();
    }
}