force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Ingresado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Ingresado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para validar envío de Email cuando se ingresa la gestión y se asigna a un Asesor.</description>
    <inlineHelpText>Bandera para validar envío de Email cuando se ingresa la gestión y se asigna a un Asesor.</inlineHelpText>
    <label>Caso Ingresado Email2Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_de_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/DAU_Salesforce_Tarjetas__e.object-meta.xml
<CustomObject>
    <label>DAU_Salesforce_Tarjetas</label>
    <pluralLabel>DAU_Salesforce_Tarjetas</pluralLabel>
</CustomObject>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_Borrar_Cuotas_S10__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas_S10__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para borrar las cuotas del saldo 10 en la gestión de Afiliación de débito automático.</description>
    <label>DAU_Borrar Cuotas S10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_Borrar_Cuotas_S18__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas_S18__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para borrar las cuotas del saldo 18 en la gestión de Afiliación de débito automático.</description>
    <label>DAU_Borrar Cuotas S18</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_EjecutarSYSDE__c.field-meta.xml
<CustomField>
    <fullName>DAU_EjecutarSYSDE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DAU_EjecutarSYSDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_EjecutarSYSDEOper__c.field-meta.xml
<CustomField>
    <fullName>DAU_EjecutarSYSDEOper__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera cuando el caso es aprobado desde Operaciones.</description>
    <label>DAU_EjecutarSYSDEOperaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_IdCaso__c.field-meta.xml
<CustomField>
    <fullName>DAU_IdCaso__c</fullName>
    <label>DAU_IdCaso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nueva_fecha_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nueva_fecha_aporte__c</fullName>
    <label>Nueva fecha de aporte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Nuevo_canal_aporte__c.field-meta.xml
<CustomField>
    <fullName>Nuevo_canal_aporte__c</fullName>
    <label>Nuevo canal de aporte</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_Operacion__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CK</fullName>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>AH</fullName>
                <label>Debito a Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Debito a Tarjeta de Crédito Ficohsa</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Debito a Tarjeta de Crédito Otros Bancos</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Móvil</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
                <default>true</default>
                <label>Aumento de Aporte</label>
            </value>
            <value>
                <fullName>A2</fullName>
                <label>Disminución de Aporte</label>
            </value>
            <value>
                <fullName>A3</fullName>
                <label>Cambio de Canal de Aporte</label>
            </value>
            <value>
                <fullName>A4</fullName>
                <label>Cambio de Fecha de Aporte</label>
            </value>
            <value>
                <fullName>A5</fullName>
                <label>Cambio de # de CA/CC</label>
            </value>
            <value>
                <fullName>A6</fullName>
                <label>Cambio de # Tarjeta</label>
            </value>
            <value>
                <fullName>A7</fullName>
                <label>Cancelación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DAU_TG_LogHelperTest.cls
@isTest
public class DAU_TG_LogHelperTest {
    
	@IsTest static void execute() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.SuppliedEmail = 'test@gmail.com';
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Correo electrónico FPC';
        c.Type = 'Solicitud';                
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TA';
        Insert detC;
        
        Test.startTest();
        DAU_Salesforce_Tarjetas__e event = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr = EventBus.publish(event);
        Test.stopTest();
    }
    
    @IsTest static void execute2() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.SuppliedEmail = 'test@gmail.com';
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Correo electrónico FPC';
        c.Type = 'Solicitud';                
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TA';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDEOper__c=true,DAU_Borrar_Cuotas_S10__c=false);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute3() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.SuppliedEmail = 'test@gmail.com';
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Correo electrónico FPC';
        c.Type = 'Solicitud';                
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TA';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S10__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute4() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.SuppliedEmail = 'test@gmail.com';
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Correo electrónico FPC';
        c.Type = 'Solicitud';                
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TA';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S18__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute5() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A4';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A4';
        detC.Nuevo_canal_aporte__c = '';
        detC.Nueva_fecha_aporte__c = System.today();
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_NumeroCuenta__c='353535353536');
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute6() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A4';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A4';
        detC.Nuevo_canal_aporte__c = '';
        detC.Nueva_fecha_aporte__c = System.today();
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute7() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Description = 'Test';
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '353535353535';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_SegundoServicio__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute8() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '353535353535';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_CuartoServicio__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute9() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '353535353535';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute10() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '353535353535';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S10__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute11() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '353535353535';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S18__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute12() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        detC.Banco__c = '28';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute13() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A3';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TAOB';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute14() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A3';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TAOB';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDEOper__c=true,DAU_Borrar_Cuotas_S10__c=false);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute15() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A3';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TAOB';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S10__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute16() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A3';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A3';
        detC.Nuevo_canal_aporte__c = 'TAOB';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S18__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute17() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A1';
        c.Respuesta_SF_Tarjetas__c = '';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A1';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        detC.Nuevo_monto_aporte__c = 5000;
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    /*@IsTest static void execute18() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
        
        c.Status = 'Cerrado';
        c.Archivo_Adjunto__c = true;
        update c;
                
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_PrimerServicio__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }*/
    
    @IsTest static void execute19() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute20() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S10__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute21() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A6';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'TA';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A6';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '4565678998';
        detC.Banco__c = 'Otros Bancos';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S18__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute22() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'AH';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_PrimerServicio__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute23() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'AH';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_SegundoServicio__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute24() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'AH';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_EjecutarSYSDE__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute25() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'AH';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S10__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
    
    @IsTest static void execute26() {
        
        Account acc = new Account(); 
        acc.Identificacion__c = '0801399412010';    
        acc.Name = 'Test Account';
        insert acc;
          
        Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
        insert con;
        
        Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
        insert ass;
        
        Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
        insert ent;
        
        Profile prof = [select id from profile where Name='Administrador del Sistema'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.profileId = prof.id;
        user.username = 'standarduser2020@testorg.com';
        user.email = 'standarduser2020@testorg.com';
        user.Alias = 'standar';
        user.LocaleSidKey='en_US';
        user.TimeZoneSidKey='America/Los_Angeles';
        user.EmailEncodingKey='UTF-8';
        user.LanguageLocaleKey='en_US';        
        insert user;
        
        String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Modificación de aportes'].Id;        
        Case c = new Case();
        c.AccountId = acc.Id;
        c.ContactId = con.Id;    
        c.EntitlementId = ent.Id;
        c.Priority = 'Alta';
        c.OwnerId = user.Id;
        c.Reason = 'Otro';
        c.RecordTypeId = RecordTypeId2; 
        c.Caso_Ingresado__c = false;        
        c.Status = 'Nuevo';
        c.Origin = 'Agencias_Banco';
        c.Type = 'Solicitud';  
        c.Tipo_de_Operacion__c = 'A7';
        Insert c;
        
        Producto__c prod = new Producto__c();
        prod.Name = 'PENSIONES LEMPIRAS';
        prod.Codigo__c = '01';
        Insert prod;
        
        Subproducto__c subProd = new Subproducto__c();
        subProd.Producto__c = prod.Id;
        subProd.Codigo__c = 'FI010';
        Insert subProd;
        
        Cuentas__c cuenta = new Cuentas__c();
        cuenta.Name = '87675';
        cuenta.Codigo__c = '87675';
        cuenta.Cliente__c = acc.Id;
        cuenta.CurrencyIsoCode = 'HNL';
        cuenta.Producto__c = prod.Id;
        cuenta.Subproducto__c = subProd.Id;
        cuenta.Forma_Aportacion__c = 'AH';
        Insert Cuenta;
        
        Detalle_caso__c detC = new Detalle_caso__c();
        detC.Caso__c = c.Id;
        detC.Cuenta__c = cuenta.Id;
        detC.Tipo_Operacion__c = 'A7';
        detC.Nuevo_canal_aporte__c = '';
        detc.N_Cuenta_Bancaria__c = '';
        Insert detC;
                      
        Test.startTest();        
        DAU_Salesforce_Tarjetas__e event2 = new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c=c.Id,DAU_Borrar_Cuotas_S18__c=true);
        Database.SaveResult sr2 = EventBus.publish(event2);
        Test.stopTest();
    }
}