force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hasta__c</fullName>
    <label>Fecha hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/Correo_estado_cuenta__c.object-meta.xml
<CustomObject>
    <label>Correo estado de cuenta</label>
    <nameField>
        <label>Nombre de Correo estado de cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correo estado de cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado_Mensual__c.field-meta.xml
<CustomField>
    <fullName>Enviado_Mensual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado Mensual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EstadosDeCuentaTest.cls
@isTest
public class EstadosDeCuentaTest {
    
    static testMethod void TestCasos(){
        
        Test.setMock(HttpCalloutMock.class, new testMocks());
        
        Account cliente = new Account();
        cliente.FirstName = 'Luis';
        cliente.LastName='Donaire';
        cliente.Identificacion__c='12345';
        cliente.PersonEmail = 'test@test.com';
        cliente.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Natural').getRecordTypeId();
        
        insert cliente;
        
        Case caso = new case();
        caso.AccountId = cliente.Id;
        caso.Fecha_Desde__c = date.today();
        caso.Fecha_hasta__c = date.today();
        insert caso;
        
        test.startTest();
        
        list<String> idCaso = new list<String>();
        idCaso.add(caso.Id);
        
        EstadosDeCuenta.enviarCorreos(idCaso, 'A1');
        EstadosDeCuenta.enviarCorreos(idCaso, 'A2');
        EstadosDeCuenta.InsertarCorreos();
        EstadosDeCuenta.InsertarCorreos();
        
        Correo_estado_cuenta__c a = [select Id,enviado__C,enviado_mensual__C from Correo_estado_cuenta__c ];
        a.Enviado__c = false;
        a.Enviado_Mensual__c = false;
        update a;
        
        EstadosDeCuenta.enviarCorreos(null, 'A1');
        EstadosDeCuenta.enviarCorreos(null, 'A2');
        
		EstadosDeCuenta.estadoCuentaMensual(new list<classClientesEC>());
        EstadosDeCuenta.estadoCuentaTrimestral(new list<classClientesEC>());
        EstadosDeCuenta.estadoCuentaHistorico(new list<classClientesEC>());
    }
    

}