force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_Identidad__c.field-meta.xml
<CustomField>
    <fullName>DAU_Identidad__c</fullName>
    <description>Identidad que devuelve el servicio de consulta.</description>
    <inlineHelpText>Identidad que devuelve el servicio de consulta.</inlineHelpText>
    <label>DAU_Identidad</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_No_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>DAU_No_Cuenta__c</fullName>
    <description>Número de cuenta que devuelve el servicio de validación de Identidad.</description>
    <inlineHelpText>Número de cuenta que devuelve el servicio de validación de Identidad.</inlineHelpText>
    <label>DAU_No.Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_Tarjeta_de_Sysde__c.field-meta.xml
<CustomField>
    <fullName>DAU_Tarjeta_de_Sysde__c</fullName>
    <description>Número de tarjeta de devuelve el servicio que consulta a Sysde.</description>
    <inlineHelpText>Número de tarjeta de devuelve el servicio que consulta a Sysde.</inlineHelpText>
    <label>DAU_Tarjeta de Sysde</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Respuesta_desde_Sysde__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_desde_Sysde__c</fullName>
    <label>Respuesta desde Sysde</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <label>Respuesta desde Salesforce Tarjetas</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_de_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/DAU_Salesforce_Tarjetas__e.object-meta.xml
<CustomObject>
    <label>DAU_Salesforce_Tarjetas</label>
    <pluralLabel>DAU_Salesforce_Tarjetas</pluralLabel>
</CustomObject>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_Borrar_Cuotas_S10__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas_S10__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para borrar las cuotas del saldo 10 en la gestión de Afiliación de débito automático.</description>
    <label>DAU_Borrar Cuotas S10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_EjecutarSYSDE__c.field-meta.xml
<CustomField>
    <fullName>DAU_EjecutarSYSDE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DAU_EjecutarSYSDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_IdCaso__c.field-meta.xml
<CustomField>
    <fullName>DAU_IdCaso__c</fullName>
    <label>DAU_IdCaso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_TercerServicio__c.field-meta.xml
<CustomField>
    <fullName>DAU_TercerServicio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DAU_TercerServicio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Borrar_Cuotas__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas__c</fullName>
    <label>Borrar Cuotas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>No borrar cuotas</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Borrar cuotas excepto saldo 18</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Borrar cuotas incluyendo saldo 18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <description>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</description>
    <inlineHelpText>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</inlineHelpText>
    <label>Respuesta Otro Sistema</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/Parametros_DAU__mdt.object-meta.xml
<CustomObject>
    <label>Parámetros DAU</label>
    <pluralLabel>Parámetros DAU</pluralLabel>
</CustomObject>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Contrasenia__c.field-meta.xml
<CustomField>
    <fullName>DAU_Contrasenia__c</fullName>
    <label>Contraseña</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Token__c.field-meta.xml
<CustomField>
    <fullName>DAU_Token__c</fullName>
    <label>Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametros_DAU__mdt/fields/DAU_Usuario__c.field-meta.xml
<CustomField>
    <fullName>DAU_Usuario__c</fullName>
    <label>Usuario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Salesforce_Tarjetas.cls
public class Salesforce_Tarjetas {
    
	@future(callout=true)
    public static void processCase(Set<Id> caseIds, String tipoGestion, String beneficiario, String diaPago) {
        List<Case> updateCase = new List<Case>();
        try {
            List<Case> lstCase = [Select Id,Status,Account.Identificacion__c,Respuesta_desde_Sysde__c,Respuesta_SF_Tarjetas__c, DAU_No_Cuenta__c,
                                  DAU_Identidad__c,Tipo_de_Operacion__c,DAU_Tarjeta_de_Sysde__c From Case Where Id in :caseIds Limit 1];
            List<Detalle_caso__c> detcaso = [Select Id,Caso__c,Cuenta__c,Cuenta__r.Name,Cuenta__r.CurrencyIsoCode,N_Cuenta_Bancaria__c,DAU_Borrar_Cuotas__c 
                                             From Detalle_caso__c Where Caso__c In: caseIds Limit 1];
            String Identidad = lstCase[0].DAU_Identidad__c;
            //System.debug('Identidad2: '+Identidad.substring(0,13));
            String moneda;
            System.debug('La moneda es: '+detcaso[0].Cuenta__r.CurrencyIsoCode);
            if(detcaso[0].Cuenta__r.CurrencyIsoCode == 'HNL') {
                moneda = 'L';    
            } else if(detcaso[0].Cuenta__r.CurrencyIsoCode == 'USD') {
                moneda = '$';
            }       
            for(Case c : lstCase) {    

                WsGestiones.WS_GestionesDAU servDau = new WsGestiones.WS_GestionesDAU();
                
                if(!test.isRunningTest()) {
                    
                String DAU_Usuario, DAU_Contrasenia, DAU_Token;
                Parametros_DAU__mdt[] mdt = [SELECT Id,DeveloperName,DAU_Usuario__c,DAU_Contrasenia__c,DAU_Token__c FROM Parametros_DAU__mdt Where DeveloperName = 'Salesforce_Tarjeta_Login'];
                If(!mdt.isEmpty()) {
                	DAU_Usuario = mdt[0].DAU_Usuario__c; DAU_Contrasenia = mdt[0].DAU_Contrasenia__c; DAU_Token = mdt[0].DAU_Token__c;
                }    
                              
                //Creando caso en Salesforce Tarjetas
                partnerSoapSforceCom.Soap con = new partnerSoapSforceCom.Soap();
                partnerSoapSforceCom.LoginResult loginResult = con.login(DAU_Usuario, DAU_Contrasenia + DAU_Token);
                
                WsGestiones.SessionHeader_element sessionHeader = new WsGestiones.SessionHeader_element();
                sessionHeader.sessionId = loginResult.sessionid;
                servDau.timeout_x = 120000;
                servDau.SessionHeader = sessionHeader;
                }    
                
                String asunto = '';
                String CuentaBancaria = detcaso[0].N_Cuenta_Bancaria__c;
                
                if(c.Tipo_de_Operacion__c == 'A7') { asunto = 'Cancelación DAU Pensiones';
                } else if(c.Tipo_de_Operacion__c == 'A3' || c.Tipo_de_Operacion__c == 'A8') {
                    asunto = 'Debito automático Pensiones';    
                } else if(c.Tipo_de_Operacion__c == 'A4') {
                    asunto = 'Modificacion de Beneficios';    
                } else if(c.Tipo_de_Operacion__c == 'A6' && c.Respuesta_SF_Tarjetas__c == Null) {
                    asunto = 'Cancelación DAU Pensiones';
                    CuentaBancaria = lstCase[0].DAU_Tarjeta_de_Sysde__c;
                } else if(c.Tipo_de_Operacion__c == 'A6' && c.Respuesta_SF_Tarjetas__c <> Null && c.Respuesta_SF_Tarjetas__c.contains('éxito')) {
                    asunto = 'Debito automático Pensiones';  
                }
                
                System.debug('tipoGestion: '+tipoGestion+'---'+'Identidad: '+lstCase[0].DAU_Identidad__c+'---'+'nroCuenta: '+lstCase[0].DAU_No_Cuenta__c+'---'+'# Cuenta Bancaria: '+CuentaBancaria+'---'+'moneda: '+moneda+'---'+'Cuenta Salesforce: '+detcaso[0].Cuenta__r.Name+'---'+'Asunto: '+asunto+'---'+'Beneficiario: '+beneficiario+'---'+'DiaPago: '+diaPago);
                
                if(asunto <> Null || asunto <> '') {
                    
                    String response = 'Testeando';
                    
                    if(!test.isRunningTest()) { response = String.valueOf(servDau.crearGestion(tipoGestion,lstCase[0].DAU_Identidad__c,lstCase[0].DAU_No_Cuenta__c,CuentaBancaria,'Pensiones y Cesantías -Personal Ordinario '+moneda,detcaso[0].Cuenta__r.Name,asunto,'Otros',beneficiario,diaPago,'Ficohsa Pensiones','','','','','',''));
                    	System.debug('response: '+response);
                    }
                    
                    WsGestiones.crearGestionResponse_element resultado = new WsGestiones.crearGestionResponse_element();
                    System.debug('resultado: '+resultado);   
                    
                    //Get Identity of Response
                    String respuesta;
                    JSONParser parser = JSON.createParser(JSON.serialize(resultado));
                    System.debug('parser01: '+parser);
                    while (parser.nextToken() != null) {
                        System.debug('parser.getCurrentName01(): '+parser.getCurrentName());
                        if(parser.getCurrentName() == 'field_order_type_info') {
                            parser.nextValue();
                            System.debug('field_order_type_info: ' +parser.getText());
                            respuesta = parser.getText();
                        }
                    }  
                    System.debug('respuesta: '+respuesta);
                    
                    /*String response = 'Gestión creada con éxito';
                    String response2 = 'Gestión creada con éxito 2';*/
                    
                    //c.Respuesta_SF_Tarjetas__c = String.valueOf(respuesta);               
                    if(response.contains('éxito') || response == 'Testeando') {
                        System.debug('Gestión creada con éxito'); 
                        System.debug('Tipo de Operación: '+c.Tipo_de_Operacion__c);
                        if(c.Tipo_de_Operacion__c <> 'A6') { c.Respuesta_SF_Tarjetas__c = String.valueOf(response);
                        }               
                        if(c.Tipo_de_Operacion__c == 'A6' && c.Respuesta_SF_Tarjetas__c == Null) {
                            c.Respuesta_SF_Tarjetas__c = 'Cancelación: // '+String.valueOf(response); 
                            List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                            Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_TercerServicio__c = true));
                            // Call method to publish events
                            List<Database.SaveResult> results = EventBus.publish(Logs);
                        }                    
                        if((c.Tipo_de_Operacion__c == 'A6' && asunto == 'Debito automático Pensiones') || test.isRunningTest()) {
                            c.Respuesta_SF_Tarjetas__c = c.Respuesta_SF_Tarjetas__c + ' --- Afiliación: // ' + String.valueOf(response);  
                            if(detcaso[0].DAU_Borrar_Cuotas__c == '2' || detcaso[0].DAU_Borrar_Cuotas__c == '3') {
                                List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                                Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_Borrar_Cuotas_S10__c = true));
                                // Call method to publish events
                                List<Database.SaveResult> results = EventBus.publish(Logs);
                            } else {
                                List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                                Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_EjecutarSYSDE__c = true));
                                // Call method to publish events
                                List<Database.SaveResult> results = EventBus.publish(Logs);    
                            } 
                        }                    
                        if(c.Tipo_de_Operacion__c == 'A4' || c.Tipo_de_Operacion__c == 'A7') {
                            List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                            Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_EjecutarSYSDE__c = true));
                            // Call method to publish events
                            List<Database.SaveResult> results = EventBus.publish(Logs);
                        }
                        if(c.Tipo_de_Operacion__c == 'A3' || c.Tipo_de_Operacion__c == 'A8') {
                            if(detcaso[0].DAU_Borrar_Cuotas__c == '2' || detcaso[0].DAU_Borrar_Cuotas__c == '3') {
                                List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                                Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_Borrar_Cuotas_S10__c = true));
                                // Call method to publish events
                                List<Database.SaveResult> results = EventBus.publish(Logs);
                            } else {
                                List<DAU_Salesforce_Tarjetas__e> Logs = new List<DAU_Salesforce_Tarjetas__e>();
                                Logs.add(new DAU_Salesforce_Tarjetas__e(DAU_IdCaso__c = c.Id, DAU_EjecutarSYSDE__c = true));
                                // Call method to publish events
                                List<Database.SaveResult> results = EventBus.publish(Logs);    
                            }   
                        } 
                    } else if(response.contains('error')) {
                        System.debug('Error al crear la gestion');
                        c.Respuesta_SF_Tarjetas__c = c.Respuesta_SF_Tarjetas__c + ' --- Error: // '+String.valueOf(response);
                        c.DAU_aprobacion__c = false;  
                    }
                    updateCase.add(c);
                }    
            }        
        } catch(Exception ex) {
        	System.debug('Error: '+ex.getLineNumber()+'---'+ex.getMessage());    
        } 
        Update updateCase;
    }	
    
}