force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiario</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Numero Beneficiario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/Casilla__c.field-meta.xml
<CustomField>
    <fullName>Casilla__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Utilizado en las clase APEX para marcar un registro</description>
    <inlineHelpText>Utilizado en las clase APEX para marcar un registro</inlineHelpText>
    <label>Casilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Forma_Retiro__c.field-meta.xml
<CustomField>
    <fullName>Forma_Retiro__c</fullName>
    <label>Forma de Retiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CK</fullName>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>AH</fullName>
                <label>Credito a Cuenta Ficohsa</label>
            </value>
            <value>
                <fullName>ACH</fullName>
                <label>Transferencia ACH</label>
            </value>
            <value>
                <fullName>EF</fullName>
                <label>Efectivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Constancia__c.field-meta.xml
<CustomField>
    <fullName>Constancia__c</fullName>
    <label>Constancia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constancia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Constancia__c/Constancia__c.object-meta.xml
<CustomObject>
    <label>Constancia</label>
    <nameField>
        <label>Nombre de Constancias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constancias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Constancia__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta_colectiva2__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_colectiva2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta colectiva</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cuentas__c.Colectiva__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Fecha_Apertura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Apertura__c</fullName>
    <label>Fecha de Apertura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Monto_aporte__c</fullName>
    <label>Monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario</label>
    <referenceTo>Beneficiario__c</referenceTo>
    <relationshipLabel>Detalles caso</relationshipLabel>
    <relationshipName>Detalles_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cabeza_retiro__c.field-meta.xml
<CustomField>
    <fullName>Cabeza_retiro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cabeza de retiro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cliente_quiere_capital_semilla__c.field-meta.xml
<CustomField>
    <fullName>Cliente_quiere_capital_semilla__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cliente quiere capital semilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Fecha_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_nacimiento__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Forma_Retiro__c.field-meta.xml
<CustomField>
    <fullName>Forma_Retiro__c</fullName>
    <label>Forma de Retiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CK</fullName>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>AH</fullName>
                <label>Credito a Cuenta Ficohsa</label>
            </value>
            <value>
                <fullName>ACH</fullName>
                <label>Transferencia ACH</label>
            </value>
            <value>
                <fullName>EF</fullName>
                <label>Efectivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <label>Id Externo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Monto_retirar__c.field-meta.xml
<CustomField>
    <fullName>Monto_retirar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monto a retirar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Monto_saldo__c.field-meta.xml
<CustomField>
    <fullName>Monto_saldo__c</fullName>
    <label>Monto del saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Saldo_retirar__c.field-meta.xml
<CustomField>
    <fullName>Saldo_retirar__c</fullName>
    <label>Saldo a retirar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_saldo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_retiro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_retiro__c</fullName>
    <label>Tipo de retiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>52</fullName>
                <label>Total</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>Parcial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testCostancia.cls
@isTest
public class testCostancia{
    static testMethod void asignacionConstancia(){
        
        test.startTest();
            controllerAsignacionConstancia control = new controllerAsignacionConstancia();
            control.agregar();
            control.agregar();
            control.registroS = 0;
            control.eliminar();
            control.agregar();
            control.guardar();
        test.stopTest();
    }
    
    static testMethod void adminConstancia(){
    
        test.startTest();
            controllerAdminConstancias control = 
            new controllerAdminConstancias( new ApexPages.StandardController(new Constancia__c()));
            control.relacionSeleccionada = 'CaseComment';
            control.onchangeCampoRelacionSelecionado();
            control.showModalCamposObjeto();
            control.aceptarCamposSeleccionado();
            control.cancelarCamposSeleccionado();
            control.actualizarOrdenamiento();
            
            List<SelectOption> var1 = new List<SelectOption>();
            var1 = controllerAdminConstancias.getCamposCase('Case');
            var1 = controllerAdminConstancias.getRelacionesCase();
            List<Schema.ChildRelationship> childRela = controllerAdminConstancias.relacionesCaso();
            var1 = controllerAdminConstancias.getCamposRelacionesCase(null);
            
        test.stopTest();    
    }
    
    /*static testMethod void casosSAC(){ 
        MultiStaticResourceCalloutMock mock = new MultiStaticResourceCalloutMock();
        mock.setStaticResource('http://190.5.68.11:9090/api/obtenerinfocuenta?IdCliente=12345','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/constancias','mockAportes');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        
        
        Producto__c producto = new Producto__c(Name = 'Producto1', Codigo__c = 'Pro1');
        insert producto;
        
        Subproducto__c subproducto = new Subproducto__c(Name = 'SubProducto1', Codigo__c = 'SubPro1', Producto__c = producto.id);
        insert subproducto;
        
        Subproducto__c subproducto2 = new Subproducto__c(Name = 'SubProducto2', Codigo__c = 'SubPro2', Producto__c = producto.id);
        insert subproducto2;
        
        Account natural = new Account(FirstName = 'Juan', LastName = 'Perez', Identificacion__c = '12345',
                                    RecordTypeId = [Select id From RecordType Where sObjectType = 'Account' AND DeveloperName = 'Natural'].id);
        insert natural;
        Date hoy = date.today();
        Cuentas__c cuentaIndi = new Cuentas__c(Name = 'Cuenta', Codigo__c = '123', Cliente__c = natural.id, Producto__c = producto.id,
                                            Subproducto__c = subproducto.id, currencyIsoCode = 'HNL', Fecha_Apertura__c = hoy);
        insert cuentaIndi;
        
        Beneficiario__c bene = new Beneficiario__c(Cliente__c = natural.id, Cuenta__c = cuentaIndi.id, Primer_Apellido__c = 'system',
                                                    Id_Externo__c = 0801, Fecha_nacimiento__c = date.today());
        insert bene;
                                    
        Account juridico = new Account(Name = 'Intellect', Identificacion__c = '54321',
                                    RecordTypeId = [Select id From RecordType Where sObjectType = 'Account' AND DeveloperName = 'Juridico'].id);
        insert juridico;                            
        
        Cuentas__c cuentaColec = new Cuentas__c(Name = 'Cuenta2',Codigo__c = '789', Cliente__c = juridico.id, currencyIsoCode = 'HNL');
        insert cuentaColec;
        
        Cuentas__c cuentaIndiColec = new Cuentas__c(Name = 'Cuenta3', Codigo__c = '456', Cliente__c = natural.id, 
                        Cuenta_colectiva2__c = cuentaColec.id, currencyIsoCode = 'HNL', Fecha_Apertura__c = hoy);
        insert cuentaIndiColec;
        
        list<RecordType> tiposR = [Select Name From RecordType Where sObjectType = 'Case' Order by Name];
        system.debug(tiposR);
        
        list<Case> casos = new list<Case>();
        
        Case casoActualizacion = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[0].id);
        casos.add(casoActualizacion);
        
        Case casoSubproducto = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[2].id);
        casos.add(casoSubproducto);
        
        Case casoConstancia = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[3].id);
        casos.add(casoConstancia);
        
        Case casoRetiros = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[6].id);
        casos.add(casoRetiros);
        
        Case casoAumentoD2 = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[1].id);
        casos.add(casoAumentoD2);
        
        Case casoRetiros2 = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[6].id);
        casos.add(casoRetiros2);
              
        insert Casos;
        
        Case casoAumentoD = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[1].id);
        
        list<Detalle_caso__c> detalleCasos = new list<Detalle_caso__c>();
        Detalle_caso__c detalle = new Detalle_Caso__c(Caso__c = Casos[0].id, Cuenta__c = cuentaIndi.id);
        detalleCasos.add(detalle);
        
        Detalle_caso__c detalle1 = new Detalle_Caso__c(Caso__c = Casos[5].id, Cuenta__c = cuentaIndi.id,Cabeza_retiro__c = true,
        										Forma_Retiro__c = 'ACH');
        detalleCasos.add(detalle1);
        
        Detalle_caso__c detalle2 = new Detalle_Caso__c(Caso__c = Casos[5].id, Cuenta__c = cuentaIndi.id,
        								Saldo_retirar__c = '10', Monto_Saldo__c = 100, Monto_retirar__c = 50);
        detalleCasos.add(detalle2);
        
        insert detalleCasos;
        
        test.startTest();
            extensionCasoDetalle controlActinfo = new extensionCasoDetalle(new ApexPages.StandardController(Casos[0]));
            controlActinfo.selecCuenta();
            controlActinfo.llenarCuentasDesdeSysde();
            controlActinfo.verBeneficiarios();
            controlActinfo.listBeneficiarios[0].Casilla__c = true;
            controlActinfo.agregarBeneficiarios();
            controlActinfo.agregarCuenta();
            controlActinfo.eliminarCuenta();
            controlActinfo.idDetalleEliminar = cuentaIndi.id;       
            controlActinfo.verAportes();
            controlActinfo.selecAporte();
            controlActinfo.guardar();
            
            extensionCasoDetalle controlSubproducto = new extensionCasoDetalle(new ApexPages.StandardController(casos[1]));
            controlSubproducto.accionSubproducto();
            controlSubproducto.buscarCuentaC();
            controlSubproducto.buscarSubPro();
            controlSubproducto.guardar();
            
            extensionCasoDetalle controlConsta = new extensionCasoDetalle(new ApexPages.StandardController(casos[2]));                                  
            controlConsta.agregarCuenta();
            controlConsta.agregarCuenta();
            controlConsta.idDetalleEliminar = cuentaIndi.id;        
            controlConsta.eliminarCuenta();             
            controlConsta.guardar();
            
            extensionCasoDetalle controlRetiro = new extensionCasoDetalle(new ApexPages.StandardController(casos[3]));
            controlRetiro.verPropietarioCuenta();            
            controlRetiro.detalleCaso.Cliente_quiere_capital_semilla__c = false;
            controlRetiro.detalleCaso.Tipo_retiro__c = '52';
            controlRetiro.selecTipoRetiro();
            controlRetiro.detalleCaso.Cliente_quiere_capital_semilla__c = true;
            controlRetiro.selecTipoRetiro();
            controlRetiro.verMovimientos();
            controlRetiro.selecMovimiento(); 
            controlRetiro.cuentasCaso.add(new Detalle_Caso__c(Cuenta__c = natural.id, Caso__c = casos[3].id, Saldo_retirar__c = '10',
	    									Monto_Saldo__c = 100, Monto_retirar__c = -2));  
	    									
            controlRetiro.guardar();
            controlRetiro.cuentasCaso[0].Monto_retirar__c = 200;
            controlRetiro.guardar();
            controlRetiro.cuentasCaso[0].Monto_retirar__c = 50;
            controlRetiro.guardar();
            
            cuentaIndiColec.fecha_apertura__c = date.today() - 950;
            update cuentaIndiColec;
            
            extensionCasoDetalle controlRetiro2 = new extensionCasoDetalle(new ApexPages.StandardController(casos[5]));
            controlRetiro2.selecCuentaRetiros();
            controlRetiro2.detalleCaso.Tipo_retiro__c = '52';
            controlRetiro2.selecTipoRetiro();
            controlRetiro2.guardar();
            
            extensionCasoDetalle controlADA2 = new extensionCasoDetalle(new ApexPages.StandardController(casos[4]));            
            controlADA2.guardar();
            
            ApexPages.currentPage().getParameters().put('idCliente',natural.id);
            extensionCasoDetalle controlADA = new extensionCasoDetalle(new ApexPages.StandardController(casoAumentoD));
            controlADA.accionVacia();
            controlADA.accionVacia2();
            controlADA.continuarAlPaso2();
            controlADA.idTipoRCaso = tiposR[1].id;
            controlADA.continuarAlPaso2();
            controlADA.formularioCliente();
            controlADA.adjuntarArchivo();
            controlADA.Caso.Origin = 'Call center';
            controlADA.guardar();
            
            extensionCasoDetalle controlNormal = new extensionCasoDetalle();
            controlNormal.idCaso = casos[3].id;
            controlNormal.verCaso();
            controlNormal.cerrarCaso();
        test.stopTest();                                        
    }
    
    static testMethod void llamadasREST(){ 
        MultiStaticResourceCalloutMock mock = new MultiStaticResourceCalloutMock();
        mock.setStaticResource('http://190.5.68.11:9090/api/subproducto','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/aumentodisminucion','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/info','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/ec/portada?IdCliente=12345','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/ec/trimestral?IdCliente=12345','mockCuentas');
        mock.setStaticResource('http://190.5.68.11:9090/api/ec/mensual?IdCliente=12345&fechaDesde=2017-07-18&fechaHasta=2017-07-23','mockCuentas');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        
        Producto__c producto = new Producto__c(Name = 'Producto1', Codigo__c = 'Pro1');
        insert producto;
        
        Subproducto__c subproducto = new Subproducto__c(Name = 'SubProducto1', Codigo__c = 'SubPro1', Producto__c = producto.id,
                currencyIsoCode = 'HNL');
        insert subproducto;
        
        Subproducto__c subproducto2 = new Subproducto__c(Name = 'SubProducto2', Codigo__c = 'SubPro2', Producto__c = producto.id,
                currencyIsoCode = 'HNL');
        insert subproducto2;
        
        Account natural = new Account(FirstName = 'Juan', LastName = 'Perez', Identificacion__c = '12345',
                                    RecordTypeId = [Select id From RecordType Where sObjectType = 'Account' AND DeveloperName = 'Natural'].id);
        insert natural;
        
        Date hoy = date.today();
        Cuentas__c cuentaIndi = new Cuentas__c(Name = 'Cuenta', Codigo__c = '123', Cliente__c = natural.id, Producto__c = producto.id,
                                            Subproducto__c = subproducto.id, currencyIsoCode = 'HNL', Fecha_Apertura__c = hoy,
                                            Monto_aporte__c = 5000, Forma_Aportacion__c = 'AH');
        insert cuentaIndi;
        
        list<RecordType> tiposR = [Select Name From RecordType Where sObjectType = 'Case' Order by Name];
        system.debug(tiposR);
        
        list<Case> casos = new list<Case>();
        
        Case casoActualizacion = new Case(AccountId = natural.id, Nombre_Cliente__c = 'FPC',
                                Status = 'Nuevo', RecordTypeId = tiposR[0].id, Telefono_Casa__c = '234524534',
                                Telefono_Movil__c = '2345345', Telefono_Trabajo__c = '2345234534');
        casos.add(casoActualizacion);
        
        Case casoSubproducto = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[2].id);
        casos.add(casoSubproducto);     
        
        Case casoAumentoD = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[1].id);
        casos.add(casoAumentoD);
        
        Case casoConstancia = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[3].id);
        casos.add(casoConstancia);
        
        Case casoEDC = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[4].id,
                    Fecha_desde__c = date.today() - 10, Fecha_hasta__c = date.today());
        casos.add(casoEDC);
        
        Case casoRetiro = new Case(AccountId = natural.id, Status = 'Nuevo', RecordTypeId = tiposR[6].id);
        casos.add(casoRetiro);
                
        insert Casos;
        
        list<Detalle_caso__c> detalles = new list<Detalle_caso__c>();
        
        Detalle_caso__c nuevoSP = new Detalle_Caso__c(Caso__c = Casos[0].id,Cuenta__c = cuentaIndi.id,
                Fecha_nacimiento__c = date.today());
        detalles.add(nuevoSP);
        detalles.add(new Detalle_Caso__c(Caso__c = Casos[1].id,Nuevo_Subproducto__c = subproducto2.id, Cuenta__c = cuentaIndi.id));
        detalles.add(new Detalle_Caso__c(Caso__c = Casos[2].id, Nuevo_monto_aporte__c = 50000, Cuenta__c = cuentaIndi.id));
        detalles.add(new Detalle_Caso__c(Caso__c = Casos[5].id, Cuenta__c = cuentaIndi.id));
        insert detalles;
        
        test.startTest();
            list<Case> casosF = [Select Status,Aprobado__c From Case Where Id In: casos];
            system.debug(casosF);
            For(Case item : casosF){
                item.Status = 'Cerrado';
                item.Aprobado__c = true;
                item.Segunda_aprobacion__c = true;
            }
            update casosF;
            
            //ApexPages.currentPage().getParameters().put('idCaso',Casos[4].id);
            //controllerEstadoCuentaTrimestral controlEDCT = new controllerEstadoCuentaTrimestral();
            classECPortada controlEDC1 = aSysdeCallouts.estadoCuentaCorreo(Casos[4].id);
            classECMensual controlEDC2 = aSysdeCallouts.estadoCuentaMensual(Casos[4].id);
            classECTrimestral controlEDC3 = aSysdeCallouts.estadoCuentaTrimestral(Casos[4].id, null);
            classECHistorico controlEDC4 = aSysdeCallouts.estadoCuentaHistorico(Casos[4].id, null);
            Boolean fechaCierre = aSysdeCallouts.fechaCierreSysde(Date.today());
            Decimal montoCambio = aSysdeCallouts.montoCambioDolar();
            
            ApexPages.currentPage().getParameters().put('id',Casos[2].id);
            controllerAprobarCasos controlAprobar = new controllerAprobarCasos();
            controlAprobar.rechazar();
            controlAprobar.adjuntar();
            controlAprobar.cerrar();
            controlAprobar.aprobar();
            
            ApexPages.currentPage().getParameters().put('id',Casos[2].id);
            controllerAdjuntarArchivo controlAdjuntar = new controllerAdjuntarArchivo();
            controlAdjuntar.UploadFile();
            controlAdjuntar.fileBody = blob.valueOf('Probando');  
            controlAdjuntar.fileName = 'Algo';
            controlAdjuntar.UploadFile();
            Attachment hola = new Attachment(ParentId = casos[2].id, Body = blob.valueOf('Nada'), Name = 'Llui');
            insert hola;
            
            ApexPages.currentPage().getParameters().put('id',Casos[2].id);
            controllerAdjuntarArchivo controlAdjuntar2 = new controllerAdjuntarArchivo();
            controlAdjuntar2.fileBody = blob.valueOf('Probando');  
            controlAdjuntar2.fileName = 'Algo';
            controlAdjuntar2.UploadFile();
            
        test.stopTest();
    }*/
    
}