force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/Contenido_Planilla__c.object-meta.xml
<CustomObject>
    <label>Contenido Planilla</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contenidos Planilla</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Empleado_Obligatorio__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Empleado_Obligatorio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Empleado Obligatorio</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Empleado_Voluntario__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Empleado_Voluntario__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Aporte Empleado Voluntario</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Patrono_obligatorio__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Patrono_obligatorio__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Aporte Patrono obligatorio</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Patrono_Voluntario__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Patrono_Voluntario__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Patrono Voluntario</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Empleado2__c.field-meta.xml
<CustomField>
    <fullName>Empleado2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empleado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contenidos Planilla</relationshipLabel>
    <relationshipName>Contenidos_Planilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Planilla__c.field-meta.xml
<CustomField>
    <fullName>Planilla__c</fullName>
    <label>Planilla</label>
    <referenceTo>Planilla__c</referenceTo>
    <relationshipLabel>Contenidos Planilla</relationshipLabel>
    <relationshipName>Contenidos_Planilla</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Reserva_Laboral__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Reserva Laboral</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Planilla__c/Planilla__c.object-meta.xml
<CustomObject>
    <label>Planilla</label>
    <nameField>
        <displayFormat>PLA-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla__c/fields/Cantidad_empleados__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_empleados__c</fullName>
    <label>Cantidad de empleados</label>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha depósito</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/TA_Empleado_Obligatorio__c.field-meta.xml
<CustomField>
    <fullName>TA_Empleado_Obligatorio__c</fullName>
    <label>Total Aporte Empleado Obligatorio</label>
    <summarizedField>Contenido_Planilla__c.Aporte_Empleado_Obligatorio__c</summarizedField>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/TA_Empleado_Voluntario__c.field-meta.xml
<CustomField>
    <fullName>TA_Empleado_Voluntario__c</fullName>
    <label>Total Aporte Empleado Voluntario</label>
    <summarizedField>Contenido_Planilla__c.Aporte_Empleado_Voluntario__c</summarizedField>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/TA_Patrono_obligatorio__c.field-meta.xml
<CustomField>
    <fullName>TA_Patrono_obligatorio__c</fullName>
    <label>Total Aporte Patrono obligatorio</label>
    <summarizedField>Contenido_Planilla__c.Aporte_Patrono_obligatorio__c</summarizedField>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/TA_Patrono_Voluntario__c.field-meta.xml
<CustomField>
    <fullName>TA_Patrono_Voluntario__c</fullName>
    <label>Total Aporte Patrono Voluntario</label>
    <summarizedField>Contenido_Planilla__c.Aporte_Patrono_Voluntario__c</summarizedField>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Total_obligatorios__c +  Total_voluntarios__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Total_obligatorios__c.field-meta.xml
<CustomField>
    <fullName>Total_obligatorios__c</fullName>
    <formula>TA_Patrono_obligatorio__c + TA_Empleado_Obligatorio__c + Total_Reserva_Laboral2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total obligatorios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Total_Reserva_Laboral2__c.field-meta.xml
<CustomField>
    <fullName>Total_Reserva_Laboral2__c</fullName>
    <label>Total Reserva Laboral</label>
    <summarizedField>Contenido_Planilla__c.Reserva_Laboral__c</summarizedField>
    <summaryForeignKey>Contenido_Planilla__c.Planilla__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Total_voluntarios__c.field-meta.xml
<CustomField>
    <fullName>Total_voluntarios__c</fullName>
    <formula>TA_Empleado_Voluntario__c + TA_Patrono_Voluntario__c + TA_Empleado_Extraordinario__c + TA_Patrono_Extraordinario__c + TA_Seguro_de_Vida__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total voluntarios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/controladorVerPlanillaNormal.cls
public class controladorVerPlanillaNormal {
    
    public list <Contenido_Planilla__c> listEmpleados {get;set;}
    public list <Contenido_Planilla__c> listEmpleados2 {get;set;}
    public boolean activarmodal{get;set;}
    public planilla__C totalPlanilla{get;set;}
    
    public controladorVerPlanillaNormal()
    {
        activarmodal=true;
        listEmpleados = new list<Contenido_Planilla__c>();
        listEmpleados2 = new list<Contenido_Planilla__c>();
        string idPlanilla=ApexPages.currentPage().getParameters().get('idPlanilla');
        totalplanilla=[select TA_Empleado_Obligatorio__c, name,TA_Empleado_Voluntario__c, TA_Patrono_obligatorio__c, 
                       Cantidad_empleados__c, total__C,Total_obligatorios__c ,Total_voluntarios__c,
                       TA_Patrono_Voluntario__c, Total_Reserva_Laboral2__c
                       from planilla__C where id=:idPlanilla];
        string query ='select empleado2__r.Identificacion__c, empleado2__r.name, Planilla__r.Fecha__c,   ';
        query +=  'Aporte_Patrono_obligatorio__c, Aporte_Empleado_Obligatorio__c, Aporte_Patrono_Voluntario__c, ';
        query +=  ' Aporte_Empleado_Voluntario__c, Reserva_Laboral__c  from Contenido_Planilla__c ';
        query +=   ' where planilla__c=\''+IdPlanilla + '\' order by empleado2__r.name asc limit 2200';
        listEmpleados=database.query(query);
        
    }
    
    
}