force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Ingresado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Ingresado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para validar envío de Email cuando se ingresa la gestión y se asigna a un Asesor.</description>
    <inlineHelpText>Bandera para validar envío de Email cuando se ingresa la gestión y se asigna a un Asesor.</inlineHelpText>
    <label>Caso Ingresado Email2Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_No_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>DAU_No_Cuenta__c</fullName>
    <description>Número de cuenta que devuelve el servicio de validación de Identidad.</description>
    <inlineHelpText>Número de cuenta que devuelve el servicio de validación de Identidad.</inlineHelpText>
    <label>DAU_No.Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_Tarjeta_de_Sysde__c.field-meta.xml
<CustomField>
    <fullName>DAU_Tarjeta_de_Sysde__c</fullName>
    <description>Número de tarjeta de devuelve el servicio que consulta a Sysde.</description>
    <inlineHelpText>Número de tarjeta de devuelve el servicio que consulta a Sysde.</inlineHelpText>
    <label>DAU_Tarjeta de Sysde</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24</fullName>
                <label>Bac Honduras</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Banco Atlantida</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Banco Azteca</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>Banco Banadesa</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Banco Banrural</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Banco Central de Honduras</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Banco Davivienda</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Banco de Honduras</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Banco de los Trabajadores</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Banco del País</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Banco de Occidente</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Banco Ficensa</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Banco Ficohsa</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Banco Hondureño del Café</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Banco Lafise</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Banco Promerica</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Bancovelo</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Credi Q</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Fondo_Inversion__c.field-meta.xml
<CustomField>
    <fullName>Fondo_Inversion__c</fullName>
    <label>Fondo de Inversión</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>101</fullName>
                <label>Mixto</label>
            </value>
            <value>
                <fullName>106</fullName>
                <label>Dólares</label>
            </value>
            <value>
                <fullName>113</fullName>
                <label>Lempiras Puros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Banco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Tipo_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
                <default>true</default>
                <label>Aumento de Aporte</label>
            </value>
            <value>
                <fullName>A2</fullName>
                <label>Disminución de Aporte</label>
            </value>
            <value>
                <fullName>A3</fullName>
                <label>Cambio de Canal de Aporte</label>
            </value>
            <value>
                <fullName>A4</fullName>
                <label>Cambio de Fecha de Aporte</label>
            </value>
            <value>
                <fullName>A5</fullName>
                <label>Cambio de # de CA/CC</label>
            </value>
            <value>
                <fullName>A6</fullName>
                <label>Cambio de # Tarjeta</label>
            </value>
            <value>
                <fullName>A7</fullName>
                <label>Cancelación</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FechaDC_Sysde__c/FechaDC_Sysde__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fecha de cierre Sysde</label>
</CustomObject>

force-app/main/default/objects/FechaDC_Sysde__c/fields/Fecha_cierre__c.field-meta.xml
<CustomField>
    <fullName>Fecha_cierre__c</fullName>
    <label>Fecha de cierre</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateCaseTest.cls
@isTest
public class updateCaseTest {
  public static testmethod void execute() {
        
      if(!System.isFuture() && !System.isBatch()) {
          //crear cuenta
          Account acc = new Account(); 
          acc.Identificacion__c = '0801399412010';    
          acc.Name = 'Test Account';
          insert acc;
          
          Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
          insert con;
          
          Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
          insert ass;
          
          Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
          insert ent;
          
          FechaDC_Sysde__c fdcSysde2 = new FechaDC_Sysde__c(Name = 'CierreAlDia2', Fecha_cierre__c  = date.today());
          insert fdcSysde2;
          
          Profile prof = [select id from profile where Name='Administrador del Sistema'];
          User user = new User();
          user.firstName = 'test1';
          user.lastName = 'test2';
          user.profileId = prof.id;
          user.username = 'standarduser2020@testorg.com';
          user.email = 'standarduser2020@testorg.com';
          user.Alias = 'standar';
          user.LocaleSidKey='en_US';
          user.TimeZoneSidKey='America/Los_Angeles';
          user.EmailEncodingKey='UTF-8';
          user.LanguageLocaleKey='en_US';        
          insert user;
          
          String RecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Email to Case'].Id;    
          Case c0 = new Case();
          c0.AccountId = acc.Id;
          c0.ContactId = con.Id;    
          c0.EntitlementId = ent.Id;
          c0.Priority = 'Alta';
          c0.OwnerId = user.Id;
          c0.RecordTypeId = RecordTypeId; 
          c0.SuppliedEmail = 'test@gmail.com';
          c0.Caso_Ingresado__c = false;
          c0.Status = 'Nuevo';
          c0.Origin = 'Agencias FPC';
          c0.Type = 'Solicitud';                  
          Insert c0;       
          
          String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Reposición de Carnet'].Id;        
          Case c = new Case();
          c.AccountId = acc.Id;
          c.ContactId = con.Id;    
          c.EntitlementId = ent.Id;
          c.Priority = 'Alta';
          c.OwnerId = user.Id;
          c.Reason = 'Otro';
          c.RecordTypeId = RecordTypeId2; 
          c.SuppliedEmail = 'test@gmail.com';
          c.Caso_Ingresado__c = false;        
          c.Status = 'Nuevo';
          c.Origin = 'Agencias FPC';
          c.Type = 'Solicitud';                
          Insert c;     
          
          Case c1 = new Case();
          c1.Priority = 'Alta';
          c1.OwnerId = user.Id;
          c1.EntitlementId = ent.Id;
          c1.RecordTypeId = RecordTypeId; 
          c1.SuppliedEmail = 'test@gmail.com';
          c1.Caso_Ingresado__c = false;
          c1.Status = 'Nuevo'; 
          c1.Origin = 'Agencias FPC';  
          c1.DAU_Tarjeta_de_Sysde__c = '456787654';  
          c1.DAU_No_Cuenta__c = '545678';    
          Insert c1;    
          
          List<Id> setCaseId = new List<Id>();
          setCaseId.add(c.id);
          
          set<Id> setCaseIds = new set<Id>();
          setCaseIds.add(c.id);
          
          set<Id> casoOrigen = new set<Id>();
          casoOrigen.add(c.Id);    
          
          Producto__c prod = new Producto__c();
          prod.Name = 'PENSIONES LEMPIRAS';
          prod.Codigo__c = '01';
          Insert prod;
          
          Subproducto__c subProd = new Subproducto__c();
          subProd.Producto__c = prod.Id;
          subProd.Codigo__c = 'FI010';
          Insert subProd;
          
          Cuentas__c cuenta = new Cuentas__c();
          cuenta.Name = '87675';
          cuenta.Codigo__c = '87675';
          cuenta.Cliente__c = acc.Id;
          cuenta.CurrencyIsoCode = 'HNL';
          cuenta.Producto__c = prod.Id;
          cuenta.Subproducto__c = subProd.Id;
          cuenta.Forma_Aportacion__c = 'TA';
          cuenta.Fondo_Inversion__c = '113';
          Insert Cuenta;
          
          Detalle_caso__c detC = new Detalle_caso__c();
          detC.Caso__c = c.Id;
          detC.Cuenta__c = cuenta.Id;
          detC.Tipo_Operacion__c = 'A6';
          detC.N_Cuenta_Bancaria__c = '456788765';
          detC.Banco__c = '28';    
          Insert detC;    
          
          Test.startTest();
          updateCase.processCase(setCaseId);
          updateCase.processCasePortalAuto(setCaseIds);
          updateCase.createDetail(setCaseId, casoOrigen);
          Test.stopTest();
      }
  }
    
  public static testmethod void execute2() {
        
      if(!System.isFuture() && !System.isBatch()) {
          //crear cuenta
          Account acc = new Account(); 
          acc.Identificacion__c = '0801399412010';    
          acc.Name = 'Test Account';
          insert acc;
          
          Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
          insert con;
          
          Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
          insert ass;
          
          Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
          insert ent;
          
          FechaDC_Sysde__c fdcSysde2 = new FechaDC_Sysde__c(Name = 'CierreAlDia2', Fecha_cierre__c  = date.today());
          insert fdcSysde2;
          
          Profile prof = [select id from profile where Name='Administrador del Sistema'];
          User user = new User();
          user.firstName = 'test1';
          user.lastName = 'test2';
          user.profileId = prof.id;
          user.username = 'standarduser2020@testorg.com';
          user.email = 'standarduser2020@testorg.com';
          user.Alias = 'standar';
          user.LocaleSidKey='en_US';
          user.TimeZoneSidKey='America/Los_Angeles';
          user.EmailEncodingKey='UTF-8';
          user.LanguageLocaleKey='en_US';        
          insert user;
          
          String RecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Email to Case'].Id;    
          Case c0 = new Case();
          c0.AccountId = acc.Id;
          c0.ContactId = con.Id;    
          c0.EntitlementId = ent.Id;
          c0.Priority = 'Alta';
          c0.OwnerId = user.Id;
          c0.RecordTypeId = RecordTypeId; 
          c0.SuppliedEmail = 'test@gmail.com';
          c0.Caso_Ingresado__c = false;
          c0.Status = 'Nuevo';
          c0.Origin = 'Agencias FPC';
          c0.Type = 'Solicitud';                  
          Insert c0;       
          
          String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Reposición de Carnet'].Id;        
          Case c = new Case();
          c.AccountId = acc.Id;
          c.ContactId = con.Id;    
          c.EntitlementId = ent.Id;
          c.Priority = 'Alta';
          c.OwnerId = user.Id;
          c.Reason = 'Otro';
          c.RecordTypeId = RecordTypeId2; 
          c.SuppliedEmail = 'test@gmail.com';
          c.Caso_Ingresado__c = false;        
          c.Status = 'Nuevo';
          c.Origin = 'Agencias FPC';
          c.Type = 'Solicitud';                
          Insert c;     
          
          Case c1 = new Case();
          c1.Priority = 'Alta';
          c1.OwnerId = user.Id;
          c1.RecordTypeId = RecordTypeId; 
          c1.EntitlementId = ent.Id;
          c1.SuppliedEmail = 'test@gmail.com';
          c1.Caso_Ingresado__c = false;
          c1.Status = 'Nuevo'; 
          c1.Origin = 'Agencias FPC';  
          c1.DAU_Tarjeta_de_Sysde__c = '456787654';  
          c1.DAU_No_Cuenta__c = '545678';    
          Insert c1;    
          
          List<Id> setCaseId = new List<Id>();
          setCaseId.add(c.id);
          
          set<Id> setCaseIds = new set<Id>();
          setCaseIds.add(c.id);
          
          set<Id> casoOrigen = new set<Id>();
          casoOrigen.add(c.Id);    
          
          Producto__c prod = new Producto__c();
          prod.Name = 'PENSIONES LEMPIRAS';
          prod.Codigo__c = '01';
          Insert prod;
          
          Subproducto__c subProd = new Subproducto__c();
          subProd.Producto__c = prod.Id;
          subProd.Codigo__c = 'FI010';
          Insert subProd;
          
          Cuentas__c cuenta = new Cuentas__c();
          cuenta.Name = '87675';
          cuenta.Codigo__c = '87675';
          cuenta.Cliente__c = acc.Id;
          cuenta.CurrencyIsoCode = 'HNL';
          cuenta.Producto__c = prod.Id;
          cuenta.Subproducto__c = subProd.Id;
          cuenta.Forma_Aportacion__c = 'TA';
          cuenta.Fondo_Inversion__c = '113';
          Insert Cuenta;
          
          Detalle_caso__c detC = new Detalle_caso__c();
          detC.Caso__c = c.Id;
          detC.Cuenta__c = cuenta.Id;
          detC.Tipo_Operacion__c = 'A6';
          detC.N_Cuenta_Bancaria__c = '456788765';
          detC.Banco__c = 'Otros Bancos';    
          Insert detC;    
          
          Test.startTest();
          updateCase.processCase(setCaseId);
          updateCase.processCasePortalAuto(setCaseIds);
          updateCase.createDetail(setCaseId, casoOrigen);
          Test.stopTest();
      }
  }  
    
  public static testmethod void execute3() {
        
      if(!System.isFuture() && !System.isBatch()) {
          //crear cuenta
          Account acc = new Account(); 
          acc.Identificacion__c = '0801399412010';    
          acc.Name = 'Test Account';
          insert acc;
          
          Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
          insert con;
          
          Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
          insert ass;
          
          Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
          insert ent;
          
          FechaDC_Sysde__c fdcSysde2 = new FechaDC_Sysde__c(Name = 'CierreAlDia2', Fecha_cierre__c  = date.today());
          insert fdcSysde2;
          
          Profile prof = [select id from profile where Name='Administrador del Sistema'];
          User user = new User();
          user.firstName = 'test1';
          user.lastName = 'test2';
          user.profileId = prof.id;
          user.username = 'standarduser2020@testorg.com';
          user.email = 'standarduser2020@testorg.com';
          user.Alias = 'standar';
          user.LocaleSidKey='en_US';
          user.TimeZoneSidKey='America/Los_Angeles';
          user.EmailEncodingKey='UTF-8';
          user.LanguageLocaleKey='en_US';        
          insert user;
          
          String RecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Email to Case'].Id;    
          Case c0 = new Case();
          c0.AccountId = acc.Id;
          c0.ContactId = con.Id;    
          c0.EntitlementId = ent.Id;
          c0.Priority = 'Alta';
          c0.OwnerId = user.Id;
          c0.RecordTypeId = RecordTypeId; 
          c0.SuppliedEmail = 'test@gmail.com';
          c0.Caso_Ingresado__c = false;
          c0.Status = 'Nuevo';
          c0.Origin = 'Agencias FPC';
          c0.Type = 'Solicitud';                  
          Insert c0;       
          
          String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Reposición de Carnet'].Id;        
          Case c = new Case();
          c.AccountId = acc.Id;
          c.ContactId = con.Id;    
          c.EntitlementId = ent.Id;
          c.Priority = 'Alta';
          c.OwnerId = user.Id;
          c.Reason = 'Otro';
          c.RecordTypeId = RecordTypeId2; 
          c.SuppliedEmail = 'test@gmail.com';
          c.Caso_Ingresado__c = false;        
          c.Status = 'Nuevo';
          c.Origin = 'Agencias FPC';
          c.Type = 'Solicitud';                
          Insert c;     
          
          Case c1 = new Case();
          c1.Priority = 'Alta';
          c1.OwnerId = user.Id;
          c1.EntitlementId = ent.Id;
          c1.RecordTypeId = RecordTypeId; 
          c1.SuppliedEmail = 'test@gmail.com';
          c1.Caso_Ingresado__c = false;
          c1.Status = 'Nuevo'; 
          c1.Origin = 'Agencias FPC';  
          c1.DAU_Tarjeta_de_Sysde__c = '456787654';  
          c1.DAU_No_Cuenta__c = '545678';    
          Insert c1;    
          
          List<Id> setCaseId = new List<Id>();
          setCaseId.add(c.id);
          
          set<Id> setCaseIds = new set<Id>();
          setCaseIds.add(c.id);
          
          set<Id> casoOrigen = new set<Id>();
          casoOrigen.add(c.Id);    
          
          Producto__c prod = new Producto__c();
          prod.Name = 'PENSIONES LEMPIRAS';
          prod.Codigo__c = '01';
          Insert prod;
          
          Subproducto__c subProd = new Subproducto__c();
          subProd.Producto__c = prod.Id;
          subProd.Codigo__c = 'FI010';
          Insert subProd;
          
          Cuentas__c cuenta = new Cuentas__c();
          cuenta.Name = '87675';
          cuenta.Codigo__c = '87675';
          cuenta.Cliente__c = acc.Id;
          cuenta.CurrencyIsoCode = 'HNL';
          cuenta.Producto__c = prod.Id;
          cuenta.Subproducto__c = subProd.Id;
          cuenta.Forma_Aportacion__c = 'AH';
          cuenta.Fondo_Inversion__c = '113';
          Insert Cuenta;
          
          Detalle_caso__c detC = new Detalle_caso__c();
          detC.Caso__c = c.Id;
          detC.Cuenta__c = cuenta.Id;
          detC.Tipo_Operacion__c = 'A6';
          detC.N_Cuenta_Bancaria__c = '456788765';
          detC.Banco__c = '';    
          Insert detC;    
          
          Test.startTest();
          updateCase.processCase(setCaseId);
          updateCase.processCasePortalAuto(setCaseIds);
          updateCase.createDetail(setCaseId, casoOrigen);
          
          FieldsBankManagement fields = new FieldsBankManagement();
          fields.tipoGestion = 'afiliaDebito';
          fields.identificacion = '0801198801164';
          fields.moneda = 'HNL';
          fields.fechaInicio = '2021-01-01';
          fields.periodicidad = 'S';
          fields.cuentaBancaria = '456789876';
          fields.diaCobro = '14';
          fields.montoDebito = '3000'; 
          
          fields.pctipoid = '1';
          fields.pcnroid = '865656790';
          fields.cuenta = '45678';
          fields.pcprimernombre = 'Juan';
          fields.pcprimerapellido = 'Pérez';
          fields.pcmail = 'test@gmail.com';
          fields.pnnrocertificado = '34343535636';
          fields.tipoFondo = 'P';
          fields.frecuencia = 'M';
          fields.EntitlementValue = ent.Id;
          
          List<FieldsBankManagement> values = new List<FieldsBankManagement>();
          values.add(fields);
          
          updateCase.createRecord(values);         
          
          MultiStaticResourceCalloutMock mock = new MultiStaticResourceCalloutMock();
          mock.setStaticResource('http://190.5.68.11:9091/api/gestionesBanco','mockCuentas');
          mock.setStatusCode(200); 
          mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
          Test.setMock(HttpCalloutMock.class, mock);
          
          updateCase.validarIdentidad(c.Id, '456789067', '867656790');
          updateCase.validarIdentidad2(c.Id, '456789067', '867656790');
          updateCase.validarIdentidad3(c.Id, '456789067', '867656790', 'Test');
          Test.stopTest();
      }
  }  
    
  public static testmethod void execute4() {
        
      if(!System.isFuture() && !System.isBatch()) {
          //crear cuenta
          Account acc = new Account(); 
          acc.Identificacion__c = '0801399412010';    
          acc.Name = 'Test Account';
          insert acc;
          
          Contact con = new Contact(FirstName='john', LastName='doe', Email='john@doe.com', AccountId=acc.Id);
          insert con;
          
          Asset ass = new Asset(AccountId=acc.Id,ContactId=con.Id, Name='testing');   
          insert ass;
          
          Entitlement ent = new Entitlement(Name='Testing', AccountId=acc.Id, StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)), AssetId=ass.Id);
          insert ent;
          
          FechaDC_Sysde__c fdcSysde2 = new FechaDC_Sysde__c(Name = 'CierreAlDia2', Fecha_cierre__c  = date.today());
          insert fdcSysde2;
          
          Profile prof = [select id from profile where Name='Administrador del Sistema'];
          User user = new User();
          user.firstName = 'test1';
          user.lastName = 'test2';
          user.profileId = prof.id;
          user.username = 'standarduser2020@testorg.com';
          user.email = 'standarduser2020@testorg.com';
          user.Alias = 'standar';
          user.LocaleSidKey='en_US';
          user.TimeZoneSidKey='America/Los_Angeles';
          user.EmailEncodingKey='UTF-8';
          user.LanguageLocaleKey='en_US';        
          insert user;
          
          String RecordTypeId = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Email to Case'].Id;    
          Case c0 = new Case();
          c0.AccountId = acc.Id;
          c0.ContactId = con.Id;    
          c0.EntitlementId = ent.Id;
          c0.Priority = 'Alta';
          c0.OwnerId = user.Id;
          c0.RecordTypeId = RecordTypeId; 
          c0.SuppliedEmail = 'test@gmail.com';
          c0.Caso_Ingresado__c = false;
          c0.Status = 'Nuevo';
          c0.Origin = 'Agencias FPC';
          c0.Type = 'Solicitud';                  
          Insert c0;       
          
          String RecordTypeId2 = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Reposición de Carnet'].Id;        
          Case c = new Case();
          c.AccountId = acc.Id;
          c.ContactId = con.Id;    
          c.EntitlementId = ent.Id;
          c.Priority = 'Alta';
          c.OwnerId = user.Id;
          c.Reason = 'Otro';
          c.RecordTypeId = RecordTypeId2; 
          c.SuppliedEmail = 'test@gmail.com';
          c.Caso_Ingresado__c = false;        
          c.Status = 'Nuevo';
          c.Origin = 'Agencias FPC';
          c.Type = 'Solicitud';                
          Insert c;     
          
          Case c1 = new Case();
          c1.Priority = 'Alta';
          c1.OwnerId = user.Id;
          c1.EntitlementId = ent.Id;
          c1.RecordTypeId = RecordTypeId; 
          c1.SuppliedEmail = 'test@gmail.com';
          c1.Caso_Ingresado__c = false;
          c1.Status = 'Nuevo'; 
          c1.Origin = 'Agencias FPC';  
          c1.DAU_Tarjeta_de_Sysde__c = '456787654';  
          c1.DAU_No_Cuenta__c = '545678';    
          Insert c1;    
          
          List<Id> setCaseId = new List<Id>();
          setCaseId.add(c.id);
          
          set<Id> setCaseIds = new set<Id>();
          setCaseIds.add(c.id);
          
          set<Id> casoOrigen = new set<Id>();
          casoOrigen.add(c.Id);    
          
          Producto__c prod = new Producto__c();
          prod.Name = 'PENSIONES LEMPIRAS';
          prod.Codigo__c = '01';
          Insert prod;
          
          Subproducto__c subProd = new Subproducto__c();
          subProd.Producto__c = prod.Id;
          subProd.Codigo__c = 'FI010';
          Insert subProd;
          
          Cuentas__c cuenta = new Cuentas__c();
          cuenta.Name = '87675';
          cuenta.Codigo__c = '87675';
          cuenta.Cliente__c = acc.Id;
          cuenta.CurrencyIsoCode = 'HNL';
          cuenta.Producto__c = prod.Id;
          cuenta.Subproducto__c = subProd.Id;
          cuenta.Forma_Aportacion__c = 'AH';
          cuenta.Fondo_Inversion__c = '113';
          Insert Cuenta;
          
          Detalle_caso__c detC = new Detalle_caso__c();
          detC.Caso__c = c.Id;
          detC.Cuenta__c = cuenta.Id;
          detC.Tipo_Operacion__c = 'A6';
          detC.N_Cuenta_Bancaria__c = '456788765';
          detC.Banco__c = '';    
          Insert detC;    
          
          Test.startTest();
          updateCase.processCase(setCaseId);
          updateCase.processCasePortalAuto(setCaseIds);
          updateCase.createDetail(setCaseId, casoOrigen);
          
          List<Account> accList = [Select Id,Identificacion__c From Account Where Id =: acc.Id];
          
          FieldsBankManagement fields = new FieldsBankManagement();
          fields.tipoGestion = 'afiliaDebito';
          fields.identificacion = accList[0].Identificacion__c;
          fields.moneda = 'HNL';
          fields.fechaInicio = '2021-01-01';
          fields.periodicidad = 'S';
          fields.cuentaBancaria = '456789876';
          fields.diaCobro = '14';
          fields.montoDebito = '3000'; 
          
          fields.pctipoid = '1';
          fields.pcnroid = '865656790';
          fields.cuenta = '45678';
          fields.pcprimernombre = 'Juan';
          fields.pcprimerapellido = 'Pérez';
          fields.pcmail = 'test@gmail.com';
          fields.pnnrocertificado = '34343535636';
          fields.tipoFondo = 'P';
          fields.frecuencia = 'M';
          fields.EntitlementValue = ent.Id;
          
          fields.pcformapago = 'AH';
          
          List<FieldsBankManagement> values = new List<FieldsBankManagement>();
          values.add(fields);
          
          updateCase.createRecord(values);         
          
          MultiStaticResourceCalloutMock mock = new MultiStaticResourceCalloutMock();
          mock.setStaticResource('http://190.5.68.11:9091/api/gestionesBanco','mockCuentas');
          mock.setStatusCode(400); 
          mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
          Test.setMock(HttpCalloutMock.class, mock);
          
          updateCase.validarIdentidad(c.Id, '456789067', '867656790');
          updateCase.validarIdentidad2(c.Id, '456789067', '867656790');
          updateCase.validarIdentidad3(c.Id, '456789067', '867656790', 'Test');
          Test.stopTest();
      }
  }  
}