force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Autonumerico_cuentas_Syste__c/Autonumerico_cuentas_Syste__c.object-meta.xml
<CustomObject>
    <label>Autonumerico cuentas Syste</label>
    <nameField>
        <label>Nombre de Autonumerico cuentas Syste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Autonumerico cuentas Syste</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Autonumerico_cuentas_Syste__c/fields/Contador_EDC__c.field-meta.xml
<CustomField>
    <fullName>Contador_EDC__c</fullName>
    <label>Contador EDC</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/Correo_estado_cuenta__c.object-meta.xml
<CustomObject>
    <label>Correo estado de cuenta</label>
    <nameField>
        <label>Nombre de Correo estado de cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correo estado de cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correo estado de cuenta</relationshipLabel>
    <relationshipName>Correo_estado_de_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Grupo</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Fecha_Apertura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Apertura__c</fullName>
    <label>Fecha de Apertura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testJobEDC.cls
@istest
public class testJobEDC {
    
    static testmethod void JobEDC (){
        Account cuenta = new Account();
        cuenta.LastName = 'Test';
        cuenta.Identificacion__c = '0303030303033';
        cuenta.PersonEmail = 'email@test.com';
        insert cuenta;
        
        Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;
        
        
        Cuentas__C cuentacolectiva= new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='32546';
        cuentacolectiva.Cliente__c=cuenta.id;
        cuentacolectiva.Producto__c=producto.id;
        cuentacolectiva.Fecha_Apertura__c = date.today().AddDays(-50); 
        insert cuentacolectiva;
        
        
        Correo_estado_cuenta__c a = new Correo_estado_cuenta__c(enviado__C = false, cliente__c = cuenta.Id, Grupo__c = 1);
        insert a;
        
        Autonumerico_cuentas_Syste__c c = new Autonumerico_cuentas_Syste__c (Contador_EDC__c = 1);
        insert c;
        
        JobEDC b = new JobEDC();
        b.execute(null);
    }

}