force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/Correo_estado_cuenta__c.object-meta.xml
<CustomObject>
    <label>Correo estado de cuenta</label>
    <nameField>
        <label>Nombre de Correo estado de cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correo estado de cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correo estado de cuenta</relationshipLabel>
    <relationshipName>Correo_estado_de_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Grupo</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Insertarestados.cls
public class Insertarestados {
    
    	@future(callout=true)
		public static void Inserttar()
        {
            try{
                
             list<account> todosclientes = new list<account>();
            list<account> clientes = new list<account>();
            list<string> idclientes= new list<string>();
            for(Correo_estado_cuenta__c item :[select cliente__C from Correo_estado_cuenta__c])
            {
                idclientes.add(item.cliente__C);
            }
            list<Correo_estado_cuenta__c> todoscorreos = new list<Correo_estado_cuenta__c>();
            //map<integer, list<account>> correosOrdenados = new map<integer, list<account>>();
            string correo1='notiene@ejemplo.hn';
            string correo2='notiene@example.com';
            decimal contador=0;
            if([select count() from Correo_estado_cuenta__c]>0)
            {
               contador = [select grupo__C from Correo_estado_cuenta__c order by grupo__C desc limit 1].grupo__C;
            }
            
            todosclientes = [Select id, identificacion__C From Account Where PersonEmail != null 
                             and PersonEmail !=:correo1 and PersonEmail != :correo2 and id not in :idclientes
                             and identificacion__C !=null limit 10000];
           
            integer numeroclientesGrupo=[select count() from Correo_estado_cuenta__c where grupo__C=:contador];
            for(integer i=0; i<todosclientes.size(); i++)
            {
                  clientes.add(todosclientes[i]); 
                if(clientes.size()==500 || i ==todosclientes.size()-1)
                {
                       contador++; 
                   
                  for(integer j=0; j<clientes.size(); j++)
                  {
                     todoscorreos.add(new Correo_estado_cuenta__c(cliente__C=clientes[j].id, grupo__C=contador, enviado__C=false)); 
                  }
                
                    clientes.Clear();
                }
            }
            //Database.BatchableContext BC; 
            database.insert(todoscorreos,false);
                system.debug('Exito'+ todoscorreos.size());
          }catch(Exception ex)
		{
                system.debug('Error: '+ex.getMessage()+' Linea: '+ex.getLineNumber());
        }
   }
		
}