force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>MASCULINO</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>FEMENINO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/Contenido_Planilla__c.object-meta.xml
<CustomObject>
    <label>Contenido Planilla</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contenidos Planilla</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Empleado_Extraordinario__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Empleado_Extraordinario__c</fullName>
    <label>Aporte_Empleado_Extraordinario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Patrono_Extraordinario__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Patrono_Extraordinario__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Patrono Extraordinario</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Patrono_obligatorio__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Patrono_obligatorio__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Aporte Patrono obligatorio</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Aporte_Seguro_de_Vida__c.field-meta.xml
<CustomField>
    <fullName>Aporte_Seguro_de_Vida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aporte Seguro de Vida</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Empleado2__c.field-meta.xml
<CustomField>
    <fullName>Empleado2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empleado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contenidos Planilla</relationshipLabel>
    <relationshipName>Contenidos_Planilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Planilla__c.field-meta.xml
<CustomField>
    <fullName>Planilla__c</fullName>
    <label>Planilla</label>
    <referenceTo>Planilla__c</referenceTo>
    <relationshipLabel>Contenidos Planilla</relationshipLabel>
    <relationshipName>Contenidos_Planilla</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Reserva_Laboral__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Reserva Laboral</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuenta_planilla__c/Cuenta_planilla__c.object-meta.xml
<CustomObject>
    <label>Cuenta de planilla</label>
    <nameField>
        <displayFormat>CUP-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuentas de planilla</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_planilla__c/fields/Codigo_cuenta__c.field-meta.xml
<CustomField>
    <fullName>Codigo_cuenta__c</fullName>
    <label>Código de cuenta</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuenta_planilla__c/fields/Contenido_Planilla__c.field-meta.xml
<CustomField>
    <fullName>Contenido_Planilla__c</fullName>
    <label>Contenido Planilla</label>
    <referenceTo>Contenido_Planilla__c</referenceTo>
    <relationshipLabel>Cuentas de planilla</relationshipLabel>
    <relationshipName>Cuentas_planilla</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuenta_planilla__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas de planilla</relationshipLabel>
    <relationshipName>Cuentas_de_planilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuenta_planilla__c/fields/Valor_Monto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Monto__c</fullName>
    <label>Valor / Monto</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta_colectiva2__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_colectiva2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta colectiva</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cuentas__c.Colectiva__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla__c/Planilla__c.object-meta.xml
<CustomObject>
    <label>Planilla</label>
    <nameField>
        <displayFormat>PLA-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planillas</relationshipLabel>
    <relationshipName>Planillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Estado2__c.field-meta.xml
<CustomField>
    <fullName>Estado2__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>Pendiente Aprobación Interna</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Pendiente Aprobación Ficohsa</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Error con Sysde</fullName>
            </value>
            <value>
                <fullName>Denegada Ficohsa</fullName>
            </value>
            <value>
                <fullName>Denegada</fullName>
                <isActive>false</isActive>
                <label>Denegada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha depósito</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Mes_Aporte__c.field-meta.xml
<CustomField>
    <fullName>Mes_Aporte__c</fullName>
    <label>Mes de Aporte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nombre_Mes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Planilla__c/fields/Tasa_compra__c.field-meta.xml
<CustomField>
    <fullName>Tasa_compra__c</fullName>
    <label>Tasa compra</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tasa_De_Cambio__c/Tasa_De_Cambio__c.object-meta.xml
<CustomObject>
    <label>Tasa De Cambio</label>
    <nameField>
        <label>Nombre de Tasa De Cambio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasa De Cambio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tasa_De_Cambio__c/fields/fecha__c.field-meta.xml
<CustomField>
    <fullName>fecha__c</fullName>
    <label>fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testaSysdePortalEmpresarial.cls
@istest
public class testaSysdePortalEmpresarial {
    
    static testmethod void aSysdePortalEmpresarial () {
        
        
        classDolares.classRespuestaDolares p = new classDolares.classRespuestaDolares();
        p.id='';
        p.monedaDestino='';
        p.monedaOrigen='';
        p.montoAcreditado='';
        p.tasaCambio = '';
        p.montoDebitado ='';
         Account Empresa= new Account();
        Empresa.Name='Empresa Prueba';
        Empresa.RecordTypeId = '012j0000000i2TcAAI';
        Empresa.Identificacion__c='012j0000';
        insert Empresa;
        
        Account cliente= new Account();
        cliente.lastname='Doanire';
        cliente.firstname='Luis';
        cliente.RecordTypeId = '012j0000000i3wAAAQ';
        cliente.Identificacion__c='00000000000000';
        cliente.Tipo_Identificacion__c='Cedula de identidad';
        cliente.Sexo__c='Masculino';
        cliente.CurrencyIsoCode = 'HNL';
        cliente.Estado_Civil__pc='Soltero';
        insert cliente;
        
        Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;
        
        //VOLUNTARIAS
        Cuentas__C cuentaColectiva= new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='00000';
        cuentacolectiva.Cliente__c=empresa.id;
        cuentacolectiva.Producto__c=producto.id;
        insert cuentacolectiva;
        
        Cuentas__C cuenta= new Cuentas__C();
        cuenta.CurrencyIsoCode='HNL';
        cuenta.Codigo__c='51600';
        cuenta.Cliente__c=Cliente.id;
        cuenta.Cuenta_colectiva2__c=cuentaColectiva.id;
        cuenta.Producto__c=producto.id;
        insert cuenta;
        
        
        Planilla__C planilla=new Planilla__C();
        planilla.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla.Empresa2__c=empresa.id;
        planilla.mes_aporte__c = '1';
        planilla.Fecha__c=date.today();
        planilla.Tasa_compra__c = 1;
        insert planilla;     
        
        contenido_planilla__C contenido=new contenido_planilla__C();
        contenido.empleado2__C=cliente.id;
        contenido.Salario__c=3254;
        contenido.Planilla__c=planilla.id;
        Contenido.Aporte_Empleado_Extraordinario__c  = 21;
        Contenido.Aporte_Patrono_Extraordinario__c  = 32;
        contenido.reserva_laboral__c = 21;
        contenido.Aporte_Patrono_obligatorio__c = 32;
        Contenido.Aporte_Seguro_de_Vida__c = 32;
        insert contenido;
        
        Cuenta_planilla__c cuentaPlanilla = new Cuenta_planilla__c ();
        cuentaPlanilla.Codigo_cuenta__c = '51600';
        cuentaPlanilla.Cuenta__c =cuenta.id;
        cuentaPlanilla.Valor_Monto__c = 21.21; 
        cuentaPlanilla.Contenido_Planilla__c=contenido.id; 
        insert cuentaPlanilla;
        
       
        
        
        
        
        aSysdePortalEmpresarial.CompraVentaDolares('USD', 32.32, 'Prueba');
        aSysdePortalEmpresarial.fechaCierreSysde();
        list<string> listIdentidades = new list<string>();
        listIdentidades.add('00000000000000');
        aSysdePortalEmpresarial.agregarPersonaPlanilla(listIdentidades);
        
        Tasa_De_Cambio__c tasac= new Tasa_De_Cambio__c();
        insert tasac;
        
        aSysdePortalEmpresarial.traertasacambio();
        asysdePortalEmpresarial.ConsultalAportesPatronales(listIdentidades, empresa.id);
        
        set<Id> listEnviar = new set<Id>();   
        listEnviar.add(planilla.id);
        aSysdePortalEmpresarial.cerrarPlanilla(listEnviar);
        aSysdePortalEmpresarial.EnviarAportesEmpleados('SF36,0801199411013,33101,51600,51600,1,1800.00,0.00,0,0,3000.00,0.00,0.00::::', 1, datetime.now(), planilla.id,'fd','fd');
        aSysdePortalEmpresarial.Afiliacionsysde('1', '0801199411013', '', '', '', '', '', '', 21.21, '00000', '00000','00000', '00000', '00000', '00000');
        aSysdePortalEmpresarial.VerificacionEmpleados('','');
        aSysdePortalEmpresarial.Afiliacionsysdemasiva('21,0801199411013,21,21,21,12,2,12,21,21,2121,21,21,21,21,2,21,21,21:::','', 1, 'Prueba');
        //aSysdePortalEmpresarial.fechaCierreSysde();
        /*aSysdePortalEmpresarial.CompraVentaDolares('USD', 32.32, 'Prueba')
        aSysdePortalEmpresarial.fechaCierreSysde();
        aSysdePortalEmpresarial.CompraVentaDolares('USD', 32.32, 'Prueba')
        aSysdePortalEmpresarial.fechaCierreSysde();*/
        
    }

}