force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/UltimoCasoObligatorio__c.field-meta.xml
<CustomField>
    <fullName>UltimoCasoObligatorio__c</fullName>
    <label>Ultimo Caso Obligatorio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/Beneficiario__c.object-meta.xml
<CustomObject>
    <label>Beneficiario</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Numero Beneficiario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiario__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Beneficiarios</relationshipLabel>
    <relationshipName>Beneficiarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/Primer_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Primer_Nombre__c</fullName>
    <label>Primer Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beneficiario__c/fields/TipoBeneficiario__c.field-meta.xml
<CustomField>
    <fullName>TipoBeneficiario__c</fullName>
    <label>Tipo de Beneficiario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Directo</fullName>
            </value>
            <value>
                <fullName>Contingencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Actualizacion_informacion.recordType-meta.xml
<RecordType>
    <fullName>Actualizacion_informacion</fullName>
    <active>true</active>
    <businessProcess>Aumento o Disminución de Aportes</businessProcess>
    <label>Actualización de información</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Monto_aporte__c.field-meta.xml
<CustomField>
    <fullName>Monto_aporte__c</fullName>
    <label>Monto de aporte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Subproducto__c.field-meta.xml
<CustomField>
    <fullName>Subproducto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subproducto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>equals</operation>
            <valueField>Subproducto__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subproducto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/Subproducto__c.object-meta.xml
<CustomObject>
    <label>Subproducto</label>
    <nameField>
        <label>Nombre de Subproducto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subproductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subproducto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subproducto__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Subproductos</relationshipLabel>
    <relationshipName>Subproductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ControladorBeneficiariosTest.cls
@isTest
public class ControladorBeneficiariosTest {

     @testSetup 
    static void setupMethod() {
        Account cliente = new Account();
        cliente.Name='Luis Donaire';
        cliente.Identificacion__c='0709199300155';
        cliente.UltimoCasoObligatorio__c = date.today();
        insert cliente;
        
        Producto__C producto = new Producto__C();
        producto.Codigo__c='qwqw';
        producto.name='Prueba';
        insert producto;
        
        Subproducto__c  subProducto = new Subproducto__c ();
        subProducto.Name='Test';
        subProducto.Codigo__c='3434';
        subProducto.Producto__c = producto.id;
        insert subProducto;
        
        Cuentas__C cuenta = new cuentas__C();
        cuenta.codigo__C='0000';
        cuenta.Cliente__c = cliente.id;
        cuenta.Subproducto__c = subProducto.id;
        cuenta.name='test';
        cuenta.Monto_aporte__c = 100;
        cuenta.Forma_Aportacion__c='TA';
        insert cuenta;
        
        Beneficiario__c b = new Beneficiario__c();
        b.Cuenta__c = cuenta.Id;
        b.Id_Externo__c = 12321;
        b.Primer_Nombre__c = 'PN';
        b.Primer_Apellido__c = 'PA';
        b.TipoBeneficiario__c = 'Directo';
        insert b;
        
        b = new Beneficiario__c();
        b.Cuenta__c = cuenta.Id;
        b.Id_Externo__c = 123221;
        b.Primer_Nombre__c = 'PN';
        b.Primer_Apellido__c = 'PA';
        b.TipoBeneficiario__c = 'Contingencia';
        insert b;
        
	}
    
     static testMethod void ControladorBeneficiarios(){
        
        Account acc = [Select Id from Account];
         
         Case caso = new Case();
         caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Actualizacion_informacion').getRecordTypeId();
         caso.Status = 'Nuevo';
         caso.type = 'Solicitud de Gestión';
         caso.Origin = 'Web';
         caso.Priority = 'Media';
         caso.AccountId = acc.Id;
         insert caso;
         
         ControladorBeneficiarios.ResultWrapper controlador = ControladorBeneficiarios.getBeneficiarios(caso.Id, true);
         ControladorBeneficiarios.insertarBeneficiarios(caso.Id, JSON.serialize(controlador));
         ControladorBeneficiarios.getBeneficiarios(acc.Id, false);
         ControladorBeneficiarios.validacionCamposBeneficiario(controlador.listBeneficiarios);
        
    }
   
   
}