force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PAPCE__c.field-meta.xml
<CustomField>
    <fullName>PAPCE__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Empleador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Empleador</inlineHelpText>
    <label>% Pilar Complementario Patrono</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAPCT__c.field-meta.xml
<CustomField>
    <fullName>PAPCT__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Trabajador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Trabajador</inlineHelpText>
    <label>% Pilar Complementario Trabajador</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_IVM__c</fullName>
    <label>Porc Apor SSoc Empleado IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_Mater__c</fullName>
    <label>Porc Apor SSoc Empleado Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_IVM__c</fullName>
    <label>Porc Apor SSoc Empleador IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_Mater__c</fullName>
    <label>Porc Apor SSoc Empleador Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_Aportaciones_Reserva_Labor__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_Aportaciones_Reserva_Labor__c</fullName>
    <label>Porcentaje de Aportaciones Reserva Labor</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Riesgo_Profecional_Patronal__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_Profecional_Patronal__c</fullName>
    <label>Riesgo Profesional Patronal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Pilar_Complementario__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Pilar_Complementario__c</fullName>
    <label>Salario Base Pilar Complementario</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Reserva_Laboral__c</fullName>
    <label>Techo Reserva Laboral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social__c</fullName>
    <label>Salario Base Seguro Social IVM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_Mater__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_Mater__c</fullName>
    <label>Salario Base Seguro Social Mater</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_RP__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_RP__c</fullName>
    <description>Salario Base Seguro Social Riesgo Profecional</description>
    <inlineHelpText>Salario Base Seguro Social Riesgo Profecional</inlineHelpText>
    <label>Salario Base Seguro Social RP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>MASCULINO</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>FEMENINO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Identificacion__c</fullName>
    <label>Tipo Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>CARNET DE RESIDENTE</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>CEDULA DE IDENTIDAD</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>RTN</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/Contenido_Planilla__c.object-meta.xml
<CustomObject>
    <label>Contenido Planilla</label>
    <nameField>
        <displayFormat>CPL-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contenidos Planilla</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contenido_Planilla__c/fields/Planilla__c.field-meta.xml
<CustomField>
    <fullName>Planilla__c</fullName>
    <label>Planilla</label>
    <referenceTo>Planilla__c</referenceTo>
    <relationshipLabel>Contenidos Planilla</relationshipLabel>
    <relationshipName>Contenidos_Planilla</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contenido_Planilla__c/fields/Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Reserva_Laboral__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Reserva Laboral</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cuenta_planilla__c/Cuenta_planilla__c.object-meta.xml
<CustomObject>
    <label>Cuenta de planilla</label>
    <nameField>
        <displayFormat>CUP-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuentas de planilla</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_planilla__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas de planilla</relationshipLabel>
    <relationshipName>Cuentas_de_planilla</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Cuenta_colectiva2__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_colectiva2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta colectiva</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cuentas__c.Colectiva__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Tipo_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cuenta__c</fullName>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Cuenta bancaria</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Cuenta de pensiones</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuentas_Colectivas__c/Cuentas_Colectivas__c.object-meta.xml
<CustomObject>
    <label>Cuentas Colectivas</label>
    <nameField>
        <label>Nombre de Cuentas Colectivas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas Colectivas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas_Colectivas__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Codigo</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cuentas_Colectivas__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas Colectivas</relationshipLabel>
    <relationshipName>Cuentas_Colectivas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuentas_Colectivas__c/fields/Tipo_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Cuenta__c</fullName>
    <label>Tipo Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voluntarias</fullName>
            </value>
            <value>
                <fullName>Censatías</fullName>
            </value>
            <value>
                <fullName>Pilar Complementario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empresa_x_Empleado__c/Empresa_x_Empleado__c.object-meta.xml
<CustomObject>
    <label>Empleado por Empresa</label>
    <nameField>
        <displayFormat>EE-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empleado por Empresa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empresa_x_Empleado__c/fields/Activo_Nueva_Planilla__c.field-meta.xml
<CustomField>
    <fullName>Activo_Nueva_Planilla__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo Nueva Planilla</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empresa_x_Empleado__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Empleado_X_Empresa1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Planilla__c/Planilla__c.object-meta.xml
<CustomObject>
    <label>Planilla</label>
    <nameField>
        <displayFormat>PLA-{0000000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Planilla__c/fields/Empresa2__c.field-meta.xml
<CustomField>
    <fullName>Empresa2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planillas</relationshipLabel>
    <relationshipName>Planillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestcontroladorPlanillasEnviadas.cls
@isTest
public class TestcontroladorPlanillasEnviadas {
    static testmethod void Colavoradore(){
        Account Empresa= new Account();
        Empresa.Name='Empresa Prueba';
        Empresa.RecordTypeId = '012j0000000i2TcAAI';
        Empresa.Identificacion__c = '012j0000';
        Empresa.Salario_Base_Pilar_Complementario__c=10000;
        Empresa.Salario_Base_Reserva_Laboral__c=10000;
        Empresa.PAPCT__c=3;
        Empresa.PAPCE__c=3;
        Empresa.Porcentaje_de_Aportaciones_Reserva_Labor__c=4;
        Empresa.Salario_Base_Seguro_Social__c=432;
        Empresa.Porc_Apor_SSoc_Empleador_IVM__c=3;
        Empresa.Porc_Apor_SSoc_Empleado_IVM__c=3;
        Empresa.Salario_Base_Seguro_Social_Mater__c=4;
        Empresa.Porc_Apor_SSoc_Empleador_Mater__c=5;
        Empresa.Porc_Apor_SSoc_Empleado_Mater__c=5;
        Empresa.Salario_Base_Seguro_Social_RP__c=43433;
        Empresa.Riesgo_Profecional_Patronal__c=6;
        insert Empresa;
        
        Account cliente= new Account();
        cliente.lastname='Doanire';
        cliente.firstname='Luis';
        cliente.RecordTypeId = '012j0000000i3wAAAQ';
        cliente.Identificacion__c='00000000000000';
        cliente.Tipo_Identificacion__c='Cedula de identidad';
        cliente.Sexo__c='Masculino';
        cliente.CurrencyIsoCode = 'HNL';
        cliente.Estado_Civil__pc='Soltero';
        insert cliente;
        
        
        Producto__C producto=New Producto__C();
        producto.Codigo__c='01';
        producto.CurrencyIsoCode='HNL';
        insert producto;
        
        //VOLUNTARIAS
        Cuentas__C cuentaColectiva = new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='00000';
        cuentacolectiva.Cliente__c=empresa.id;
        cuentacolectiva.Producto__c=producto.id;
        insert cuentacolectiva;
        
        Cuentas__C cuenta= new Cuentas__C();
        cuenta.CurrencyIsoCode='HNL';
        cuenta.Codigo__c='51600';
        cuenta.Cliente__c=Cliente.id;
        cuenta.Cuenta_colectiva2__c=cuentaColectiva.id;
        cuenta.Producto__c=producto.id;
        insert cuenta;
        
        Cuentas_Colectivas__c Colectiva= new Cuentas_Colectivas__c();
        colectiva.Tipo_Cuenta__c='Voluntarias';
        colectiva.Codigo__c='00000';
        colectiva.Empresa__c=empresa.id;
        insert colectiva;
        
        //Censatías 
        cuentaColectiva= new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='00001';
        cuentacolectiva.Cliente__c=empresa.id;
        cuentacolectiva.Producto__c=producto.id;
        insert cuentacolectiva;
        
        cuenta= new Cuentas__C();
        cuenta.CurrencyIsoCode='HNL';
        cuenta.Codigo__c='51601';
        cuenta.Cliente__c=Cliente.id;
        cuenta.Cuenta_colectiva2__c=cuentaColectiva.id;
        cuenta.Producto__c=producto.id;
        insert cuenta;
        
        Colectiva= new Cuentas_Colectivas__c();
        colectiva.Tipo_Cuenta__c='Censatías';
        colectiva.Codigo__c='00001';
        colectiva.Empresa__c=empresa.id;
        insert colectiva;
        
        
        //Pilar Complementario
        cuentaColectiva= new Cuentas__C();
        cuentacolectiva.CurrencyIsoCode='HNL';
        cuentacolectiva.Codigo__c='00002';
        cuentacolectiva.Cliente__c=empresa.id;
        cuentacolectiva.Producto__c=producto.id;
        insert cuentacolectiva;
        
        cuenta= new Cuentas__C();
        cuenta.CurrencyIsoCode='HNL';
        cuenta.Codigo__c='51602';
        cuenta.Cliente__c=Cliente.id;
        cuenta.Cuenta_colectiva2__c=cuentaColectiva.id;
        cuenta.Producto__c=producto.id;
        insert cuenta;
        
        Colectiva= new Cuentas_Colectivas__c();
        colectiva.Tipo_Cuenta__c='Pilar Complementario';
        colectiva.Codigo__c='00002';
        colectiva.Empresa__c=empresa.id;
        insert colectiva;
        
        empresa_x_empleado__C empleado= new empresa_x_empleado__C();
        empleado.Activo_Nueva_Planilla__c=true;
        empleado.Empresa2__c=empresa.id;
        empleado.Salario__c=20000;
        empleado.Estado__c='Activo';
        empleado.Empleado2__c=cliente.id;
        insert empleado;
        
        Autonumerico_cuentas_Syste__c form = new Autonumerico_cuentas_Syste__c(Id_Formulario_Sysde__c =21);
        insert form;
       
        test.startTest();
        
        Planilla__C planilla=new Planilla__C();
        planilla.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla.Empresa2__c=empresa.id;
        planilla.mes_aporte__c = '1';
        planilla.Fecha__c=date.today();
        planilla.Tasa_compra__c = 1;
        insert planilla;
        
        contenido_planilla__C contenido=new contenido_planilla__C();
        contenido.empleado2__C=cliente.id;
        contenido.Salario__c=3254;
        contenido.Planilla__c=planilla.id;
        Contenido.Aporte_Empleado_Extraordinario__c  = 21;
        Contenido.Aporte_Patrono_Extraordinario__c  = 32;
        contenido.reserva_laboral__c = 21;
        contenido.Aporte_Patrono_obligatorio__c = 32;
        Contenido.Aporte_Seguro_de_Vida__c = 32;
        insert contenido;
        
        Cuenta_planilla__c cuentaPlanilla = new Cuenta_planilla__c ();
        cuentaPlanilla.Codigo_cuenta__c = '51600';
        cuentaPlanilla.Cuenta__c =cuenta.id;
        cuentaPlanilla.Valor_Monto__c = 21.21; 
        cuentaPlanilla.Contenido_Planilla__c=contenido.id; 
        insert cuentaPlanilla;
        
        cuentaPlanilla = new Cuenta_planilla__c ();
        cuentaPlanilla.Codigo_cuenta__c = '51601';
        cuentaPlanilla.Cuenta__c =cuenta.id;
        cuentaPlanilla.Valor_Monto__c = 21.21; 
        cuentaPlanilla.Contenido_Planilla__c=contenido.id; 
        insert cuentaPlanilla;
        
        cuentaPlanilla = new Cuenta_planilla__c ();
        cuentaPlanilla.Codigo_cuenta__c = '51602';
        cuentaPlanilla.Cuenta__c =cuenta.id;
        cuentaPlanilla.Valor_Monto__c = 21.21; 
        cuentaPlanilla.Contenido_Planilla__c=contenido.id; 
        insert cuentaPlanilla;
        
        planilla=new Planilla__C();
        planilla.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla.Empresa2__c=empresa.id;
        planilla.mes_aporte__c = '1';
        planilla.Fecha__c=date.today();
        planilla.Tasa_compra__c = 0;
        insert planilla; 
        
        contenido=new contenido_planilla__C();
        contenido.empleado2__C=cliente.id;
        contenido.Salario__c=3254;
        Contenido.Aporte_Empleado_Extraordinario__c  = 21;
        Contenido.Aporte_Patrono_Extraordinario__c  = 32;
        Contenido.Aporte_Seguro_de_Vida__c = 32;
        contenido.Planilla__c=planilla.id;
        insert contenido;
        
        cuentaPlanilla = new Cuenta_planilla__c ();
        cuentaPlanilla.Codigo_cuenta__c = '51600';
        cuentaPlanilla.Cuenta__c =cuenta.id;
        cuentaPlanilla.Valor_Monto__c = 21.21; 
        cuentaPlanilla.Contenido_Planilla__c=contenido.id; 
        cuentaPlanilla.Valor_Monto_Patrono__c =21;
        insert cuentaPlanilla;
        
        planilla=new Planilla__C();
        planilla.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla.Empresa2__c=empresa.id;
        planilla.mes_aporte__c = '1';
        planilla.Fecha__c=date.today();
        planilla.Tasa_compra__c = 1;
        insert planilla; 
        
        controladorPlanillasEnviadas planillaEnviada = new controladorPlanillasEnviadas();
        planillaEnviada.Id_Planilla = planillaEnviada.planillas[0].id_cambiarSalario;
        planillaEnviada.planillas[0].rezago = 'N';
        planillaEnviada.planillas[0].Planilla_Aprobada = date.today();
        //Rezagos
        planillaEnviada.Num_CodReferencia_Rez = 'FT20prueba4';
        planillaEnviada.CodRefTest = 'FT20prueba4';
        planillaEnviada.num_CodCuenta_Rez = '100110';
        planillaEnviada.Monto_Calculado = '40000';
        planillaEnviada.Monto_Sal = '40000';
        planillaEnviada.Monto = '40000';
        planillaEnviada.Moneda = 'HNL';
        planillaEnviada.Compra_Dolar = 'N';
        //
        planillaEnviada.Aprobarplanilla();
        
        
        planillaEnviada.Id_Planilla =planillaEnviada.planillas[0].id_cambiarSalario;
        planillaEnviada.planillas[0].rezago = 'N';
        planillaEnviada.planillas[0].Planilla_Aprobada = date.today();
        planillaEnviada.Aprobarplanilla();
        
        planillaEnviada.Id_Planilla = planillaEnviada.planillas[0].id_cambiarSalario;
        planillaEnviada.planillas[0].rezago = 'N';
        planillaEnviada.planillas[0].Planilla_Aprobada = date.today();
        planillaEnviada.Denegarplanilla();
        //Nuevo
        Planilla__C planilla2=new Planilla__C();
        planilla2.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla2.Empresa2__c = empresa.id;
        planilla2.mes_aporte__c = '1';
        planilla2.Fecha__c=date.today();
        planilla2.Tasa_compra__c = 1;
        insert planilla2;
        
        contenido_planilla__C contenido2=new contenido_planilla__C();
        contenido2.empleado2__C=cliente.id;
        contenido2.Salario__c=3254;
        contenido2.Planilla__c=planilla.id;
        Contenido2.Aporte_Empleado_Extraordinario__c  = 21;
        Contenido2.Aporte_Patrono_Extraordinario__c  = 32;
        contenido2.reserva_laboral__c = 21;
        contenido2.Aporte_Patrono_obligatorio__c = 32;
        Contenido2.Aporte_Seguro_de_Vida__c = 32;
        insert contenido2;
        
        Cuenta_planilla__c cuentaPlanilla2 = new Cuenta_planilla__c ();
        cuentaPlanilla2.Codigo_cuenta__c = '51600';
        cuentaPlanilla2.Cuenta__c =cuenta.id;
        cuentaPlanilla2.Valor_Monto__c = 21.21; 
        cuentaPlanilla2.Contenido_Planilla__c=contenido2.id; 
        insert cuentaPlanilla2;
        
        cuentaPlanilla2 = new Cuenta_planilla__c ();
        cuentaPlanilla2.Codigo_cuenta__c = '51601';
        cuentaPlanilla2.Cuenta__c =cuenta.id;
        cuentaPlanilla2.Valor_Monto__c = 21.21; 
        cuentaPlanilla2.Contenido_Planilla__c=contenido2.id; 
        insert cuentaPlanilla2;
        
        cuentaPlanilla2 = new Cuenta_planilla__c ();
        cuentaPlanilla2.Codigo_cuenta__c = '51602';
        cuentaPlanilla2.Cuenta__c =cuenta.id;
        cuentaPlanilla2.Valor_Monto__c = 21.21; 
        cuentaPlanilla2.Contenido_Planilla__c=contenido2.id; 
        insert cuentaPlanilla2;
        
        planilla2=new Planilla__C();
        planilla2.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla2.Empresa2__c=empresa.id;
        planilla2.mes_aporte__c = '1';
        planilla2.Fecha__c=date.today();
        planilla2.Tasa_compra__c = 0;
        insert planilla2; 
        
        contenido2=new contenido_planilla__C();
        contenido2.empleado2__C=cliente.id;
        contenido2.Salario__c=3254;
        Contenido2.Aporte_Empleado_Extraordinario__c  = 21;
        Contenido2.Aporte_Patrono_Extraordinario__c  = 32;
        Contenido2.Aporte_Seguro_de_Vida__c = 32;
        contenido2.Planilla__c=planilla2.id;
        insert contenido2;
        
        cuentaPlanilla2 = new Cuenta_planilla__c ();
        cuentaPlanilla2.Codigo_cuenta__c = '51600';
        cuentaPlanilla2.Cuenta__c =cuenta.id;
        cuentaPlanilla2.Valor_Monto__c = 21.21; 
        cuentaPlanilla2.Contenido_Planilla__c=contenido2.id; 
        cuentaPlanilla2.Valor_Monto_Patrono__c =21;
        insert cuentaPlanilla2;
        
        planilla2=new Planilla__C();
        planilla2.Estado2__c='Pendiente Aprobación Ficohsa';
        planilla2.Empresa2__c=empresa.id;
        planilla2.mes_aporte__c = '1';
        planilla2.Fecha__c=date.today();
        planilla2.Tasa_compra__c = 1;
        insert planilla2; 
        
        controladorPlanillasEnviadas planillaEnviada2 = new controladorPlanillasEnviadas();
        planillaEnviada2.Id_Planilla = planillaEnviada2.planillas[0].id_cambiarSalario;
        planillaEnviada2.planillas[0].rezago = 'S';
        planillaEnviada2.planillas[0].Planilla_Aprobada = date.today();
        //Rezagos
        planillaEnviada2.Num_CodReferencia_Rez = 'FT20prueba4';
        planillaEnviada2.CodRefTest = 'FT20prueba4';
        planillaEnviada2.num_CodCuenta_Rez = '100110';
        planillaEnviada2.Monto_Calculado = '40000';
        planillaEnviada2.Monto_Sal = '40000';
        planillaEnviada2.Monto = '40000';
        planillaEnviada2.Moneda = 'HNL';
        planillaEnviada2.Compra_Dolar = 'N';
        //
        planillaEnviada2.Aprobarplanilla();
        //
        planillaEnviada2.Id_Planilla = planillaEnviada2.planillas[1].id_cambiarSalario;
        planillaEnviada2.planillas[1].rezago = 'S';
        planillaEnviada2.planillas[1].Planilla_Aprobada = date.today();
        planillaEnviada2.Aprobarplanilla();
        
        planillaEnviada.id_pantalla = '2';
        planillaEnviada.Controladorbg();
        
        planillaEnviada.id_pantalla = '1';
        planillaEnviada.Controladorbg();
        
        planillaEnviada.cerrar();
        
        
        planillaEnviada.showPopup();
        planillaEnviada.SearchValores();
        planillaEnviada.Aplicar();
        
        test.stopTest();
    }
    
}