force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_Identidad__c.field-meta.xml
<CustomField>
    <fullName>DAU_Identidad__c</fullName>
    <description>Identidad que devuelve el servicio de consulta.</description>
    <inlineHelpText>Identidad que devuelve el servicio de consulta.</inlineHelpText>
    <label>DAU_Identidad</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_llamarSalesforceTarjeta__c.field-meta.xml
<CustomField>
    <fullName>DAU_llamarSalesforceTarjeta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para ejecutar el servicio de Salesforce Tarjeta.</description>
    <inlineHelpText>Bandera para ejecutar el servicio de Salesforce Tarjeta.</inlineHelpText>
    <label>DAU_llamarSalesforceTarjeta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/DAU_Tarjeta_de_Sysde__c.field-meta.xml
<CustomField>
    <fullName>DAU_Tarjeta_de_Sysde__c</fullName>
    <description>Número de tarjeta de devuelve el servicio que consulta a Sysde.</description>
    <inlineHelpText>Número de tarjeta de devuelve el servicio que consulta a Sysde.</inlineHelpText>
    <label>DAU_Tarjeta de Sysde</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Respuesta_desde_Sysde__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_desde_Sysde__c</fullName>
    <label>Respuesta desde Sysde</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <label>Respuesta desde Salesforce Tarjetas</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo_de_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Operacion__c</fullName>
    <label>Tipo de Operación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/businessProcesses/Otros.recordType-meta.xml
<RecordType>
    <fullName>Otros</fullName>
    <active>true</active>
    <businessProcess>Otros</businessProcess>
    <label>Otros</label>
</RecordType>

force-app/main/default/objects/Cuentas__c/Cuentas__c.object-meta.xml
<CustomObject>
    <label>Cuenta</label>
    <nameField>
        <label>Descripción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuentas__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cuentas__c/fields/Forma_Aportacion__c.field-meta.xml
<CustomField>
    <fullName>Forma_Aportacion__c</fullName>
    <label>Forma de Aportación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AH</fullName>
                <label>Cuenta de Ahorro</label>
            </value>
            <value>
                <fullName>CK</fullName>
                <label>Cuenta de Cheques</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Interbanca</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Planilla</label>
            </value>
            <value>
                <fullName>TL</fullName>
                <label>Talonario</label>
            </value>
            <value>
                <fullName>TA</fullName>
                <label>Tarjeta de Credito/Debito</label>
            </value>
            <value>
                <fullName>TAOB</fullName>
                <label>Tarjeta de Crédito/Debito otros Bancos</label>
            </value>
            <value>
                <fullName>MV</fullName>
                <label>Movil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/DAU_Salesforce_Tarjetas__e.object-meta.xml
<CustomObject>
    <label>DAU_Salesforce_Tarjetas</label>
    <pluralLabel>DAU_Salesforce_Tarjetas</pluralLabel>
</CustomObject>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_Borrar_Cuotas_S10__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas_S10__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para borrar las cuotas del saldo 10 en la gestión de Afiliación de débito automático.</description>
    <label>DAU_Borrar Cuotas S10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_Borrar_Cuotas_S18__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas_S18__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera para borrar las cuotas del saldo 18 en la gestión de Afiliación de débito automático.</description>
    <label>DAU_Borrar Cuotas S18</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_EjecutarSYSDE__c.field-meta.xml
<CustomField>
    <fullName>DAU_EjecutarSYSDE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DAU_EjecutarSYSDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_EjecutarSYSDEOper__c.field-meta.xml
<CustomField>
    <fullName>DAU_EjecutarSYSDEOper__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bandera cuando el caso es aprobado desde Operaciones.</description>
    <label>DAU_EjecutarSYSDEOperaciones</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DAU_Salesforce_Tarjetas__e/fields/DAU_IdCaso__c.field-meta.xml
<CustomField>
    <fullName>DAU_IdCaso__c</fullName>
    <label>DAU_IdCaso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/Detalle_caso__c.object-meta.xml
<CustomObject>
    <label>Detalle caso</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Correlativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Cuentas__c</referenceTo>
    <relationshipName>Cuentas_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Borrar_Cuotas__c.field-meta.xml
<CustomField>
    <fullName>DAU_Borrar_Cuotas__c</fullName>
    <label>Borrar Cuotas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>No borrar cuotas</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Borrar cuotas excepto saldo 18</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Borrar cuotas incluyendo saldo 18</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/DAU_Dia_de_pago__c.field-meta.xml
<CustomField>
    <fullName>DAU_Dia_de_pago__c</fullName>
    <label>DAU_Día de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificación</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/N_Cuenta_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>N_Cuenta_Bancaria__c</fullName>
    <label># Cuenta Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detalle_caso__c/fields/Respuesta_SF_Tarjetas__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_SF_Tarjetas__c</fullName>
    <description>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</description>
    <inlineHelpText>Respuesta desde Salesforce tarjeta, Ficohsa o Bac</inlineHelpText>
    <label>Respuesta Otro Sistema</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DAU_TG_LogHelper.cls
public class DAU_TG_LogHelper {
	public static void ProcessLog(List<DAU_Salesforce_Tarjetas__e> st) {
    	Case c = new Case();
        List<Case> caso = new List<Case>();
        try {
        	c = [Select Id,Account.Name,Account.Identificacion__c,DAU_Identidad__c,DAU_aprobacion__c,Status,Tipo_de_Operacion__c,
                 Respuesta_desde_Sysde__c, Respuesta_SF_Tarjetas__c, DAU_llamarSalesforceTarjeta__c, DAU_Tarjeta_de_Sysde__c
                 From case Where Id =: st[0].DAU_IdCaso__c];
            
            List<Detalle_caso__c> detailCase = [Select Id,Caso__c,N_Cuenta_Bancaria__c,DAU_Dia_de_pago__c, DAU_Borrar_Cuotas__c, Cuenta__r.Name, 
                                                Cuenta__r.Forma_Aportacion__c From Detalle_caso__c where Caso__c =: c.Id Limit 1];
            
            if(!detailCase.isEmpty()) {
                //Lllamar al servico de *Salesforce Tarjetas* cuando la forma de aportación de la cuenta es: Tarjeta de Crédito/Debito
                if(detailCase[0].Cuenta__r.Forma_Aportacion__c == 'TA') {
                    if(c.Tipo_de_Operacion__c == 'A4') {
                        if(c.DAU_Tarjeta_de_Sysde__c == Null && c.DAU_Identidad__c == Null) {
                            DAU_BorrarCuotas.ConsultaInfoClienteC(c.Id,detailCase[0].Cuenta__r.Name);
                        } 
                        if(c.DAU_Tarjeta_de_Sysde__c <> Null && c.DAU_Identidad__c == Null) {
                            updateCase.validarIdentidad(c.Id, c.DAU_Tarjeta_de_Sysde__c, c.Account.Identificacion__c);    
                        }
                        if(c.DAU_llamarSalesforceTarjeta__c == false && c.DAU_Identidad__c <> Null) {
                            c.DAU_llamarSalesforceTarjeta__c = true;
                            update c;
                        }
                        //LLamar al servicio que procesa el caso en Sysde 
                        if(st[0].DAU_EjecutarSYSDE__c == true && c.Respuesta_SF_Tarjetas__c <> Null) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                    }
                    
                    if(c.Tipo_de_Operacion__c == 'A6') { 
                        if(c.DAU_Tarjeta_de_Sysde__c == Null && c.DAU_Identidad__c == Null) {
                            DAU_BorrarCuotas.ConsultaInfoClienteC(c.Id,detailCase[0].Cuenta__r.Name);
                        } 
                        if(c.DAU_Tarjeta_de_Sysde__c <> Null && c.DAU_Identidad__c == Null) {
                            updateCase.validarIdentidad(c.Id, c.DAU_Tarjeta_de_Sysde__c, c.Account.Identificacion__c);    
                        }
                        //LLamar al servicio que procesa el caso en Sysde cuando es débito a titular
                        if(st[0].DAU_EjecutarSYSDE__c == true) {
                            System.debug('Entra a cerrar el caso');
                            c.DAU_aprobacion__c = true;
                            c.Status = 'Cerrado';
                            update c;
                        }
                        //Bandera para que el trigger de caso llama al Servio de Salesforce Tarjetas
                        if(c.DAU_llamarSalesforceTarjeta__c == false && c.DAU_Identidad__c <> '') {
                            c.DAU_llamarSalesforceTarjeta__c = true;
                            update c;
                        }
                    }
                    
                    if(c.Tipo_de_Operacion__c == 'A7') {
                        if(c.DAU_Tarjeta_de_Sysde__c == Null && c.DAU_Identidad__c == Null) {
                            DAU_BorrarCuotas.ConsultaInfoClienteC(c.Id,detailCase[0].Cuenta__r.Name);
                        } 
                        if(c.DAU_Tarjeta_de_Sysde__c <> Null && c.DAU_Identidad__c == Null) {
                            updateCase.validarIdentidad(c.Id, c.DAU_Tarjeta_de_Sysde__c, c.Account.Identificacion__c);    
                        }
                        if(c.DAU_llamarSalesforceTarjeta__c == false && c.DAU_Identidad__c <> Null) {
                            c.DAU_llamarSalesforceTarjeta__c = true;
                            update c;
                        }
                        //LLamar al servicio que procesa el caso en Sysde 
                        if(st[0].DAU_EjecutarSYSDE__c == true && c.Respuesta_SF_Tarjetas__c <> Null) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                    }
                    
                    if(c.Tipo_de_Operacion__c == 'A3' || c.Tipo_de_Operacion__c == 'A8') {
                        //Bandera para que el trigger de caso llama al Servio de Salesforce Tarjetas                
                        if(st[0].DAU_EjecutarSYSDE__c == true) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                        
                        //LLamar al servicio que procesa el caso en Sysde cuando es débito a tercero y caso pasa por aprobación de Operaciones
                        if(st[0].DAU_EjecutarSYSDEOper__c == true && st[0].DAU_Borrar_Cuotas_S10__c == false) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                        
                        //Llamar al servicio que borra las cuotas del saldo 10 en el caso de Afiliación de Débito Automático
                        String tipoSaldo = '';
                        if(st[0].DAU_Borrar_Cuotas_S10__c == true) {
                            System.debug('Solo llama al servicio que Borra la cuotas del Saldo 10');
                            tipoSaldo = '10';
                            DAU_BorrarCuotas.aumentoDisminucion(c.Id, tipoSaldo);
                        } 
                        
                        //Llamar al servicio que borra las cuotas del saldo 10 en el caso de Afiliación de Débito Automático
                        if(st[0].DAU_Borrar_Cuotas_S18__c == true) {
                            System.debug('Solo llama al servicio que Borra la cuotas del Saldo 18');
                            tipoSaldo = '18';
                            DAU_BorrarCuotas.aumentoDisminucion2(c.Id, tipoSaldo);
                        } 
                    } 
                //Lllamar al servico de *BAC* cuando la forma de aportación de la cuenta es: Tarjeta de Crédito/Debito otros Bancos	    
                } else if(detailCase[0].Cuenta__r.Forma_Aportacion__c == 'TAOB') {
                	if(c.Tipo_de_Operacion__c == 'A3' || c.Tipo_de_Operacion__c == 'A8') {
                        //Bandera para que el trigger de caso llama al Servio de Salesforce Tarjetas                
                        if(st[0].DAU_EjecutarSYSDE__c == true) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                        
                        //LLamar al servicio que procesa el caso en Sysde cuando es débito a tercero y caso pasa por aprobación de Operaciones
                        if(st[0].DAU_EjecutarSYSDEOper__c == true && st[0].DAU_Borrar_Cuotas_S10__c == false) {
                            aSysdeCallouts.aumentoDisminucion(c.id); 
                        }
                        
                        //Llamar al servicio que borra las cuotas del saldo 10 en el caso de Afiliación de Débito Automático
                        String tipoSaldo = '';
                        if(st[0].DAU_Borrar_Cuotas_S10__c == true) {
                            System.debug('Solo llama al servicio que Borra la cuotas del Saldo 10');
                            tipoSaldo = '10';
                            DAU_BorrarCuotas.aumentoDisminucion(c.Id, tipoSaldo);
                        } 
                        
                        //Llamar al servicio que borra las cuotas del saldo 10 en el caso de Afiliación de Débito Automático
                        if(st[0].DAU_Borrar_Cuotas_S18__c == true) {
                            System.debug('Solo llama al servicio que Borra la cuotas del Saldo 18');
                            tipoSaldo = '18';
                            DAU_BorrarCuotas.aumentoDisminucion2(c.Id, tipoSaldo);
                        } 
                    }    
                }
            }
        } catch(Exception ex) {
        	System.debug('Error: '+ex.getMessage()+'--'+ex.getLineNumber());      
        }
    }
}