force-app/main/default/objects/Account/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <externalId>true</externalId>
    <label>Identificacion</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CerrarCasoJob__c.field-meta.xml
<CustomField>
    <fullName>CerrarCasoJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cerrar Caso con Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hasta__c</fullName>
    <label>Fecha hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Identificacion__c.field-meta.xml
<CustomField>
    <fullName>Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobCerrarCasoTest.cls
@isTest
public class JobCerrarCasoTest {
    
    static testMethod void JobCerrarCaso(){
        Datetime fecha = Datetime.now().addSeconds(15);
        String acron = fecha.second()+' '+fecha.minute()+' '+fecha.hour()+' '+fecha.day()+' '+fecha.month()+' ? '+fecha.year();
        System.schedule('CerrarCasos', acron, new JobCerrarCaso());
        
        Account cliente = new Account();
        cliente.FirstName = 'Luis';
        cliente.LastName='Donaire';
        cliente.Identificacion__c='12345';
        cliente.PersonEmail = 'test@test.com';
        cliente.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Natural').getRecordTypeId();
        
        insert cliente;
        
        Case caso = new case();
        caso.AccountId = cliente.Id;
        caso.Fecha_Desde__c = date.today();
        caso.Fecha_hasta__c = date.today();
        Caso.CerrarCasoJob__c = true;
        insert caso;
        
        JobCerrarCaso a = new JobCerrarCaso();
        a.execute(null);
        
    }

}