force-app/main/default/objects/Account/fields/PAPCE__c.field-meta.xml
<CustomField>
    <fullName>PAPCE__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Empleador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Empleador</inlineHelpText>
    <label>% Pilar Complementario Patrono</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAPCT__c.field-meta.xml
<CustomField>
    <fullName>PAPCT__c</fullName>
    <description>Porcentaje de aportaciones Pilar complementario Trabajador</description>
    <inlineHelpText>Porcentaje de aportaciones Pilar complementario Trabajador</inlineHelpText>
    <label>% Pilar Complementario Trabajador</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_IVM__c</fullName>
    <label>Porc Apor SSoc Empleado IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleado_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_Mater__c</fullName>
    <label>Porc Apor SSoc Empleado Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_IVM__c</fullName>
    <label>Porc Apor SSoc Empleador IVM</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porc_Apor_SSoc_Empleador_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_Mater__c</fullName>
    <label>Porc Apor SSoc Empleador Mater</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_Aportaciones_Reserva_Labor__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_Aportaciones_Reserva_Labor__c</fullName>
    <label>Porcentaje de Aportaciones Reserva Labor</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Riesgo_Profecional_Patronal__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_Profecional_Patronal__c</fullName>
    <label>Riesgo Profesional Patronal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rubro__c.field-meta.xml
<CustomField>
    <fullName>Rubro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rubro</label>
    <referenceTo>Rubro__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Pilar_Complementario__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Pilar_Complementario__c</fullName>
    <label>Salario Base Pilar Complementario</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Reserva_Laboral__c</fullName>
    <label>Techo Reserva Laboral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social__c</fullName>
    <label>Salario Base Seguro Social IVM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_Mater__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_Mater__c</fullName>
    <label>Salario Base Seguro Social Mater</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario_Base_Seguro_Social_RP__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_RP__c</fullName>
    <description>Salario Base Seguro Social Riesgo Profecional</description>
    <inlineHelpText>Salario Base Seguro Social Riesgo Profecional</inlineHelpText>
    <label>Salario Base Seguro Social RP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/Rubro__c.object-meta.xml
<CustomObject>
    <label>Rubro</label>
    <nameField>
        <label>Nombre de Rubro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rubros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rubro__c/fields/PAPCE__c.field-meta.xml
<CustomField>
    <fullName>PAPCE__c</fullName>
    <label>PAPCE</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/PAPCT__c.field-meta.xml
<CustomField>
    <fullName>PAPCT__c</fullName>
    <label>PAPCT</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Porc_Apor_SSoc_Empleado_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_IVM__c</fullName>
    <label>Porc_Apor_SSoc_Empleado_IVM</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Porc_Apor_SSoc_Empleado_Mate__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleado_Mate__c</fullName>
    <label>Porc_Apor_SSoc_Empleado_Mate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Porc_Apor_SSoc_Empleador_IVM__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_IVM__c</fullName>
    <label>Porc_Apor_SSoc_Empleador_IVM</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Porc_Apor_SSoc_Empleador_Mater__c.field-meta.xml
<CustomField>
    <fullName>Porc_Apor_SSoc_Empleador_Mater__c</fullName>
    <label>Porc_Apor_SSoc_Empleador_Mater</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Porcentaje_de_aportaciones_Reserva_Labor__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_aportaciones_Reserva_Labor__c</fullName>
    <label>Porcentaje de aportaciones Reserva Labor</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Riesgo_Profecional_Patronal__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_Profecional_Patronal__c</fullName>
    <label>Riesgo_Profecional_Patronal</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Salario_Base_Pilar_Complementario__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Pilar_Complementario__c</fullName>
    <label>Salario Base Pilar Complementario.</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Salario_Base_Reserva_Laboral__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Reserva_Laboral__c</fullName>
    <label>Salario Base Reserva Laboral.</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Salario_Base_Seguro_Social__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social__c</fullName>
    <label>Salario Base Seguro Social IVM</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Salario_Base_Seguro_Social_Mater__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_Mater__c</fullName>
    <label>Salario Base Seguro Social Mater</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rubro__c/fields/Salario_Base_Seguro_Social_RP__c.field-meta.xml
<CustomField>
    <fullName>Salario_Base_Seguro_Social_RP__c</fullName>
    <description>Salario Base Seguro Social Riesgo Profecional</description>
    <inlineHelpText>Salario Base Seguro Social Riesgo Profecional</inlineHelpText>
    <label>Salario Base Seguro Social RP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/controladorCrearRubro.cls
public class controladorCrearRubro {

   
  
    public List<SelectOption> options {get;set;}
    string nombrerubro;
    public string Nombre_Boton{get;set;}
    public string id_Rubro{get;set;}
    public boolean MostarGuardar {get;set;}
    public boolean MostarActualizar {get;set;}
    public Rubro__c rubro {get;set;}
    
    
    
    public controladorCrearRubro() {
			MostarGuardar=false;
            MostarActualizar=true;
        	Nombre_Boton='Nuevo Rubro';
           rubro=new Rubro__c();
          options=new List<SelectOption>();
        	llenarRubros();
          
     }
    public void llenarRubros()
    {
         list<Rubro__c> rubros = new list<Rubro__C>();
        rubros=[select id, name from rubro__c order by name asc];
        options=new List<SelectOption>();
        for(integer i=0; i<rubros.size(); i++)
        {
            options.add(new SelectOption(rubros[i].id,rubros[i].name));
        }
        if(rubros.size() > 0)
        {
         rubro =[select name,PAPCE__c,PAPCT__c,Porc_Apor_SSoc_Empleado_IVM__c,Porc_Apor_SSoc_Empleado_Mate__c,
                 Salario_Base_Seguro_Social_Mater__c, Salario_Base_Seguro_Social_RP__c,
                   Porc_Apor_SSoc_Empleador_IVM__c,Porc_Apor_SSoc_Empleador_Mater__c,Porcentaje_de_aportaciones_Reserva_Labor__c,
                   Riesgo_Profecional_Patronal__c,Salario_Base_Pilar_Complementario__c,Salario_Base_Reserva_Laboral__c,Salario_Base_Seguro_Social__c
                   from rubro__c where id=:rubros[0].id ];
            nombrerubro=rubro.name;
        }
    }
    
  
    
    public void Guardar() {
        try{
            integer u =[select count() from rubro__c where name=:rubro.name];
            if(u==0 && rubro.name !=null)
            {   
                if(rubro.Salario_Base_Pilar_Complementario__c!=null && rubro.Salario_Base_Reserva_Laboral__c!=null &&
                  rubro.PAPCE__c!=null && rubro.PAPCT__c!=null &&
                  rubro.Porcentaje_de_aportaciones_Reserva_Labor__c!=null && rubro.Salario_Base_Seguro_Social__c!=null &&
                  rubro.Porc_Apor_SSoc_Empleador_IVM__c!=null && rubro.Porc_Apor_SSoc_Empleado_IVM__c!=null &&
                  rubro.Salario_Base_Seguro_Social_Mater__c!=null && rubro.Porc_Apor_SSoc_Empleador_Mater__c!=null &&
                  rubro.Porc_Apor_SSoc_Empleado_Mate__c!=null && rubro.Salario_Base_Seguro_Social_RP__c!=null &&
                  rubro.Riesgo_Profecional_Patronal__c!=null)
                {
                    insert rubro;
                ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'El Rubro se guado exitosamente'));
                 Nombre_Boton='Nuevo Rubro';
                Rubro = new Rubro__c();
                llenarRubros();
                MostarActualizar=true;
                MostarGuardar=false;
                
                }
                else
                {
                     ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'Faltan campos obligatorios')); 
                    
                }
                
                
            }
            else
            {
                 ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'Ya existe un rubro con este nombre')); 
                
            }
           }
        Catch(Exception ex)
        {
            
        }
   }
    public Pagereference regresar()
    {
        return new PageReference('/apex/vfConfigPortalPlanillas');
    }
    public VOid crearRubro()
    {
        rubro = new Rubro__c();
        if(Nombre_Boton=='Cancelar')
        {
            Nombre_Boton='Nuevo Rubro';
            llenarRubros();
            MostarActualizar=true;
            MostarGuardar=false;
        }
        else
        {
            MostarActualizar=false;
            MostarGuardar=true;
            options=new List<SelectOption>();
            options.add(new SelectOption('sqw','--Ninguno--'));
            Nombre_Boton='Cancelar';
        }
    }
    
    
    
    public void Modificar() {
        try{
             
            
                if(rubro.Salario_Base_Pilar_Complementario__c!=null && rubro.Salario_Base_Reserva_Laboral__c!=null &&
                  rubro.PAPCE__c!=null && rubro.PAPCT__c!=null &&
                  rubro.Porcentaje_de_aportaciones_Reserva_Labor__c!=null && rubro.Salario_Base_Seguro_Social__c!=null &&
                  rubro.Porc_Apor_SSoc_Empleador_IVM__c!=null && rubro.Porc_Apor_SSoc_Empleado_IVM__c!=null &&
                  rubro.Salario_Base_Seguro_Social_Mater__c!=null && rubro.Porc_Apor_SSoc_Empleador_Mater__c!=null &&
                  rubro.Porc_Apor_SSoc_Empleado_Mate__c!=null && rubro.Salario_Base_Seguro_Social_RP__c!=null &&
                  rubro.Riesgo_Profecional_Patronal__c!=null)
                {
               		 if(nombrerubro == rubro.name )
            {
                Rubro__c rubroviejo=new Rubro__c();            
				rubroviejo=[select PAPCE__c, PAPCT__c, Porc_Apor_SSoc_Empleado_IVM__c, Porc_Apor_SSoc_Empleado_Mate__c, 
                            Porc_Apor_SSoc_Empleador_Mater__c, Porcentaje_de_aportaciones_Reserva_Labor__c, 
                            Porc_Apor_SSoc_Empleador_IVM__C, Riesgo_Profecional_Patronal__c, 
                            Salario_Base_Pilar_Complementario__c, Salario_Base_Reserva_Laboral__c, 
                            Salario_Base_Seguro_Social__c, Salario_Base_Seguro_Social_Mater__c,
                            Salario_Base_Seguro_Social_RP__c 
                            from rubro__C where id=:id_rubro];          
            	rubro.id=id_rubro;
                update rubro;
            list<Account> Empresas =new List<Account>();
            empresas=[select id, PAPCE__c, PAPCT__c, Porc_Apor_SSoc_Empleado_IVM__c, Porc_Apor_SSoc_Empleado_Mater__c, 
                      Porc_Apor_SSoc_Empleador_Mater__c, Porcentaje_de_aportaciones_Reserva_Labor__c, 
                      Porc_Apor_SSoc_Empleador_IVM__C, Riesgo_Profecional_Patronal__c, 
                      Salario_Base_Pilar_Complementario__c, Salario_Base_Reserva_Laboral__c, 
                      Salario_Base_Seguro_Social__c,Salario_Base_Seguro_Social_Mater__c,
                      Salario_Base_Seguro_Social_RP__c 
                      from Account where rubro__C=:id_rubro];
            for(Integer i=0; i<empresas.size(); i++)
            {
                if(empresas[i].PAPCE__c==rubroviejo.PAPCE__c)
                {
                    empresas[i].PAPCE__c=rubro.PAPCE__c;
                }
                if(empresas[i].PAPCT__c==rubroviejo.PAPCT__c)
                {
                    empresas[i].PAPCT__c=rubro.PAPCT__c;
                }
                if(empresas[i].Porc_Apor_SSoc_Empleado_IVM__c==rubroviejo.Porc_Apor_SSoc_Empleado_IVM__c)
                {
                    empresas[i].Porc_Apor_SSoc_Empleado_IVM__c=rubro.Porc_Apor_SSoc_Empleado_IVM__c;
                }
                 if(empresas[i].Porc_Apor_SSoc_Empleado_Mater__c==rubroviejo.Porc_Apor_SSoc_Empleado_Mate__C)
                {
                    empresas[i].Porc_Apor_SSoc_Empleado_Mater__c=rubro.Porc_Apor_SSoc_Empleado_Mate__c;
                }
                 if(empresas[i].Porc_Apor_SSoc_Empleador_Mater__c==rubroviejo.Porc_Apor_SSoc_Empleador_Mater__C)
                {
                    empresas[i].Porc_Apor_SSoc_Empleador_Mater__c=rubro.Porc_Apor_SSoc_Empleador_Mater__c;
                }
                if(empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c==rubroviejo.Porcentaje_de_aportaciones_Reserva_Labor__C)
                {
                  empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c=rubro.Porcentaje_de_aportaciones_Reserva_Labor__c;  
                }
                 if(empresas[i].Porc_Apor_SSoc_Empleador_IVM__C==rubroviejo.Porc_Apor_SSoc_Empleador_IVM__C)
                {
                  empresas[i].Porc_Apor_SSoc_Empleador_IVM__C=rubro.Porc_Apor_SSoc_Empleador_IVM__c;
                }
                 if(empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c==rubroviejo.Porcentaje_de_aportaciones_Reserva_Labor__c)
                {
                    empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c=rubro.Porcentaje_de_aportaciones_Reserva_Labor__c;
                }
                 if(empresas[i].Riesgo_Profecional_Patronal__c==rubroviejo.Riesgo_Profecional_Patronal__C)
                {
                   empresas[i].Riesgo_Profecional_Patronal__c=rubro.Riesgo_Profecional_Patronal__c; 
                }
                if(empresas[i].Salario_Base_Pilar_Complementario__c==rubroviejo.Salario_Base_Pilar_Complementario__C)
                {
                    empresas[i].Salario_Base_Pilar_Complementario__c=rubro.Salario_Base_Pilar_Complementario__c;
                }
                if( empresas[i].Salario_Base_Reserva_Laboral__c==rubroviejo.Salario_Base_Reserva_Laboral__C)
                { 
                	empresas[i].Salario_Base_Reserva_Laboral__c=rubro.Salario_Base_Reserva_Laboral__c;
                }
                if(empresas[i].Salario_Base_Seguro_Social__c==rubroviejo.Salario_Base_Seguro_Social__C)
                {
                    empresas[i].Salario_Base_Seguro_Social__c=rubro.Salario_Base_Seguro_Social__c;
                }
                if(empresas[i].Salario_Base_Seguro_Social_Mater__c==rubroviejo.Salario_Base_Seguro_Social_Mater__c)
                {
                      empresas[i].Salario_Base_Seguro_Social_Mater__c=rubro.Salario_Base_Seguro_Social_Mater__c;
               }
               if(empresas[i].Salario_Base_Seguro_Social_RP__c==rubroviejo.Salario_Base_Seguro_Social_RP__c)
               {
                    empresas[i].Salario_Base_Seguro_Social_RP__c=rubro.Salario_Base_Seguro_Social_RP__c;
               }
                
            }
           
                update empresas;
                 ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'El Rubro se actualizo exitosamente')); 
               //Rubro = new Rubro__C(); 
				//llenarRubros();            
            }
           	else
            {
             	 integer u = [select count() from rubro__C where name =:rubro.name and name !=null];
                if(u==0)
                {
                    Rubro__c rubroviejo=new Rubro__c();            
                        rubroviejo=[select PAPCE__c, PAPCT__c, Porc_Apor_SSoc_Empleado_IVM__c, Porc_Apor_SSoc_Empleado_Mate__c, 
                                    Porc_Apor_SSoc_Empleador_Mater__c, Porcentaje_de_aportaciones_Reserva_Labor__c,
                                    Porc_Apor_SSoc_Empleador_IVM__C, Riesgo_Profecional_Patronal__c, 
                                    Salario_Base_Pilar_Complementario__c, Salario_Base_Reserva_Laboral__c,
                                    Salario_Base_Seguro_Social__c,Salario_Base_Seguro_Social_Mater__c,
                      				Salario_Base_Seguro_Social_RP__c  from rubro__C where id=:id_rubro];          
                        rubro.id=id_rubro;
                        update rubro;
                        list<Account> Empresas =new List<Account>();
                        empresas=[select id, PAPCE__c, PAPCT__c, Porc_Apor_SSoc_Empleado_IVM__c, Porc_Apor_SSoc_Empleado_Mater__c, 
                                  Porc_Apor_SSoc_Empleador_Mater__c, Porcentaje_de_aportaciones_Reserva_Labor__c, 
                                  Porc_Apor_SSoc_Empleador_IVM__C, Riesgo_Profecional_Patronal__c, 
                                  Salario_Base_Pilar_Complementario__c, Salario_Base_Reserva_Laboral__c, 
                                  Salario_Base_Seguro_Social__c,Salario_Base_Seguro_Social_Mater__c,
                      			Salario_Base_Seguro_Social_RP__c  from Account where rubro__C=:id_rubro];
                    for(Integer i=0; i<empresas.size(); i++)
                    {
                        if(empresas[i].PAPCE__c==rubroviejo.PAPCE__c)
                        {
                            empresas[i].PAPCE__c=rubro.PAPCE__c;
                        }
                        if(empresas[i].PAPCT__c==rubroviejo.PAPCT__c)
                        {
                            empresas[i].PAPCT__c=rubro.PAPCT__c;
                        }
                        if(empresas[i].Porc_Apor_SSoc_Empleado_IVM__c==rubroviejo.Porc_Apor_SSoc_Empleado_IVM__c)
                        {
                            empresas[i].Porc_Apor_SSoc_Empleado_IVM__c=rubro.Porc_Apor_SSoc_Empleado_IVM__c;
                        }
                         if(empresas[i].Porc_Apor_SSoc_Empleado_Mater__c==rubroviejo.Porc_Apor_SSoc_Empleado_Mate__C)
                        {
                            empresas[i].Porc_Apor_SSoc_Empleado_Mater__c=rubro.Porc_Apor_SSoc_Empleado_Mate__c;
                        }
                         if(empresas[i].Porc_Apor_SSoc_Empleador_Mater__c==rubroviejo.Porc_Apor_SSoc_Empleador_Mater__C)
                        {
                            empresas[i].Porc_Apor_SSoc_Empleador_Mater__c=rubro.Porc_Apor_SSoc_Empleador_Mater__c;
                        }
                        if(empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c==rubroviejo.Porcentaje_de_aportaciones_Reserva_Labor__C)
                        {
                          empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c=rubro.Porcentaje_de_aportaciones_Reserva_Labor__c;  
                        }
                         if(empresas[i].Porc_Apor_SSoc_Empleador_IVM__C==rubroviejo.Porc_Apor_SSoc_Empleador_IVM__C)
                        {
                          empresas[i].Porc_Apor_SSoc_Empleador_IVM__C=rubro.Porc_Apor_SSoc_Empleador_IVM__c;
                        }
                         if(empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c==rubroviejo.Porcentaje_de_aportaciones_Reserva_Labor__c)
                        {
                            empresas[i].Porcentaje_de_aportaciones_Reserva_Labor__c=rubro.Porcentaje_de_aportaciones_Reserva_Labor__c;
                        }
                         if(empresas[i].Riesgo_Profecional_Patronal__c==rubroviejo.Riesgo_Profecional_Patronal__C)
                        {
                           empresas[i].Riesgo_Profecional_Patronal__c=rubro.Riesgo_Profecional_Patronal__c; 
                        }
                        if(empresas[i].Salario_Base_Pilar_Complementario__c==rubroviejo.Salario_Base_Pilar_Complementario__C)
                        {
                            empresas[i].Salario_Base_Pilar_Complementario__c=rubro.Salario_Base_Pilar_Complementario__c;
                        }
                        if( empresas[i].Salario_Base_Reserva_Laboral__c==rubroviejo.Salario_Base_Reserva_Laboral__C)
                        { 
                            empresas[i].Salario_Base_Reserva_Laboral__c=rubro.Salario_Base_Reserva_Laboral__c;
                        }
                        if(empresas[i].Salario_Base_Seguro_Social__c==rubroviejo.Salario_Base_Seguro_Social__C)
                        {
                            empresas[i].Salario_Base_Seguro_Social__c=rubro.Salario_Base_Seguro_Social__c;
                        }
                         if(empresas[i].Salario_Base_Seguro_Social_Mater__c==rubroviejo.Salario_Base_Seguro_Social_Mater__c)
                        {
                            empresas[i].Salario_Base_Seguro_Social_Mater__c=rubro.Salario_Base_Seguro_Social_Mater__c;
                        }
                        if(empresas[i].Salario_Base_Seguro_Social_RP__c==rubroviejo.Salario_Base_Seguro_Social_RP__c)
                        {
                            empresas[i].Salario_Base_Seguro_Social_RP__c=rubro.Salario_Base_Seguro_Social_RP__c;
                        }
                       
                        
                    }
                   
                        update empresas;
                         ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'El Rubro se actualizo exitosamente')); 
                   // Rubro = new Rubro__C(); 
				//llenarRubros();  
                }
                else
                {
                     ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'Ya existe un Rubro con este Nombre')); 
                    
                }
            }     
                }
                else
                {
                   ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.ERROR, 'Faltan campos obligatorios'));  
                }
                
               
            
            	
           }
        Catch(Exception ex)
        {
            
        }
        
        
   }
   
    
	public void LLenardatos()
        {
            try{
            rubro = new Rubro__C();
            rubro =[select name,PAPCE__c,PAPCT__c,Porc_Apor_SSoc_Empleado_IVM__c,Porc_Apor_SSoc_Empleado_Mate__c,
                   Porc_Apor_SSoc_Empleador_IVM__c,Porc_Apor_SSoc_Empleador_Mater__c,Porcentaje_de_aportaciones_Reserva_Labor__c,
                   Riesgo_Profecional_Patronal__c,Salario_Base_Pilar_Complementario__c,Salario_Base_Reserva_Laboral__c,Salario_Base_Seguro_Social__c,
                    Salario_Base_Seguro_Social_MAter__c,Salario_Base_Seguro_Social_RP__c
                   from rubro__c where id=:id_rubro];
             	nombrerubro=rubro.name;
            }
            Catch(Exception ex)
            {
                
            }
        }    
    
    
    
    
    
    
    
}