force-app/main/default/objects/Bitacora_Conciliacion__c/Bitacora_Conciliacion__c.object-meta.xml
<CustomObject>
    <description>Objeto en la cual se guardara toda la información que realizaran los usuario en el sistema de conciliación.</description>
    <label>Bitacora Conciliacion</label>
    <nameField>
        <label>Nombre de Bitacora Conciliacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bitacora Conciliaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bitacora_Conciliacion__c/fields/Actividades__c.field-meta.xml
<CustomField>
    <fullName>Actividades__c</fullName>
    <label>Actividades</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bitacora_Conciliacion__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <label>Evento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bitacora_Conciliacion__c/fields/Pantalla__c.field-meta.xml
<CustomField>
    <fullName>Pantalla__c</fullName>
    <label>Pantalla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bitacora_Conciliacion__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <label>Usuario</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/Pantalla_Aportes__c.object-meta.xml
<CustomObject>
    <label>Pantalla Aportes</label>
    <nameField>
        <label>Nombre de Pantalla Aportes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pantalla Aportess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Aplica_Comision_SI__c.field-meta.xml
<CustomField>
    <fullName>Aplica_Comision_SI__c</fullName>
    <label>Aplica Comision SI</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Comprobante_imagen__c.field-meta.xml
<CustomField>
    <fullName>Comprobante_imagen__c</fullName>
    <label>Comprobante imagen</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>cuenta</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Estado_Aporte__c.field-meta.xml
<CustomField>
    <fullName>Estado_Aporte__c</fullName>
    <description>El estado es &apos;A&apos;  o &apos;D&apos; A = &apos;Aprobada&apos;  D = &apos;Denegada&apos;</description>
    <label>Estado Aporte</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Fecha_Deposito__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Deposito__c</fullName>
    <label>Fecha Deposito</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Monto_Deposito__c.field-meta.xml
<CustomField>
    <fullName>Monto_Deposito__c</fullName>
    <label>Monto Deposito</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/No_Aplica_Comision__c.field-meta.xml
<CustomField>
    <fullName>No_Aplica_Comision__c</fullName>
    <label>No Aplica Comisión</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Numero_Correlativo__c.field-meta.xml
<CustomField>
    <fullName>Numero_Correlativo__c</fullName>
    <displayFormat>A-{00000000}</displayFormat>
    <label>Numero Correlativo</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/Tipo_Moneda__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Moneda__c</fullName>
    <label>Tipo Moneda</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pantalla_Aportes__c/fields/TIPO_SALDO__c.field-meta.xml
<CustomField>
    <fullName>TIPO_SALDO__c</fullName>
    <label>TIPO SALDO</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ControllerLoginAfiliados.cls
public class ControllerLoginAfiliados {
    
    public String Contrasena { get; set; }
    public String usuario { get; set; }
    public boolean ActivarModal { get; set; }
    public string Cambiousuario {get; set;}
    public Usuarios_de_Pantallas__c Cambiopass {get; set;}
    public string pagina{get;set;}
    public static string UsuarioJuridico {get;set;}
    public static string UsuarioNatural {get;set;}
    public boolean mostrarlogin { get; set; }
    public boolean Mostrarhome { get; set; }
    public static string SMS{get;set;}
    public static string ClienteN {get;set;}
    public String usuarioPrueba{ get; set; }
    public static string EnvioUser {get;set;}
    public integer anio{ get; set; }
    
    public ControllerLoginAfiliados (){
        //usuario = '';
        //contrasena = '';
        salir();
        Desactivartab();
        mostrarlogin=true;
        mostrarhome=false;
        anio = date.today().year();
        
    } 
    
    //activar modal
    public void olvide()
    {
        ActivarModal=true;        
    }
    public void salir()
    {
        ActivarModal=false;
    }
    
    public void EnvioSaldo()
    {
        Desactivartab();
        pagina = 'vfEnvioEstadosCuenta?hytrd='+usuario;
        SMS = 'slds-is-active';     
    }
    public void UsuarioJuridico()
    {
        Desactivartab();
        pagina = 'VFPantallaJuridicos';
        UsuarioJuridico = 'slds-is-active';         
    }
    
    public void crearUsuarioNat()
    {
        Desactivartab();
        pagina = 'VFPantallaConciliacion_Aportes?hytrd='+usuario;
        UsuarioNatural = 'slds-is-active';     
    }
    
    public void ListaVF()
    {
        Desactivartab();
        pagina = 'VFPantallaConciliacion_Aportes?hytrd='+usuario;
        
    }
    
    public static void Desactivartab()
    {
        
        UsuarioJuridico='';
        UsuarioNatural='';
        ClienteN = '';
    }
    public void cerrar(){
        mostrarlogin=true;
        mostrarhome=false;
        pagina = '';
    }
    
    public void ClienteNatural()
    {
        Desactivartab();
        usuario =  ApexPages.currentPage().getParameters().get('usuario');
        pagina = 'VFPantallaClienteProducto?hytrd='+usuario;
        ClienteN = 'slds-is-active';     
    }
    
    Public void cambiarclave()
    {
        try {
            
            Usuarios_de_Pantallas__c user = [Select Email__c,name,id 
                                             From Usuarios_de_Pantallas__c 
                                             Where Usuario__c=:Cambiousuario];
            
            string contra = '';
            integer o;
            List<Messaging.SingleEmailMessage> MessageList = new List<Messaging.SingleEmailMessage>();
            for(integer i=0; i<15; i++)
            {
                o=Math.round(Math.random() * 15);
                if(o==0){contra+='w';}
                if(o==4){contra+='A';}
                if(o==11){contra+='d';}
                if(o==12){contra+='H';}
                if(o==8){contra+='m';}
                if(o==2){contra+='B';}
                if(o==10){contra+='L';}
                if(o==1 || o==3 || o==5 || o==6 || o==7 || 0==9 ||o==13 || o==14 || 0==15){contra+=string.valueOf(o);}
            }
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
            mail.setToAddresses(new String[] {User.Email__c});
            system.debug('Correo: '+User.Email__c);
            mail.setSenderDisplayName('FICOHSA PENSIONES Y CESANTIAS');
            mail.setSubject('Pantallas Afiliados');
            mail.setPlainTextBody('Estimad@ ' + User.Name +'.\n\n Hemos recibido una solicitud para el cambio de tu contraseña del Pantallas de Afiliados. \n' +
                                  +'\n Puedes ingresar al siguiente link para cambiar tu contraseña. link: '+ claseUtil.urlSysde('Site_pantallas')+'vfCambioPasswordPantallasAfi \n'+
                                  'favor escríbenos a ficohsapensiones@ficohsa.com.\n\nFicohsa Pensiones y Cesantías\n www.ficohsa.com. \n2275-2424');
            MessageList.add(mail);  
            system.debug(mail);
            Messaging.sendEmail(MessageList); 
            user.Contrase_a__c=contra;
            update user;               
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'¡Se ha enviado un correo electrónico al usuario!'));
            
        }
        catch(exception ex)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'¡Usuario no encontrado!'+ ex.getMessage()));       
        }
    }
    
    
    public pageReference sesionIniciada(){
        try{
            Usuarios_de_Pantallas__c usuario = [Select Contrase_a__c, Usuarios_de_Pantallas__c.Name, Activo__c
                                                From Usuarios_de_Pantallas__c
                                                Where Usuario__c =: usuario Limit 1];
            
            if(usuario.Contrase_a__c == Contrasena){
                if(usuario.Activo__c){
                    
                    
                    mostrarlogin=false;
                    mostrarhome=true;
                    llenarCuentasDesdeSysde();
                    llenarPantallasDesdeSysde();
                    bitaco();
                    
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Usuario no activo.'));    
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Usuario o Contraseña no válidos.')); 
            }
        }Catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Usuario o Contraseña no válidos.'));   
        }
        return null;
    }
    
    //Traer Lista
    
    public list<controllerApiClienteNatural.classRespuestaAportesCuenta> resultado {get;set;}
    Public list<string> Numcuentas {get; set;}
    public string CuentaPrueba {get; set;}
    
    public list<Pantalla_Aportes__c> McontenidoAporte{get;set;}
    
    
    Public void llenarCuentasDesdeSysde(){
        try{
            /*
CuentaPrueba = '58623';
resultado = new list<controllerApiClienteNatural.classRespuestaAportesCuenta>();                    
resultado =  controllerApiClienteNatural.ConsultalAportesPatronales(CuentaPrueba);  
if(resultado.size()>0)
{
Numcuentas= new list<string>();
for(integer j=0; j<resultado.size(); j++)
{
for(integer i=0; i<resultado[j].cuentas.size(); i++)
{
Numcuentas.add(resultado[j].cuentas[i].cuenta);
}
}

}
*/
            
            McontenidoAporte =[ select cuenta__c,Nombre_Completo__c,Tipo_Moneda__c,Fecha_Deposito__c,Monto_Deposito__c,TIPO_SALDO__c ,
                               Forma_de_Pago__c,Codigo_Referencia__c,Aplica_Comision_SI__c, Descripcion__c,
                               No_Aplica_Comision__c,Comprobante_imagen__c, Numero_Correlativo__c, Estado_Aporte__c
                               from Pantalla_Aportes__c order where Estado_Aporte__c = ''];
            
            
            
        }Catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error desde SYSDE ' + e.getMessage() ));  
        }
    }
    
    public void bitaco()
    {
        //Insertar en la bitacora 
        
        Bitacora_Conciliacion__c bita1 = new Bitacora_Conciliacion__c ();
        bita1.Actividades__c = 'Inició Sesión en el Sistema';
        bita1.Fecha__c = datetime.now();
        bita1.Pantalla__c = 'VfLoginPantallas';
        bita1.Evento__c = 'Consulta';
        bita1.Usuario__c = string.valueOf(usuario);
        insert bita1;
    }
    
    public  void Mostra()
    {
        resultado2 = new list<controllerApiClienteNatural.classRespuestaMenu>();                    
        resultado2 =  controllerApiClienteNatural.ConsultaPantallas2(usuario);
        
        for(integer j=0; j<resultado2.size(); j++)
        {
            if ( resultado2[j].nombreMetodo == ClienteN)
            {
                pagina = resultado2[j].nombreMetodo + '?hytrd=' + usuario + '&rol='+resultado2[j].rol;
                Desactivartab(); 
                
                //Insertar en la bitacora 
                
                Bitacora_Conciliacion__c bita = new Bitacora_Conciliacion__c ();
                bita.Actividades__c = 'Se ingreso a la pantalla' +':'+ resultado2[j].nombreMetodo ;
                bita.Fecha__c = date.today();
                bita.Pantalla__c = resultado2[j].nombreMetodo;
                bita.Evento__c = 'Consulta';
                bita.Usuario__c = Usuario;
                insert bita;
                
                
            }    
            
            
        }
        
    }
    
    
    //Metodo que trae las pantallas 
    
    public list<controllerApiClienteNatural.classRespuestaMenu> resultado2 {get;set;}
    //Public list<string> Numcuentas {get; set;}
    
    Public void llenarPantallasDesdeSysde()
    {
        try{
            
            resultado2 = new list<controllerApiClienteNatural.classRespuestaMenu>();                    
            resultado2 =  controllerApiClienteNatural.ConsultaPantallas2(usuario);  
            
            system.debug('Resultado2'+ resultado2  );
            system.debug('resultado del rol desde login: '+resultado2[0].rol );
            ApexPages.currentPage().getParameters().put('rol',resultado2[0].rol);
            if(resultado2.size()>0)
            {
                Numcuentas= new list<string>();
                
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Usuario Correctooo.')); 
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Datos menor que 0.')); 
                
            }
        }Catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Error desde SYSDE ' + e.getMessage() ));  
        }
    }
    
    
    //Metodos Nuevos Agregados Luis 01/12/2019
    public void ACI(){
        Desactivartab();
        pagina = 'vfAfiliacionclienteindividual?usuario='+usuario;
    }
    public void ACC(){
        Desactivartab();
        pagina = 'vfAfiliacionescarga?usuario='+usuario;
    }
    public void ACYC(){
        Desactivartab();
        pagina = 'vfAfiliacionclientescargados?usuario='+usuario;
    }
    public void AME(){
        Desactivartab();
        pagina = 'vfAfiliacionmasivaEmpresa?usuario='+usuario;
    }
    public void EKC(){
        Desactivartab();
        pagina = 'vfEntregakitCom?usuario='+usuario;
    }
    public void RSC(){
        Desactivartab();
        pagina = 'vfReporteseguimento?usuario='+usuario;
    }
    
    
    public void RCI(){
        Desactivartab();
        pagina = 'vfReporteCalidadIndividuales?usuario='+usuario;
    }
    
    public void RCC(){
        Desactivartab();
        pagina = 'vfReportecalidad_C_NC_PL?usuario='+usuario+'&idPantalla=C';
    }
    
    public void RCNC(){
        Desactivartab();
        pagina = 'vfReportecalidad_C_NC_PL?usuario='+usuario+'&idPantalla=N';
    }
    
    public void RCP(){
        Desactivartab();
        pagina = 'vfReportecalidad_C_NC_PL?usuario='+usuario+'&idPantalla=P';
    }
    
    public void RCBFH(){
        Desactivartab();
        pagina = 'vfReporteCalidad_bfh_pm_fic?usuario='+usuario+'&idPantalla=BFK';
    }
    
    public void RCPM(){
        Desactivartab();
        pagina = 'vfReporteCalidad_bfh_pm_fic?usuario='+usuario+'&idPantalla=PM';
    }
    
    public void RCFIC(){
        Desactivartab();
        pagina = 'vfReporteCalidad_bfh_pm_fic?usuario='+usuario+'&idPantalla=FC';
    }
    
    public void EKS(){
        Desactivartab();
        pagina = 'vfEntregakitSac?usuario='+usuario;
    }
    
    public void RSS(){
        Desactivartab();
        pagina ='vfReporteseguienteSac?usuario='+usuario;
    }
    
    public void AFC(){
        Desactivartab();
        pagina ='vfAfiliacionficopen?usuario='+usuario;
    }
    
    public void ABFK(){
        Desactivartab();
        pagina ='vfAfiliacionBFH?usuario='+usuario+'&pantalla=BFK';
    }
    
    public void APM(){
        Desactivartab();
        pagina ='vfAfiliacionBFH?usuario='+usuario+'&pantalla=PM';
    }
    public void OxA(){
        Desactivartab();
        pagina ='vfOficialxAsesor?usuario='+usuario; 
    }
    public void OxE(){
        Desactivartab();
        pagina ='vfOficialesXEmpresa?usuario='+usuario;
    }
    
    
    // FIN METODOS NUEVOS
    
    
}