force-app/main/default/objects/ActivacionCuenta__c/ActivacionCuenta__c.object-meta.xml
<CustomObject>
    <description>Son los campos necesarios para realizar una activacion correcta de cuentas.</description>
    <label>ActivacionCuenta</label>
    <nameField>
        <label>Nombre de ActivacionCuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActivacionesCuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivacionCuenta__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <description>Mostrará el asesor relacionado con la cuenta.</description>
    <inlineHelpText>Nombre del asesor</inlineHelpText>
    <label>Asesor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Causa__c.field-meta.xml
<CustomField>
    <fullName>Causa__c</fullName>
    <description>Porque va a cambiar el estado de la cuenta.</description>
    <inlineHelpText>Porque va activar o porque va a inactivar el estado de la cuenta.</inlineHelpText>
    <label>Causa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/CausaNuevo__c.field-meta.xml
<CustomField>
    <fullName>CausaNuevo__c</fullName>
    <description>Causa del estado nuevo de la cuenta.</description>
    <inlineHelpText>Explica el estado nuevo de la cuenta.</inlineHelpText>
    <label>CausaNuevo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <description>Mostrará el nombre del cliente.</description>
    <inlineHelpText>Nombre del cliente.</inlineHelpText>
    <label>Cliente</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <description>Mostrará el nombre de la empresa.</description>
    <inlineHelpText>Nombre de la empresa.</inlineHelpText>
    <label>Empresa</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Tendrá los diferentes estado que va tener el documento.</description>
    <inlineHelpText>Tendrá los diferentes estado que va tener el documento.</inlineHelpText>
    <label>Estado</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/EstadoActual__c.field-meta.xml
<CustomField>
    <fullName>EstadoActual__c</fullName>
    <description>Muestra si el estado de cuenta está activa o inactiva.</description>
    <inlineHelpText>A si está activa y I si está inactiva.</inlineHelpText>
    <label>EstadoActual</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/EstadoNuevo__c.field-meta.xml
<CustomField>
    <fullName>EstadoNuevo__c</fullName>
    <description>El estado nuevo de la cuenta.</description>
    <inlineHelpText>Ver si el estado nuevo está Activo o Inactivo.</inlineHelpText>
    <label>EstadoNuevo</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Fecha_CargaA__c.field-meta.xml
<CustomField>
    <fullName>Fecha_CargaA__c</fullName>
    <label>Fecha_CargaA</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Identificador_CargaA__c.field-meta.xml
<CustomField>
    <fullName>Identificador_CargaA__c</fullName>
    <label>Identificador_CargaA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/NoCuenta__c.field-meta.xml
<CustomField>
    <fullName>NoCuenta__c</fullName>
    <description>El usuario introducira los numeros de cuenta previamente autorizado a activacion.</description>
    <inlineHelpText>Numero de cuenta.</inlineHelpText>
    <label>noCuenta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/noIdentidad__c.field-meta.xml
<CustomField>
    <fullName>noIdentidad__c</fullName>
    <description>Identificación del cliente.</description>
    <inlineHelpText>noIdentidad</inlineHelpText>
    <label>noIdentidad</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Situaci_n__c.field-meta.xml
<CustomField>
    <fullName>Situaci_n__c</fullName>
    <description>Mostrará si los datos cargados están correctos.</description>
    <inlineHelpText>Si sale OK está correcto, si sale NO COINCIDE hay un error.</inlineHelpText>
    <label>Situación</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivacionCuenta__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <label>Usuario</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/testActivaInactivaCtas.cls
@isTest 
public class testActivaInactivaCtas {
static testMethod void ActivaciondeCuentas()
    {
        test.startTest();        
        ActivacionCuenta__c archivo = new ActivacionCuenta__c  (NoCuenta__c='28459', noIdentidad__c='09887665544', Cliente__c='pruebaaa', 
                                                                Empresa__c='empresa prueba', EstadoActual__c='A', Causa__c='PruebaPens', 
                                                                EstadoNuevo__c='A',CausaNuevo__c='Prueba', Situaci_n__c='',
                                                                Usuario__c='hn3456', Estado__c='', Fecha_CargaA__c= string.valueOf(date.today()),Identificador_CargaA__c=4);
       
        insert archivo;
       
              
        String objeto;       
        objeto=ActivaciondeCuentas.llenarObjetos('"prueba"');
        objeto=ActivaciondeCuentas.llenarObjetos('""');
        objeto=ActivaciondeCuentas.llenarObjetos('prueba');
        
        string ags=''; 
	    string encabezado='"NCuenta","Identidad","EstadoActual","CAUSA ACTUAL","Estado.Nuevo","Causa.Nueva"';
        string cuerpo='"28387","08065478909","A","Pensiones","I","Pensiones2"';
        string stringCSV= encabezado +'\n'+ cuerpo;
        classWRetorno2 error = new classWRetorno2();
        error = ActivaciondeCuentas.SUbirInformacion(stringCSV, 'UserPru' ,ags);
        
        String prueba;
        String prueba2;
        String pruebaCSV;
        prueba='"NCuenta","Identidad","EstadoActual","CAUSA ACTUAL","Estado.Nuevo","Causa.Nueva"';//'"No.Cuenta","No.Identidad","Estado Actual","CAUSA ACTUAL","Estado Nuevo","CAUSA NUEVA"';
        prueba2='"28387","08065478909","A","Pensiones","I","Pensiones2"';
        pruebaCSV=prueba+prueba2;
        error = ActivaciondeCuentas.SUbirInformacion(pruebaCSV, 'UserPru', ags);
        
        String prueba3;
        String prueba4;
        String pruebaCSV1;
        prueba='"NCuenta","Identidad","EstadoActual","CAUSA ACTUAL","Estado.Nuevo","Causa.Nueva"';//'"No.Cuenta","No.Identidad","Estado Actual","CAUSA ACTUAL","Estado Nuevo","CAUSA NUEVA"';
        prueba2='"28387","08065478909","A","Pensiones","I","Pensiones2"';
        pruebaCSV1=prueba3+prueba4;
        error = ActivaciondeCuentas.SUbirInformacion(pruebaCSV1, 'UserPru' ,ags);  
                             
               
        ActivaciondeCuentas p = new ActivaciondeCuentas();
        
        p.usuario1= '';
        p.mostrarTabla = false;
        p.mostrarTabla = false;
        p.EnviarDatos =false;
        p.ActivarDatos = false;
        p.Modificar= false;
        p.Cont = 0;
		p.valida =false;
		p.Num_CodReferencia =1;
		p.Num_Cod = 2;    
        p.aprobarM =false;
        p.VerContenido =false;
        p.total =0;
        p.FechaInclusion =date.today();
        p.Motivo ='';
        p.Cambiar=false;
        p.rechazarM1 =false;
        p.VentanaPlanilla =false;
        
        p.rechazoPla();
        p.cambio();
        p.aprobado();
        p.salir();
        p.mtabla();
        
        list<ActivacionCuenta__c> Activacion = new list<ActivacionCuenta__c>();
        list<ActivacionCuenta__c> CambioActiva = new list<ActivacionCuenta__c>();
        p.VerPlanilla();                        
        list<ContenidoActivaciondeCuentas> validaDatos= new list<ContenidoActivaciondeCuentas>();
        list<ActivacionCuenta__c> ModifList = new list<ActivacionCuenta__c>(); 
        Usuarios_de_Pantallas__c InfoUsuario = new Usuarios_de_Pantallas__c ();
        
        p.Limpiar();
        p.ModificarContenido();
        p.ValidarContenido();
        p.VerContenido();
        p.VerPlanillaArchivo();
        p.MostrarVentanaPlanilla();
        p.aprobarPlanilla();
        
        ContenidoActivaciondeCuentas ClaseDatos = new ContenidoActivaciondeCuentas('NoCuenta','NoIdentidad','EstadoActual','Causa','EstadoNuevo','CausaNueva',
                                                                     'Registrador','Autorizador',1, date.today(),'Descripcion');  
        p.paraMotivo();
        
        Api_ActivaciondeCuentas apii = new Api_ActivaciondeCuentas();  
        p.denegarPlanilla();
        
        Api_ActivaciondeCuentas.classRespuestaActivacion A= new Api_ActivaciondeCuentas.classRespuestaActivacion();
        A.Certificado='325';
        A.Mensaje='325';   
        A.nEmpresa ='prueba';
        A.nombreCliente ='Maria';
        A.Asesor= 'Carla Hernandez';
        
        ActivacionCuenta__c carga = new ActivacionCuenta__c (Identificador_CargaA__c = 1);  
        insert carga;
        
        A.ModificarEstado = [select Situaci_n__c, NoCuenta__c, Cliente__c, Empresa__c, Asesor__c                              
                             from ActivacionCuenta__c where Identificador_CargaA__c =: 1]; 
        
        A.sizeResu = 5;
        A.sizeModi = 5;     
        A.IdCarga = 2;  
        
        valResgistroActivaciondeCuentas env = new valResgistroActivaciondeCuentas(validaDatos); 
        Api_ActivaciondeCuentas.actualizaEstadoCausa(env);
        Api_ActivaciondeCuentas.BitacoraDCausaEstado(env); 
		                
        test.stopTest();
    }

}