force-app/main/default/objects/User/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Contrase_a__c.field-meta.xml
<CustomField>
    <fullName>Contrase_a__c</fullName>
    <label>Contraseña</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <externalId>true</externalId>
    <label>Usuario</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/fields/Zona__c.field-meta.xml
<CustomField>
    <fullName>Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Zona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUsuarioNatural.cls
@isTest
public class TestUsuarioNatural 
{
 static testMethod void ControllerUsuarioNatural(){
    test.startTest();
 	ControllerUsuarioNatural natural = new ControllerUsuarioNatural();
    natural.tipoUsuarioNatural = 'N';
    natural.PEP = false;
    natural.AML = false;
    natural.FATCA = false;
    natural.tipoId = '1';
    natural.numeroId = '0801-1993-15869';
    natural.primerNombre = 'MARIA';
    natural.segundoNombre = 'JOSEFA';
    natural.primerApellido = 'MARTINEZ';
    natural.segundoApellido = 'MEJIA';
    natural.fechaNacimiento = null;
    natural.nacionalidad = 'HONDUREÑA';
    natural.telefono = '99456986';
    natural.pais = '074';
    natural.colonia = '000';
    natural.departamento = '000';
    natural.municipio = '000';
    natural.calleDetalle = 'PAYAQUI';
    natural.procedenciaFondos = 'null';
    natural.nivelRiesgo = '2';
    natural.debidaDiligencviaAplicada = '1';
    natural.numeroIdentificacion = '0801-1994-11013';
    natural.numeroCuenta = '51600';
    natural.nombreCompleto = 'null';
     
     
     natural.bloqPep();
     natural.guardar();
     natural.buscar();
     natural.validar();
     natural.limpiar();
     natural.cancelar();
     //natural.mostrarBoton = true;
     //natural.mostrarSiguiente = true;
     //natural.mostrarAnterior = true;
     //natural.siguiente();
     //natural.anterior();
     natural.unblock();
     natural.desUn();
     natural.contrUn();
     natural.mostPop();
     natural.desBtn();
     natural.hidePop();
    // natural.opcionColonia = '';
     
     classUsuarioNatural j =new classUsuarioNatural();
     
     controllerApiUsuarioNatural api = new controllerApiUsuarioNatural();
     
     ControllerLoginAfiliados login = new ControllerLoginAfiliados();
     Usuarios_de_Pantallas__c user = new Usuarios_de_Pantallas__c();
     user.Activo__c = true;
     user.Apellido__c = 'castaneda';
     user.Contrase_a__c = '123';
     user.Email__c = 'luis.castaneda@intellectsystem.net';
     user.Usuario__c = 'kike';
     user.Zona__c = 'Tegucigalpa';
     insert user;
     
     login.Cambiousuario = 'kike'; 
     login.cambiarclave();
     login.usuario = 'walvarado';
     login.Contrasena = '';     
     login.cerrar();
     login.crearUsuarioNat();
     login.olvide();
     login.salir();
     login.sesionIniciada();
     login.UsuarioJuridico();
     login.EnvioSaldo();
     login.ListaVF();
     login.ClienteNatural();
     login.bitaco(); 
     login.Mostra();
     login.llenarPantallasDesdeSysde();
     login.llenarCuentasDesdeSysde();
     login.ACI();
     login.ACC();
     login.ACYC();
     login.AME();
     login.EKC();
     login.RSC();
     login.RCI();
     login.RCC();
     login.RCNC();
     login.RCP();
     login.RCBFH();
     login.RCPM();
     login.RCFIC();
     login.EKS();
     login.RSS();
     login.AFC();
     login.ABFK();
     login.APM();
     login.OxA();
     login.OxE();
     
     controllerLink home = new controllerLink();
     home.UsuarioJuridico();
     home.crearUsuarioNat();     
     
     classListas lista = new classListas();
     lista.numeroId = '0801-1972-05033';
     
     test.stopTest();
 }
}