force-app/main/default/objects/Cambio_de_Fecha__c/Cambio_de_Fecha__c.object-meta.xml
<CustomObject>
    <description>Este objeto es para guardar la información de los aportes que se van actualizar o eliminar, de la pantalla VFpantallacambiofechaaporte y su controlador: Controllercambiofechaaporte.</description>
    <label>Cambio_de_Fecha</label>
    <nameField>
        <label>Nombre de Cambio_de_Fecha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cambio_de_Fechas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cambio_de_Fecha__c/fields/Moneda__c.field-meta.xml
<CustomField>
    <fullName>Moneda__c</fullName>
    <label>Moneda</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cambio_de_Fecha__c/fields/Nombrecliente__c.field-meta.xml
<CustomField>
    <fullName>Nombrecliente__c</fullName>
    <label>Nombrecliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cambio_de_Fecha__c/fields/num_doc__c.field-meta.xml
<CustomField>
    <fullName>num_doc__c</fullName>
    <label>num_doc</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usuarios_de_Pantallas__c/Usuarios_de_Pantallas__c.object-meta.xml
<CustomObject>
    <label>Usuarios de P. Afiliación</label>
    <nameField>
        <label>Nombres</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios de P. Afiliación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testaprobarCambioFechaAporte.cls
@isTest
public class testaprobarCambioFechaAporte {

    static testMethod void Controlleraprobarfechaaporte()
        {
            Controlleraprobarfechaaporte p = new Controlleraprobarfechaaporte();
            Cambio_de_Fecha__c pp = new Cambio_de_Fecha__c();
            Usuarios_de_Pantallas__c ppp = new Usuarios_de_Pantallas__c();
            
            p.codCuenta ='104684';
            p.Usuario = 'hn1234';
            p.fechaporte = date.newInstance(2020, 03, 13);
            p.nombre = 'Prueba132';
            p.pcproducto = '01';
            p.pcsubproducto = '001';
            p.tama = 1;
            p.TipMoneda = null;
            p.tipomoneda = null;
            p.opciones = null;
            p.num_doc = '1';
            p.MuestraTabla = true;
            p.contador= 1;
            p.FCsysde = date.newInstance(2020, 03, 13);
            p.accion = 'Actualizar';
            p.DenegarVentana = true;
            p.Motivo = null;
            p.opcionSubproducto = null;
            p.FCsysde = date.newInstance(2020, 03, 13);
            p.ListData.add(pp);
            p.ListData[0].Nombrecliente__c = p.nombre;
            p.ListData[0].Moneda__c = '1';
            p.ListData[0].num_doc__c = p.num_doc;
            p.correoEmpleado = null;
            p.NombreUsuario = null; 
            p.idEmail = '5654';
        	p.estadEmail = null;
            
            p.BuscaCuentas();
            p.mostrarTabla();
            p.Actualizar();
            p.MostrarImagen();
            p.popSalirImagen();
            p.popDenegarSalir();
            p.Aprobar();
            p.mostrarDenegar();
            p.limpiar();
            p.LimpiarTabla();
            p.Cancelar();
            p.enviar();
            p.Denegar();
            p.EnvioCorreo(); 
            
            
            classfechacambioaporte t = new classfechacambioaporte();
          
            classAcualizaFechaAporte s = new classAcualizaFechaAporte();
             s.numDocumento = 'sdda';
        s.nuevafecha = date.valueOf(dateTime.now());
           
        }
}