force-app/main/default/objects/Vehiculo__c/Vehiculo__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <displayFormat>VH-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehiculos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehiculo__c/fields/Anio__c.field-meta.xml
<CustomField>
    <fullName>Anio__c</fullName>
    <label>Año</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Existencia__c.field-meta.xml
<CustomField>
    <fullName>Existencia__c</fullName>
    <label>Existencia</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehiculo__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClassVehiculo.cls
public class ClassVehiculo {
    
    public List<Vehiculo> listVehiculos {get;set;}
    public Vehiculo vehiculo {get;set;}
     public String vehiculoId {get;set;}
    public Boolean popNV {get;set;}
    
    public ClassVehiculo(){
        vehiculo = new Vehiculo();
        getVehiculos();
        popNV = false;
    }
    
    public void getVehiculos(){
        listVehiculos =  new List<Vehiculo>();
        for(Vehiculo__c item: [Select Name, Marca__c, Precio__c, Modelo__c, Existencia__c, Anio__c from Vehiculo__c]){
            Vehiculo v = new Vehiculo();
            v.id = item.Name;
            v.marca = item.Marca__c;
            v.modelo = item.Modelo__c;
            v.anio = item.Anio__c;
            v.existencia = item.Existencia__c;
            v.precio = item.Precio__c;
            v.idSF = item.id;
            listVehiculos.add(v);
        }
    }
    
     public void popEditar(){
         for(Vehiculo item : listVehiculos){
             if(item.id == vehiculoId){
                  vehiculo = item;
                 popVehiculo();
             }
         }
     }
    
     public void popVehiculo(){
         popNV = !popNV;
     }
    
    public void postVehiculos(){
        Vehiculo__c item = new Vehiculo__c();
        item.Marca__c =  vehiculo.marca;
        item.Modelo__c = vehiculo.modelo;
        item.Anio__c = vehiculo.anio;
        item.Existencia__c = vehiculo.existencia;
        item.Precio__c =  vehiculo.precio;
        insert item;
        vehiculo = new Vehiculo();
        getVehiculos();
        popNV = false;
    }
    
    public void putVehiculos(){
        Vehiculo__c item = new Vehiculo__c();
        item.Marca__c =  vehiculo.marca;
        item.Modelo__c = vehiculo.modelo;
        item.Anio__c = vehiculo.anio;
        item.Existencia__c = vehiculo.existencia;
        item.Precio__c =  vehiculo.precio;
        item.Id =  vehiculo.idSF;
        update item;
        vehiculo = new Vehiculo();
        getVehiculos();
        popNV = false;
    }
    
    public void deleteVehiculos(){
        Vehiculo__c item = new Vehiculo__c();
        item.Id = vehiculoId;
        delete item;
        vehiculo = new Vehiculo();
        getVehiculos();
        popNV = false;
    }
    
    public void getVehiculo(){
        listVehiculos =  new List<Vehiculo>();
        for(Vehiculo__c item: [Select Name, Marca__c, Precio__c, Modelo__c, Existencia__c, Anio__c from Vehiculo__c]){
            Vehiculo v = new Vehiculo();
            v.id = item.Name;
            v.marca = item.Marca__c;
            v.modelo = item.Modelo__c;
            v.anio = item.Anio__c;
            v.existencia = item.Existencia__c;
            v.precio = item.Precio__c;
            listVehiculos.add(v);
        }
    }
    
    public class Vehiculo {
        public String id {get;set;}
        public String idSF {get;set;}
        public String marca {get;set;}
        public String modelo {get;set;}
        public Decimal anio {get;set;}
        public Decimal existencia {get;set;}
        public Decimal precio {get;set;}
    }

}