force-app/main/default/objects/Configuracion_Cobro__mdt/Configuracion_Cobro__mdt.object-meta.xml
<CustomObject>
    <label>Configuracion Cobro y Limites</label>
    <pluralLabel>Configuracion de Cobros</pluralLabel>
</CustomObject>

force-app/main/default/objects/Configuracion_Cobro__mdt/fields/Monto_dolar__c.field-meta.xml
<CustomField>
    <fullName>Monto_dolar__c</fullName>
    <label>Monto dolar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControlerPIntereses.cls
public class ControlerPIntereses {
  /*Variables*/ 
    public string error {get;set;}
    public string Usuario  {get;set;}
    public string enviado {get;set;}
    public date Fechapintereses {get;set;}
   	public boolean mostrarTablaIntereses {get;set;} 
    public List<ClassConsultaInteres> ListPagosIntereses {get;set;}
    public integer tama {get;set;}
    
    public void BuscarIntereses(){
        try{
        ClassConsultaInteres claseEnvio = new ClassConsultaInteres();
        ClassConsultaInteres fcsd = ControllerAPIPagaInteres.BuscaPerIntereses(Fechapintereses);
        system.debug('Respuestaaaaaaaa: '+fcsd);
         ListPagosIntereses = fcsd.ListPagosIntereses;
         tama = ListPagosIntereses.size();
        system.debug('ListaConciliados: '+ ListPagosIntereses);
        
        if(ListPagosIntereses != null){
            mostrarTablaIntereses = true;
            //ListPagosIntereses = fcsd.ListPagosIntereses; 
            
        }else{
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Clientes no Encontrados'));

        }
        }
			catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Errro: ' + e.getMessage()+' LINEA '+E.getLineNumber()));
        }
    }
    
    public void Guardar()
    {        
        try{
          
        error='EL CAMPO FECHA ESTÁ VACÍO';
        enviado='ENVIADO CORRECTAMENTE';
        if(Fechapintereses==null)
        {
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, error)); 
      
        }
       
        else{
            
            ClassPagarIntereses PI = new ClassPagarIntereses();
            
            String queryACH = 'Select Monto__c, Monto_dolar__c From Configuracion_Cobro__mdt Where DeveloperName = '; 
                queryACH += '\'ACH\'';
                Configuracion_Cobro__mdt ACH = dataBase.query(queryACH);
                PI.MontoACH = ACH.Monto__c;
            	PI.MontoACHD = ACH.Monto_dolar__c;
            
            String queryCheque = 'Select Monto__c, Monto_dolar__c From Configuracion_Cobro__mdt Where DeveloperName = '; 
                queryCheque += '\'Cheque\'';
                Configuracion_Cobro__mdt Cheque = dataBase.query(queryCheque);
                PI.MontoCheque = Cheque.Monto__c;
            	PI.MontoChequeD = Cheque.Monto_dolar__c;
                PI.Fechapintereses = Fechapintereses;
            
            string resultado = ControllerAPIPagaInteres.guardarfecha(PI);
    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, resultado));
            
            //Fechapintereses=null;
            system.debug('Hola controlador');
        }
       
    }catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Errro: ' + e.getMessage()+' LINEA '+E.getLineNumber()));
        }

    }
    
}