force-app/main/default/objects/Autonumerico_cuentas_Syste__c/Autonumerico_cuentas_Syste__c.object-meta.xml
<CustomObject>
    <label>Autonumerico cuentas Syste</label>
    <nameField>
        <label>Nombre de Autonumerico cuentas Syste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Autonumerico cuentas Syste</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Autonumerico_cuentas_Syste__c/fields/Contador_EDC__c.field-meta.xml
<CustomField>
    <fullName>Contador_EDC__c</fullName>
    <label>Contador EDC</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correo_estado_cuenta__c/Correo_estado_cuenta__c.object-meta.xml
<CustomObject>
    <label>Correo estado de cuenta</label>
    <nameField>
        <label>Nombre de Correo estado de cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correo estado de cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correo_estado_cuenta__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/batchEnvioEDC.cls
global class batchEnvioEDC implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    
    global batchEnvioEDC(){
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('select Contador_EDC__c, id from Autonumerico_cuentas_Syste__c');
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        for(Sobject s : scope){
            Autonumerico_cuentas_Syste__c c = (Autonumerico_cuentas_Syste__c)s;
            c.Contador_EDC__c ++;
            if([select count() from Correo_estado_cuenta__c where enviado__C = false ] > 0){
                boolean d = EnvioCorreosEDC.enviarCorreos();
            }
            update c;
        }
    } 
    
    global void finish(Database.BatchableContext bc) {
        decimal contador = [select count() from Correo_estado_cuenta__c where enviado__C=false];
        Autonumerico_cuentas_Syste__c c= [select Contador_EDC__c, id from Autonumerico_cuentas_Syste__c limit 1];
        if(contador > 0 && c.Contador_EDC__c <48){ // DESARROLLO
       //if(contador > 0 && c.Contador_EDC__c <100){ // PRODUCCIÓN
            batchEnvioEDC l = new batchEnvioEDC();
            Id batchprocessid = Database.executeBatch(l,1);
        }else {
            c.Contador_EDC__c = 0;
            update c;
        }
    }
}