force-app/main/default/objects/FPC_ErroresEstadosDeCuenta__c/FPC_ErroresEstadosDeCuenta__c.object-meta.xml
<CustomObject>
    <label>Errores Estados De Cuenta</label>
    <nameField>
        <displayFormat>EDC-{000000}</displayFormat>
        <label>Nombre de Errores Estados De Cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errores Estados De Cuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPC_ErroresEstadosDeCuenta__c/fields/FPC_Contacto__c.field-meta.xml
<CustomField>
    <fullName>FPC_Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Errores Estados De Cuentas</relationshipLabel>
    <relationshipName>Errores_Estados_De_Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FPC_ErroresEstadosDeCuenta__c/fields/FPC_Error__c.field-meta.xml
<CustomField>
    <fullName>FPC_Error__c</fullName>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/InformeEDC__c.object-meta.xml
<CustomObject>
    <description>Creado específicamente con el fin de completar un informe que incluya diversos campos que no pueden relacionarse en un reporte estándar.</description>
    <label>Informe EDC</label>
    <nameField>
        <displayFormat>ES-{0000000000}</displayFormat>
        <label>Informe EDC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informe EDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformeEDC__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informe EDC</relationshipLabel>
    <relationshipName>Informe_EDC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/FechaEnvio__c.field-meta.xml
<CustomField>
    <fullName>FechaEnvio__c</fullName>
    <label>Fecha de Envío</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/FechaQueSeAbrio__c.field-meta.xml
<CustomField>
    <fullName>FechaQueSeAbrio__c</fullName>
    <label>Fecha en que se abrió</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/FPC_ErrorEnvio__c.field-meta.xml
<CustomField>
    <fullName>FPC_ErrorEnvio__c</fullName>
    <label>Error de Envío</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/NumeroVecesQueSeAbrio__c.field-meta.xml
<CustomField>
    <fullName>NumeroVecesQueSeAbrio__c</fullName>
    <label>Número de veces que se abrió</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InformeEDC__c/fields/UltimaFechaQueSeabrio__c.field-meta.xml
<CustomField>
    <fullName>UltimaFechaQueSeabrio__c</fullName>
    <label>Última Fecha en que se abrió</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchDatosInformeEDC.cls
global without sharing class BatchDatosInformeEDC implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    public DateTime desde;
    public DateTime hasta;
    
    global BatchDatosInformeEDC(DateTime desde, DateTime hasta){
        this.desde = desde;
        this.hasta = hasta;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select AccountId,Id, EmailBouncedReason, IsEmailBounced,'+
                                        ' (Select Id, CreatedDate,FirstOpenDate,LastOpenDate,TimesOpened,Task.WhatId  '+
                                        ' From EmailStatuses '+
                                        ' where Task.Subject = \'Correo electrónico: Estado de cuenta.\' and Task.WhatId = null),' +
                                        ' (Select Id,CreatedDate,FPC_Error__c from Errores_Estados_De_Cuentas__r)'+
                                        ' From Contact  ');
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<InformeEDC__c > listInformeEDC  = new List<InformeEDC__c >();
        List<String> listTareas = new  List<String>();
        for(Object s: scope){
            Contact contacto = (Contact) s;
            List<EmailStatus> ES = new List<EmailStatus>();
            ES = !test.isRunningTest() ?  contacto.EmailStatuses : getEmailStatus();
            for(EmailStatus emstat : ES){
                listTareas.add(emstat.TaskId);
            }
        }
        for(Object s: scope){
            
            Contact contacto = (Contact) s;
            List<EmailStatus> ES = new List<EmailStatus>();
            ES = !test.isRunningTest() ?  contacto.EmailStatuses : getEmailStatus();
            
            for(EmailStatus emstat : ES){
                if((desde != null && emstat.CreatedDate < desde) || (hasta != null && emstat.CreatedDate > hasta.addDays(1)) ){
                    continue;
                }
                InformeEDC__c informeEDC  = new InformeEDC__c ();
                informeEDC.IdExterno__c = emstat.Id;
                informeEDC.Cliente__C = contacto.AccountId;
                informeEDC.FechaEnvio__c = emstat.CreatedDate;
                informeEDC.FechaQueSeAbrio__c = emstat.FirstOpenDate;
                informeEDC.UltimaFechaQueSeAbrio__c = emstat.LastOpenDate;
                informeEDC.NumeroVecesQueSeAbrio__c = emstat.TimesOpened;
                informeEDC.FPC_ErrorEnvio__c = contacto.IsEmailBounced ? contacto.EmailBouncedReason : null;
                listInformeEDC.add(informeEDC);
                break;
                
            }
            for(FPC_ErroresEstadosDeCuenta__c item : contacto.Errores_Estados_De_Cuentas__r){
                if((desde != null && item.CreatedDate < desde) || (hasta != null && item.CreatedDate > hasta.addDays(1)) ){
                    continue;
                }
                InformeEDC__c informeEDC  = new InformeEDC__c ();
                informeEDC.IdExterno__c = item.Id;
                informeEDC.Cliente__c = contacto.AccountId;
                informeEDC.FechaEnvio__c = item.CreatedDate;
                informeEDC.FPC_ErrorEnvio__c = item.FPC_Error__c;
                listInformeEDC.add(informeEDC);
                break;
                
            }
        }
        Database.upsert(listInformeEDC, InformeEDC__c.IdExterno__c, false);
       
    } 
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
    public static List<EmailStatus> getEmailStatus(){
        String body = '[ { "WhoId": "0035400000JsVB3AAN", "Id": "01854000000vCrPAAU","CreatedDate": "2020-07-28T11:42:14.000+0000" ,"FirstOpenDate": "2020-07-28T19:42:14.000+0000", "LastOpenDate": "2020-07-28T19:42:14.000+0000", "TimesOpened": 1 } ]';
        return (List<EmailStatus>)System.JSON.deserialize(body, List<EmailStatus>.class);
    }
}