force-app/main/default/objects/Cuenta_Formularios__c/Cuenta_Formularios__c.object-meta.xml
<CustomObject>
    <label>Cuenta Formularios</label>
    <nameField>
        <displayFormat>FORM-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuenta Formularios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Formularios__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UploadFileController_TESTAGN.cls
@isTest
public class UploadFileController_TESTAGN {
	@isTest
    public static void metodo1(){
        UploadFileControllerAGN.saveChunk('2345', 'test', 'gdgundi76556a78d', 'aplication/pdf', '');
        Cuenta_Formularios__c cuf=new  Cuenta_Formularios__c();
        cuf.Cuenta__c='2345';
        insert cuf;
        Test.startTest();
        UploadFileControllerAGN.saveChunk('2345', 'test', 'gdgundi76556a78d', 'aplication/pdf', '');
        UploadFileControllerAGN.saveChunk('2345', 'test', 'gdgundi76556a78d', 'aplication/pdf', cuf.Id);
        UploadFileControllerAGN.initCuenta('1');
        UploadFileControllerAGN.initCuenta('2345');
        UploadFileControllerAGN.init('test', '2');
        UploadFileControllerAGN.init('test', '2345');
        Cuenta_Formularios__c cuf2=new  Cuenta_Formularios__c();
        cuf2.Cuenta__c='8888';
        insert cuf2;
        UploadFileControllerAGN.init('testw', '2345');
        Test.stopTest();
    }
}